### ISSUE TITLE
Pull API returning null 

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#10025]
- Gitea version (or commit ref): 51f6a7ab1
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) 
https://gitea.com/api/swagger#/repository/repoGetPullRequest
```
owner = gitea
repo = go-sdk
index = 217
```

## Description

I deleted my fork of `go-sdk` and now the API call is "failing" because it returns `nil`.  
Note "failing" because it _does_ return a response, but it's `null`.

This is the offending func:  
https://github.com/go-gitea/gitea/blob/3c8a5d8783f23eca06eabc5903183f4a2bca2606/modules/convert/pull.go#L18

Shouldn't be too hard to fix, but we need to distinguish what qualifies returning `nil` rather than as much data as possible, because currently returning `null` in the JSON response means PRs will get missed by services using API calls.

**Comment by zeripath** [comment]
So presumably the problem is here:

https://github.com/go-gitea/gitea/blob/3c8a5d8783f23eca06eabc5903183f4a2bca2606/modules/convert/pull.go#L39-L43

One you've deleted your head repo that will return an `ErrRepoNotExist`. That should just be ignored and the nil repo dealt with here:

https://github.com/go-gitea/gitea/blob/3c8a5d8783f23eca06eabc5903183f4a2bca2606/modules/convert/pull.go#L102-L129
