### ISSUE TITLE
Restricting user access to git operations only

### ISSUE THREAD

**Issue by devsentient** [go-gitea/gitea#10075]
Hi,

We're trying to use Gitea as a server that is managed by other systems through the API, and users interact with solely through git commands like pull, push, clone, etc.

Is there a way to restrict access so that users can only perform operations on specific repos and there is no web frontend exposed?

**Comment by zeripath** [comment]
Why you want to do this I'm not certain but...

Presumably you want git over http to still be available otherwise it's simple just don't expose the http interface publicly.

However if you stick Gitea behind a proxy and then only redirect through the appropriate git URLs then that would work similarly.
