### ISSUE TITLE
Cross reference doesn't render as a link if followed by punctuation signs (colon, semicolon, question, ...)

### ISSUE THREAD

**Issue by InExtremaRes** [go-gitea/gitea#10074]
- Gitea version (or commit ref): 1.12.0+dev-220-gd7f4f87aa (current at try.gitea.io)
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/inextremares/testing/issues/5
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When a message references another issue with `#number` syntax the reference doesn't show as a link if there is a colon, semicolon, question sign or others punctuation signs just after it. I didn't test more but I thinks these are very common and should be supported.

## Screenshots

![image](https://user-images.githubusercontent.com/1635491/73452003-bb293380-4347-11ea-991e-cb5caf65356f.png)

**Comment by guillep2k** [comment]
For context, this was enabled for mentions (`@user`) in #8889, but there was no discussion about what characters are allowed following an issue or pr reference. It's tricky business because issue references can take [a lot of shapes](https://docs.gitea.io/en-us/automatically-linked-references/#issues-and-pull-requests-references-summary). For simple numeric references, currently only `)`, `]`, `:` and `.` are supported; the latter only if it's immediately followed by space or EOL. I think `;` and `,` could follow the same rule as well.

**Comment by InExtremaRes** [comment]
Yes, you're right that it's tricky. Support for `;` and `,` with the same rules that `:` and `.` would be great.

Can  `?` and `!` be supported as well? I think if the rule is the same (space or EOL immediately after) then it isn't ambiguous, but I can say nothing about the troubles to implement that.

**Comment by guillep2k** [comment]
This can be closed as per #10091
