### ISSUE TITLE
A way to disable the Code tab for a project, or make the Wiki the first tab.

### ISSUE THREAD

**Issue by lpar** [go-gitea/gitea#10265]
Maybe I'm crazy, but I'd like to be able to use Gitea as a lightweight issue tracking system for projects which don't necessarily have source code in any meaningful sense, or where the source code isn't the first thing you'd want users to see.

How difficult would it be to have an option to disable the code tab completely, or failing that, an option to make the Wiki be the first tab and open by default on clicking through to the project?

**Comment by guillep2k** [comment]
Reordering the tabs can be probably accomplished by providing your own copy of `templates/repo/header.tmpl`. You must take the original file from [the source](https://github.com/go-gitea/gitea/blob/v1.11.0/templates/repo/header.tmpl), and place it inside your `custom` directory (check [Customizing Gitea](https://docs.gitea.io/en-us/customizing-gitea/)). Please make sure you use the version that matches your Gitea. In the previous example I've linked to `v1.11.0` just because it's the current release.

**Comment by lpar** [comment]
Right, I don't want it like that for _every_ project though.

**Comment by guillep2k** [comment]
As an idea, an `{{if ...}}` could be placed to change the tab order if a repository name begins with "tracker-", or when it has a certain topic (label).

I don't mean to put your request down, however. I too think it's a valid use case. I know however that doing that properly (disabling code) might require a lot of changes because Gitea assumes code is always enabled, and code handling code (ehem) is everywhere.

**Comment by lunny** [comment]
Currently, if you create a repository on an orgnization and create a team with no code permission. That it is.
That means, it's not difficult to implement but need a PR.

**Comment by yardenshoham** [comment]
@lunny did you implement this?

**Comment by lunny** [comment]
Yes
