### ISSUE TITLE
[Bug] Rust repositories are identified as TOML

### ISSUE THREAD

**Issue by FunctionalHacker** [go-gitea/gitea#10266]
Example: https://git.reekynet.com
Look for the "lqsd" repository and you can see that it is identified as TOML, when it in fact is a Rust project.

**Comment by Aviortheking** [comment]
this is normal as there is more TOML content than Rust content

**Comment by ReekyMarko** [comment]
There are 4 .rs files in src and one .toml file in the repository root.

**Comment by jolheiser** [comment]
GH correctly identified it as Rust, I'm assuming they have some override based on certain files etc.

It's being identified as TOML because there's more lines of TOML than Rust, likely due to the cargo files.

Using `src` is a possible solution for some cases, but it's definitely not fair to assume a `src` directory as the golden standard.

My guess is there'd be a list of things to look for that would "override" primary language, such as a cargo file or `go.mod` for Go etc etc. 
When a project has more than one for some reason, it would just default to using most lines like currently?

**Comment by lafriks** [comment]
Cargo.lock file is also detected as yaml so based on file size calculation seems correct

**Comment by ReekyMarko** [comment]
Not stale

**Comment by jolheiser** [comment]
Fixed by #11681
