### ISSUE TITLE
Need a feature to save disk space and bandwidth

### ISSUE THREAD

**Issue by imfantuan** [go-gitea/gitea#10272]
1. If user A and user B mirrored a same repository, i think it should be saved in one public git space(they should be two repos in the database);
2. When user A convert it to a regular repository, gitea can copy it to his private git space from the public.

**Comment by lafriks** [comment]
It has been proposed before but that is not so easy to do as it seems

**Comment by a1012112796** [comment]
hello! I also found a useful way on www.gitee.com , which is to give a message when the public mirror of the repository already exists on the site.
![jt](https://user-images.githubusercontent.com/25342410/74580169-06944080-4fdc-11ea-83a5-60a9e2caf6a9.jpg)

**Comment by lunny** [comment]
I think there are two improvments here:

- [ ] When some repositories have the same mirror URLs, some repository could be as a main repository and it will mirror from the URL in real. Other repositories will mirror from the main repository. This will save bandwidth.
- [ ] And for disk save, we have to share the same git repository. We need a reference count, and only delete it after all the repositories removed.

**Comment by zeripath** [comment]
git clone uses hard links by default which reduces some of the problem. The issue is repacks and updating during mirroring operations which are unlikely to be shared.

If we try to start being too clever with object storage we're likely to end up having to implement git at some point. Another more worrying point is whether it could open us up to security issues whereby a malicious user could request private git objects through guessing a sha1.

**Comment by cipherboy** [comment]
Another concern is authentication: in the case of a mirror with authentication, another user shouldn't be able to piggy-back off of those credentials and should be forced to re-auth. An unlikely scenario is two users authing to the same URL (with different credentials) getting different repos; it'd break a de-deup scheme based entirely on URL (regardless of whether it verifies that the supplied credentials work).
