### ISSUE TITLE
Drop build dependency on nodejs

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#10505]
Is `JS transpilation and lazy-loading, CSS preprocessing and SVG bundling` not something a Go module can do? Like https://news.ycombinator.com/item?id=22335707 maybe ?

Introducing a new dependency on nodejs really reduced the appeal of Gitea for me, attracted here by the elegant single-tool compiler (Go)

**Comment by jolheiser** [comment]
To be fair, Gitea (and Gogs) have used things like less etc. for an incredibly long time.  
However, compiled assets were stored in Git so that they weren't needed for those building from source.

We have some work being done so that we can included pre-compiled assets for releases (https://github.com/go-gitea/gitea/pull/10325), but removing them from Git makes new requests that change these resources _much_ easier.

**Comment by strk** [comment]
I'm only asking if we can have Go, instead of javascript, fetch the required js dependencies, from git repositories, as it's done with Go dependencies

**Comment by strk** [comment]
The new `backend` target doesn't completely help. I'm still left with unusable Gitea unless I somehow fetch those assets from somewhere, and right now fetching assets is still only possible via the `frontend` rule, which depends on npm/nodejs once again (and not even the version available on my Ubuntu 18.04 system...).

**Comment by jolheiser** [comment]
This was the original PR for sources (https://github.com/go-gitea/gitea/pull/10295)

Downloads at https://dl.gitea.io/gitea/ (starting with 1.11.1) now include fully built sources as well.

e.g. https://dl.gitea.io/gitea/1.11.1/gitea-src-1.11.1.tar.gz has the Gitea source, including pre-built assets.

**Comment by silverwind** [comment]
IMHO, there is no way around Node.js (and increasingly, webpack) for frontend development.

I took a look at ESbuild but it seems rather limited in what it can bundle (only JS) in comparison to webpack (can do everything) and it's a one-man-show that may likely get eventually abandoned soon. The author even states he's not willing to accept contributions (wtf).

Node.js is not needed for `src` tarball downloads, only for git builds. `make` should skip over it so once frontend assets are built, they will not rebuild unless their sources have changes.

**Comment by techknowlogick** [comment]
Compiled assists are provided as above, and so having nodejs is only required as in the past if you need to make changes to CSS. Removing compiled assets from git itself was because we end up with many PRs that authors disappear from that we are then required to resolve conflicts, or even when we go to merge many PRs we get blocked because each PR would then require the author to recompile the CSS/JS (when we have very powerful CI servers that should be doing repetitive resource consuming tasks like that).

**Comment by holgersson32644** [comment]
Hi, gitea 1.11.4 still complains if nodejs is not installed on the building system:
"Gitea requires Node.js 10.0.0 or greater and npm to build. You can get it at https://nodejs.org/en/download/" using the snapshot named gitea-src-1.11.4.tar.gz.

**Comment by silverwind** [comment]
It should work if you run `make backend` (which only requires go) instead of `make build` (which required both go and node).

**Comment by holgersson32644** [comment]
Right, layer8 bug. Thanks a lot for your quick response!
