### ISSUE TITLE
Stable version tag for Docker

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#10589]
## Description

Would it be possible to have a stable version tag? Something like an alias called `1-stable` that will always return the latest but stable build for version `1` (seems that [this is not always the case](https://github.com/go-gitea/gitea/issues/10657))?

**Comment by sapk** [comment]
We could. This has already been discussed to also change what `1` and `1.11` tag means. 
Actually `1` and `1.11` mean latest `1.11.x` tag (what I would call stable) and that the default comportement of the drone plugin we use. 
From my point of view that would add another pipeline configuration for such case which add complexity to a file that is already complex. I think that people that would use this tag could easely build the image locally from the last commit themself. 
To be clear, this is only my point of view and why I am not in favor but if someone want to do it and it get 2 validation I wouldn't block because maybe and simply doesn't see the full need.

**Comment by alexanderadam** [comment]
Ah, in that case `1` is what I'm looking for and I'm happy with it. :+1:
