### ISSUE TITLE
Find unused forks

### ISSUE THREAD

**Issue by sefsh** [go-gitea/gitea#10590]
I've a bunch of user-created forks of a large repo. Some of the forks seem completely unused and thus only takes up space for no benefit. How can I find the all unused forks for removal?

**Comment by guillep2k** [comment]
Well, forks are repositories created by users at their discretion. Depending on your site policies (e.g. a company?) it's difficult to establish what is unused and what is not.

Having said that, the API will probably give you the flexibility you're looking for. Also, the `/admin/repos` page (sorted by least recently updated) might help too.

**Comment by yusf** [comment]
Yes, it's a user choice. For this instance's purpose however, there's no need in keeping unused forks around and I can free space instead.

I'm not familiar with the API but it sounds like I have to dive into it because the admin UI doesn't give enough information regarding this.

Come to think of it, where I really want this feature is built as an action in the "Maintenance Operation" section called something like "Delete all unused forks".

**Comment by guillep2k** [comment]
@yusf You'll find the API pretty convenient. Just check: https://try.gitea.io/api/swagger

(also present in your Gitea installation, in the footer, `API` link). 😁

**Comment by yusf** [comment]
Also, Commit Graph to the rescue 🎉
