### ISSUE TITLE
SSH login is very slow

### ISSUE THREAD

**Issue by MicePilot** [go-gitea/gitea#10683]
- Gitea version (or commit ref):gitea-1.11.1
- Git version: 2.25.0
- Operating system: Windows Server 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea is deployed under windows and the built-in ssh server is used, but SSH login is very slow. I think it's a DNS reverse query problem, but I can't find the place to modify the settings

**Comment by guillep2k** [comment]
After much digging I _think_ you could set `VerifyHostKeyDNS = no` in your ssh config. But that's tricky because it should be Gitea's service user, actually. For example, if Gitea is running as "myserver\giteauser", you'd need to go to `c:\users\giteauser\.ssh` and create/edit a `config` file. There you can add the [`VerifyHostKeyDNS`](https://man.openbsd.org/ssh_config.5#VerifyHostKeyDNS) entry.

This is only just "in theory", because as I could see in the sources we're using this package https://github.com/kevinburke/ssh_config indirectly.

**Comment by MicePilot** [comment]
> After much digging I _think_ you could set `VerifyHostKeyDNS = no` in your ssh config. But that's tricky because it should be Gitea's service user, actually. For example, if Gitea is running as "myserver\giteauser", you'd need to go to `c:\users\giteauser\.ssh` and create/edit a `config` file. There you can add the [`VerifyHostKeyDNS`](https://man.openbsd.org/ssh_config.5#VerifyHostKeyDNS) entry.
> 
> This is only just "in theory", because as I could see in the sources we're using this package https://github.com/kevinburke/ssh_config indirectly.

I made these settings, but they are invalid, so I changed the server of Linux system, all the problems are gone. Thank you anyway.

**Comment by MicePilot** [comment]
I think of another problem. I deployed it through binary files under Linux. If I want to upgrade, can I just replace this binary file

**Comment by guillep2k** [comment]
Yes. Please do so maintaining the same name and path. The executable path is used in the git hooks and the sshe keys. Also, make sure you use the latest release for upgrading (currently 1.11.3).
