### ISSUE TITLE
Improve "You can not upload files of this type" message

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#10694]
We should give the user a hint that it's a configuration issue and change the message for something more useful like "Your site administrator has not explicitly enabled uploading files of this type".

**Comment by alexanderadam** [comment]
Is this restriction done using an allowlist or a blocklist?
It would be nice if some information could be given what actually _is_ allwed (in case it is an allowlist).

For instance

> Your site administrator has not explicitly enabled uploading `.pdf` files but you can upload `.jpg`, `.png`, `.webp` and `.gif` files.

Otherwise the user won't know in which format a conversion would make sense.

**Comment by guillep2k** [comment]
It's not so simple, unfortunately. Currently Gitea knows nothing about file extensions, only MIME types. So, there's no direct relationship between one and the other. For example, the following is a list of MIME types the admin can allow... which one or ones are `.zip`?:

- `application/zip`
- `application/x-zip-compressed`
- `multipart/x-zip`
- `application/gzip`
- `application/x-gzip`
- `application/x-gzip-compressed`
- `multipart/gzip`
- `application/x-compressed-tar`
- `application/x-gtar`
- `application/x-tgz`
- `application/rar`
- `application/x-rar-compressed`
- `application/x-7z-compressed`
- `application/x-compress`

If the admin omits `application/x-zip-compressed`, are `zip` files allowed or not? 😓

**Comment by alexanderadam** [comment]
IMHO *nix operating systems often have `/etc/mime.types` or `/usr/local/lib/mime.types` which will usually contain much relevant information, right?

And looking up certain main file extensions by their mime type in Ruby or Crystal would be something like
```ruby
mime_types = %w[application/zip application/x-zip-compressed multipart/x-zip
                application/gzip application/x-gzip application/x-gzip-compressed 
                multipart/gzip application/x-compressed-tar application/x-gtar 
                application/x-tgz application/rar application/x-rar-compressed 
                application/x-7z-compressed application/x-compress]

mime_types.map { |m| Mime::Type.lookup(m).symbol }.compact.uniq
```

and would I guess that it wouldn't be much more complicated in Go?

At least it seems like [the `mime` package has similar functionality](https://golang.org/pkg/mime/#ExtensionsByType).

> If the admin omits `application/x-zip-compressed`, are `zip` files allowed or not?

Of course there might be some inconsistencies between a mime type but I guess even then it would be more helpful than a message that wouldn't even give _any_ hint?
Otherwise there are also some libraries that will give out a "friendly" name (i.e. `Textfile`).

I just thought it might be a useful addition if this topic will be handled anyway but I will understand if this is too complicated.

**Comment by bauermarkus** [comment]
I think this is duplicated to #8229
