### ISSUE TITLE
gitea web  lost css.

### ISSUE THREAD

**Issue by mmiker** [go-gitea/gitea#10718]
- Gitea version (or commit ref):
- Git version:   1.11.2/1.11.1
- Operating system:  win10 x64 ltsc  17763.1039
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:

  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
the web page of http://localhost:3000/  look like only load text/html , and no css loading.
...

## Screenshots
![lost_css](https://user-images.githubusercontent.com/7027280/76480721-86ca8c00-644a-11ea-88e2-bc7373337770.png)
![lost_css2](https://user-images.githubusercontent.com/7027280/76481176-ca71c580-644b-11ea-8726-1b9b52f86a33.png)

**Comment by guillep2k** [comment]
Some questions:

Can you show us your app.ini (passwords removed)?

Have you installed a docker image, from binaries or from source?

Can you tell us the URL in your browser to compare with your results?

Are you using a reverse proxy?

How are you starting gitea? As a windows service? Manually?

**Comment by mmiker** [comment]
I'm run gitea in console mode. eg.    "C:\GITEA>gitea.exe web"
I tried http://127.0.0.1:3000/ , http://localhost:3000/ , and in other LAN IP visit my computer. http://192.168.0.102:3000/,  the result is same.
I'd tested Windows Service mode . the result is same.
I'd tested some explorer,  include IE ,chrome, firefox. result is same.
I'm only used in my own computer  and not use reverse proxy.
[app.zip](https://github.com/go-gitea/gitea/files/4322373/app.zip)

**Comment by mmiker** [comment]
here is some console log 
[console_log.zip](https://github.com/go-gitea/gitea/files/4322401/console_log.zip)

**Comment by guillep2k** [comment]
I normally use Gitea in a Linux environment, but this is what I did to test your case:

- I'm using Windows 10 Home
- Created `C:\Gitea` and `C:\Gitea\etc`
- Copied your `app.ini` into `C:\Gitea\etc`.
- Downloaded both adm64 and x86 versions from https://dl.gitea.io/gitea/1.11.3/ (I didn't know which one you've used).
- Copied one (started with the amd64 version) as `C:\Gitea\Gitea.exe`.
- Executed the program.
- From `localhost:3000` in my browser (Firefox), everything looks fine.
- Closed Gitea.
- Copied the x86 version over `C:\Gitea\Gitea.exe`.
- Tested again. Everything looks fine.

(It's the first time I run Gitea in this Notebook).

So it seems that your problem comes from the way you've got Gitea (have you compiled it yourself? Is it possible it is an incomplete download?).

**Comment by guillep2k** [comment]
Note: in Firefox, if I need to reload the service worker and make sure that all cached content is dropped, I use `CTRL+F5`.

**Comment by mmiker** [comment]
Maybe my system had same problem. I'd run gitea on another LAN computer. It samed work fine.

**Comment by skye95git** [comment]
> Maybe my system had same problem. I'd run gitea on another LAN computer. It samed work fine.

I have the same problem with you. Have you found the cause of the problem?How to solve it?
