### ISSUE TITLE
feature suggestion: default custom template for dashboard info display

### ISSUE THREAD

**Issue by nergdron** [go-gitea/gitea#10870]
- Gitea version (or commit ref): gitea docker image (00ca50a67b9a)
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description
loving gitea so far, very happy to be switching over to it from commercial hosting. something I'd like to see is a default custom template which gets loaded into the user's dashboard view by the default templates, like `extra_links.tmpl` or similar. I'd use it for displaying things like system info and help, other integrated js features, or just a fun graphic for users. would really help me expose the customizations (like mermaid) that I've done to the server so users are aware of them.

adding it to the upstream template would be good because then I'm not copying the whole `dashboard.tmpl` and editing it, which could cause me to lose upstream changes to that template as you guys do further development. I'd rather have a location on that page I can just update independently and know it'll always show up on the dashboard, but I'll still get other upstream improvements.

I was thinking a good location would be under the right repo / org bar, as that typically has lots of free space vs the history list on the left.

## Screenshots
![gitea-template](https://user-images.githubusercontent.com/292681/77834316-1043b480-7101-11ea-8858-a04cecd3b586.png)

**Comment by guillep2k** [comment]
We could add some empty templates in some specific pages, like dashboard, new issue/PR, etc. for this kind of job. Also a good place to do that would be in mail footers. I don't think that would add too much overhead; IIRC templates are loaded on startup, even the custom ones.

**Comment by nergdron** [comment]
yeah, I've had to restart gitea every time I change templates, so I'm under that impression as well. and I love the idea of having a dedicated info space on every major page we can adjust with a builtin custom template. more places to easily customize without having to track the upstream templates is better! :)

**Comment by mrsdizzie** [comment]
IMO it would be better to fully enclose all the current sections of the dashboard in their own templates so people can easily create their own dashboard template without falling behind important upstream changes (So think of it like having blocks you can build with)

So you'd be able to create your own dashboard page easily like

<template/navbar>
<template/heatmap>
<template/feed>
<template/repos>
<template/customsection>

And not really fall behind upstream because any important changes would take place within those template files. 

It is actually already about 50% like this, with navbar and feeds being in their own file. If Heatmap and repo list moved into their own file it could probably easily work that way.

This would fix the issue of templates being annoying to use because they fall out of sync/don't get updates and also provide more flexibility because you could easily arrange a dashboard page any way you want, add multiple sections, etc..

**Comment by nergdron** [comment]
@mrsdizzie love it, even better!

**Comment by guillep2k** [comment]
@nergdron if you set [`RUN_MODE = dev`](https://docs.gitea.io/en-us/config-cheat-sheet/#overall-default) in `app.ini`, Gitea will detect changes in the file-system under `public/`, `custom/` and/or `static/` if you use any of them (which of course will be a little slower, but handy for testing templates and such). And you can compile Gitea without the `bindata` flag to force it to look for all the templates and files in the file-system under `/static` instead of having them embedded.
