### ISSUE TITLE
On hooks tries to execute folders in ${hookname}.d

### ISSUE THREAD

**Issue by bazilek** [go-gitea/gitea#10954]
- Gitea version: Current master 2a06d3a59064eba9fd74832fd138df50924b0d13
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
`remote: hooks/update: line 8: ./hooks/update.d/__pycache__: Is a directory`
## Description
Face the issue when managing hooks in python.

**Comment by mrsdizzie** [comment]
We probably shouldn't try and run a directory (!) but also a script in general shouldn't be creating folders or other files inside of update.d either since the only purpose of that folder is "execute anything that is put in here as a hook"

I believe you can either run python with -B flag or set ``PYTHONDONTWRITEBYTECODE=1``` to avoid creating that in general

**Comment by jolheiser** [comment]
Closed by #10955
