### ISSUE TITLE
[Feature] [API] Initialize Empty repo if repoCreateFile is used

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10993]
as title

related bug for this api: #10982

**Comment by MarkusAmshove** [comment]
For context why this is interesting:

I want to fully script creating repositories in our company, including creating a branch, default README, branch protection and merge settings.

I can't initialize the repository with `auto_init`, because our commit messages need to follow a convention which is checked and rejected via hook.

With the `repoCreateFile` I can create the README, the branch (after this is implemented) and can use a custom commit message.

**Comment by MarkusAmshove** [comment]
Please no stale :-)

**Comment by s-nt-s** [comment]
I have the same problem
