### ISSUE TITLE
500 Errors on creating and accessing repsitoris

### ISSUE THREAD

**Issue by bjoernbarthusel** [go-gitea/gitea#11178]
- Gitea version (or commit ref):
- Git version:  1.12.0+dev-206-g49f8b2057
- Operating system: Windows 10
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:

After installing the gitea Windows service I can sign in at http://localhost:3000 and edit my user account but creating a repsitory - not matter with what options - results in an internal error 500.

![Error500](https://user-images.githubusercontent.com/34130251/79976561-1bd69100-849d-11ea-8d17-ea3a4b8148c7.png)

The log states there were no gitea-repositories path:

2020/04/22 12:10:02 ...o/xorm/session_tx.go:46:Rollback() [I] [SQL] ROLL BACK []
2020/04/22 12:10:02 ...sitory/repository.go:23:CreateRepository() [E] Rollback deleteRepository: repository does not exist [id: 7, uid: 1, owner_name: , name: ]
2020/04/22 12:10:02 routers/repo/repo.go:162:handleCreateError() [E] CreatePost: initRepository: git.InitRepository: exit status 128 - fatal: Invalid path 'C:/WINDOWS/system32/config/systemprofile/gitea-repositories': No such file or directory

However this is wrong the path does exist:

![FolderSystemprofile](https://user-images.githubusercontent.com/34130251/79976661-47597b80-849d-11ea-84fb-f298b67c06b1.png)

At my first attempt the log had stated "fatal error repositora directory <repsitory name> does not exist". When I created the repository manually it was filled with all the subfolders, objects, hooks and so on and I could see the created repository in the ui. But when I try to open it I allway get the 500 error again.

On this computer I have provided a Postgres 9.5 Server which gitea could access an populate with lots of data.

Then I installed the gitea service (gitea-master-windows-4.0-386.exe) on another Windows 10 computer (both with Git version Git-2.26.2-64-bit). On computer 2 I went for sqlite3 but it was the same result. In the log I find some errors:

2020/04/22 13:01:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? [version]
2020/04/22 13:01:03 ...eue/queue_wrapped.go:70:setInternal() [W] [Attempt: 1] Failed to create queue: level for notification-service cfg: queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"notification-service-level"}, DataDir:"C:\\Programme\\Gitea\\data\\queues\\notification-service"} error: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

The German message says "the process cannot access the file because it is used by a diffenrent process." I have no idea what that could be. There are hundrets of similar errors:

2020/04/22 13:03:46 ...eue/queue_wrapped.go:70:setInternal() [W] [Attempt: 1610] Failed to create queue: level for notification-service cfg: queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"notification-service-level"}, DataDir:"C:\\Programme\\Gitea\\data\\queues\\notification-service"} error: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
2020/04/22 13:03:47 ...eue/queue_wrapped.go:70:setInternal() [W] [Attempt: 1611] Failed to create queue: level for notification-service cfg: queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"notification-service-level"}, DataDir:"C:\\Programme\\Gitea\\data\\queues\\notification-service"} error: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

This is my first post, sorry if I have forgotten something. I'm glad for any help.

**Comment by lunny** [comment]
Could you confirm that the user you run gitea has the permissions to read/write the `gitea-repository` folder?

**Comment by ObfusCleaner** [comment]
Yes I have stated RUN_USER = <computername> in the app.ini and gitea ui shows me that it picked up this information. It has also successfully created some files i.e. under C:\Program Files\Gitea\data\*.* as well as under C:\Windows\System32\config\systemprofile\gitea-repositories\*.* So there is no general write protection.

Meanwhile I have checked that the Acronis ransomware protection had identified gitea as potentially eval. But when I switch it off and restart the service or even reboot it has no effect. I am also running Process Explorer but I can't find overly supicious programs.

**Comment by 6543** [comment]
so LevelQueue has a file locking problem on windows

**Comment by ObfusCleaner** [comment]
The screenshots of my previous posts show that gitea gets a "folder does not exist" error when the folder actually does exist and was even created and populated by gitea itself some lines before. It seems the commands have different truths about what the right path is. How can that happen?

**1. Accessing with two different users?**

In app.ini I have set "RUN_USER = MYNAME-PC05". Maybe gitea does some operations under this user and some under a different one? Windows changes the location of some files depending on the user so this could happen:

- Write: /Windows/Path/repositories
- Read: /Windows/Nirwana/repositories


**2. Accessing the same file from indipendent processes?**

Maybe opening for read and for write acess with diffrent parameters? Searching the reccource monitor for processes that might block to the repositores folder i found nothing:

![03 Prozesse](https://user-images.githubusercontent.com/34130251/80065056-c603f680-8539-11ea-89f7-c5449e983d09.png)


**3. Using resolved paths in one place and magic paths in another?**

Root path in app.ini:

`[log]
MODE      = file
LEVEL     = info
ROOT_PATH = C:/Programme/Gitea/log
...
[repository]
ROOT = C:/Windows/system32/config/systemprofile/gitea-repositories`

Maybe I could not recreate the behaviour under  https://try.gitea.io because this server is not Windows or not set to foreign locales. My machines run in system locale 1031 (German) which makes windows display some translated folders.

Showing invisible folders you see two "Program Files" folders. The upper one (internally called "Program Files") is just displayed with its local name "Programme" and works fine. The lower one is the symbolic folder "Programme" which redirects to "Program Files". Access results in an error "Acess denied" which looks quite similar to gitea log errors.

![01 Programme OK](https://user-images.githubusercontent.com/34130251/80065335-3a3e9a00-853a-11ea-9fe2-6921e28a84c3.png)

![02 Programme Fehler](https://user-images.githubusercontent.com/34130251/80065346-3dd22100-853a-11ea-9ae4-d74a0d3f8fc4.png)

Unfortunately the logs hide the accessed path but only show the error message. Maybe that could be changed for improved debugging.

### Heres what happens when i create a rpository step by step:

1. Deleted all other contents in /repositories and created the new user "testuser".

![04 Vor neues Repository](https://user-images.githubusercontent.com/34130251/80065539-93a6c900-853a-11ea-9700-2219b1c690da.png)

2. Created new repository "testrep" with error 500.

`2020/04/23 07:40:03 routers/repo/repo.go:162:handleCreateError() [E] CreatePost: initRepository: git.InitRepository: exit status 128 - fatal: Invalid path 'C:/Windows/system32/config/systemprofile/gitea-repositories/testuser': No such file or directory
`
3.  Inserted the user folder manually

![05 Testuser manuell](https://user-images.githubusercontent.com/34130251/80065662-c9e44880-853a-11ea-8318-760aa5e51448.png)

4. Created new repository "testrep" again with error 500. But in fact the repository is created now:

![06 Repository created](https://user-images.githubusercontent.com/34130251/80065760-f1d3ac00-853a-11ea-860a-994ce4588b69.png)

But the logs report an error anyway:

`2020/04/23 07:47:06 ...ules/context/repo.go:500:func1() [E] RepoAssignment Invalid repo C:\Windows\system32\config\systemprofile\gitea-repositories\testuser\testrep.git: repository does not exist`

**Comment by guillep2k** [comment]
Reading about the problem in your first machine: `C:\Windows\System32` is a special directory in x64 systems. Depending on the architecture of the running application the actual folder could be [masked](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector?redirectedfrom=MSDN) from `C:\Windows\SysWOW64`.

You should not use any path below `C:\Windows`, since that would require Gitea to run with Administrator permissions or even worse, System. Please use a directory in a Path that is not reserved and run Gitea with a user identity that is not privileged.

**Comment by ObfusCleaner** [comment]
@gillep2k: Thanks for the tip. But how to change that? Gitea for Windows comes as a precompiled service that has it's storage location hard coded.

**Comment by lafriks** [comment]
You have to change app.ini

**Comment by ObfusCleaner** [comment]
Bingo! I have changed the app.ini settings to

`[repository]`
`ROOT = C:/LOKAL/STORAGE/Gitea/gitea-repositories`

and after restarting the gitea service it works. New repositories can be created and accessed now, so that was the bug!  :-)

Playing around I also found out what makes some paths  resolve and some not:

`[database]`
`...`
`PATH     = C:\Programme\Gitea\data\gitea.db`
``
`[repository]`
`ROOT = C:/WINDOWS/system32/config/systemprofile/gitea-repositories`
``
`[server]`
`...`
`LFS_CONTENT_PATH = C:/Programme/Gitea/data/lfs`

Some paths are notated with slashes and others with backslashes. This controls if they are resolved! A specific test location using Windows network folders only worked after the slashes were put the right way. So there are more reasons to fix it but Windows folder structure. As I don't know how Go procedures handle paths the bug might be quite unobvious to the developers.

Thinking twice about the storage folder uncovers another bug: The original storage path that gitea initializes on it's first run 

`C:\Windows\System32\config\systemprofile\gitea-repositories`

violates the stucture of Windows Application storage! It should read

`C:\Windows\System32\config\systemprofile\AppData\Local\Gitea\gitea-repositories`

so it doesn't write to an area of the tree where it is not supposed to.

### Conclusion

To make gitea work from scratch the slashes in it's data access functions should be corrected as well as the default windows storage location. Setting up the gitea service without a setup.exe is hard enough for the average Windows user. ;-) Thank You all for the support!

**Comment by guillep2k** [comment]
@ObfusCleaner but why is Gitea related to `c:\windows\system32` at all? Can't you just install it at `C:\Gitea` or something? It shouldn't even get the _smell_ of `c:\windows\system32`.

**Comment by ObfusCleaner** [comment]
@guillep2k: That´s a good question! The windows service comes as `gitea-master-windows-4.0-386.exe` with hardcoded configuration defaults. Why does it create an `app.ini` with a path to `C:\Windows\System32` at it's first start? - I don't know.

Of course it's ok using the same storage locations Windows provides and which other programs also use. But it should be set up correctly.

**Comment by guillep2k** [comment]
@ObfusCleaner questions:
1. what is the name of the Windows user which runs the Gitea service? Is it "Local System" by any chance?
2. what is the path where `gitea.exe` resides in your system?

**Comment by ObfusCleaner** [comment]
@guillep2k:

1. Gitea is running under the computername as suggested by the installation instructions at https://docs.gitea.io/en-us/windows-service/:

![2020-26-04 002 Gitea Run User](https://user-images.githubusercontent.com/34130251/80314530-5c624180-87f2-11ea-8a64-02f29601773f.png)

2. The path is `C:\Program Files\Gitea\gitea.exe`. The exe has been renamed from `gitea-master-windows-4.0-386.exe` to `gitea.exe`. The screenshot demonstrates how Windows resolves the path different for display on non English machines. 

![2020-26-04 001 Pfad zu Gitea](https://user-images.githubusercontent.com/34130251/80314588-b82cca80-87f2-11ea-8f64-1142005294eb.png)

**Comment by guillep2k** [comment]
@ObfusCleaner I meant the service (here an example to clarify):

![image](https://user-images.githubusercontent.com/18600385/80446641-c14e9200-88ed-11ea-8c35-f51d5f15350c.png)

**Comment by ObfusCleaner** [comment]
Sorry for the delay, here's the answer:

![2020-05-08 Server Eigenschaften](https://user-images.githubusercontent.com/34130251/81364915-17d68000-90e7-11ea-9076-74091b6d88dc.png)

**Comment by guillep2k** [comment]
I suggest you use a real user there, _not_ local system (lokales systemkonto).
