### ISSUE TITLE
UI loading google fonts for lato

### ISSUE THREAD

**Issue by daniubi** [go-gitea/gitea#11243]
jquery.js  load  error   

https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin&display=swap

wait 55s   very slow

**Comment by techknowlogick** [comment]
related https://github.com/fomantic/Fomantic-UI/issues/367 and https://github.com/fomantic/Fomantic-UI/issues/373

**Comment by daniubi** [comment]
if we don't have the internet,there is a problem.

**Comment by alexanderadam** [comment]
> if we don't have the internet,there is a problem.

This is clear but it relies on [the mentioned fomatic issue](https://github.com/fomantic/Fomantic-UI/issues/367), nevertheless.
You can override the font manually if you don't want to wait until [the fomatic issue](https://github.com/fomantic/Fomantic-UI/issues/367) is solved.

**Comment by lunny** [comment]
@alexanderadam I think yes but haven't spent time to investigate how to instead it.

**Comment by silverwind** [comment]
I think we already fixed this [here](https://github.com/go-gitea/gitea/blob/6b6f20b6d43b6263320ee872799373f33a751304/web_src/fomantic/theme.config.less#L102) but because of https://github.com/go-gitea/gitea/pull/10655, `semantic.css` is currently not being custom-built but instead copied.

Still waiting on the next Fomantic UI release for https://github.com/fomantic/Fomantic-UI/commit/6f8dc82d045a2f3553d721f9e49781df27e6378b. Maybe we should consider patching `Fomantic-UI` after installation using [patch-package](https://github.com/ds300/patch-package) or similar.

**Comment by 6543** [comment]
best way would still be to have it fixed upstream

**Comment by silverwind** [comment]
It is fixed upstream, but just not released yet.

**Comment by daniubi** [comment]
thanks
