### ISSUE TITLE
FYI - your dl.gitea.io is marked as category MALWARE by my Firewall (I use Untangle)

### ISSUE THREAD

**Issue by patrickave** [go-gitea/gitea#11315]
I just wanted to let you know your dl.gitea.io is marked as malicous by my firewall.  They have a categorization system.  They dont develop it on their own and I assume they use a service for these categorizes.  I dont have much details but that is the case right now.

**Comment by techknowlogick** [comment]
Thanks for report :)

Untangle utilizes (or at least my last experience with it) zvelo URL classification, and per https://tools.zvelo.com/ it appropriately classifies it as "tech", so perhaps your FW rules may need to be synced to most recent? We also offer compressed binaries which sometimes malware uses similar functions to hide itself so that may also confuse the classification software.

If you are able to provide more details when available we would appreciate it. For now I will close ticket as at least the current zvelo url database classifies us correctly.
