### ISSUE TITLE
[Question] How redirect to login instead of 404 for private repo?

### ISSUE THREAD

**Issue by badstorm** [go-gitea/gitea#11400]
- Gitea version: 1.11.5
- Git version: 1.14.2
- Operating system: linux-amd64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes
  - [ ] No
  - [ ] Not relevant

## Description
There is the possibility to redirect to _login page_ or show a custom alert message instead of the _404 page_ in this two cases when i try to connect directly form a _url_ of a private repo:

- if I'm not logged in
- my user not have permissions for that repo.

For example i create this repo on [try.gitea](https://try.gitea.io/badstorm/bds_private_rep) 

## Screenshots
![Schermata 2020-05-13 alle 12 23 41](https://user-images.githubusercontent.com/230256/81801413-af3b3900-9514-11ea-8470-736b8b7f63a7.png)
![Schermata 2020-05-13 alle 12 24 08](https://user-images.githubusercontent.com/230256/81801415-b104fc80-9514-11ea-8616-d82f53773d4b.png)

**Comment by zeripath** [comment]
Create a custom `status/404.tmpl` template. You should be able to detect ``{{.IsSigned}}` and you could put a form in to login.

If you come up with something that looks good and is understandable then please feel free to push it back as a PR.

**Comment by badstorm** [comment]
Thanks for your suggestion. I'll try to work on it.
There is a way to detect from the 404 template if the error was generated by a wrong url or for a private repo?

**Comment by lafriks** [comment]
Detecting wrong url or private repo would not be desirable becouse of security concerns. I would recommend just redirecting to login always

**Comment by silverwind** [comment]
How about an config option to emit the correct status code 403? I'd even lean to defaulting it to on and security-concerned people can still turn it off and have a (technically incorrect) 404.

**Comment by lafriks** [comment]
@silverwind I don't agree, every other platform does the same as we do currently. Github for example adds additional link below 404 description to Sign in page where you can click to login

**Comment by silverwind** [comment]
It's a tradeoff between security (hiding a repo's existance) and usability (not confusing users with wrong messages), I think it should be the user's choice.

**Comment by guillep2k** [comment]
@silverwind I agree (but that's potentially a lot of work!). The problem here is that Gitea has "two faces": one is a public service where people from all over the world could get in and collaborate; the other is a corporate service where users are strictly listed and probably doesn't even face the Internet. This duality creates a lot of conundrums where the solution for one is bad news for the other.

Gitea 2.0 should be refactored so settings are more manageable, and this kind of decision tree is easier to maintain.

**Comment by silverwind** [comment]
@guillep2k  What I don't quite get it why would you want to respond differently whether a instance is private or public? Let's say we return proper 401,403,404 status codes, in which case would you want to return different ones for public/private?

**Comment by lafriks** [comment]
> It's a tradeoff between security (hiding a repo's existance) and usability (not confusing users with wrong messages), I think it should be the user's choice.

And imho all systems take such tradeoff in favor of security. Just look at github, gitlab or pretty much any other

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k What I don't quite get it why would you want to respond differently whether a instance is private or public? Let's say we return proper 401,403,404 status codes, in which case would you want to return different ones for public/private?

IMHO it's because when it's a public service (facing Internet), some people may have _privacy_ concerns (_"I don't want anybody that I'm working on a particular fork, or even that I am registered in that site"_), but in a corporate environment the company can dictate the policies and might care more about confusing new users than about hiding the existence of a particular resource. I work in a small company and I'm unsure whether I should maintain separate teams, because everybody knows about everybody else and anybody might be assigned to any project; secrecy would be overly bureaucratic.

**Comment by silverwind** [comment]
I guess a per-repo setting to mask status codes might be perfect. That way, you can still properly hide your top-secret repos while returning proper status codes for less important ones.

**Comment by guillep2k** [comment]
> 
> 
> I guess a per-repo setting to mask existance might be perfect. That way, you can still properly hide your top-secret repos while returning proper status codes for less important/public ones.

@silverwind That exists already. Repository: `public`, `private`. But there's a lot of gray-area cases, like public repo but private organization, or public repo but only for logged in users, etc. 😵

**Comment by silverwind** [comment]
I guess one could introduce a `semi-private` option 🤣
