### ISSUE TITLE
Docker Gitea: Built-in ssh server fails to start

### ISSUE THREAD

**Issue by axeldeau** [go-gitea/gitea#11431]
- Gitea version (or commit ref): 
  - 1.12.0+dev-310-g41be23086 built with GNU Make 4.2.1, go1.14.2 : bindata, sqlite, sqlite_unlock_notify
- Git version: g41be23086
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

While running the lastest gitea docker image in kubernetes, the built-in ssh server fails to start if the ssh folder is not created manually, because the ssh-keygen command endlessly fails to create the various server certificates.

## Workaround

Create the folder before running the installer, and chmod 775, if not certificate creations fails with permissions denied

```bash
bash# mkdir ssh
bash# chown nobody:nogroup ssh
bash# chmod 775 ssh
ls -ld ssh
drwx------ 2 nobody nogroup 4096 May 15 21:45 ssh
```

Note that after the install completes, the chmod is 600 for obvious security reasons.

**Comment by zeripath** [comment]
Is this still an issue?

**Comment by zeripath** [comment]
This is interesting because:

https://github.com/go-gitea/gitea/blob/78cbd0ca72619a25849edc3460ec0c492b838a59/docker/root/etc/s6/openssh/setup#L3-L5

https://github.com/go-gitea/gitea/blob/78cbd0ca72619a25849edc3460ec0c492b838a59/docker/root/etc/s6/openssh/setup#L35-L37

Implies that we do attempt to create this directory.

Are you able to change this script to make it work correctly?
