### ISSUE TITLE
Error: context deadline exceeded when trying to create a pullrequest. Returns error 500

### ISSUE THREAD

**Issue by pommetjehorlepiep** [go-gitea/gitea#11472]
- Gitea version (or commit ref): 1.11.5
- Git version: 2.24.3
- Operating system: Alpine Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [gitea.log](https://github.com/go-gitea/gitea/files/4641198/gitea.log)

## Description
Trying to create a pull request from branch rename-activity into master.
After clicking 'create pull request' button nothing happens and screen with 500 error appears.

Additional information:
- Running gitea in a Alpine Linux 3.11 Docker container, with a MariaDB backend.
- Also using git-lfs
- Setup been running ok for a long time.
...

## Screenshots

![screenshot](https://user-images.githubusercontent.com/8982487/82161772-ed54a600-98e2-11ea-8140-96a2ab12c669.png)

**Comment by ChouAroua** [comment]
Me to same error !?

**Comment by zeripath** [comment]
Please could you try on 1.12-rc1

**Comment by pommetjehorlepiep** [comment]
> Please could you try on 1.12-rc1

I worked around it by just merging the branch straight in without a pull-request.

I can try restoring a backup from before the merge and try it with version 1.12-rc1.

Thx.

**Comment by sumrex** [comment]
I also have this problem, would love to know a solution

**Comment by zeripath** [comment]
@sumrex on which version of Gitea?

**Comment by sumrex** [comment]
@zeripath I'm on version 1.13.0. I get 500 error when trying to do a pull request to merge my branches.

**Comment by zeripath** [comment]
Ok I need some logs to see where the deadline is being exceeded.

But in the meantime have you changed any of these values: https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout

**Comment by sumrex** [comment]
I haven't changed any values, no. I'm really new to this so I'm not even sure where that is configured.

**Comment by sumrex** [comment]
@zeripath Ok the log error has now changed.

2020/08/04 22:48:05 ...es/pull/temp_repo.go:57:createTemporaryRepo() [E] git init tmpBasePath: exit status 128 - fatal: unable to get current working directory: No such file or directory
2020/08/04 22:48:05 ...rvices/pull/patch.go:53:TestPatch() [E] CreateTemporaryPath: exit status 128 - fatal: unable to get current working directory: No such file or directory	
2020/08/04 22:48:05 routers/repo/pull.go:978:CompareAndPullRequestPost() [E] NewPullRequest: exit status 128 - fatal: unable to get current working directory: No such file or directory

Previously I think it was:
2020/08/04 21:36:18 .../repository/check.go:39:func1() [W] Failed to health check repository (&{3 1 omnibox-admin <nil> spacestation SpaceStation   2 https://github.com/omnibox-games/SpaceStation master 1 0 0 0 0 0 1 1 0 0 0 0 false false false false <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 5040177869 <nil> <nil> true false []  1592244948 1596489535}): context deadline exceeded

I tried turning off the health check just now and I got the first set of errors instead.

**Comment by zeripath** [comment]
Ok so this is not the same issue at all. The errors do not match in any way. You should have opened a new bug.

This error is caused because Gitea cannot access its appdatapath.

2020/08/04 22:48:05 ...es/pull/temp_repo.go:57:createTemporaryRepo() [E] git init tmpBasePath: exit status 128 - fatal: unable to get current working directory: No such file or directory

Presumably you're running Gitea in systemd or have a packaged version rather than one of our downloads - we need that information to help you otherwise we're guessing. The app.ini would also have been useful.

However, I suspect the issue is you're not running gitea with a mutable work path - presumably you've avoided earlier failures with some settings in app.ini. 

Either set the $GITEA_WORK_PATH or $APP_DATA_PATH environment variables, use the --work-path option or set the appropriate settings in app.ini. (the proximate issue here is the LOCAL_COPY_PATH setting in the [repository] section - but you will be better off seeing work path to something mutable.)

**Comment by wxiaoguang** [comment]
Outdated
