### ISSUE TITLE
After updating from gogs 0.11.91 to gitea 1.13, can't access my dashboard

### ISSUE THREAD

**Issue by JellyBrick** [go-gitea/gitea#11560]
- Gitea version (or commit ref): 1.13.0+dev-37-g6af13dbac
- Gogs version: 0.11.91
- Git version: 2.17.1
- Operating system: Ubuntu 18.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If I have signed out, I can access my dashboard.
If I haven't signed out, an error occurs when accessing my dashboard.

(I followed `Upgrade from gogs` doc and #4286)

Error message:
```
template: user/dashboard/feeds:94:35: executing "user/dashboard/feeds" at <index .GetIssueInfos 1>: error calling index: reflect: slice index out of range
```
...

### If I have signed out

![image](https://user-images.githubusercontent.com/16558115/82701685-9b799a80-9cab-11ea-997c-a0c51efbc2f2.png)

### If I haven't signed out

![image](https://user-images.githubusercontent.com/16558115/82701811-d11e8380-9cab-11ea-85a5-6b5f1bd73808.png)

**Comment by jolheiser** [comment]
It looks like `GetIssueInfos` tries to split up `content` in the `action` table based on a pipe (`|`)

Can you check your `action` table?

**Comment by moepman** [comment]
I have the exact same error after upgrading from Gogs 0.11.91 using PostgreSQL to Gitea 1.0.2 -> 1.1.4 -> 1.2.3 -> 1.3.3 -> 1.4.3 -> 1.5.3 -> 1.6.4 -> 1.11.6.

What should I look for in the action table?

**Comment by moepman** [comment]
I have found a solution to the problem. I cloned my gogs VM again, and went a different route for the upgrade to gitea:
* stop gogs
* create a new minimal app.ini
* set DB version to 13 as per #5318
* start gitea 1.6.4 (since #5318 seems to imply this is spported without going through previous versions)
* sop gitea
* start gitea 1.11.6 (with #10026 dropping migrations from before 1.6.x in current code that to me implies going from 1.6.4 to 1.11.6 should be safe)

The issue with the dashboard is gone now, still having one or two other issues (still checking wether I did something wrong or if those warrant opening a new bug.)

**Comment by moepman** [comment]
If it helps: I have found out that the `op_type` used in gogs 0.11.91 and gitea 1.11.x/1.12.x differ for `op_type > 15`. Currently trying to figure out how to migrate them.
