### ISSUE TITLE
PostgreSQL minimal version

### ISSUE THREAD

**Issue by salesgroup** [go-gitea/gitea#11951]
We are using Gitea with Synology NAS and Sqlite, but we would like to move to PostgreSQL.
The postgresql 9.3.25 is already installed.
Can we use this version?
Is there any compatibility issues with this version?

**Comment by 6543** [comment]
it should - But I'm test it via  #11952 ...

**Comment by 6543** [comment]
(https://drone.gitea.io/go-gitea/gitea/27256/3/6)

**Comment by 6543** [comment]
@salesgroup no you should upgrade, CI failed

**Comment by zeripath** [comment]
Hmm I would not assume that just because the migration-tests failed that it would not work. If you look at the failure that's because of the specific language in the migration tests which I created using pg_dump because xorm dump was not working correctly at that point in time.

The real test would be to see if the tests succeed if you exclude the migration tests.
