### ISSUE TITLE
Remove licensing headers in go files

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11988]
I think having these headers is an archaic practice that has no real benefit. We're not consistent with having that header in every file and the copyright year is never updated. I think it's sufficient to have the root `LICENSE` file only.

**Comment by lunny** [comment]
@silverwind, I don't think so. The copyright headers should be kept because some copyright from other projects. i.e. Gogs. And for new files from Gitea, it will be provided by other forked or referenced projects. They should keep the copyright headers in their files to follow the MIT license.

**Comment by silverwind** [comment]
>  some copyright from other projects

We already have a gogs copyright in the `LICENSE`, that ought to be enough?

> And for new files from Gitea, it will be provided by other forked or referenced projects

Git blame/history already lets one already determine when/how a file was introduced and it gives much better information than those loosely maintained headers.

**Comment by codestation** [comment]
> We're not consistent with having that header in every file and the copyright year is never updated.

There is no reason to update the copyright year unless you have made a significant change to the code that requires a renewal. In my opinion, if a year update is needed then the year must be appended rather than replaced (to don't lose the starting year).

An quote from the [FSF](https://www.gnu.org/licenses/gpl-howto.en.html) about this (related to GPL but it can apply to other licenses):

> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each past release; for example, “Copyright 1998, 1999 Terry Jones” if some releases were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.
> 
> For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.

Note that the GPL licenses recommends to add the license header [to every file](http://www.gnu.org/licenses/gpl-3.0.html), so this is probably where the practice comes from:

> To do so, attach the following notices to the program. It is safest to attach them to the start of each source file to most effectively convey the exclusion of warranty; and each file should have at least the "copyright" line and a pointer to where the full notice is found. 

IMO the copyright notices should be kept. If the files are used in other projects outside Gitea then it becomes easier to see where it comes from and the license of the file. In this case the git history wouldn't be present (isn't present either in the release source tarballs).
