### ISSUE TITLE
User's public activity isn't filtered by user

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1202]
- Gitea version (or commit ref): 1.1.0

## Description

When displaying an user's profile page (https://git.xxxx.io/username?tab=activity), the page shows mixed users activities, not only the current user's activities. 
Is this a normal behavior? 

## Screenshots

![hosting](https://cloud.githubusercontent.com/assets/1597611/23805915/12ef3376-05c0-11e7-98a8-2bc4d31c71a0.png)

**Comment by lunny** [comment]
cannot reproduce in https://try.gitea.io

**Comment by bkcsoft** [comment]
I can reproduce on `1.1.0+63-g9a9f8fa` 😞

**Comment by bkcsoft** [comment]
Did some testing on my instance.  
There's 3 (active) users (X, Y, Z) and 2 repos (A, B).  
User X and Y works on repos A and B, while Z only works on B.  
Going to activity for X and Y shows `X pushed to A` all over the place. Going to activity for user Z shows X, Y and Z pushing to repo B.

From this it looks like the activity is linked to Repos rather than Users 😕

**Comment by bkcsoft** [comment]
Or rather, to repos that said user have pushed to...

**Comment by lunny** [comment]
@bkcsoft right. There are should two activities feeds. One is for dashboard which show all activities yourself and you stared repos, another is for only user's act ivies. So this is exactly a bug.
