### ISSUE TITLE
Commit button stays disabled when summary initally was > 100 chars

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#12072]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When editing a file in the web GUI and trying to commit with a commit summary of > 100 characters, the commit button gets disabled and stays disabled even when shortening the summary afterwards. Workaround is to remove the disabled attribute from the button in the browser DOM inspector.

Originally reported here: https://codeberg.org/Codeberg/Community/issues/207

![Screenshot_2020-06-27 pages](https://user-images.githubusercontent.com/1254676/85925134-b638c380-b896-11ea-8707-77cfccfd9ada.png)

**Comment by zeripath** [comment]
The problem lies in index.js within `async function initEditor() {...}` 

https://github.com/go-gitea/gitea/blob/7187fdbb1c5ddf3258269b1bab4a4bf357f03981/web_src/js/index.js#L1595

This line disables the commit button by default. I suspect that on post with error we should just not disable this button.
