### ISSUE TITLE
Different syntax highlighting in diff when a line was added/removed

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#12190]
https://try.gitea.io/silverwind/updates/commit/aef19fda0861f9c76776f22522aae7703bebc83f

Tokenization seems different when a line is added/removed compared to the rest of the file. Ideally, these lines should tokenize using the same tokens:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/115237/86943303-8e731680-c146-11ea-8827-662e0b215705.png">

**Comment by mrsdizzie** [comment]
Grr yea this is more trouble with how we process modifications within a line as totally separate diff parts. For a line with "added-code" it actually processes it in these 3 separate parts:

```
eslint-config-silverwind": "4.2.
```

```
3
```

```
",
```

Because the quote is broken up it sees the number as a literal float vs string. I'll see whats the best way to fix this with little modification -- our diff code is not pleasant to work in and touching it as little as possible will be best I think

**Comment by silverwind** [comment]
I think ideally we want to process both the original and updated file as a whole and then look for exact line matches with the diff's +/- lines. I think this is also what GitHub does.

**Comment by mrsdizzie** [comment]
Put up a PR that should fix this
