### ISSUE TITLE
Emojis are too huge

### ISSUE THREAD

**Issue by realpixelcode** [go-gitea/gitea#12312]
In the new Gitea version, many emojis are displayed too huge. For example, they don't fit in regular text. These are some examples on Github: 😎🤪🔐🤑❓ They just fit. That's what they look like in Gitea:

![Gitea emojis](https://user-images.githubusercontent.com/52963327/88383583-4f75cf80-cd9a-11ea-9cf7-3ed2be4cb4cb.png)

**Comment by techknowlogick** [comment]
Which specific version of gitea are you using?

**Comment by jolheiser** [comment]
[Reproduced on try](https://try.gitea.io/jolheiser/md/issues/3)

![emoji](https://user-images.githubusercontent.com/42128690/88400818-7d551700-cd8e-11ea-94b9-8ef05bcd2980.png)

**Comment by silverwind** [comment]
Strange that some of these emoji's are wrapped in `<span>` while others aren't. Maybe a separate issue in the detection code.

For this issue: I think Emojis should not be rendered bigger than the current line height.

**Comment by mrsdizzie** [comment]
Seems like one is a bug not detecting the sunglasses emoji which is strange (will look at).

The size difference of emojis in general is intentional as it is what github/gitlab do also. Gitlab is 1.5em maybe Github used to be and it is now 1.25 after their recent change? I'm fine if people want to change it to 1.25 instead of 1.5 it was initially just copied from one of those.

**Comment by silverwind** [comment]
I can probably do the necessary styling tweaks. I think 1.25 is ideal and it's what I've been proposing in the original emoji PR too.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/12317 for the 1.25em.

**Comment by realpixelcode** [comment]
> 
> 
> Which specific version of gitea are you using?

I don't know, I've discovered this issue on Codeberg after their big update which was heavily announced.
