### ISSUE TITLE
Emoji alias not parsed in links

### ISSUE THREAD

**Issue by rodolpheh** [go-gitea/gitea#12331]
- Gitea version (or commit ref): 1.13.0+dev-322-g54513452a docker version
- Git version:
- Operating system: Docker on Arch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) : https://try.gitea.io/toc-test/emoji-markdown-tests
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When using an emoji alias in an inline link, it is not displayed as an emoji but keeps its alias. The test page created shows the result of emoji alias in most cases. The inline link does not show an emoji but its alias.

## Screenshots

![image](https://user-images.githubusercontent.com/4491499/88483170-6537f000-cf66-11ea-9963-06f78daa20c4.png)

**Comment by mrsdizzie** [comment]
Our renderers intentionally ignore existing links for modifying text so you would need to just use the real  character you want instead of an alias. If it is something being created through an issue/wiki editor on our site it should give a dropdown menu to insert the real character if typing out an alias.

https://github.com/go-gitea/gitea/blob/master/modules/markup/html.go#L357

**Comment by silverwind** [comment]
Pushed that repo to GH, it seems they do render emoji tokens in links. Otherwise, output seems to match ours:

https://github.com/silverwind/emoji-markdown-tests
