### ISSUE TITLE
Add API endpoints for pulls created by, assigned to and requested to review for a user

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#12461]
Hi,

I wanted to create a tool to have a better overview of my pull requests (created), the ones I'm assigned to and the ones I've been requested to do a review.

I wanted to add the endpoints myself, but before doing any work,  they should be designed  and agreed upon :-)

## Suggestion

I've chosen  `/api/.../pulls` for this proposal, because this path is is the same the UI uses (e.g. https://gitea.com/pulls when logged in).

`GET /api/v1/pulls`: returns all pull requests from all repositories the authenticated user can see (same as with the UI).

`GET /api/v1/pulls/created`: returns all pull requests from all repositories the authenticated user has created

`GET /api/v1/pulls/assigned`: returns all pull requests from all repositories the authenticated user was assigned to

`GET /api/v1/pulls/reviewee`: returns all pull requests from all repositories the authenticated user was requested to do a review

If they're implemented, the filters in the UI could reuse them and also add a new filter (reviewee):

![grafik](https://user-images.githubusercontent.com/2401875/89714629-59095500-d9a0-11ea-9d4a-341dfdd91e2b.png)

**Comment by 6543** [comment]
@MarkusAmshove sorry for the late responce

what about add filter options in-query for `GET /repos/issues/search` [docu](https://try.gitea.io/api/swagger#/issue/issueSearchIssues)

so issues can be filtered the same way ... yes name is bit missleading, but since pulls are "issues with additional info" it's handled that way ... (I think we should mention pulls in the endpoint description too ...)

**Comment by MarkusAmshove** [comment]
That would be fine :-)
If the query string from that endpoint can support all my usecases (even if that means multiple invocations) then I have all I need :-)

**Comment by 6543** [comment]
closed by  #13514
