### ISSUE TITLE
[Feature] Sticky fileheader when code reviewing

### ISSUE THREAD

**Issue by Floaf** [go-gitea/gitea#12552]
It would be nice with sticky fileheader since it can be a bit messy when reviewing long files, like github has:

![image](https://user-images.githubusercontent.com/27698216/90896759-77217d00-e3c4-11ea-9cd6-17d8000a5896.png)

**Comment by bryanpedini** [comment]
Is CSS capable of "keeping track" of existing parts with the "sticky bit" set?

Explain better: if answer to the previous section is yes, then you can check `app.ini` for "stickyness" variables/section, then give the same `sticky-top` class to one/both (issue/pull) title and filename accordingly, then CSS "figures out" to put the first on top and the latter just below it.

PS: may I ask a thing too, one that even GitHub nor GitLab have?
Please add the home/back button to the sticky header as well. When working with keyboard shortcuts sure it's quick to `alt`+`left` to go back, but when using mouse only to perform quick searches and you've scrolled down a lot, a quick "home" button would be helpful too (especially since I always open things in a new page, so I can't use the browser back/forward functions, my bad 😅)

**Comment by silverwind** [comment]
CSS sticky requires absolute positioning on all stickied elements so it can't work with two individual elements, so I assume some JS is needed for the second sticky bar and if the solution is JS-based, it's probably better to do both in JS.
