### ISSUE TITLE
Artifacts on geometric avatar

### ISSUE THREAD

**Issue by lhinderberger** [go-gitea/gitea#12631]
- Gitea version (or commit ref):
- Git version: 1.13.0+dev-484-g1d47a2575 (try.gitea.io)
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/knut

## Description
Hello everyone. I want to bring your attention to a rather minor, but optically very unpleasing bug:

When creating an account, I noticed that the avatar had bad-looking artifacts after uploading (see attached screenshots). I suspect that this is due to a scaling algorithm that performs poorly on geometric shapes like circles.

I’ve attached the original image and a screenshot for reference.

Thank you!

## Screenshots
Screenshot from codeberg-test (another instance where this also occurs):
![Screenshot_2020-08-28 knut](https://user-images.githubusercontent.com/5623987/91601347-d144b400-e969-11ea-9241-b276bd7990b1.png)

Original avatar:
![polarbear-face](https://user-images.githubusercontent.com/5623987/91601358-d6a1fe80-e969-11ea-8fb7-5ad52e07f120.png)

**Comment by 6543** [comment]
looks like it's present in v1.12.x too

**Comment by 6543** [comment]
this issue is has to do how we resize things ...
https://github.com/go-gitea/gitea/blob/43c303d35c74562bf2eaf221d46f7ef1539179a6/modules/avatar/avatar.go#L92

Wikipedia has interesting infos: https://en.wikipedia.org/wiki/Image_scaling

I thin we just have to switch from `NearestNeighbor` to `Lanczos3`/`Bilinear`/`Bicubic`...
-> https://github.com/nfnt/resize

or switch to a better resize lib

**Comment by 6543** [comment]
source: https://codeberg.org/Codeberg/Community/issues/243
