### ISSUE TITLE
[Feature] Ability to exclude files from diffs

### ISSUE THREAD

**Issue by hanabanashiku** [go-gitea/gitea#12653]
Github uses Linguist for code analysis in its repositories, and resulting from that introduced a nifty feature in its .gitattributes definitions: `linguist-generated`. This attribute can be used to exclude specific file types from diffs, code reviews, and hide it from showing in the file listing.
I've found that to be invaluable to working with Unity3D in order to keep .meta and .prefab files from cluttering code reviews. It would be cool to have a similar feature in Gitea

---

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=92731348)](https://www.bountysource.com/issues/92731348-feature-ability-to-exclude-files-from-diffs)

**Comment by mattdavis90** [comment]
This would be a great feature. An alternative to the `linguist-generated` attribute, might be having gitea observe the `-diff` and `-merge` attributes.

**Comment by kdumontnu** [comment]
Bounty available [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=92731348)](https://www.bountysource.com/issues/92731348-feature-ability-to-exclude-files-from-diffs)

If you'd like to promote this, please add
```
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=92731348)](https://www.bountysource.com/issues/92731348-feature-ability-to-exclude-files-from-diffs)
```
To the issue summary

**Comment by mattdavis90** [comment]
@KN4CK3R You beat me to it, with a much cleaner solution :smile: Was fun to play around though.

My less elegant approach is [here](https://github.com/mattdavis90/gitea/commit/91e04f8bfd24ba3ef0aed5b75a16a1f1e08fb29c) in case there is anything of use.

It attempts to find the `.gitattributes` file on the current commit and temporarily stores it in `<repo>/info/attributes` so that it is available to the `git diff` command later. A little hacky, and I'm sure there is probably an issue if two API calls come in together.
