### ISSUE TITLE
Submodule links not recognized by web ui when SSH_DOMAIN is used

### ISSUE THREAD

**Issue by MartB** [go-gitea/gitea#12747]
- Gitea version (or commit ref): 1.12.4

## Description
When using a different domain for ssh access, submodules links are not correct within the gitea web interface.

Having a `.gitmodules` set up like this:
```
...
url = ssh://gitea@ssh.martb.eu/....
```

and a gitea instance set up with https://git.martb.eu/ with its `SSH_DOMAIN` set to `ssh.martb.eu` leads to ssh. being used as a http href instead of gitea translating it to the "known" git. domain.

## Affected lines 
https://github.com/go-gitea/gitea/blob/332dbe73935ba960d8769bfc20b8d275922e4137/templates/repo/view_list.tmpl#L50

## Screenshots
![image](https://user-images.githubusercontent.com/4820905/92332249-c205ea80-f07c-11ea-9dac-5e16aaebd532.png)

**Comment by MartB** [comment]
I just noticed that this is a duplicate of https://github.com/go-gitea/gitea/issues/9756, any news regarding this?

**Comment by 6543** [comment]
@MartB I think it is similar or related ... throu I think we can keep both open

**Comment by 6543** [comment]
there was done some work on submodule recognizion in the master branch some time ago , so it has to be checked if this is still present on master ...

**Comment by zeripath** [comment]
@MartB could you confirm that this is present on try?

**Comment by mrsdizzie** [comment]
@zeripath I don't think you can check this on try because it doesn't use a different domain name for SSH_HOST and DOMAIN

The issue is that we use AppUrl as the urlPrefix value here:

 https://github.com/go-gitea/gitea/blob/ad2bf376dfd934394cad46c3ff3e022ca232958f/modules/git/submodule.go#L42

So this will never match:

https://github.com/go-gitea/gitea/blob/ad2bf376dfd934394cad46c3ff3e022ca232958f/modules/git/submodule.go#L79

Because they use a different hostname in the submodule file that matches the separate hostname they have used for SSH_DOMAIN. So our logic thinks this is hosted elsewhere but really it is still the same copy of Gitea just with a different hostname for SSH_DOMAIN.

I think the issue here is that we need to also check if the hostname found in the submodule file matches the SSH_DOMAIN value and then create the link with the AppUrl instead.

**Comment by MartB** [comment]
Thanks for looking into that!
