### ISSUE TITLE
Question: Why create gitea hosted gitea when codeberg already has the infra and rans Gitea?

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#12875]
See https://codeberg.org/

**Comment by techknowlogick** [comment]
Gitea.com came first, as well it allows for the project to be in control of the infrastructure and allows us to upgrade as we please. For example on Gitea.com we are running on the bleeding edge. Codeberg is great, but doesn’t meet our current needs. As well, our project has over 100GB of assets, it wouldn’t be fair to codeberg to be that heavy of users.

**Comment by Codeberg-org** [comment]
Just to set the historical record straight: [Codeberg has launched on January 1st 2018](https://blog.codeberg.org/codebergorg-launched.html), the project had been started with working title "teahub" in Summer 2017, right after the take-over announcement for GH (gitea team members have been involved in early discussions, namely mentioned for example in a Heise news article).

Gitea.com came to attention when [Lunny mentioned gitea.com launch plans on April 18, 2019](https://github.com/go-gitea/gitea/issues/3840#issuecomment-484451344), the site became function a couple months later.

**Comment by lunny** [comment]
Codeberg is a great site I like. But we begin the work from 2017, see https://github.com/go-gitea/gitea/issues/1029. Currently, almost gitea related projects have been migrated to https://gitea.com/gitea . The main repository hasn't yet because there are some network problems we need to resolve. I'm writing a PR #12244 to dump the repository from GitHub and restore it to gitea.com. I think it will not far away.

**Comment by Codeberg-org** [comment]
Yeah, precisely, that's exactly the difference: Codeberg was right from the beginning planned and discussed as free and open platform for all Free and Open Source software projects, not limited to one particular project.

Many Open-Source projects aim for self-hosting, especially when reaching some size (and we absolutely like+support the distributed approach!). The length of #1029 to self-host gitea tells the story of complexities involved.

Also, Codeberg is not only about technical issues, but also legal entity (the non-profit Codeberg e.V. NGO with statutes ensuring independence, and organizational checks and balances) to ensure longevity and long-term endurance not tied to any particular person.

We aim to be friendly home, network, and community for those projects that are smaller or do not want to spend time and resources on self-hosting, but focus on their project work.


@techknowlogick :
> [...] our project has over 100GB of assets, it wouldn’t be fair to codeberg to be that heavy of users.

That's surely [243MB to be exact](https://codeberg.org/codeberg/gitea)? (we are hosting the Codeberg gitea repo since the beginning.) Never underestimate gitea's power ;) Projects with >>100MB repos are calling Codeberg their home, no concerns! Gitea is a great and has developed wonderfully since the early days!

Gitea developers are a great bunch. Communication and relationship to the developer team is a breeze and 100% productive, we would be totally delighted to welcome Gitea projects to https://codeberg.org!

**Comment by zeripath** [comment]
Remember when you migrate you take all of the pull heads and releases too - the size of the git repository increases somewhat because of this and all of the tags get a zip and tgz built for them. It's a problem that we still need to sort out.

**Comment by lunny** [comment]
@Codeberg-org Thanks for your invitation. But we will still keep Gitea in https://gitea.com/gitea. The main aim of gitea.com is to host Gitea's development. It is a part of Gitea team's work. It MUST be managed by Gitea teams just like maintain the codes of Gitea. Since Gitea is an open community, I think guys of codeberg could also contribute to Gitea and become maintainers of Gitea.
