### ISSUE TITLE
Issue/comment edit history

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#12886]
<img width="306" alt="图片" src="https://user-images.githubusercontent.com/81045/93554816-eaf47c80-f9a6-11ea-8268-db1ba91fee81.png">

**Comment by delvh** [comment]
I am conflicted about this feature:
I can totally see its value regarding data integrity and traceability.
However, I noticed that I also find it refreshing that Gitea does not track the edit history as small typos can then be deleted without a trace.

**Comment by redstonedesigner** [comment]
Perhaps as a compromise, there could be a set amount of time where an edit wouldn't be logged (configurable by an administrator) to allow for typographical errors to be caught and corrected.
After that, the edits would be logged as depicted above.

Just my opinion.

**Comment by delvh** [comment]
That sounds to me like a really good promise.
I would suggest a timespan of 15-30 minutes as default.

**Comment by lunny** [comment]
> That sounds to me like a really good compromise.
> I would suggest a timespan of 15-30 minutes as default.
> (If you read through the edit history of this message, you can also already see why I think that this is a good compromise 😉 )

Or the time is configuable.

**Comment by delvh** [comment]
Yes, but I meant as fallback if no time has been specified inside the `app.ini`.

I would definitely say that this should **only** be a server-wide setting with no further extensibility because otherwise you can have repositories where you cannot assume the validity of comments which would make this feature in my opinion less useful.
