### ISSUE TITLE
Cannot use Repository template

### ISSUE THREAD

**Issue by Aragur** [go-gitea/gitea#12908]
- Gitea version (or commit ref): 1.13.0+dev-656-g7f966f316 
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I created a Repository Template, now I wanted to use it.  
It seems that there is no button to create the repository now. (See attached Screensot)  
Manually removing the Footer via the F12 Inspector also doesn't show any button.

## Screenshots

![Screenshot_20200920_131658](https://user-images.githubusercontent.com/11004008/93710063-d7324d00-fb43-11ea-8366-749324c456e9.png)

**Comment by a1012112796** [comment]
That's because the buttons part div was be considered as a child of ``non_template`` div, but in tmpl file, it's not. I don't why.

![tmp](https://user-images.githubusercontent.com/25342410/93737200-24322400-fc15-11ea-9983-c3c17d8cbb00.jpg)

https://github.com/go-gitea/gitea/blob/2dbca92a0f145ddf6d0e3d4487be28071f6fd792/templates/repo/create.tmpl#L103-L198

**Comment by 6543** [comment]
#12924 fix view if you dont use templates - for templates we need to look closer  ...

**Comment by 6543** [comment]
#12924 fix this :)
