### ISSUE TITLE
Pull request can't be merged with notification "This Pull Request has changes requested by an official reviewer."

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#12954]
- Gitea version (or commit ref):
1.13.0+dev-683-gb725c4ee5
- Git version:
2.26.2
- Operating system:
Alpine Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Pull request can't be merged with notification "This Pull Request has changes requested by an official reviewer.", though there is only 1 approval requirement for target branch which has already been satisfied.

...

## Screenshots

![Screenshot from 2020-09-27 12-12-32](https://user-images.githubusercontent.com/29179059/94361179-15d38480-00bb-11eb-89e8-2ab80c8ce9b3.png)
![Screenshot from 2020-09-27 12-13-01](https://user-images.githubusercontent.com/29179059/94361181-166c1b00-00bb-11eb-81e6-afa03e4667a3.png)

**Comment by themikemayer** [comment]
We are experiencing the exact same problem.

- Gitea Version
1.12.5
- Git version
2.24.0
- Database
SQLite

Everything seems to work as long as we do not assign a "Reviewer".

At first, the PR indicates 0 of 1 required approval. -> Correct.
As soon as someone approves the PR, it shows "This Pull Request has changes requested by an official reviewer." -> Incorrect.

**Comment by zeripath** [comment]
Can you replicate this on try?

**Comment by themikemayer** [comment]
Yes I can replicate it on try. Only happens if I manually assign multiple reviewers.
**User:** tmm0001
**Repo:** sandbox

_(1) Before Approval_:

![2020-10-07 08_32_22-#1 - Just a test commit; - sandbox - Gitea_ Git with a cup of tea](https://user-images.githubusercontent.com/57800819/95295954-3ac4b600-0878-11eb-8fb9-ae5362520aa5.png)

_(2) After Approval_:

![2020-10-07 08_33_26-#1 - Just a test commit; - sandbox - Gitea_ Git with a cup of tea](https://user-images.githubusercontent.com/57800819/95295797-02bd7300-0878-11eb-8eb1-1d8adfb5e318.png)

**Comment by dungjk** [comment]
I also get same issue.
- Branch setting: Required approvals = 0
- Number of **Reviewers** added to PR > 1
=> If one of **reviewer** approve then it will show these message

Solution: Remove **reviewer** that not reviewed

**Comment by lakostin** [comment]
any news?

**Comment by zeripath** [comment]
Hi! Sorry for letting this issue fester is this still a problem on 1.15.0-RC2 or on try.gitea.io?
