### ISSUE TITLE
Can not save ldap-user config in site admin page.

### ISSUE THREAD

**Issue by sanigo** [go-gitea/gitea#12952]
- Gitea version (or commit ref): 1.12.4
- Git version: 2.12.2
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When save users that are from ldap, gitea complains `Password length cannot be less than 6 characters.`

## Screenshots
<img width="1450" alt="截屏2020-09-27 上午10 43 44" src="https://user-images.githubusercontent.com/3064634/94354543-9f308a00-00ae-11eb-804c-73876d95213e.png">

**Comment by zeripath** [comment]
This is interesting because Password length cannot be less then x characters is `auth.password_too_short`

Now presuming you are posting to: 

`/admin/users/:id`

That matches:

https://github.com/go-gitea/gitea/blob/3878e985b66cc6d4cb4d2b0e7406d5cf91af6191/routers/routes/routes.go#L450

i.e.

https://github.com/go-gitea/gitea/blob/3878e985b66cc6d4cb4d2b0e7406d5cf91af6191/routers/admin/users.go#L200-L201

then this can only be emitted:

https://github.com/go-gitea/gitea/blob/3878e985b66cc6d4cb4d2b0e7406d5cf91af6191/routers/admin/users.go#L227-L233

So the question is why is the form.Password not empty...

**Comment by zeripath** [comment]
Probably the safest thing to do is to ignore this setting unless it would have been shown - and in fact we should definitely do that.
