### ISSUE TITLE
[API] Add an delete tag option to DELETE releases

### ISSUE THREAD

**Issue by sigma-frossignol** [go-gitea/gitea#12973]
When the release is deleted via the web interface the tag is deleted
When the release is deleted via the API the tag is not deleted

The DeleteReleaseByID function already has an argument to either delete or not the tag.

that argument is set to true when called from the web interface 
https://github.com/go-gitea/gitea/blob/3878e985b66cc6d4cb4d2b0e7406d5cf91af6191/routers/repo/release.go#L353

and to false when called from the API
https://github.com/go-gitea/gitea/blob/3878e985b66cc6d4cb4d2b0e7406d5cf91af6191/routers/api/v1/repo/release.go#L333

that'd be nice we could decide wether or not we want to delete the tag whith the API call

Thanks in advance

**Comment by 6543** [comment]
similar to #12913

**Comment by 6543** [comment]
I think this can be done as in query option?
or should we start sending a json in body ... ?

github does not have this option so we are free to invent one

**Comment by jolheiser** [comment]
From what I can tell, there isn't really a defined standard. You _can_ send query parameters and you _can_ send a body with a DELETE request, however it is not in the spec (from what I could tell) and so it would be somewhat undefined territory.

I think, unfortunately, this should probably be delegated to #12913 and will require two API calls to completely remove a release and tag.

-----

I think this is fine when considering git has no concept of a release (it as a construct made up by services like ourselves and GH).

Releases are tied to tags, thus creating a release means creating the required tag as well.  
However, deleting a release does not inherently mean the tag should be deleted, because tags can be created via git itself.

**Comment by jolheiser** [comment]
Resolved with #13358
