### ISSUE TITLE
[Question] is the swagger.json available at a static place?

### ISSUE THREAD

**Issue by erikh** [go-gitea/gitea#13219]
Hopefully this question is welcome. I'd like to generate a golang client for it that's reliable enough to include in my source tree, but have a little hesitation generating from local instances or through the demo site.

I can probably make this work but it'd be nice if you would consider hosting archived versions somewhere.

**Comment by jolheiser** [comment]
Well, first I'd like to mention

1. We do have a Go client over at [go-sdk](https://gitea.com/gitea/go-sdk)
2. I've also tried to generate based on Swagger, and in all honesty it didn't end up being all that worth it due to a few various problems. My archived repo can be found at [gitea-sdk](https://gitea.com/jolheiser/gitea-sdk) ([README](https://gitea.com/jolheiser/gitea-sdk/src/branch/master/README2.md))
   * It had some problems with `nil` values, specifically around dates. This could probably be patched, but it's manual work to remember to do.
   * There are other things details in the linked README that didn't quite come out right.

All that being said, you could take a look at my [Makefile](https://gitea.com/jolheiser/gitea-sdk/src/branch/master/Makefile) to see how I did it. Basically you grab the raw template from e.g. [master](https://raw.githubusercontent.com/go-gitea/gitea/master/templates/swagger/v1_json.tmpl) and make sure to remove the parts with `{{AppSubUrl}}` (since `.tmpl` refers to it being used as a Go template)

I'm going to close this issue because "archived" versions technically exist via raw content on their specific branch. 🙂

**Comment by erikh** [comment]
Thanks for the discussion, appreciate the refs to the sdk! Helps a lot.

**Comment by erikh** [comment]
oh, one last thing. I couldn't find anywhere where this sdk was documented in the official documentation. I just wanted to let someone know, because it lead to this question!

**Comment by jolheiser** [comment]
Hmm, I suppose it isn't directly mentioned in documentation, however there are a few spots that I think could get you there.

Both the [CI/CD](https://docs.gitea.io/en-us/ci-cd/) and [Third-party tools](https://docs.gitea.io/en-us/third-party-tools/) pages refer you to [awesome-gitea](https://gitea.com/gitea/awesome-gitea), which has an [SDK](https://gitea.com/gitea/awesome-gitea#user-content-sdk) section.

Perhaps the documentation could link to the SDK section for those interesting in building integrations.

**Comment by techknowlogick** [comment]
@jolheiser maybe on our API documentation page: https://docs.gitea.io/en-us/api-usage/

**Comment by 6543** [comment]
@erikh if some things to go-sdk are unclear ... pleace create an issue at https://gitea.com/gitea/go-sdk/issues :)

**Comment by erikh** [comment]
@6543 thanks! It looks really great so far.
