### ISSUE TITLE
add refs/tags/* permission

### ISSUE THREAD

**Issue by hilariocoelho** [go-gitea/gitea#13403]
## Description

At the current Gitea's version any user with repository "write" permission can create and push a new tag. Gitea should add more granularity for permissions configuration so I can specify if users/teams have commit/tag push permissions, tag/branch delete permissions...

Since we are using tag event to trigger release CI pipelines, anyone who can commit code to a repository can also create a new tag which means create a new repository release.

Github, GitLab, Bitbucket, Gerrit... all those git systems allow to remove repo tag permission to certain users/teams-

- Gitea version (or commit ref): v1.12.5

**Comment by SpaWn2KiLl** [comment]
This is kinda related to #12293.

I would like to limit merges to master with "Merge pull request" options and "Squash and merge" to any other branch but `release/*`/`release-*`. If I could also forbid contributors to create tag I could have a perfect GitFlow model implemented with CI/CD pipelines for all development and delivery lifecycle where all commits of a feature/fix would be squashed into one commit only and then a batch of features/fixes would be simply merged to `master` or `release` branch. This way I could have an auto generated changelog for each release containing the name (and link) of all merged PRs.

Every release is associated to a git tag and the CI/CD pipeline would create the tag on every `push` event to master or release branches. Then I would have a pipeline triggered by the `tag` event that would create the release and deploy my product into a given environment.

In order to have such a model implemented I think these would be the required changes:
- Define merging options per branch (or at least the default merge option);
- "Developers" team would only be able to push commits to any branch but `release/*`/`release-*`;
- "Project Admins" team would be able to push commits to `release/*`/`release-*` branches;
- No one can push commits to `master` or `develop` branches.
- No one but "CI/CD" user/team would have permissions to create a git tag

**Comment by delvh** [comment]
Should have been implemented by #15629 over a year ago.
