### ISSUE TITLE
Conflicting files shown on pull request but merging without conflict

### ISSUE THREAD

**Issue by mschoettle** [go-gitea/gitea#13679]
- Gitea version (or commit ref): `1.12.5` and ` 1.14.0+dev-251-g78204a7a7`
- Git version: `2.24.1`
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I created a pull request which showed me that one of the files was conflicting. I then wanted to resolve this conflict locally but the merge worked just fine.

I re-created this on `try.gitea.io` with a simplified example, see this test repo: https://try.gitea.io/test-gitea3/conflict-test

**Steps taken:**

1. created initial version on `master`
1. created branch `test`
1. modified same file on branch `test`
1. modified same file on branch `master`
1. created PR

**Result:**

> 	This pull request has changes conflicting with the target branch.
settings.py

This is the output when merging locally:

```
$ git merge test
Auto-merging settings.py
Merge made by the 'recursive' strategy.
 settings.py | 41 +++++++++++++++++++++++++++++++++++++++--
 1 file changed, 39 insertions(+), 2 deletions(-)
```

**Comment by 6543** [comment]
the easyest workarounds would either be a **rebase** or a merge from base int head-branch.

**Comment by lunny** [comment]
I found sometimes github also has the problem. It seems it depends on different merge style.

**Comment by mschoettle** [comment]
Interesting. How are the conflicting files determined?

**Comment by a1012112796** [comment]
check logic is here 
note: ``tracking`` is the head branch
https://github.com/go-gitea/gitea/blob/24330f71b6ee874debec273952579c7c07d61140/services/pull/patch.go#L111-L126

**Comment by a1012112796** [comment]
maybe we can try this way
```
# try merge by ``--no-commit``
zzc:conflict-test (master)$ git merge --no-commit --no-ff test_2 
Auto-merging aa.c
CONFLICT (content): Merge conflict in aa.c
Automatic merge failed; fix conflicts and then commit the result.
# get conflict markers by ``--check``
zzc:conflict-test (master *+|MERGING)$ git diff --check 
aa.c:3: leftover conflict marker
aa.c:5: leftover conflict marker
aa.c:7: leftover conflict marker
zzc:conflict-test (master *+|MERGING)$ 
```

**Comment by zeripath** [comment]
```
$ git merge test
Auto-merging settings.py
Merge made by the 'recursive' strategy.
 settings.py | 41 +++++++++++++++++++++++++++++++++++++++--
 1 file changed, 39 insertions(+), 2 deletions(-)
```

Please note the merge made by 'recursive' strategy. That means that the merge required a checked out copy of the codebase to do the merge. We cannot do that.

@a1012112796 your proposal would also require a complete checked out copy of the codebase.

**Comment by a1012112796** [comment]
> ```
> $ git merge test
> Auto-merging settings.py
> Merge made by the 'recursive' strategy.
>  settings.py | 41 +++++++++++++++++++++++++++++++++++++++--
>  1 file changed, 39 insertions(+), 2 deletions(-)
> ```
> 
> Please note the merge made by 'recursive' strategy. That means that the merge required a checked out copy of the codebase to do the merge. We cannot do that.
> 
> @a1012112796 your proposal would also require a complete checked out copy of the codebase.

@zacheryph secound choice, should check diff beturn head branch and merge base if they are not same. only when the file has been changed is in ``git diff merge_base head_branch`` and  ``git diff merge_base base_branch`` is real conflict file. how about this way?

**Comment by MarkusAmshove** [comment]
Related: #6417

**Comment by zeripath** [comment]
I think we need to be clear here that the automatic system in gitea can never be as good a merger as git on the command line.

Why?

Well git on the command line has a checked out copy and can do octopus merges and take account of history to resolve conflicts that the system cannot do.

We can only do basic diff patch applications.

**Comment by lunny** [comment]
In fact, github also has the problem.

**Comment by MarkusAmshove** [comment]
#6417 demonstrates a case where GitHub shows a PR as mergeable while Gitea doesn't, although I haven't tried that exact case in Gitea in a long time, maybe there have been improvements already

**Comment by fergusonsa** [comment]
I have a similar issue. Using git, I created a branch from a feature branch, deleted over 1000 of old files and directories. One of the directories contained 10 .docx Word files. I committed these changes, pushed them to my remote repository on the Gitea v1.14.1 server, and created a pull request to push the deletes to the feature branch. Gitea complained that "This pull request has changes conflicting with the target branch. ", listing the the 10 .docx Word files. 

No option was provided to merge the feature branch to my branch.
I tried to checkout and pull the feature branch, but git said it was already up to date. I checked out my branch and tried merging the feature branch but git again said it was already up to date. 

In Gitea, on the Files Changed tab, it does show the contents of the docx files as being deleted.

**Comment by zeripath** [comment]
At the risk of repeating myself - we cannot be as good at conflict resolution as git with a worktree.

Having a worktree allows git to run `git merge-index`, `git merge-one-file` and `git merge-file` allowing it to resolve intra file conflicts.

Without a worktree present - which we cannot have - we are limited to a much stronger set of conditions.

If you genuinely believe that the is a better algorithm for merge collision detection please provide it - however, it can only be run in a bare repository - not one with a worktree. (You are allow to create an index file though.) The above demonstration is a false comparison because there is a worktree present.

**Comment by a1012112796** [comment]
> Having a worktree allows git to run git merge-index, git merge-one-file and git merge-file allowing it to resolve intra file conflicts.

@zeripath Note: ``git merge-file`` not need work tree. just request two file.
![image](https://user-images.githubusercontent.com/25342410/127243382-8199fa03-e6ac-4abd-9e03-a00065461e72.png)

**Comment by zeripath** [comment]
Sorry - yes `git merge-file` shows the way that you could avoid having to checkout the entire worktree to assess for mergeability.

**Comment by giordanolins** [comment]
I am the responsible for deploying Gitea on the company. Some devs have found this issue, and after arriving to this thread I tried a couple solutions for the problem. Despite the fact that we have different merge strategies that "are not supported" by gitea for the reasons mentioned above, every time I restart the server, the devs are capable of creating the PRs. Why is that? Here is my error log and the issue seems to be the same. Why after a restart it works if the "merge strategy" is "limited"? :/

`2021/09/20 14:17:24 ...dules/git/command.go:120:RunInDirTimeoutEnvFullPipelineFunc() [D] /data/gitea/tmp/local-repo/pull.git026407621: /usr/bin/git -c credential.helper= -c protocol.version=2 -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= diff -p --binary 29c82abb3763511d55950bcb21be93c0b90561cf tracking,
2021/09/20 14:17:24 ...rvices/pull/patch.go:114:checkConflicts() [E] Unable to get patch file from 29c82abb3763511d55950bcb21be93c0b90561cf to feature/IC-17046 in Genius/SourceCode Error: exit status 128,
2021/09/20 14:17:24 ...ers/web/repo/pull.go:1113:CompareAndPullRequestPost() [E] NewPullRequest: Unable to get patch file from 29c82abb3763511d55950bcb21be93c0b90561cf to feature/IC-17046 in Genius/SourceCode Error: exit status 128,
2021/09/20 14:17:24 ...s/context/context.go:185:HTML() [D] Template: status/500,
2021/09/20 14:17:24 Completed POST /Genius/SourceCode/compare/14.0.0...feature/IC-17046 500 Internal Server Error in 262.213925ms,
2021/09/20 14:17:24 Started GET /avatar/a648882f54a315b38d3678634b264be5?size=96 for 10.0.0.3:50250,
2021/09/20 14:17:24 ...s/context/context.go:740:1() [D] Session ID: eb6b8a26aea8e4bf,
2021/09/20 14:17:24 ...s/context/context.go:741:1() [D] CSRF Token: JX18PgPaRWarf_8-ydBuGpnU6iQ6MTYzMjE0NzMzNzI3NzI0NTQ3NA,
2021/09/20 14:17:24 ...ices/auth/session.go:57:SessionUser() [T] Session Authorization: Found user[3],`

**Comment by jpraet** [comment]
I quite often run into this as well. Our CI applies automatic dependency upgrades to Maven pom.xml.
It does this for PR builds as well as builds of master and release branches.
When the exact same change has been automatically applied on the PR branch, as well as the target branch,
we get "This pull request has changes conflicting with the target branch: pom.xml".

**Comment by zeripath** [comment]
Hmm... 

I've just had a thought - maybe we can use `git read-tree -m` here. 

---

What is really needed though is a few good testcases that reliable replicate the problem because without them we cannot be sure that any improvement we suggest is actually an improvement.

**Comment by jpraet** [comment]
Here's a minimal reproducer for my usecase: https://try.gitea.io/jpraet/conflict-detection/pulls/1

**Comment by zeripath** [comment]
OK, my proposed PR using `git read-tree -m` works correctly for that.

Can you give an example that should conflict too?

**Comment by jpraet** [comment]
This one should conflict: https://try.gitea.io/jpraet/conflict-detection/pulls/2

**Comment by zeripath** [comment]
yup and #18004 does that correctly too.

**Comment by jpraet** [comment]
Unfortunately OP's https://try.gitea.io/test-gitea3/conflict-test/pulls/1 example is still detected as conflicting with #18004.

**Comment by zeripath** [comment]
OK if we do an git apply with --3way that will work but we can't do that for git <2.32.0.

now `git merge-tree` will output a reasonable attempt at merge but I'm not sure how to ingest that/ensure it's correct.

**Comment by zeripath** [comment]
To get this working properly means that I would need to reimplement git-merge-one-file but so that it can work without a worktree. 

I think that's possible and it would improve the cherry-pick PR I've written too. I'll look at it but I'll leave #18004 up as it's a clear improvement from what we currently have. If #18004 isn't merged by the time I've done that I'll update it.

**Comment by MarkusAmshove** [comment]
My repro from #6417 is no longer on Gitea, but the repository is still on Github if you want to try that one too :-)

**Comment by zeripath** [comment]
OK I've finally implemented git-merge-one-file within gitea - it wasn't actually that bad I can't believe I've been avoiding doing that for 3 almost years.

**Comment by zeripath** [comment]
Now that the git-merge-one-file algorithm is implemented, to improve further would require implementing a checkoutless git merge recursive or even ort. 

This would be quite a bit more difficult and potentially quite a bit slower.
