### ISSUE TITLE
Comments for PR are in the wrong spot on the main page.

### ISSUE THREAD

**Issue by iarepandemonium** [go-gitea/gitea#13683]
- Gitea version (or commit ref): Gitea Version: 1.14.0+dev-208-g6280af032
- Git version: 2.29.0
- Operating system: linux 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
When the page is shown, the comments are in the wrong location. On the main page they are in the wrong spot, but where i commented on them in the actual diff its in the right spot.

## Screenshots

![image](https://user-images.githubusercontent.com/8331173/100027679-46822280-2dbb-11eb-90ed-51c6a22a10cd.png)

![image](https://user-images.githubusercontent.com/8331173/100027659-3e29e780-2dbb-11eb-82aa-d81986f3e0a7.png)

**Comment by afocus** [comment]
1.13 has the same problem

**Comment by jpraet** [comment]
Also running into this issue after upgrading to 1.13.0. On the conversation overview page some comments are in the wrong location, or have no code context showing at all. On the actual files diff page the comments are on the correct locations.

I can't reproduce my particular example on https://try.gitea.io because it is happening for a file larger than 1000 lines (I have custom value for MAX_GIT_DIFF_LINES = 10000).

**Comment by jpraet** [comment]
It's not just a UI bug, the diff snippet that is listed on the overview page for these review comments is also incorrect in the database.

I think it may be related to this PR: https://github.com/go-gitea/gitea/pull/13448/files#diff-db20b9154b0af934aaf3b3fea8463c4e597562b7f75aa0ae70164fc55383454dR178

The `GetRepoRawDiffForFile` used to be called with the `headCommitID`, now it is called with the `commitID` from the blame for the commented line.
