### ISSUE TITLE
Kanban "board" naming is misleading, Column is a better name

### ISSUE THREAD

**Issue by remram44** [go-gitea/gitea#13802]
- Gitea version (or commit ref): 1.13.0
- Git version: all
- Operating system: all
  
  
  
- Database: all
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

The "board" naming is inconsistent with the rest of the world. Basically everywhere else (original Kanban method, Trello, GitHub, GitLab, ...) the "board" refers to the whole wall. A "project" in Gitea (or GitHub) is a single "board". A column in the board is referred to as "list" (Trello, GitLab), "column" (GitHub), "step" (original method), never "board".

Having used many of those systems, Gitea's interface had me very confused and it took me minutes of starring at my single-column board to figure out how to add new columns. It was just so obvious to me that the "new project board" button at the top right would create a board, and not add a column to the current board.

Additionally, referring to a Kanban view (e.g. board) as a "project" is also confusing, since one would assume that "project" = "repository" (e.g. my software project, which has a repo and bug tracker). This is what GitLab calls them (since it is possible in GitLab to disable the Git repository feature, to use only the bug tracker or package storage features for example). However I understand GitHub called them "project" first and I'm sure that's why you did this.

## See also

* Issue #3476 "SCRUM backlog/sprint backlog per project "
* PR #8346 "Kanban board"

### Trello

![Trello](https://user-images.githubusercontent.com/426784/100932749-5506c300-34ba-11eb-866b-1c2523cbd8d9.png)

![Trello](https://user-images.githubusercontent.com/426784/100932759-57691d00-34ba-11eb-8898-d020d0a73c4f.png)

### GitLab

![GitLab](https://user-images.githubusercontent.com/426784/100932766-59cb7700-34ba-11eb-8f3b-2fb9972cb0d9.png)

### GitHub

![GitHub](https://user-images.githubusercontent.com/426784/100932776-5cc66780-34ba-11eb-821f-cc1d6759313b.png)

**Comment by lafriks** [comment]
Yeah, I just only now tried and had the same confusing associations myself. I would propose to rename "Projects" to "Boards" and "Board" to "Column"

**Comment by zaha** [comment]
Just fell into the same trap 😂

**Comment by wolftune** [comment]
> I would propose to rename "Projects" to "Boards" and "Board" to "Column"

I'm skeptical about renaming "Projects" to be called "Boards" because projects are useful organizing of issues whether or not we use the board view really, particularly if this is done https://github.com/go-gitea/gitea/issues/15553

But I do see an issue with "projects" as a name since often an entire um, *project* is the whole user/myproject space, which includes the repo, issues, PRs, etc. and I think that's how GitHub and GitLab etc use the term. That said, GTD uses "project" the way Gitea does. Gitea calls the whole set of stuff "repository", and then calls the git-tracked content (not issues etc) "code" which is unfortunate for all the various non-code projects such as markdown-based text for human reading (although markup like markdown is arguably "code" I guess).

Anyway, "board" referring to a particular *view* of a project makes sense, so I support the request here. Use "column" to refer to each column of a board. Just don't use "board" to refer to the project overall.

**Comment by lonix1** [comment]
Agree with OP, respectfully disagree with @wolftune. There is a standard nomenclature, and right now gitea gets it wrong.

The word "project" means different things to different people at different times. Whether that page represents part of a project, an entire project, multiple projects, or whatever, is up to the user.

*But, that page that has columns and swimlanes and tasks - that's a kanban board*.

**Comment by wolftune** [comment]
@lonix1 you are **not** disagreeing with me. I am **not** saying (and did not say) that the view of columns-and-lanes-and-tasks should be called anything other than a "board". That view is a board, that's what it is.

I'm saying that it's not *ideal* (though it might be the practical trade-off *if* the term "project" should be reserved for something else for some reason) to use "board" to refer to projects. Projects are (using GTD speak, and as GItea uses the term now) a collection of issues where once *all* those issues are done, the project has been completed. Milestones work like that too, but the difference is that milestones are like "we agree to do all these things by Friday" or "we will include all this in v1.4" regardless of any relationships among that set of issues. Projects are strictly-related issues that all go together to accomplish some larger *project*, and it makes sense to be able to group issues that way whether or not you use the **board view** (which is me *agreeing* with your use of "board").

Projects could in principle be eventually viewed with a different style than kanban and the set of these-issues-all-need-to-be-done-to-accomplish-this-project remains.

Again, I *agree* that the thing you *see* in Gitea today when you click the title of a project, that *whole* 2-dimensional layout is a "board".

**Comment by lonix1** [comment]
@wolftune I'm sorry if I misunderstood you, but to be frank, I still don't understand. You said that you agree it should be called a board, not a project, but you also said it's "not ideal".

The feature was introduced as a "kanban board" by PR https://github.com/go-gitea/gitea/pull/8346. So it should be named a "board". Anything else is not kanban.

If we agree, then there's no point in arguing because we'll just derail this thread.

**Comment by eeyrjmr** [comment]
The project tab can hold multiple boards thus it should be labelled board (singular).

**Comment by anbraten** [comment]
There are two parts which could be renamed. - Gitea "board" => column / list
- Gitea "project" => board / ..., or leave it as is

The first one is way more important IMO.

**Comment by wolftune** [comment]
> The project tab can hold multiple boards

The tab is "projects" plural, so the implication is that each item on that tab is a "project".

Just now, verifying this, I got confused with the "New project board" button because I thought for a moment it meant I could make a *whole new view* with multiple columns (i.e. imagine a project with specific issues included and *multiple* kanban boards where for example, person-A and person-B could *view* the same set of issues in different column arrangements).

I 100% support the renaming of "board" to "column"

I think all the misunderstandings are that I am imagining a potential future where projects have *additional* features and uses besides kanban board. Right now, projects have *no* other feature, the *only* thing they do is present a kanban board, and that's why others here think they could be renamed "boards". We all agree on the meaning of the word "board" here.

Consider how GitLab uses "epics" (proprietary EE feature, boo) https://docs.gitlab.com/ee/user/group/epics/index.html they are like higher level ways of grouping issues that are different from milestones. I actually think it is bad and confusing how they have boards, epics, milestones… too many different distinct ways of organizing. But I can imagine Gitea "projects" being like epics and *containing* board(s) (plural perhaps). So, that's why I'm hesitant to just rename "projects" to "boards".

An alternative idea: go ahead renaming projects to boards, don't expand the function of "projects", but allow issues to be *nested* instead of just flat (just allow any issue to have parent- and sub-issues).

All I'm saying boils down to: consider the potential or plans for future features of "projects" before deciding that they are *just boards*.

**Comment by lonix1** [comment]
What you are saying is you want more than kanban... various useful project management features. That is fine, I agree, I also want more features, as most other people here do.

So open a new issue and let's discuss. But we must remember that this issue is to fix the kanban board feature *that already exists*. It has confusing conceptual bugs. The more we complicate this issue, the less chance we'll move forward.

**Comment by wolftune** [comment]
@lonix1 yes, put shortly: I want "board" to refer to a whole kanban board, as this issue asks for. I'm just suggesting *considering* leaving "project" as the name *in case* other features besides kanban might be later added. So, do we now say "boards" and drop "projects" or do we say that "projects have boards" (perhaps multiple) and have both terms? Indeed, any other features projects might have would be separate issues.

**Comment by remram44** [comment]
Can we agree that "board" should be renamed to "column", and PR towards
that would be accepted?

Then it sounds like we agree "project" should be renamed "board", unless
there is still discussion there?

**Comment by lafriks** [comment]
I agree for renaming

**Comment by lunny** [comment]
Let's rename it to `Column`.

**Comment by remram44** [comment]
Both Trello and GitLab call those "lists" but "columns" is fine as well (and matches GitHub's naming, though it is confusing, with "projects" for boards, which recently moved from inside repositories to alongside them in an organization).

![Trello](https://user-images.githubusercontent.com/426784/187086454-3d6aaa0d-abdb-4591-895c-507f62502597.jpg)

![GitLab](https://user-images.githubusercontent.com/426784/187086456-53a6ab5a-2df0-420e-9d55-da05a4617621.jpg)

**Comment by wolftune** [comment]
I like "columns". "Lists" are all sorts of things in different uses, not as precise a name. "List" is almost like the set of things, whereas column is the container, which is an appropriate name in this case.

**Comment by remram44** [comment]
If none of the stuff proposed by @wolftune is being considered, then I agree column is good. In fact I prefer it.

If you are considering the reuse of those categories somewhere else than in boards, or if the board might be shown in a way that is not a traditional Kanban view, then you will have a similar problem again down the line when those "columns" can be shown in ways that are not columns.

**Comment by wolftune** [comment]
@remram44 "columns" still can be the name for those parts of "boards" (again, I *agree* the whole view is a "board") even if there's another view later added in which the same set of issues is shown.

So, GitLab implements kanban columns by use of labels. When you drag an item from one column to another, it removes a label and adds a different label. You can view those same sets of things simply by filtering the issue list by label. The fact that there's another view of the same issue collection doesn't cause any trouble in calling them "columns" in the kanban view.

**Comment by lonix1** [comment]
I'm sure we will have, in time, many useful project management features and plugins, and we'll have these naming arguments each time. But to make such features useful to the widest audience, we should stick to the basics.

Kanban = board + columns + swimlanes + cards.

**Comment by anbraten** [comment]
I started renaming `boards` to `columns`. #20985 
I would suggest renaming / rearranging other terms in a new PR if necessary.

**Comment by tobiasBora** [comment]
I 100% agree with renaming to colums… regarding "projects" I agree that it is confusing as it could mean many different things. To adress @wolftune comment that the tab "project" may contain other stuff than boards whose aim is to organize issues, then it may be possible to find another name for the tab that is neither "project" nor "kanban"… However I feel that "boards" is not as specific as "kanban" (quoting @lonix1 `Kanban = board + columns + swimlanes + cards`), so I guess we could still imagine other kinds of organization models that can be considered as boards. But if you think that boards = kanboard, then we can think of other names… maybe "Organize" (but we also want to avoid confusions with "Organizations"), "Arrangements", "Classification"…

**Comment by wolftune** [comment]
@tobiasBora FWIW, "projects" is problematic anyway. GTD uses "project" to just mean like an epic, a thing that requires many issues to get completed. However, "project" is often used to mean almost "product" in the sense of Gitea itself being called a "project" which never ends, "project" being the ongoing work, while "product" is the existing thing as it stands and can be used. I really wish to find a good word to replace the GTD meaning. I think the GTD meaning is an important abstraction. I don't really like "epic" as a name. I'm not going to keep arguing about this unless an ideal solution arises. I'll accept "boards" or "kanban", since "projects" and "project-management" and "workflow" and other options are all not *great*.

**Comment by lunny** [comment]
I think #22767 has partially resolve the problem.
