### ISSUE TITLE
Drone CI Gitea-Release 404 not found

### ISSUE THREAD

**Issue by cmueller-tp** [go-gitea/gitea#13902]
- Gitea version (or commit ref): 1.13.0 (system package)
- Git version: 2.26.2
- Operating system: Alpine Linux PPC64le
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
```
[Macaron] 2020-12-08 13:51:16: Started GET /api/v1/version for <ip>
[Macaron] 2020-12-08 13:51:16: Completed GET /api/v1/version 200 OK in 2.357098ms
[Macaron] 2020-12-08 13:51:16: Started GET /api/v1/repos/trufflepig/minion/releases?limit=0&page=0 for <ip>
[Macaron] 2020-12-08 13:51:16: Completed GET /api/v1/repos/trufflepig/minion/releases?limit=0&page=0 404 Not Found in 3.216813ms
[Macaron] 2020-12-08 13:51:16: Started POST /api/v1/repos/trufflepig/minion/releases for <ip>
[Macaron] 2020-12-08 13:51:16: Completed POST /api/v1/repos/trufflepig/minion/releases 404 Not Found in 3.33654ms
```
I did not find any other logs related to this problem.

## Description
Hi folks!
We're using Drone CI and since we've updated Gitea to 1.13.0 the Gitea release plugin gives us a 404 when trying to upload artifacts from Drone.
The only change I found that seems somewhat relevant is #12933 but I don't think it causes the 404.
I'd appreciate any help, sorry for not being able to provide more (helpful) information.
Cheers

**Comment by cmueller-tp** [comment]
Ok, there were actually 2 issues:
after updating Gitea, we had to:
- regenerate the API key
- refresh the oauth2 client secret

both were necessary to get drone properly working again.

**Comment by techknowlogick** [comment]
Unfortunately we are unable to offer debugging for third party software (specifically the drone plugin). I recommend opening up an issue at: https://github.com/drone-plugins/drone-gitea-release for the plugin itself.

I suspect that since you've regenerated the API Key and the oauth2 client secret and don't run into this issue anymore we won't be able to debug it.

As for providing logs in these issues please read: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems as right now we can only see that some routes gave a 404, but by following that then gitea will provide debugging information. Also in the future providing additional details also is helpful, for example what version of drone are you using, what version of Gitea did you upgrade from, etc... and to keep separate issues in separate threads.

Since your drone install is working again I will close this.
