### ISSUE TITLE
Support adding GPG signing sub-key

### ISSUE THREAD

**Issue by etanot** [go-gitea/gitea#14036]
**Type** : Feature request

## Description
As @a1012112796 has mentioned in https://github.com/go-gitea/gitea/issues/14009#issuecomment-746558233 "Now gitea only allow add public gpg keys bounded with the user's email", it would be nice if Gitea also support adding GPG sub-key, just like mention in issue https://github.com/go-gitea/gitea/issues/14009.

**Comment by quhsi** [comment]
Currently, the email address cannot be kept private when using the PGP key feature. So this issue is more a bugfix than a feature.

**Comment by zeripath** [comment]
#14054 was an attempt at fixing this issue - however, due to the lack of real life testing of this feature I've had to move it to the 1.15 milestone. Hopefully we'll merge after the merge window for 1.14 is closed.

If you really want this feature in 1.14 you will need to download and test this PR to ensure that it does what you want.
