### ISSUE TITLE
Mark repo as NSFW

### ISSUE THREAD

**Issue by SoniEx2** [go-gitea/gitea#14053]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

It'd be nice if you could mark a repo as NSFW, for projects involving NSFW topics.

**Comment by techknowlogick** [comment]
Please feel free to use repo topics to tag your repos as such.

**Comment by SoniEx2** [comment]
Opening a NSFW repo should require the user to click through, tho.

**Comment by zeripath** [comment]
I guess fundamentally we are not trying to build a general purpose file repository but instead a source code repository.

Almost all content and use of content that is not safe for work is not going to be best stored within git. That is, in the majority of cases the content will be binary data that does not change and there is in no need or meaningful use of version control. In the rare cases that there actual call for version control - i.e. because there is editing, then it's likely that the content is work and an nsfw click through would just be annoying.

Whilst a PR that added such a feature might be reasonably mergable. I'm not certain we would want to, as I don't think I understand how this would all work and what it's purpose is.

**Comment by SoniEx2** [comment]
It would be appropriate for collaborative smut, open source sex games, and whatnot. Github bans those and Gitea could provide an alternative.

**Comment by jolheiser** [comment]
Since Gitea is self hostable and has options for private, public, limited visibility orgs, etc.
I also think there are plenty of ways to achieve this without an explicit NSFW filter.
