### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by Barteling** [go-gitea/gitea#14267]
Gitea instance crashes with out of memory exception when performing sync action from visual studio
It does not happen every time, but often.

Gitea runs on an Windows 10 Hyper-V virtual machine with 8gb ram attached. I disabled dynamic memory as test but no succes.

- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

[app.ini.txt](https://github.com/go-gitea/gitea/files/5775030/app.ini.txt)
[CLI log.txt](https://github.com/go-gitea/gitea/files/5775024/CLI.log.txt)
Sample of the CLI 

> 
> 2021/01/06 10:36:58 Started GET /a
pi/v1/users/Gerhard_Barteling/repos for 192.168.250.25
> runtime: out of memory: cannot allocate 67108864-byte block (1583972352 in use)
> fatal error: out of memory
> 
> runtime stack:
> runtime.throw(0x252a93b, 0xd)
>         /usr/local/go/src/runtime/panic.go:1116 +0x64
> runtime.largeAlloc(0x4000000, 0x5020101, 0x1)
>         /usr/local/go/src/runtime/malloc.go:1179 +0x15d
> runtime.mallocgc.func1()
>         /usr/local/go/src/runtime/malloc.go:1071 +0x39
> runtime.systemstack(0x879fec8)
>         /usr/local/go/src/runtime/asm_386.s:391 +0x53
> runtime.mstart()
>         /usr/local/go/src/runtime/proc.go:1116

**Comment by lunny** [comment]
Could you paste your gitea version here?

**Comment by Barteling** [comment]
I'm using this executable: gitea-1.13.1-windows-4.0-386

**Comment by zeripath** [comment]
In future please complete the proforma in particular provide information on the version. It's highly relevant.

--- 

Right, we discovered a number of memory issues related to go-git in gitea. In master/1.14 we've switched back to using pure git commands which are much lighter on memory.

You may find that switching to using master resolves these issues.

**Comment by lmx1989219** [comment]
i meet the same problem,then i temporarily improve physical memory.
follow is the system message( centerOS7 /var/log/message):
`gitea kernel: Out of memory: Kill process 3449 (gitea) score 741 or sacrifice child`

**Comment by zeripath** [comment]
1.14.0+dev-312-g48a3bb7a3 is an unreleased version of gitea that is 774 commits behind the last released version of v1.14.7 and 1244 commits behind v1.15.2 and 1376 commits behind main.

At the time of the OP opening this issue their version was also many versions of out-of-date.

I don't doubt that there are memory issues in Gitea but we have been working hard to reduce them. It's pointless to talk about memory issues on out-of-date versions. 

Try a latest version. Give us some logs or information as to how you got the out of memory.

Looking at OP's logs - their issue was because they were using argon2 as their password hashing algorithm - that's seriously memory intensive and we changed the default password hashing algorithm back to pkdf2 for that reason. 

Update your version of Gitea - it's extremely out of date. Try to replicate the issue and open another issue if it happens again.

**Comment by lmx1989219** [comment]
thanks，i upgrade the docker image now



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 8, 2021 17:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [go-gitea/gitea] Out of memory exception (#14267)




 
1.14.0+dev-312-g48a3bb7a3 is an unreleased version of gitea that is 774 commits behind the last released version of v1.14.7 and 1244 commits behind v1.15.2 and 1376 commits behind main.
 
At the time of the OP opening this issue their version was also many versions of out-of-date.
 
I don't doubt that there are memory issues in Gitea but we have been working hard to reduce them. It's pointless to talk about memory issues on out-of-date versions.
 
Try a latest version. Give us some logs or information as to how you got the out of memory.
 
Looking at OP's logs - their issue was because they were using argon2 as their password hashing algorithm - that's seriously memory intensive and we changed the default password hashing algorithm back to pkdf2 for that reason.
 
Update your version of Gitea - it's extremely out of date. Try to replicate the issue and open another issue if it happens again.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
