### ISSUE TITLE
Add three buttons `previous page`, `directory`,  `next page` on the bottom of markdown render page when there are a summary.md in the root of tree path.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14331]
It will become convenient for read the book.

**Comment by noerw** [comment]
For reference: `SUMMARY.md` is a defacto standard filename for ToC in long-form markdown renderers like [mdbook](https://github.com/rust-lang/mdBook) and [gitbook](https://www.gitbook.com).
Its format is underspecified, and can differ a lot in handling of relative URLs, indentation, directory traversal, multi-language support

While this feature provides some UX enhancements, I'm not convinced that supporting a parser like this in core Gitea is a good idea. Because of the mentioned ambiguities in the format, there probably will never be a generic, good enough solution.
I've worked with this stuff for a while, trust me, it's a pain.

If really wanted, I'd put this in an external renderer (or do these only work on file-level?)

**Comment by techknowlogick** [comment]
I think this should be left up to external tools such as gitbook or mdbook
