### ISSUE TITLE
Complete notifications system

### ISSUE THREAD

**Issue by andreynering** [go-gitea/gitea#145]
Today Gitea can send e-mail for new Issues/PRs/Comments and that's it.

I think it should have a complete notifications system, like GitHub and GitLab.

- [x] Notifications would be saved in a database table
- [x] A page to manage them. Equivalent to https://github.com/notifications
- [x] Mark as read/unread, pinning a notification (visible even if read)
- [x] Subscribe/Unsubscribe button
- [x] Mark all notifications as read
- [ ] Mark all notifications as unread
- [ ] Automatic subscribe on Open/Comment, etc
- [ ] Also more refined watch options?
- [ ] E-mail read means notification gone. Each user should have the ability to disable this
- [ ] E-Mail notifications for pushes

**Comment by lunny** [comment]
If you watch some repository, then defaultly, you will subscribe all the issues and prs on this repository except you unsubscribe this issue.

**Comment by bkcsoft** [comment]
Please implement notifications like GitLab does, where you actually have to press "I'm done with this" before it goes away 🙂

**Comment by stevenroose** [comment]
If you add an "e-mail read means notification gone" system like GitHub's, please make it opt-out :)

**Comment by lunny** [comment]
@stevenroose that is a great idea. I think I can implement it.

**Comment by lunny** [comment]
@andreynering could you add `e-mail read means notification gone` to the check list?

**Comment by andreynering** [comment]
@lunny @stevenroose Updated

GitHub implements that by having a 1px-1px transparent image which point to `https://github.com/some-route?token=...`. When the GitHub server serve that image for the first time the notification is marked as read.

**Comment by lunny** [comment]
Yes. A small trick. :)

**Comment by stevenroose** [comment]
@andreynering I know they do it like that. But most e-mail clients don't have a feature to block displaying emails from specific senders :) So if you don't like that feature, it can be annoying.

**Comment by tboerger** [comment]
:+1: for opt-out of this feature.

**Comment by stevenroose** [comment]
@tboerger Don't get me wrong. I got to like the e-mail thing because now I read all my GitHub stuff from e-mail. But for someone who doesn't it be annoying. I had a lot of "ah, let me quickly check this issue in my email and look at it further tonight" and then I ended up not finding the issue and ploughing through archived e-mails to find it back :D

**Comment by stroucki** [comment]
My team would like commit messages, so I'm working on implementing that for all watchers to a repository.

There is a "notifyWatchers" function on commit, but all it does is make an entry in a database table.

**Comment by andreynering** [comment]
@stroucki Did you start anything?

I just started but only had time to create the database table until you sent this message. :smiley: 

Maybe we should create a feature branch and work together on this, so we don't have conflicting changes.

**Comment by stroucki** [comment]
@andreynering Actually I have something that works :)

Though it is probably not acceptable for general usage, since you can't opt out. It is similar to what gogs does for mentionemails: Do a database entry that apparently is only useful for webhooks, then send out email to all watchers.

You can see it in my fork: (note I am still based on gogs)
https://github.com/stroucki/gogs/tree/commitemails

But while testing I see that it is not working for commits made via ssh yet.

**Comment by andreynering** [comment]
@stroucki Thanks for linking your branch.

I started something on https://github.com/go-gitea/gitea/pull/321 (still in an early stage) for who's interested.

We will probably integrate notifications and email sending. Your patch will be useful.

**Comment by stroucki** [comment]
I've been looking at getting notifications working on ssh commits today.
This is pretty messy, because 1) the serve command doesn't set up any of the mailer stuff and 2) it uses "log.GitLogger" to log stuff, but the mailer initialization bits want to log, they use "log". Things don't even seem to blow up then, the git-receive-pack ends up hanging and nothing really happens.
I got to the point now where it is sending commit messages, but the command line output gets a "failed to push some refs" error (but things have committed).

**Comment by stroucki** [comment]
OK. I think I have it. I now get commit messages on https and ssh commits.

The big thing was that console logs interfere with the git processes that gogs creates. I'm guessing that since the log used stdout, the subprocess never terminated. Besides that, mailing services needed to be initialized too.
It is too late for tonight, but tomorrow I'll update my branch.

**Comment by bkcsoft** [comment]
@andreynering I also think that `Action`-table holds most of the data already. Might be worth looking into before making a new table 🙂

**Comment by lunny** [comment]
^

**Comment by andreynering** [comment]
@bkcsoft @lunny I will take a look at that, but I think we need another table. An action is created every time an issue changes, but we should have only one notification per issue/PR.

Also, an user may be subscribed to an issue but don't watch the repo, so won't have an action for him, etc. Situations like this.

**Comment by stroucki** [comment]
Is the action table actually used for anything?

**Comment by stroucki** [comment]
I committed changes to my branch that now let commit messages go out to watchers on https and ssh commits.

**Comment by andreynering** [comment]
@stroucki 

> Is the action table actually used for anything?

It's only used by the feed on the dashboard.

> I committed changes to my branch that now let commit messages go out to watchers on https and ssh commits

I'll look into integrate that after I'm done with my implementation

**Comment by bkcsoft** [comment]
@lunny this isn't done yet ,only part 1 of 2 ;)

**Comment by bkcsoft** [comment]
ooh, it was #523 that had the text "resolve #number" in it 😆

**Comment by lunny** [comment]
So not me? Or maybe we have to review and change the title when merging it.

**Comment by bkcsoft** [comment]
@lunny no need to change the title, just the body 🙁

**Comment by strk** [comment]
Is the roadmap in the original submission updated after part 2 ?
I've tested notifications on try.gitea.io but doesn't seem to be working: https://try.gitea.io/gitea/gitea/issues/1

**Comment by strk** [comment]
Step 2, merged, was #539

**Comment by andreynering** [comment]
@strk You are not watching the repo, so you won't get any notifications: 

https://try.gitea.io/gitea/gitea/watchers

**Comment by strk** [comment]
On Thu, Jan 05, 2017 at 04:39:14PM -0800, Andrey Nering wrote:
> @strk You are not watching the repo, so you won't get any notifications: 
> 
> https://try.gitea.io/gitea/gitea/watchers

I thought one of the goals of the notification system was allowing
for per-issue watchers ?

**Comment by andreynering** [comment]
> I thought one of the goals of the notification system was allowing for per-issue watchers?

Yes, but it was not implemented yet. I'm doing it in parts. By now it's only notifying watchers. I hope we get it 100℅ on v1.1.0

**Comment by gayprogrammer** [comment]
I would like to note that email notifications currently do not say which user commented on the issue. It only displays the content of the comment.

Can we add the name of who commented to the email somehow?

**Comment by tboerger** [comment]
Than the current mail template is missing that information

**Comment by mxmehl** [comment]
It would be good to have a button to **mark all notifications as read**. (I hope this is the right issue for this feature request)

**Comment by andreynering** [comment]
@mxmehl Yes, that's reasonable.

**Comment by mxmehl** [comment]
> @mxmehl Yes, that's reasonable.

Cool! Could you please add that to the list in the top post?

**Comment by andreynering** [comment]
@mxmehl Done!

**Comment by McLive** [comment]
Any update on this? I'd like to see E-Mail notifications for pushes.

https://github.com/gogits/gogs/issues/1441

**Comment by lunny** [comment]
@McLive added

**Comment by hasufell** [comment]
What I find missing here is optional admin notifications, like when a user has registered.

**Comment by Worthy7** [comment]
2019 is this not happening?

**Comment by lafriks** [comment]
@Worthy7 everyone works of features they need most as no one is paid to work on Gitea and we are spending our free time to work on this project...

**Comment by Worthy7** [comment]
That's not true - some people need the features but can't work on the project because it's in Go - a language not everyone knows. I would do this myself but I don't know anything about Go. So the best I can do is complain.
If other people don't think this is important, I'd like to know how organization owners (anyone out there) deals with issues and @mentioning people.... Perhaps I'm just using it wrong?

**Comment by stroucki** [comment]
@Worthy7 then pick up a book and start learning. It's not a secret language.

**Comment by Worthy7** [comment]
I suppose people can just get round this by unwatching/unsubscribing to everything not concerning them for now. It doesn't seem like there's much demand for the feature since last year.

**Comment by McLive** [comment]
I‘m also still waiting for this 🙈

**Comment by hasufell** [comment]
> a language not everyone knows

It takes about ~3 days to learn Go. I think you will have more problems with the sheer complexity of the application than you will have with the language :)

**Comment by worthy7** [comment]
Yea to be honest that's what I meant.

**Comment by 6543** [comment]
beside `Also more refined watch options?` <- I think for repos you mean

I'll close this, feel free to open a new issue for the speciffic case you are missing for notifications
