### ISSUE TITLE
Issue/Pull dependencies is inefficient

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14560]
look like gitea >= 1.13.0; gitea < 1.14.0 is affected

-> if you type text into search field no issues/pulls are displayed to select
-> JS does not hit the API to get issues :/

**Comment by lunny** [comment]
If it affected v1.13.0, I think we should move milestone to v1.13.3

**Comment by seigieu** [comment]
From gitea chat what I came to:
```
Gitea Version: 1.12.6  This one shows me only #20 and up.
[20:35]
@6543 search by name does not work either. Like it was limited to some number of entries to check. No idea. For example load last 10 to memory, then filter from these 10 matching elements.
[20:37]
@6543 Pattern seems to be, it only shows searches from these, that are visible on 1st page of issues.
On repo1 where I have on 1st page issues #18 and up (#19 is closed) and it shows #18 and up. without #19
On repo2 where on first page i have #20 and up visible, only these are searchable
So it seems to be bound only to 1st page of issues somehow
```

**Comment by 6543** [comment]
sqlite + 1.14.0+dev-765-g42118c6bc works ...

**Comment by zeripath** [comment]
OK I just tested on 1.13.0+30-g205be63bc 

On the issues page this works. On pulls page this works.

(Chromium linux)

**Comment by zeripath** [comment]
There is a minimum number of letters required to make it do a search - perhaps this was the issue?

**Comment by zeripath** [comment]
As I cannot reproduce I'm gonna unmilestone and mark it as needs-feedback.

**Comment by seigieu** [comment]
@zeripath  https://try.gitea.io/seigieu/test/issues/23
On this one, I currently cannot even search for issues
https://youtu.be/c_msyXXHD2I

**Comment by seigieu** [comment]
https://youtu.be/iJhSqSpA0X4 
Here is movie of my instance. 1.12.6 currently. Cant select any from second page

**Comment by 6543** [comment]
@seigieu witch browser & OS do you use?

**Comment by zeripath** [comment]
Could you add arandomer@mailinator.com to that repository as a writing collaborator so I can test.

That the number of issues is >20 makes me suspicious it's a paging issue but I'm not certain.

**Comment by zeripath** [comment]
Ok your second video looks exactly like a paging issue, does typing the issue in to the search box reveal the issues?

In your first video try.gitea.io looks like it's running very slow indeed and I suspect that the API call to list the issues hasn't returned by the time you're expecting it to have and our UI doesn't have any marker to show that it's doing a search.

**Comment by seigieu** [comment]
@6543 
Linux Firefox (newest) also Chromium. Same effect.
@zeripath i get  "User does not exist" on try.gitea.com.
If you mean my repository I cannot route it to world. It's only available in LAN. 

*(after some testing...)*

But when I tested it more to look for issue. Search seems to work. But it searches ONLY for whole words.
If i type `propa` it will not look for `popragation` etc. Have to type `propagation` literally for it to search just fine.
Typing `#33` have found `33` string in `2020-10-21 13:02:33` text line, but not issue `#33`.

I'm not sure if I didn't get confused, since I was 100% sure I can search issues by `#33` and partial words etc. 

And for pagination part. Pagination issue seems to be present only when I click and scroll down (not sure if its feature or issue now. May be feature to limit to latest entries). 

try.gitea.com - yes, its running very slow. checked in network tab and its a long loading issue.

**Comment by zeripath** [comment]
I meant on the try.gitea.io repository you'd uploaded. 

In regards to exact searching #14694 should help there.

I'll look at the rest of your comments tomorrow. Sorry I didn't get to this today.

**Comment by zeripath** [comment]
I think in part some of this issue is related to #12827

**Comment by zeripath** [comment]
Looking at try.gitea.io it appears that the improvement from 15179 could actually be sufficient to close this issue! Although I would still argue that the API is still too non-performant.

**Comment by 6543** [comment]
let it open

**Comment by 6543** [comment]
close in favour of #12827
