### ISSUE TITLE
Correct commands displayed in PR

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#14690]
Clicking to view the commands to enter in the console to integrate the PR should display the commands according to the selected integration method.

![image](https://user-images.githubusercontent.com/41587659/107968287-e8fe0c00-6f8c-11eb-9793-18ee3352bc89.png)

![image](https://user-images.githubusercontent.com/41587659/107968060-a5a39d80-6f8c-11eb-9bb7-6a14c5d69917.png)

**Comment by jolheiser** [comment]
As far as I know, the repo settings only affect the actions you can take in a PR via the button. 

You are allowed to merge however you want via CLI, as that's up to the repo owner (or someone with write permissions).

**Comment by zeripath** [comment]
The purpose here is not to show how to replicate how gitea does merging - the instructions would not be concise otherwise - the purpose is to show one method of merging.

---

However, if say you wanted the instructions to change with the selected merge option you'd need to look at several files.

Gitea's merging methods are demonstrated here:

https://github.com/go-gitea/gitea/blob/0a9a484e1e2c082f7ebd747837e9c9557b3bacac/services/pull/merge.go#L241-L367

and would need to be turned into clear and understandable instructions.

You would need to change:

https://github.com/go-gitea/gitea/blob/0a9a484e1e2c082f7ebd747837e9c9557b3bacac/templates/repo/issue/view_content/pull.tmpl#L393-L406

probably to have the various options tabbed but have it change with the results of:

https://github.com/go-gitea/gitea/blob/0a9a484e1e2c082f7ebd747837e9c9557b3bacac/templates/repo/issue/view_content/pull.tmpl#L372-L390

likely keeping the current text as the default is there are no merge options set.
