### ISSUE TITLE
postgres ERROR: duplicate key value violates unique constraint "email_hash_pkey"

### ISSUE THREAD

**Issue by ntlspck** [go-gitea/gitea#14725]
- Gitea version (or commit ref): v1.13.2 built with GNU Make 4.3, go1.15.7
- Git version:     2.26.2
- Operating system: Raspbian GNU/Linux 10, docker kunde21/gitea-arm   v1.13.2-armv7
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Using gitea 1.13.2 and postgres 13.0 I still have the following reoccuring postgres errors:

2021-02-16 21:31:14.345 UTC [20446] ERROR:  duplicate key value violates unique constraint "email_hash_pkey"
2021-02-16 21:31:14.345 UTC [20446] DETAIL:  Key (hash)=(xxxxxxxxxx) already exists.
2021-02-16 21:31:14.345 UTC [20446] STATEMENT:  INSERT INTO "email_hash" ("hash","email") VALUES ($1,$2)

I understand that this should be fixed in 1.13.0 via https://github.com/go-gitea/gitea/pull/12577 
...

**Comment by zeripath** [comment]
Your sequences have somehow become out of sync. If I had to guess this could be because the sequences are not in the same schema as the rest of Gitea.

There have been multiple recent issues (closed) on this issue - can you look at those for how to figure out how to update them.

It would be helpful to know if you're running Gitea in a schema in order to help us figure out how this happened. Or if you used a backup and restore method, or something else

**Comment by joseluisq** [comment]
I'm using the latest Gitea 1.13.4 and Postgres 13 and I got something similar but for topics.
I can add existing topics but not new ones.

In my case the problem happened after an upgrade via my Docker service. I'm just using a Gitea database with the default `public`  schema.

When I try to add a new topic Gitea complains with a status `500` for `https://server.com//my-org/my-repo/topics` and a `{"message":"Save topics failed."}` response.

The `debug` log is the following:

```log
2021/03/12 21:53:45 Started POST /my-org/my-repo/topics for 10.255.0.2
2021/03/12 21:53:45 ...s/context/context.go:332:func1() [D] Session ID: 1ab234cvy10c157f
2021/03/12 21:53:45 ...s/context/context.go:333:func1() [D] CSRF Token: oabCDEFGHIjkHlmn0PQ1234Z3D06MVYxNTU4MzUoCzU9WPWzNiyXMh
2021/03/12 21:53:45 ...outers/repo/topic.go:50:TopicsPost() [E] SaveTopics failed: pq: duplicate key value violates unique constraint "topic_pkey"
2021/03/12 21:53:45 Completed POST /my-org/my-repo/topics 500 Internal Server Error in 32.477988ms
```

**Comment by zeripath** [comment]
Your postgres sequences are out of kilter.

Are you using a schema? Were the sequences in the public schema?

You need to update your sequences:

https://github.com/go-gitea/gitea/issues/14692#issuecomment-779450604

**Comment by joseluisq** [comment]
> Are you using a schema?

Yes, I have a public schema in my gitea database.

> Were the sequences in the public schema?

Inside the same public schema.

> You need to update your sequences:
> 
> [#14692 (comment)](https://github.com/go-gitea/gitea/issues/14692#issuecomment-779450604)

I did it but doesn't help since when I execute the setintval queries I get an error on the last one:
```
SQL Error [42P01]: ERROR: relation "tmp_recreate__topic" does not exist
```

**Comment by joseluisq** [comment]
I did try to recreate the tables but doesn't help.

```
$ gitea doctor recreate-table
2021/03/13 20:19:22 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.26.2, Wire Protocol Version 2 Enabled
2021/03/13 20:19:22 ...rm/session_schema.go:25:Ping() [I] PING DATABASE postgres
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: user for Bean: User
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: public_key for Bean: PublicKey
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: access_token for Bean: AccessToken
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: repository for Bean: Repository
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: deploy_key for Bean: DeployKey
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: collaboration for Bean: Collaboration
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: access for Bean: Access
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: upload for Bean: Upload
2021/03/13 20:19:22 ...ations/migrations.go:364:func1() [I] Recreating Table: watch for Bean: Watch
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: star for Bean: Star
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: follow for Bean: Follow
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: action for Bean: Action
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: issue for Bean: Issue
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: pull_request for Bean: PullRequest
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: comment for Bean: Comment
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: attachment for Bean: Attachment
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: label for Bean: Label
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: issue_label for Bean: IssueLabel
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: milestone for Bean: Milestone
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: mirror for Bean: Mirror
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: release for Bean: Release
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: login_source for Bean: LoginSource
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: webhook for Bean: Webhook
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: hook_task for Bean: HookTask
2021/03/13 20:19:23 ...ations/migrations.go:364:func1() [I] Recreating Table: team for Bean: Team
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: org_user for Bean: OrgUser
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: team_user for Bean: TeamUser
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: team_repo for Bean: TeamRepo
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: notice for Bean: Notice
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: email_address for Bean: EmailAddress
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: notification for Bean: Notification
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: issue_user for Bean: IssueUser
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: lfs_meta_object for Bean: LFSMetaObject
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: two_factor for Bean: TwoFactor
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: gpg_key for Bean: GPGKey
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: gpg_key_import for Bean: GPGKeyImport
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: repo_unit for Bean: RepoUnit
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: repo_redirect for Bean: RepoRedirect
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: external_login_user for Bean: ExternalLoginUser
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: protected_branch for Bean: ProtectedBranch
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: user_open_id for Bean: UserOpenID
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: issue_watch for Bean: IssueWatch
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: commit_status for Bean: CommitStatus
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: stopwatch for Bean: Stopwatch
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: tracked_time for Bean: TrackedTime
2021/03/13 20:19:24 ...ations/migrations.go:364:func1() [I] Recreating Table: deleted_branch for Bean: DeletedBranch
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: repo_indexer_status for Bean: RepoIndexerStatus
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: issue_dependency for Bean: IssueDependency
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: lfs_lock for Bean: LFSLock
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: reaction for Bean: Reaction
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: issue_assignees for Bean: IssueAssignees
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: u2f_registration for Bean: U2FRegistration
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: team_unit for Bean: TeamUnit
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: review for Bean: Review
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: oauth2_application for Bean: OAuth2Application
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: oauth2_authorization_code for Bean: OAuth2AuthorizationCode
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: oauth2_grant for Bean: OAuth2Grant
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: task for Bean: Task
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: language_stat for Bean: LanguageStat
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: email_hash for Bean: EmailHash
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: project for Bean: Project
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: project_board for Bean: ProjectBoard
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: project_issue for Bean: ProjectIssue
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: topic for Bean: Topic
2021/03/13 20:19:25 ...ations/migrations.go:364:func1() [I] Recreating Table: repo_topic for Bean: RepoTopic
2021/03/13 20:19:25 ...rm/session_schema.go:360:Sync2() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
```

**Comment by joseluisq** [comment]
> ```
> SQL Error [42P01]: ERROR: relation "tmp_recreate__topic" does not exist
> ```

Since this error is related to the `topic` I assume is the reason why is not working.

**Comment by zeripath** [comment]
agh!  don't understand what is happening in that list there should not be a `tmp_recreate__topic` so I've adjusted that person's comment to just use `topic`.

Try it again!

**Comment by joseluisq** [comment]
> agh! don't understand what is happening in that listbut there should not be a `tmp_recreate__topic`. I've adjusted that person's comment to just use `topic`.
> 
> Try it again!

```sql
> SELECT setval('topic_id_seq', (SELECT MAX(id) FROM topic));
-- SQL Error [42P01]: ERROR: relation "topic_id_seq" does not exist
```

**Comment by zeripath** [comment]
Hmm. There really should be a primary key on that table: https://github.com/go-gitea/gitea/pull/12639

https://github.com/go-gitea/gitea/blob/71a2adbf10f0f3df9d9f2ab59c51bbcb19c00c4b/models/topic.go#L27-L33

and the recreate-table command should have created one too:

https://github.com/go-gitea/gitea/blob/release/v1.13/models/migrations/migrations.go#L376-L400

Could you go into your db and check?

**Comment by joseluisq** [comment]
Right now the DDL for `topic` table looks like:

```sql
CREATE TABLE public.topic (
	id bigserial NOT NULL,
	"name" varchar(25) NULL,
	repo_count int4 NULL,
	created_unix int8 NULL,
	updated_unix int8 NULL,
	CONSTRAINT topic_pkey PRIMARY KEY (id)
);
CREATE INDEX "IDX_topic_created_unix" ON public.topic USING btree (created_unix);
CREATE INDEX "IDX_topic_updated_unix" ON public.topic USING btree (updated_unix);
CREATE UNIQUE INDEX "UQE_topic_name" ON public.topic USING btree (name);
```

Is there something wrong with it?

**Comment by zeripath** [comment]
Well there should be an associated sequence on the topic primarily key...

**Comment by joseluisq** [comment]
Now I got after push some commits

```
021/03/15 00:41:33 ...odules/cron/tasks.go:103:func2() [E] CreateNotice: pq: duplicate key value violates unique constraint "notice_pkey"
```

**Comment by joseluisq** [comment]
Can you tell me how I can repair the db?
I was using inside the gitea app container: 
```
su git
gitea doctor recreate-table
```

But it doesn't fix the problem. Or am I doing the command wrong?

**Comment by zeripath** [comment]
The issue is the sequences are out of kilter. 

That means you need to go in to your postgres dB and fix them. 

We don't have a command to do that for you because we haven't written one because we didn't expect this to be such a problem.

My only suspicion is that recreate table is causing the sequences to disappear or be set at 0 but you're not giving me any information to do that.

Could you tell me the what the values of your sequences are and if they exist?

**Comment by joseluisq** [comment]
> The issue is the sequences are out of kilter.
> 
> That means you need to go in to your postgres dB and fix them.
> 
> We don't have a command to do that for you because we haven't written one because we didn't expect this to be such a problem.

That's great

> My only suspicion is that recreate table is causing the sequences to disappear or be set at 0 but you're not giving me any information to do that.
> 
> Could you tell me the what the values of your sequences are and if they exist?

I have restored the database to the previous state.
Here the sequences that the database had until the beginning of my first comment.

<details>
  <summary>Sequences in gitea.public</summary>

```sh
access_id_seq
access_token_id_seq
action_id_seq
attachment_id_seq
collaboration_id_seq
comment_id_seq
commit_status_id_seq
deleted_branch_id_seq
deploy_key_id_seq
email_address_id_seq
follow_id_seq
gpg_key_id_seq
hook_task_id_seq
issue_assignees_id_seq
issue_dependency_id_seq
issue_id_seq
issue_label_id_seq
issue_user_id_seq
issue_watch_id_seq
label_id_seq
language_stat_id_seq
lfs_lock_id_seq
lfs_meta_object_id_seq
login_source_id_seq
milestone_id_seq
mirror_id_seq
notice_id_seq
notification_id_seq
oauth2_application_id_seq
oauth2_authorization_code_id_seq
oauth2_grant_id_seq
org_user_id_seq
project_board_id_seq
project_id_seq
project_issue_id_seq
protected_branch_id_seq
public_key_id_seq
pull_request_id_seq
reaction_id_seq
release_id_seq
repo_indexer_status_id_seq
repo_redirect_id_seq
repo_unit_id_seq
repository_id_seq
review_id_seq
star_id_seq
stopwatch_id_seq
task_id_seq
team_id_seq
team_repo_id_seq
team_unit_id_seq
team_user_id_seq
tmp_recreate__topic_id_seq
tracked_time_id_seq
two_factor_id_seq
u2f_registration_id_seq
upload_id_seq
user_id_seq
user_open_id_id_seq
version_id_seq
watch_id_seq
webhook_id_seq
```

</details>

Note that the already mentioned `topic_id_seq` is missing.
Also there is a `tmp_recreate__topic_id_seq` that I have no idea why is there for.

Below the content of the `tmp_recreate__topic_id_seq`:

```sql
SELECT * FROM performance_schema.events_statements_summary_global_by_event_name AS t
ORDER BY t.COUNT_STAR DESC;
```

So please I would like to have the list of valid sequences and their queries in order to fix them manually because looks like the "repair" tool doesn't work for that purpose.

**Comment by zeripath** [comment]
Dude, I don't know if you mean to be quite as rude as you're appearing - I'm sorry that there was a mistake and an error but we can't get right all the time and I'm only inferring from what you're saying as to what the problem could be.

I do all my work on Gitea for free. I get no payment despite the many hours of time I put in to this project. It appears I get even less thanks - a little bit of appreciation for the fact that you're getting help for free would go a long way.

I'm sorry something has gone wrong and I'm just trying to help. I appreciate how stressful things, especially databases, can be when they're not working.

--- 

In terms of the Topic table, it should have a sequence attached to its primary key:

```sql
SELECT * FROM information_schema.columns WHERE table_name = 'topic';
```

for me reveals that the column default for the `id` column is `nextval('topic_id_seq'::regclass)`

Now `pg_dump -st topic testgitea` for me gives: (dropping the comments and any data)

```
CREATE TABLE gtestschema.topic (
    id bigint NOT NULL,
    name character varying(50),
    repo_count integer,
    created_unix bigint,
    updated_unix bigint
);

ALTER TABLE gtestschema.topic OWNER TO gitea;

CREATE SEQUENCE gtestschema.topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE gtestschema.topic_id_seq OWNER TO gitea;
ALTER SEQUENCE gtestschema.topic_id_seq OWNED BY gtestschema.topic.id;

ALTER TABLE ONLY gtestschema.topic ALTER COLUMN id SET DEFAULT nextval('gtestschema.topic_id_seq'::regclass);

ALTER TABLE ONLY gtestschema.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id);

CREATE INDEX "IDX_topic_created_unix" ON gtestschema.topic USING btree (created_unix);

CREATE INDEX "IDX_topic_updated_unix" ON gtestschema.topic USING btree (updated_unix);

CREATE UNIQUE INDEX "UQE_topic_name" ON gtestschema.topic USING btree (name);
```

Where `gtestschema` is the schema the topic table is in.

How do we explain this `tmp_recreate__topic_id_seq`?

The `tmp_recreate__topic_id_seq` will be related to a migration which is supposed to fix the problem of a missing Primary key on the topic table - which clearly  isn't working properly on postgres - (likely because we haven't accounted for the sequences in PostgreSQL). The sequence should have been attached to the Primary Key ID on the copied temporary topic table, and was expected to have increased in turn when copying the data into the table, finally when the topic table was renamed should have continued to be attached. Without more information I can only guess that the issue is when the data was copied in to the temporary table the sequence isn't updated and when the table is renamed the sequence isn't renamed too. 

Assuming that you discover that the `tmp_recreate__topic_id_seq` is attached to the `id` column of the `topic` table then:
`SELECT setval('tmp_recreate__topic_id_seq', (SELECT MAX(id) FROM topic));` should restore the correct value and  `ALTER SEQUENCE tmp_recreate__topic_id_seq RENAME TO topic_id_seq` should restore things completely to normal.

---

Now that I think I understand the problem I can adjust the recreate-table commands and functions to properly account for this newly discovered complexity in postgres - however it would be helpful to just confirm that this is what is going on first.

Unfortunately you didn't tell what the values of the sequences was before or after your restore. Restore shouldn't have been completely necessary as even if the sequences were all zero'd all you would have needed to do was set the sequences back to their values using setval. It would have been helpful to know if the sequences were completely missing after recreate-table or just incorrect.

```sql
SELECT last_value FROM tmp_recreate__topic_id_seq;
```

and similarly for a few chosen other sequences e.g. `user_id_seq` would have been useful. However I should be able to figure this out with testing myself.

**Comment by joseluisq** [comment]
> Dude, I don't know if you mean to be quite as rude as you're appearing - I'm sorry that there was a mistake and an error but we can't get right all the time and I'm only inferring from what you're saying as to what the problem could be.

I don't want to discuss off-topic things here that are not related with the problem so please keep the issue and related topics as a priority. However bellow I clarify some things.

> _The issue is the sequences are out of kilter._
> _That means you need to go in to your postgres dB and fix them._
> _We don't have a command to do that for you because we haven't written one because we didn't expect this to be such a problem._
> R: That's great

It's no rudeness but bewilderment because you are suggesting me execute stuff in my database as well as run the gitea tool to see what happen (that's fine) but then you tell me something like _"your sequences are out of kilter, you need to fix them and We don't have a command to do that for you because we didn't expect this to be such a problem"_.
Sure but It would be better to just say that you can not simply help because lack of feedback from my side so then I could provide you the necessary to find the root of the problem.

No, I'm not taking the rude approach here I just want to solve the problem that until now isn't yet since as far as I know there are other users facing similar issues.
Therefore please don't take my comments personal or any kind of. 

> I do all my work on Gitea for free. I get no payment despite the many hours of time I put in to this project. It appears I get even less thanks - a little bit of appreciation for the fact that you're getting help for free would go a long way.

Sure, I understand since I do too OSS in my free time (or even with extra hours) without profit of any kind even with no economic retribution for the effort, but It's not a complaint or something like that, I'm fine with it. However I receive contributions and feedback which are what I appreciate more.
Therefore I appreciate your effort here too, no doubts.

> I'm sorry something has gone wrong and I'm just trying to help. I appreciate how stressful things, especially databases, can be when they're not working.

It's part of our job sometimes face annoyance or difficulties but let's work together to solve the problem.

---

For now I'm replaying this until get my workstation again in next hours then I will answer the technical questions needed as well as providing more insights in order to help to solve the problem.

**Comment by joseluisq** [comment]
Sorry for the delay below my reply.

> Assuming that you discover that the `tmp_recreate__topic_id_seq` is attached to the `id` column of the `topic` table then:

Yes, `tmp_recreate__topic_id_seq` is attached to column's `id` of `topic` I have just confirmed:

```sql
SELECT table_catalog, table_schema, column_name, table_name, column_default
FROM information_schema.columns
WHERE table_name = 'topic' AND column_name = 'id';

-- table_catalog|table_schema|column_name|table_name|column_default                                 |
-- -------------|------------|-----------|----------|-----------------------------------------------|
-- gitea        |public      |id         |topic     |nextval('tmp_recreate__topic_id_seq'::regclass)|
```

> `SELECT setval('tmp_recreate__topic_id_seq', (SELECT MAX(id) FROM topic));` should restore the correct value and `ALTER SEQUENCE tmp_recreate__topic_id_seq RENAME TO topic_id_seq` should restore things completely to normal.

It seems working again, the rename was successfully. But as you said probably was because a failed migration process that left topic table and sequences in an inconsistent state. Anyway here the SQL dump of `topic` table before the ALTER SEQUENCE:

<details>
  <summary>public.topic</summary>

```sh
pg_dump -U gitea -st topic gitea
```

```sql
--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: topic; Type: TABLE; Schema: public; Owner: gitea
--

CREATE TABLE public.topic (
    id bigint NOT NULL,
    name character varying(25),
    repo_count integer,
    created_unix bigint,
    updated_unix bigint
);

ALTER TABLE public.topic OWNER TO gitea;

--
-- Name: tmp_recreate__topic_id_seq; Type: SEQUENCE; Schema: public; Owner: gitea
--

CREATE SEQUENCE public.tmp_recreate__topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.tmp_recreate__topic_id_seq OWNER TO gitea;

--
-- Name: tmp_recreate__topic_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: gitea
--

ALTER SEQUENCE public.tmp_recreate__topic_id_seq OWNED BY public.topic.id;

--
-- Name: topic id; Type: DEFAULT; Schema: public; Owner: gitea
--

ALTER TABLE ONLY public.topic ALTER COLUMN id SET DEFAULT nextval('public.tmp_recreate__topic_id_seq'::regclass);

--
-- Name: topic topic_pkey; Type: CONSTRAINT; Schema: public; Owner: gitea
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id);

--
-- Name: IDX_topic_created_unix; Type: INDEX; Schema: public; Owner: gitea
--

CREATE INDEX "IDX_topic_created_unix" ON public.topic USING btree (created_unix);

--
-- Name: IDX_topic_updated_unix; Type: INDEX; Schema: public; Owner: gitea
--

CREATE INDEX "IDX_topic_updated_unix" ON public.topic USING btree (updated_unix);

--
-- Name: UQE_topic_name; Type: INDEX; Schema: public; Owner: gitea
--

CREATE UNIQUE INDEX "UQE_topic_name" ON public.topic USING btree (name);

--
-- PostgreSQL database dump complete
--
```

</details>

> Unfortunately you didn't tell what the values of the sequences was before or after your restore. Restore shouldn't have been completely necessary as even if the sequences were all zero'd all you would have needed to do was set the sequences back to their values using setval. It would have been helpful to know if the sequences were completely missing after recreate-table or just incorrect.
> 
> ```sql
> SELECT last_value FROM tmp_recreate__topic_id_seq;
> ```
> 
> and similarly for a few chosen other sequences e.g. `user_id_seq` would have been useful. However I should be able to figure this out with testing myself.

I think (looking the dump above result) that the sequences were incorrect from the beginning (from my first comment here) and probably during a incomplete migration process that I did weeks ago (if I remember well) from a minor version (not bug fix). The problem is that I have not added topics to my repos for very long time so I'm not really sure when exactly the problem arose.

Here the final results:

```sql
SELECT last_value FROM tmp_recreate__topic_id_seq;
-- last_value|
-- ----------|
--         70|

-- NOTE: This setval also outputs 70 like the before query
SELECT setval('tmp_recreate__topic_id_seq', (SELECT MAX(id) FROM topic));
-- last_value|
-- ----------|
--         70|
```

> Now that I think I understand the problem I can adjust the recreate-table commands and functions to properly account for this newly discovered complexity in postgres - however it would be helpful to just confirm that this is what is going on first.

Well it's up to Gitea contributors but It would be great to workaround the migration process in some form since looks like sometimes between migrations is not so precise. Therefore annoying specially for non-advanced Postgres user like me. Knowing also that there are other users facing similar issues.
 
Anyway feel free to pinging me if it's necessary since the problem was solved with manual intervention and I'm able to add topics again via the GUI as before.

Thanks for your help.

**Comment by zeripath** [comment]
See #15015 I've already put up a PR to attempt to fix this and to prevent this from happening again.

**Comment by joseluisq** [comment]
BTW of course now `SELECT last_value FROM topic_id_seq;` is giving  the right result after the renaming (in my case 70 as shown above).

**Comment by joseluisq** [comment]
> See #15015 I've already put up a PR to attempt to fix this and to prevent this from happening again.

Great :+1:

**Comment by zeripath** [comment]
thanks for your help @joseluisq - it was useful to go through the details to confirm my suspicions as to what was really happening.

**Comment by joseluisq** [comment]
Congrats for the merge. Happy to have helped a bit.
