### ISSUE TITLE
Gitea wont update on web ui

### ISSUE THREAD

**Issue by TKDKid1000** [go-gitea/gitea#14813]
- Gitea version (or commit ref):
- Git version: git version 2.25.1 
- Operating system: Ubuntu
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Gitea is not updating the web interface. This is a fresh install (just got it), and the web ui will not update. But after I commited using
```
git add .
git commit -m "message"
git push origin master
```
and then ran `git pull` it said everything up to date, but the web ui is not updating. (see ss)
## Screenshots

![image](https://user-images.githubusercontent.com/69736165/109361224-6f440900-783d-11eb-9f31-fa1eb0b98d63.png)

**Comment by 6543** [comment]
@TKDKid1000 we need the gitea version you run on ...

**Comment by TKDKid1000** [comment]
> @TKDKid1000 we need the gitea version you run on ...

How do I get that?

**Comment by TKDKid1000** [comment]
> > @TKDKid1000 we need the gitea version you run on ...
> 
> How do I get that?

Wait, nevermind. I found it. `Gitea version 1.13.2 built with GNU Make 4.1, go1.15.7 : bindata, sqlite, sqlite_unlock_notify`

**Comment by 6543** [comment]
look's like an setup issue ... the best way is to ask for help on [Discord](https://discord.gg/Gitea) ... since each time you write a commit around 470 people get emails :/

**Comment by zeripath** [comment]
Essentially this problem boils down to hooks not running.

That could be due to:

* You pushing not through gitea.
* The hooks not having the  right address for gitea.
* The hooks aren't executable because they're on a noexec partition
* the hooks aren't executable due to some security feature of the way gitea is run.

We need more Information. How are you pushing http(s) or SSH, internal or external SSH, where are you pushing, have you ran resynchronize hooks, are your repositories on a noexec partition, are you running gitea from systemd etc.

Have you reviewed previous closed similar issues?

**Comment by mus-candidus** [comment]
Could this be documented in the gitea installation instructions? Took me quite some time to realize that noexec doesn't work. You can't even search the web before you don't understand what's going on. Having a hint in the installation instructions could help many people not to waste their time.
