### ISSUE TITLE
Discusion: Migrate from JS to TS

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14816]
we use a lot of custom JavaScript [web_src/js](https://github.com/go-gitea/gitea/tree/master/web_src/js), witch we could migrate to TypeScript.

any thoughts on this topic?

**Comment by 6543** [comment]
cc @silverwind

**Comment by noerw** [comment]
If we're talking about typedefs for API responses; that might be benefitial, those could be generated from the swagger.json..

But for everything else? The current code is a hodgepodge of various imperative APIs with mostly ad-hoc types. I don't see a benefit really, it will mostly slow down the build..
otoh, if we're talking long term about a frontend rewrite, Typescript would be a good option

**Comment by gnat** [comment]
Gonna have to say no thanks because:

- No obvious advantage or win for gitea?
- More complex, slower build process.
- Increased barrier for development.
- ECMAScript has been evolving so quickly lately that it will probably get types and supersede TS in the near future anyway. The true "futureproof" choice is to continue evolving with the latest ECMAScript spec.

**Comment by a1012112796** [comment]
How to handle the code which using ``vue`` is also a problem ...

**Comment by gnat** [comment]
A bit off topic but I feel as if vue will be replaced with the ability to send POST data + show returned content as simple tag attributes as part of the upcoming HTML standard, which is the true "futureproof" way. See https://htmx.org as an example of this.

**Comment by lafriks** [comment]
I have never been fun of TS, ecmascript has evolved quite much so I don't see much use for TS to be honest

**Comment by lunny** [comment]
I think the more urgent thing is maintainable for frontend codes. We may should rework the frontend but have to consider below things:

- [ ] The new frontend should not depend on a backend technology like Go template, so that frontend and backend developers could cooperate easier.
- [ ] The new frontend should be friendly with SEO so that repositories on public Gitea site could be found by search engine.
- [ ] The new frontend could be introduced step by step because it's difficult to replace all of the frontend codes once.

**Comment by silverwind** [comment]
I also dislike TypeScript because it has no runtime support anywhere and last I checked the compilation is a major hindrance loss when developing because it easily doubles the build time. I'd rather wait to have official types support in ECMAScript.

> The new frontend should not depend on a backend technology like Go template, so that frontend and backend developers could cooperate easier.

Yes, we need to extract the JS from the templates as well as nuke that conglomerate of gotemplate and vue that is used on the frontpage repo list. Some inline scripts are still necessary for performance-critical cases, but maybe they could also be extracted to files.

**Comment by mohe2015** [comment]
If the separate build step is not wanted JSDoc  https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html may be a possibility (but keep in mind that it has some limitations (which don't matter here I think)).
