### ISSUE TITLE
kanban: feature request: "new issue" button in kanban view

### ISSUE THREAD

**Issue by sebthom** [go-gitea/gitea#14824]
- Gitea version (or commit ref): 1.13.2 built with GNU Make 4.3, go1.15.7 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version:  2.26.2
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Please add a button "New issue" in the kanban view, e.g. next to "New Project board" that creates a new issue that is automatically assigned to the kanban view's project.

Alternatively a [+] button or similar could be added to each column which then creates an issue for the current project in the given column.

## Screenshots

![image](https://user-images.githubusercontent.com/426959/109401459-3c8a3580-794f-11eb-9f68-72c315935a0c.png)

**Comment by szatyinadam** [comment]
What is the preferred place for this button?
I did a quick modification to see the upper one:
<img width="1152" alt="Screenshot 2021-03-24 at 17 21 11" src="https://user-images.githubusercontent.com/13780853/112345676-899ac680-8cc5-11eb-9b42-880fc9852f93.png">
I think the colour should be not the same as the `New Project board` button.

The second option to put it on each column, but how common is to create an issue with in progress or done status, instead of the beginning of the process/backlog? GitLab allows to create issue in each state/column.

My other question is about the way to pass project name to the new issue form. Is it possible only with GET parameters or do we have other solution for this?

**Comment by sebthom** [comment]
@szatyinadam Maybe the `New Project board` button can be replaced with `New Issue` and a new [+] button is added to the most right column that adds a new column. This way the `New Issue` is located at the same place in the same color where it also is located in the regular issue list view.

![image](https://user-images.githubusercontent.com/426959/112757142-bd892b00-8fe8-11eb-9e8e-3495ae7f9cf3.png)

**Comment by szatyinadam** [comment]
OK, I like your suggestions. Can some project maintainer accept this design?
