### ISSUE TITLE
Borked button alignment on organization page

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#14854]
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
In current Firefox & current chromium some buttons are badly aligned, see screenshots.

## Screenshots
![grafik](https://user-images.githubusercontent.com/7880552/109667177-c9a7d700-7b67-11eb-99ac-23fe4267a31e.png)

**Comment by CL-Jeremy** [comment]
Hmm okay so this was fixed differently in #14924 as I already put up a solution to the chevrons in CL-Jeremy#6 with very slight differences (I removed the outer `<div class="ui">` and used flex instead of inline-flex for `<a>`, as I used `mr-2` instead of a space as spacer). I guess I'll keep my solution for 1.15.0 when that PR gets merged by then.

**Comment by zeripath** [comment]
Whatever looks best and is simplest without breaking stuff. I only went the way I went because it appeared simpler
