### ISSUE TITLE
Gitea dump fails with denied permissions on mkdir /usr/local/bin/data

### ISSUE THREAD

**Issue by pizzabreath** [go-gitea/gitea#14916]
- Gitea version (or commit ref): Gitea v1.13.3 built with GNU Make 4.1, go1.15.8
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9
Installed via the executable, started via the gitea.service.

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
I'm attempting to create a backup and followed the backup/restore documentation. The command failed as shown below.

The backup process fails at `mkdir /usr/local/bin/data`, as the git user does not have write permissions in that directory. I can't seem to identify the reason why the process attempts to create a directory there, or how to change this behaviour.
I assumed this may be the temporary working directory, but `-t /tmp/` fails with the same error.

## Terminal
```
$ gitea dump -c /etc/gitea/app.ini 
2021/03/07 10:02:26 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.11.0
2021/03/07 10:02:26 ...dules/setting/log.go:297:newLogService() [I] Gitea v1.13.3 built with GNU Make 4.1, go1.15.8 : bindata, sqlite, sqlite_unlock_notify
2021/03/07 10:02:26 ...dules/setting/log.go:343:newLogService() [I] Gitea Log Mode: Console(Console:info)
2021/03/07 10:02:26 ...dules/setting/log.go:249:generateNamedLogger() [I] Macaron Log: Console(console:info)
2021/03/07 10:02:26 ...dules/setting/log.go:249:generateNamedLogger() [I] Router Log: Console(console:info)
2021/03/07 10:02:26 ...les/setting/cache.go:70:newCacheService() [I] Cache Service Enabled
2021/03/07 10:02:26 ...les/setting/cache.go:81:newCacheService() [I] Last Commit Cache Service Enabled
2021/03/07 10:02:26 ...s/setting/session.go:63:newSessionService() [I] Session Service Enabled
2021/03/07 10:02:26 ...s/storage/storage.go:151:initAttachments() [I] Initialising Attachment storage with type: 
2021/03/07 10:02:26 ...les/storage/local.go:43:NewLocalStorage() [I] Creating new Local Storage at /usr/local/bin/data/attachments
2021/03/07 10:02:26 main.go:112:main() [F] Failed to run app with [gitea dump -c /etc/gitea/app.ini]: mkdir /usr/local/bin/data: permission denied
```

**Comment by sapk** [comment]
You can have a look at your configuration file `/etc/gitea/app.ini ` for the variable APP_DATA_PATH  which must be set to `data` since you must be running from `/usr/local/bin` it try to read/write the folder `/usr/local/bin/data`.

You can either run the command from the same folder as the running instance or hard-code the complete path in the configuration file.

**Comment by zeripath** [comment]
or run with `--work-path=/var/lib/gitea/` or run with the environment variable `GITEA_WORK_PATH=/var/lib/gitea/` 

Whatever environment you normally run gitea in you have to run it in when you're running commands. There is a FHS compliant script which you can use to shadow Gitea to make it compliant with the FHS see https://github.com/go-gitea/gitea/blob/master/contrib/fhs-compliant-script/gitea or when you compile Gitea it is possible to compile it so that the default paths are FHS compliant by default see https://docs.gitea.io/en-us/install-from-source/#changing-default-paths)
