### ISSUE TITLE
how to generate avatar automatically?

### ISSUE THREAD

**Issue by nkbai** [go-gitea/gitea#15040]
- Gitea version (or commit ref): 1.13.4
- Git version: 
- Operating system: linux

the older version support this feature:
generate avatar for every user from it's name, but when  I use the latest version, This feature is missing and can not automatically generate an avatar based on my initials. For example, generate a picture by Bai with three letters.

How Do I get this feature back so I can clearly identify users without having to upload their avatar.

We are a small group of only a few people,

![image](https://user-images.githubusercontent.com/10471399/111722248-712d4500-889c-11eb-80e0-ed9b76cbefd1.png)

**Comment by 6543** [comment]
this should not happen ...

**Comment by garfeng** [comment]
I don't known why, but if you edit the app.ini as the following, the feature will be activated:

![image](https://user-images.githubusercontent.com/19792314/111731345-3a602a80-88ae-11eb-9be3-9bd366e1ce99.png)


Then gittea will generate avatar automatically.

Maybe the reason is:

There are some web server can generate avatar automatically:

1. Gavator(https://cn.gravatar.com/) **blocked in China** 
2. Federated Avatars(https://cdn.libravatar.org/) **can be accessed in China**
3. ...

and gitea uses Gavator by default

**Comment by lunny** [comment]
I think this is your network problem. Please check chrome devtools network to confirm that.

**Comment by nkbai** [comment]
多谢,确实是因为被墙了的原因,但是生成的头像是随机的,我记得早期的版本生成的头像是根据名字来的,比如我的头像可能是一个很大的N

**Comment by lunny** [comment]
Hm, that feature maybe dropped?
