### ISSUE TITLE
git-migration of private repo without credentials hangs indefinitely

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#15230]
- Gitea version (or commit ref): master (v1.15.0-dev-50-gf07b137e0)
- Git version: 2.30.2
- Operating system: redhat linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: no errors in the log. :(

## Description
Do a migration of type "git", from another gitea instance, where the repo is private. Don't provide credentials.
Starting the migration, the task hangs indefinitely. It can't be killed in the admin dashboard either..
As I can't repro on try.gitea.io, this might be an sqlite race?

## Screenshots
![grafik](https://user-images.githubusercontent.com/7880552/113245263-20f3b100-92a6-11eb-9cf1-031cac3611b2.png)

**Comment by KN4CK3R** [comment]
I have/had the same issue while implementing the push mirror in #15157. The reason is the git client which tries to read the credentials from the command line. So it waits until it gets killed. I prevent this situation with the environment variable `GIT_TERMINAL_PROMPT=0`. Then it just fails with `Authentication failed: Clone: exit status 128 - fatal: could not read Username for '...': terminal prompts disabled`. The problem is `GIT_TERMINAL_PROMPT` was introduced with Git 2.3 (released 2015). If there is no other solution we need to set the minimum supported version to Git 2.3 for Gitea.
