### ISSUE TITLE
install/use instructions on github are better than on the website?

### ISSUE THREAD

**Issue by BMaxV** [go-gitea/gitea#15375]
The instruction to just

./gitea web

is nice and more helpful than the install instructions on the website, which left me confused.

https://docs.gitea.io/en-us/install-from-binary/

I thought binary would be easiest, that's why I picked that.

It got it to work, so I don't really have a problem, I just thought I'd let you know that the install/use process wasn't 100% smooth for me.

Thanks for doing what you do!

**Comment by jolheiser** [comment]
`./gitea web` is going to be incorrect for _many_ real deployments.
It does not point to a specific config, nor does it set up other environment variables.

It also runs as your user rather than a dedicated user, which can be a security problem.

`./gitea web` is really only useful to test the binary or during development.
