### ISSUE TITLE
Repo Search May Not Show Results Immediately

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#15425]
- Gitea version (or commit ref): 1.14.0
- Git version: 2.31.0
- Operating system: Debian
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes    https://try.gitea.io/?repo-search-page=2&repo-search-query=repo-11
  - [ ] No
- Log gist:

## Description

If I am on the dashboard and search a repo, matching repos are being displayed if I start the search from the first page. If I start the search from a page "after" the page which lists this repo in the absence of a search operation, there is only a number being displayed in one of the repo categories, but a matching repo is not being displayed unless one clicks the category button with the number. After that, the repo link appears in the result box and can be clicked to navigate to that repo.

## Screenshots

![20210412-gitea-search-box-problem](https://user-images.githubusercontent.com/1183079/114393896-7f683b80-9b92-11eb-8f91-fe10603c2166.png)

**Comment by zeripath** [comment]
The title of this issue is rather confusing. The issue here is that the search term has been changed but the current page number is greater than the maximum number of results for that new search term.

I guess the correct behaviour is that changing the search term should reset the page number to 1, as it makes no sense to keep the current page.

**Comment by muellert** [comment]
I didn't think of it that way, but your argument sounds very plausible.
