### ISSUE TITLE
Shrink view url hooks

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#15443]
When adding a hook the url should have a fixed size to avoid moving the action buttons.
**Url**: org/orgname/settings/hooks

![Captura realizada el 2021-04-13 00 34 55](https://user-images.githubusercontent.com/41587659/114493175-6db58100-9bf0-11eb-8067-a05fc387b892.png)

**Comment by silverwind** [comment]
Can probably use ellipsis overflow there.

**Comment by justusbunsi** [comment]
Would this do it for you? Instead of shrinking the hook url just prevent the button from moving around. The url would flow between the dot on the left and the buttons on the right. If it's ok, I can open a PR to fix this issue.

![image](https://user-images.githubusercontent.com/61625851/120900300-6761e500-c634-11eb-88fc-78a849a17188.png)

**Comment by zeripath** [comment]
Just use a truncate and ellipsis with a title attribute containing the full content. that's the simplest way to solve this

**Comment by justusbunsi** [comment]
> Just use a truncate and ellipsis with a title attribute containing the full content. that's the simplest way to solve this

Uh. Didn't noticed there is already a .truncate css class. Thanks for the hint.
