### ISSUE TITLE
Migrate 1.13.7 to 1.14.1 failed, need help

### ISSUE THREAD

**Issue by yusiwen** [go-gitea/gitea#15505]
The error output of `gitea-1.14.1-linux-amd64 doctor --all` is shown below:

```text
[2] Check Database Version
 - [C] Error: migrate: Current database version 156 is not equal to the expected version 178. Please run "gitea [--config /path/to/app.ini] migrate" to update the database version during ensure up to date
ERROR
[3] Check consistency of database
 - [C] Model version on the database does not match the current Gitea version. Model consistency will not be checked until the database is upgraded
ERROR
```

The output of `gitea-1.14.1-linux-amd64 migrate` is shown below:

```text
...
2021/04/16 15:26:55 ...ations/migrations.go:397:Migrate() [I] [SQL] ROLLBACK [] - 353.864µs
2021/04/16 15:26:55 cmd/migrate.go:38:runMigrate() [F] Failed to initialize ORM engine: migrate: do migrate: GetTagCommit: object does not exist [id: f1beee0c8b030aec9c2863ebf884f8eb88d9ed6c, rel_path: ]
```

It seems something in the database is missing, anyone can help? Thanks

**Comment by yusiwen** [comment]
BTW, the result of `gitea-1.13.7-linux-amd64 doctor --all` is all green, no error found. `1.13.7` is my current running version.

**Comment by zeripath** [comment]
Hmm. It would be useful to know if using 1.14.0 first succeed. (This is an unusual step that I would not normally recommend.)

I need to know if what you're running on: Windows, Linux or something else and if you're using gogit.

There is a release which is referring to an object in your gitea-repositories that is not present - presumably because a tag has been deleted.

The solution is to make this migration a bit more tolerant and I will do that but you should try to find out what has happened.

**Comment by raucao** [comment]
Same issue here, also with 1.14.0.

**Comment by zeripath** [comment]
Should be fixed by #15519 & its backport #15527

**Comment by 6543** [comment]
@yusiwen can you confirm that it is fixed by using https://dl.gitea.io/gitea/1.14/ binary?

**Comment by 6543** [comment]
@raucao is it solved :point_up:  ?
