### ISSUE TITLE
Discourse mention integration

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#15586]
I like how github shows related issues from a PR and vice versa, when an issue mentions a PR. It would be nice if a gitea repository could designate related discourse forums, and whenever a discourse topic mentioned a gitea issue, then the gitea issue would present a link to the discourse topic in it's feed.

**Comment by 6543** [comment]
@kanishka-work can you add some screenshots?

**Comment by 6543** [comment]
we already have this - what does this have to do with Discourse ?

**Comment by kanishka-work** [comment]
This is suggesting a completely new  (wish list) feature where a gitea repo would have a some background scheduled task that scanned an indicated discourse forum for mentions of a gitea issue. So, in the image above, instead of seeing "linked a pull request", it would say "discourse topic mentioned this issue" and display a link to the discourse topic.

**Comment by 6543** [comment]
I'm not a fan of another background task within specific for Discourse ... this is a perfect job for a **bot** creating comments ... in my opinion

**Comment by kanishka-work** [comment]
That makes sense. I don't know where to file a feature request for such a bot. I'll close this as off topic for this repo for now.
