### ISSUE TITLE
Single emails are sent even before a code review is completed

### ISSUE THREAD

**Issue by SamyakGangwal** [go-gitea/gitea#15645]
- Gitea version (or commit ref):
- Git version:1.14.1
- Operating system: Ubuntu  commandline
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
 1. Open an issue
 2. submit a pull request
 3. review the pull request
 4. Before submitting the review after every comment, an email would be sent to the person who has opened up a pull request.
 5. Instead of sending the email after submitting the review, gitea will send the email after every comment

**Comment by a1012112796** [comment]
@SamyakGangwal why need open an issue?

**Comment by SamyakGangwal** [comment]
> @SamyakGangwal why need open an issue?

@a1012112796  it should only send the emails after i complete a code review, right? So that is why i thought of opening it as an issue.

**Comment by lunny** [comment]
Have you added a single comment on code review?

**Comment by rakshith-ravi** [comment]
Hey @lunny! I'm from the same team where we faced this issue. This issue was caused when I started a review, (not a single comment), started writing comments on the PR (it even said "pending" above my comments) and while I was writing the comments the emails were going out. Once I had finished the review, a separate email went out for the review independently. Do let me know how I can help narrow down the bug

**Comment by rakshith-ravi** [comment]
Hey @lunny! What can we do to help you fix this bug? It's bloating our emails with individual emails for each comment instead of a single, bulk email and for large PRs, it becomes a pain. If you can help me understand what code to take a look at to find the source of this bug, I'd be happy to put in a PR myself to fix this

**Comment by lunny** [comment]
It seems there is already a PR to fix that maybe not link to this issue.

**Comment by rakshith-ravi** [comment]
I believe this is not fixed yet. @SamyakGangwal have you noticed this still happening recently?

**Comment by SamyakGangwal** [comment]
@rakshith-ravi  I don't think this has happened recently, I think might be fixed.

**Comment by rakshith-ravi** [comment]
Let's test it out with a PR and update this issue accordingly

**Comment by lunny** [comment]
> Let's test it out with a PR and update this issue accordingly

Could you reproduce this?

**Comment by SamyakGangwal** [comment]
> > Let's test it out with a PR and update this issue accordingly
> 
> Could you reproduce this?

We tested it on a pr after upgrading it to 1.14.5. it works now, i only got the mail after the review was complete.
