### ISSUE TITLE
pam.d authentication fails

### ISSUE THREAD

**Issue by yahess** [go-gitea/gitea#15702]
- Gitea version (or commit ref): 1.15.0+dev-206-gae6d7860b
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description

Authentication via pam.d krb5 module fails with error

`...dels/login_source.go:831:UserSignIn() [W] Failed to login 'USERID' via 'systemusers': e-mail invalid [email: USERID]`

**Comment by lunny** [comment]
I think maybe we can enable pam tags for docker build since it's Linux.

**Comment by zeripath** [comment]
@yahess are you sure that pam is compiled into your version of Gitea? as @lunny says pam isn't included in the docker builds or builds by default.

**Comment by yahess** [comment]
Hi,

I have the following version. I build it using the install from source guide.

```
root@gitea:~/gitea# ./gitea --version
Gitea version 1.15.0+dev-206-gae6d7860b built with GNU Make 4.2.1, go1.16.3 : bindata, pam
```

**Comment by zeripath** [comment]
What were your TAGS for the build?

**Comment by yahess** [comment]
`TAGS="bindata pam" make build`

**Comment by zeripath** [comment]
OK, so let's jump back a bit. This error report is coming from:

https://github.com/go-gitea/gitea/blob/1e6fa57acbe3c05cb996b789e8c2d381c953826f/models/login_source.go#L831

Which implies that the user in question is not in the db at present. (see L777 of that function)

The error (a `models.ErrEmailInvalid`) with the string content `e-mail invalid [email: USERID]` can only be returned by: 

https://github.com/go-gitea/gitea/blob/1e6fa57acbe3c05cb996b789e8c2d381c953826f/models/user_mail.go#L30-L43

and so will be coming from L888 within:

https://github.com/go-gitea/gitea/blob/1e6fa57acbe3c05cb996b789e8c2d381c953826f/models/user.go#L854-L855

(This was added by #13475 and amended slightly by #13627)

The problem is that neither of these PRs considered what happens with PAM:

https://github.com/go-gitea/gitea/blob/1e6fa57acbe3c05cb996b789e8c2d381c953826f/models/login_source.go#L682-L715

in particular:

https://github.com/go-gitea/gitea/blob/1e6fa57acbe3c05cb996b789e8c2d381c953826f/models/login_source.go#L707

This makes no attempt to check that the pamLogin would be a valid email under those constraints.

---

So... The question is what to do?

I think we can leave the email blank or we could try adding the noreply suffix. An alternative is to change the pam module you're linking in to return the email address instead of the username.
