### ISSUE TITLE
Can not edit issuses, from 1.13.7 to 1.14.2

### ISSUE THREAD

**Issue by menshiyun** [go-gitea/gitea#15815]
- Gitea version (or commit ref): 1.14.2
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.5 LTS
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

After upgrading Gitea from 1.13.7 to 1.14.2, the issues cannot be edited and the editor cannot be previewed.

## Screenshots

![Screenshot from 2021-05-10 13-31-50](https://user-images.githubusercontent.com/20251683/117610944-2c83a300-b195-11eb-9ef3-b1bf6476eaf8.png)
![Screenshot from 2021-05-10 13-32-10](https://user-images.githubusercontent.com/20251683/117610957-2f7e9380-b195-11eb-88cb-4859481c0f34.png)

**Comment by zeripath** [comment]
Ctrl-f5 would have likely solved the problem as it was likely that you just had browser cached assets.

If not the web browser console would have told us what JavaScript function was failing and would have allowed us to work out whether there was a real problem or not.

If you want to try to solve this - and you should - it might be easier to go on to discord as it is either a completely temporary issue or a configuration issue. However if you would rather do that here please reopen this issue if when you try to migrate again this issue reappears. At present this issue is little more than noise and it is not helpful for anyone.
