### ISSUE TITLE
SameSite cookie option applies only to _csrf cookie

### ISSUE THREAD

**Issue by SagePtr** [go-gitea/gitea#15972]
- Gitea version (or commit ref): 1.14.2, 1.15.0+dev-344-g5285a3e70 
- Git version: unrelated
- Operating system: unrelated
- Database: unrelated
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description
Only ```_csrf``` cookie gets SameSite option. The other cookies have no.

## Screenshots

![image](https://user-images.githubusercontent.com/3179266/119412175-c72ec680-bceb-11eb-92ee-12a7c25a43dc.png)
![image](https://user-images.githubusercontent.com/3179266/119412473-3c020080-bcec-11eb-9cc3-9d855984562e.png)
![image](https://user-images.githubusercontent.com/3179266/119412624-7e2b4200-bcec-11eb-9693-8ec44d2a69bb.png)

**Comment by SagePtr** [comment]
Mostly fixed, but the cookie "i_like_gitea" (session identifier cookie?) still comes without SameSite:
![image](https://user-images.githubusercontent.com/3179266/120131569-f7cd9f00-c1c8-11eb-91bb-724cc1d909b4.png)

**Comment by zeripath** [comment]
I almost missed this comment - please do not comment on closed bugs!

https://github.com/go-gitea/gitea/blob/effad26c0e7348d27f7fdd1c0cbf120d7558cf67/routers/routes/web.go#L156-L165 looks like it's misses setting the SameSite setting. This is probably due to a reversion at some point... I'll pop up a patch.

Damn I thought I checked all of these cookies but obviously missed this.
