### ISSUE TITLE
The repository transfer function cannot be used and has no effect

### ISSUE THREAD

**Issue by wangpre** [go-gitea/gitea#16006]
- Gitea version (or commit ref): 1.14.2 
- Git version: 
- Operating system: CentOS7
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

...
I try to transfer the test2 repository of test users to test2 users But
The repository transfer function cannot be used and has no effect！

When I switched to the test2 user and nothing happened

![微信截图_20210528185558](https://user-images.githubusercontent.com/53291931/119973788-7cac9300-bfe6-11eb-8988-af25857e9b0b.png)
## Screenshots
![微信截图_20210528190215](https://user-images.githubusercontent.com/53291931/119974661-85519900-bfe7-11eb-8efa-6bc106212312.png)

**Comment by nils91** [comment]
The target user (test2 in this case) needs to accept the transfer, however, accepting the transfer happens on the repo page, and in order to see it and be able to accept, test2 needs to have at least read access to the repo before the transfer (For private repos, like in this case, this needs to be set manually).
@johndev2020 can you confirm that this is the problem? I´ve tested with 1.14.2, but the message i´m getting is different. ("This repository has been marked for transfer and awaits confirmation")

![repo_add_user](https://user-images.githubusercontent.com/7298243/121155567-335f0d80-c848-11eb-9d88-90cf8022a25a.PNG)

![repo_await_confirm](https://user-images.githubusercontent.com/7298243/121155569-335f0d80-c848-11eb-83dd-14de40c9e545.PNG)
And after logging in as test2:
![repo_accept_transfer](https://user-images.githubusercontent.com/7298243/121155565-32c67700-c848-11eb-934d-ada38794172e.PNG)
