### ISSUE TITLE
openssh: warning: can't happen: timeout while the service is up!

### ISSUE THREAD

**Issue by Firpo7** [go-gitea/gitea#16038]
- Gitea version (or commit ref): 1.15.0+dev-356-ga5d8f5834
- Git version: 2.30.2
- Operating system: Linux raspberrypi 5.10.17-v7l+ `#1421` SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I built the docker image of Gitea for my Raspberry Pi 4, that has an armv7 architecture. If I open the logs I get a nonstop spam of these logs:
```
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
```

Searching around the web it seems a problem inherited from alpine, but I still get the error using the latest version (3.13.5 that should be the default of golang:1.16-alpine3.13).

**Comment by MPeti1** [comment]
I think I have found a problem which might be related to how I migrated the data to the rootless Gitea, so I'm writing this here.

I wanted to create a Wiki article in one of m repositories, and submitting it resulted in an 500 error. The logs revealed this error: `[E] Unable to create localcopypath directory: /var/lib/gitea/custom/tmp/local-repo (mkdir /var/lib/gitea/custom/tmp: permission denied)`
The cause is that the path `/var/lib/gitea/custom` inside the container has `r-x------` permissions.

![image](https://user-images.githubusercontent.com/9215491/141162182-a6a4d390-94b7-47a4-b9d7-7789a3861c89.png)

Judging from the git and ssh directories beside it, the `custom` directory probably should have `rwx------` permissions on it.
Setting the permissions this way fixed the problem, but I would appreciate if it could be verified whether this is the correct permission for the `/var/lib/gitea/custom` directory.
