### ISSUE TITLE
"Start review" with an empty comment breaks GUI

### ISSUE THREAD

**Issue by cvennel** [go-gitea/gitea#16051]
- Gitea version (or commit ref): Verified on 1.14.2 and 1.15.0+dev-377-g894742278
- Git version: 2.24.1
- Operating system: Centos
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL): https://try.gitea.io/cvennel/Test_gui_bug/pulls/1/files
  - [ ] No
- Log gist:

## Description

Clicking "Start review" with an empty comment seems like it should refresh the screen and display an error message, however the new screen is being shown in a smaller window where the new review comment should be. See screen capture below:

## Screenshots

https://user-images.githubusercontent.com/35314989/120482896-94d23880-c37f-11eb-958a-fcfaa4efa38f.mp4

**Comment by lunny** [comment]
Hm, should we allow empty comment when click start review?

**Comment by cvennel** [comment]
> Hm, should we allow empty comment when click start review?

Not sure if you're asking for an outside opinion or not but personally I don't see the value of being able to start a review with an empty comment. I would think ideally the start review button and likely also the single comment button would be disabled until there is content in the comment box. This would be similar to how the new pull request button is grayed out when not signed in.

Alternatively, I think the existing refresh and show the error message at the top would be more acceptable if it actually refreshed the entire page. The down-side to this is if you are reviewing a large PR and accidentally click the start button it's annoying to have to scroll back to where you were last reviewing.

**Comment by jannaahs** [comment]
I would like to work on it. Actually, I would implement it as @cvennel suggested.

**Comment by jannaahs** [comment]
My first idea was to use a vue component and wrap it around the editor and the button. Unfortunately, the vue component is not rendered, because the comment_form.tmpl will be loaded after vue was initialised.

Does anyone has a different idea?
Otherwise there is a lot more to do like a refactoring of how the html is loaded.

**Comment by cvennel** [comment]
@jannaahs I haven't looked too far into this, but it seems like right around [here](https://github.com/go-gitea/gitea/blob/d30410675b81a07d5ba8a4e7f4d25732374a8fa8/web_src/js/index.js#L1861) the javascript handles graying out the commit button on file edits if the commit message is empty or there are no file changes. Could that sort of thing be expanded for this situation or does that fall under where you were saying "there's a lot more to do."

**Comment by jannaahs** [comment]
@cvennel Yeah, I think it is not that easy.

While doing a code review you might have open more then one form. Committing files is a bit different, because there is only one form open at the same time.

In case you have two forms open, the buttons should only be disabled if the corresponding input is empty. Currently there is no mechanism in place to have the editor and the buttons in their own scope.

Implementing a own scope for each form is what I meant by "there's a lot more to do". At the moment I am not sure what would be a good solution to add a scope. Like I said a vue component would provide a scope, but is not possible due to the template being loaded after vue was initilized.

Maybe I didn't understood the [initEditor](https://github.com/go-gitea/gitea/blob/d30410675b81a07d5ba8a4e7f4d25732374a8fa8/web_src/js/index.js#L1796) you mentioned, but I don't see a quick and easy solution.

**Comment by Gusted** [comment]
Same issue as #18151, fixed by #18156
