### ISSUE TITLE
Possibility to delete last commit in gui

### ISSUE THREAD

**Issue by TimerWolf** [go-gitea/gitea#16146]
- Gitea version (or commit ref): 1.14.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.5 LTS
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Irrelevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Irrelevant
- Log gist:
  - [x] Irrelevant

## Description

Sometimes it very easy to manage the code inside the gui on the web and not use the local git with the cli.

I have found this feature very useful but know and then some of the commits that is made have some missing stuff in it typos etc that i would like to correct before i actually make the "real commit" but as we all know the human factor will always be there and it can not be perfect every time.

As it is today i have to go in to the local repo and update it with the remote and then make "git reset HEAD^ && git push --force" to delete the last commit and redo it.

Why is this not possible in the gui?

To delete the last commit, fix typos and other easy stuff and just do the "new  real intended commit" to correct it fast and easy.

My opinion that it just make unnecessary spam and a commit log that is more harder to read then it actually has to be.

And as a final comment, if it can be done in the cli why would it not be possible in the gui?

**Comment by lunny** [comment]
You can use `git reset` and `git push --force` to do that.

**Comment by wxiaoguang** [comment]
It's a management problem.

If you delete a commit on UI, the user with this commit can still push it again.

The only way to make the repo correct is making users repo correct first, the UI won't help.

**Comment by bilogic** [comment]
I think the OP's question is more about: how can a wrong commit can be wiped out so that it doesn't take up storage on the server.

Imagine an accident happens and 500MB was committed into the repository. This was re-committed with the large files being moved into the LFS. However, the git repository will now take up 1GB until the orphaned commit was removed.

I wasn't able to shrink the size. What I did was 

1. Clone the repo and ran 
  ```
  git reflog expire --expire=now --all
  git gc --prune=all --aggressive
  ```

2. Delete and recreate the gitea repository
3. Push from local again
