### ISSUE TITLE
Guide to build gitea from source in Windows

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#16213]
is there a guide to build gitea from source in Windows? I installed `make` but I'm still unable to get it to build.

**Comment by techknowlogick** [comment]
What errors are you getting? The maintainers who use windows use make, and reference the following page for details: https://docs.gitea.io/en-us/hacking-on-gitea/#on-windows

**Comment by techknowlogick** [comment]
Ah yes, Windows uses an alternative way to set env vars, it is something like `set ENV_VAR=value` or something. I've marked this issue as a docs issue so that section I linked above can have that information added (assuming powershell is used, but note git bash is posix compliant linux way is possible)
