### ISSUE TITLE
Translation guidelines for Spanish

### ISSUE THREAD

**Issue by fitojb** [go-gitea/gitea#16247]
This is a placeholder issue for me to provide the guidelines for Spanish l10n, as requested on Crowdin.

I will base them on my own l10n guidelines for LibreOffice, as almost everything there can be followed verbatim :)

https://wiki.documentfoundation.org/ES/Gu%C3%ADa_de_estilo

**Comment by zeripath** [comment]
¡Gracias y Hola @fitojb!

I think it could be useful to include a glossary of common translations - also perhaps to have a discussion about some of the choices here.

For example, we currently use `incidencía` for `issue` and we use `eliminar` for `delete/remove` instead of `borrar` - these may or may not be the right translation choices. We've chosen sometimes to use English - e.g. `Pull Request` - which is probably the right thing but it's perhaps useful to actually have some document that has these decisions. 

---

As an aside, if you would like to provide a Catalan translation - that language could be added to crowdin but you'd have to take over responsibility for proof-reading and approving the translations.

If there is someone within our Spanish speaking community who is keen to take over the role of being a proofreader for Spanish I would be happy to discuss.

**Comment by fitojb** [comment]
Yep, a glossary with explanations for each is definitely something that should be done. I filed the issue mainly to track this work and set it aside my list of to-dos for now :)

And yeah, I would be up for reviewing a Catalan translation! I'll be available in an on-and-off basis though :)

**Comment by 6543** [comment]
added Catalan ... :)
the directory to put in the spanish guideline is https://github.com/go-gitea/gitea/tree/main/docs/content/doc/translation :)

**Comment by fitojb** [comment]
Note to self: this looks great as a tool to maintain glossaries: https://github.com/elexis-eu/lexonomy

**Comment by lunny** [comment]
Closed as now all other languages except English and Chinese have been removed because of outdated with unmaintable.
