### ISSUE TITLE
Change tags to have url in href instead of data attribute

### ISSUE THREAD

**Issue by robe2** [go-gitea/gitea#16354]
- Gitea version (or commit ref): 1.14.3
- Git version: 
- Operating system: Debian
  Running Gitea using binary from https://dl.gitea.io/gitea/1.14.4
  
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No

## Description
We recently upgraded to gitea 1.14.3 and this has caused issues with debian packaging upstream.
They would like the links to the tar.gz have the URL in the href attribute instead of using the data attribute as they do now.  The href was used in older versions.

Their comment:
"Neither tags nor releases is usable currently. As is right clicking the tar.gz links on the tags page and using Save As (in Firefox ESR). Using Javascript for a download link is a little silly (and automation unfriendly)."

**Comment by jpraet** [comment]
The Gitea web UI should not be used for automation tasks. There is a REST API for that.
https://try.gitea.io/api/swagger#/repository/repoGetReleaseByTag

**Comment by sebastic** [comment]
[uscan](https://manpages.debian.org/buster/devscripts/uscan.1.en.html) doesn't support REST APIs, it looks for `<a href="URL">` in web pages to detect newer version and the download URLs for their tarballs.

On the tags page the `/<project>/<repo>/src/tag/<foo>` and `/<project>/<repo>/src/commit/<hash>` `<a>` elements have `href` attribute and hence can be used by uscan and rightclicking works in Firefox. The ZIP and TAR.GZ `<a>` elements on the tags page use the `data-url` element and an onclick event for the archives, these don't work in uscan (due to lack of `href` attribute`) nor does rightclicking in Firefox work to use Save As for example. Mousing over the link also doesn't show the URL in the status bar. Using regular `<a href>` links for the archives would fix both the issue in uscan and Firefox.

**Comment by jpraet** [comment]
The change was introduced as part of this PR: #11296

**Comment by noerw** [comment]
Hm, I don't get what this PR did, because for me there is no loading indicator displayed via JS.

Nonetheless, we could just add the link to the `href` too, but make click events ignore the default link-following behaviour.
