### ISSUE TITLE
Docker: Getting from "latest" to current release

### ISSUE THREAD

**Issue by ghmer** [go-gitea/gitea#16365]
I started a gitea instance using docker and the "latest" tag a while ago. Since then, I tried to switch to stable several times, but unfortunately, I always encountered that the db schema version of my instance was newer than the stable release and therefore the instance refused to start when switching to the stable release.

I understand that the latest tag is a daily build and therefore by nature on a bleeding edge. However, I wonder how to properly get around this issue, is there a preferred path to take? 

Thanks, G.

**Comment by techknowlogick** [comment]
Some good news is that 1. we are releasing 1.15 RC soon, which means it is less bleeding edge and almost a release candidate, and 2. we hope to change this behaviour with 1.15 (where "latest" becomes "latest stable" rather than "latest commit").

A PR exists right now to change this behaviour https://github.com/go-gitea/gitea/pull/15889, however a blocker is that we need people to evaluate the changes to the drone pipeline to ensure that they accomplish what we want to do. If you have available time we would appreciate support with testing the PR on a fork (if you don't have a personal drone instance to test with, cloud.drone.io is available for this purpose).

**Comment by noerw** [comment]
To answer your question more directly: The moment we publish a release (1.15.0 would be up next) you can safely change to a the `1.15.0` tag. Although as mentioned above, starting with 1.15.0 the `latest` tag will probably point to the latest *release* anyway.
