### ISSUE TITLE
Gitea 1.14.4 git-lfs-authenticate: command not found with SSH transfer

### ISSUE THREAD

**Issue by dehengxu** [go-gitea/gitea#16391]
Environment :
Debian, docker and I configurate server follow: https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough
forwarding ssh from host 22 to container 2222

git lfs cannot work with ssh protocol when I use `git push`
prompts error:
error: exit status 127, message: bash: git-lfs-authenticate: command not found (try: 5/6)

**Comment by noerw** [comment]
Please provide more details on how to reproduce, and ideally also server side logs of that action

**Comment by dehengxu** [comment]
> Please provide more details on how to reproduce, and ideally also server side logs of that action

Appreciate first, I have some questions :
1. Does gitea implement git-lfs-authenticate command?
2. If dose implemented , but I cannot found git-lfs-authenticate command in container space, or do I make some mistake ?

**Comment by noerw** [comment]
Yes this is implemented (but not as a separate binary, but the `gitea serv` subcommand handles all actions over SSH).

It looks like you don't have SSH set up properly. If using an external ssh server, make sure your keys are managed by gitea. Please check https://docs.gitea.io/en-us/faq/#ssh-issues to resolve that.

Please ask further questions in the `#configuration` channel in our [Discord](https://discord.gg/Gitea) since each time you write a comment on github, around 490 people get emails.
