### ISSUE TITLE
Gitea 1.16.0+dev-9-g95f40047e on Linux refuses to upload `application/zip` if it's extension is not .zip

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#16472]
Try to upload this file https://git.dotya.ml/attachments/7f4f799f-564c-4cf5-b955-f36225be902f which is from https://git.dotya.ml/kreyren/kreyren/issues/6 and expect:

![image](https://user-images.githubusercontent.com/11302521/126048765-e4433ca8-726e-4b31-bf93-33d0ced39fdc.png)

Btw. the FreeCAD extension is just a ZIP
```console
[nix-shell:~/CAD]$ file Turtlerarium.FCStd 
Turtlerarium.FCStd: Zip archive data, at least v2.0 to extract
```

Reproducible on the current try.gitea.io using `1.16.0+dev-19-gbb7a7c429`:
![image](https://user-images.githubusercontent.com/11302521/126087558-b5cdaa62-dab2-411f-b983-c75709096026.png)

**Comment by techknowlogick** [comment]
I know you out the version in the title of this issue, but the issue template exists for a reason, please use it. We ask for that absolute minimum of information so we can help you. As otherwise we would be guessing about way too much. For this it is also recommended that you include related configuration values that apply to file uploads (sometimes golang/browsers apply different mime types based on file extensions).

**Comment by zeripath** [comment]
In particular we need to know the value of `[repository.upload]` `ALLOWED_TYPES`

It's worth noting that mimetype values in this setting are also determined by your browser

**Comment by Kreyren** [comment]
CC @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf provide the requested info.

Updated the OP with known info.

**Comment by Kreyren** [comment]
FWIW it seems to just do a dumb-checking of the extension instead of the mime-type and let me know if the info provided is sufficient.. i tried to optimize it to make it more readable and faster to process u.u

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
- [x] OS: `Arch Linux`
- [x] built from sources
- [x] run with: systemd
- [x] Gitea version: `1.16.0+dev-21-g2256499db` -> Gitea was rebuilt since the issue was first reported.
- [x] git version: `git version 2.32.0.302.gb9a5e34162`

content of the ALLOWED_TYPES: `.gz,.bz2,.zst,.zstd,.zip,.gpg,.asc,.pdf,.txt,.jpeg,.jpg,.gif,.log,.png, application/zip`

since `file --mime-type <file>.FCStd` yields `application/zip`, I assumed this would suffice...

**Comment by zeripath** [comment]
> It's worth noting that mimetype values in this setting are determined by your browser so if you're using application/zip you may need to work out what the browser thinks the mimetype of that file is.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> > It's worth noting that mimetype values in this setting are determined by your browser so if you're using application/zip you may need to work out what the browser thinks the mimetype of that file is.

yes, thanks, this is useful to know.
@Kreyren could you investigate that? I'll try to modify the array then.

**Comment by Kreyren** [comment]
> @Kreyren could you investigate that? I'll try to modify the array then. -- @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf 

Didn't get the notification sorry for delay.

I don't know how to check what firefox thinks the file mime is
