### ISSUE TITLE
Feature Request: add CORS API indicating 'gitea'

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#16563]
# TL;DR

I'd like there to be some way to indicate that the service is `gitea`, as opposed to `gitlab`.

# Example

I'd like to be able to do something like this:

```js
await fetch('https://try.gitea.io/api/v1/version', { mode: 'cors' }).toJSON()
// { "name": "gitea", "version": "1.15.0" }
```

Or similar to this:

```js
await fetch('https://try.gitea.io/.well-known/openid-configuration', { mode: 'cors' }).toJSON()
// { "service_documentation": "https://docs.gitea.io" }
```

Just something that reveals "yes, this is gitea".

# Rationalé

The reason is that I'm building a tool [Bliss](https://github.com/coolaj86/bliss), which works with **GitHub**, **GitLab**, and **Gitea** and I'd like to be able to detect which system a user-supplied URL represents, since they have slightly different APIs.

**Comment by techknowlogick** [comment]
I wouldn't necessarily recommend the oidc wellknown endpoint for discovery of software type based on a docs URL (there must be a wellknown endpoint for what type of forge is in place), although regardless of purpose if a PR were to be made for the docs URL I'd recommend using https://docs.gitea.io/en-us/oauth2-provider/ 

I'd also hesitate to use the version endpoint, because users are able to mandate that endpoint require credentials.

**Comment by techknowlogick** [comment]
A PR for the wellknown nodeinfo endpoint can be found here: https://github.com/go-gitea/gitea/pull/16953

**Comment by techknowlogick** [comment]
Closing per linked PR
