### ISSUE TITLE
ORM engine initialization attempt #1/10 failed. Error: dial tcp 127.0.0.1:3306: connect: operation timed out

### ISSUE THREAD

**Issue by briguyjm** [go-gitea/gitea#16626]
- Gitea version (or commit ref): `Gitea version 1.14.5 built with GNU Make 4.3, go1.16.6 : pam, sqlite, sqlite_unlock_notify`
  - _I am using the `pkg` version of Gitea in the FreeBSD repo._
- Git version: `git version 2.32.0`
- Operating system: FreeBSD 13.0-RELEASE-p3
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: [https://gist.github.com/briguyjm/7eca41d6361a6419221fc97a8a441a3e](https://gist.github.com/briguyjm/7eca41d6361a6419221fc97a8a441a3e)
- `app.ini` gist: [https://gist.github.com/briguyjm/006f2173d1a68a670d7b3d263adf351f](https://gist.github.com/briguyjm/006f2173d1a68a670d7b3d263adf351f)
## Description
When running the version of Gitea in FreeBSD's package repos (not built from the ports collection) I am unable to access Gitea. It seems that whatever issues it is having are related to connecting to the database; it will attempt to initialize the ORM 10 times, fail all of them, and then exit. I have tried updating my database users' password and but it doesn't seem to matter.

Both the MySQL database and Gitea are running on the same server. The server is a physical machine in my house, so I am able to access it over my LAN. While I do have a way to access Gitea remotely (via my own domain) I have stopped all port forwarding, and am connecting my server on my local network. I have a few other services that are running on this same server, and connecting to the same MySQL server (Nextcloud, phpMyAdmin) and have no issues with those applications, so I don't believe that MySQL is the issue.

**Comment by zeripath** [comment]
When Gitea is trying to connect to the mysql db it can't because *nothing* is listening on 127.0.0.1:3306

That means your configuration is incorrect.

---

You need to work out what port and host your db is listening on on your server.

It could be that it's listening on the ipv6 localhost port - e.g. `HOST = [::1]:3306` 

It could be that it's only listening on a Unix file socket, in which case just put that path in.

It could be that it's listening on some other port.

If you need further help pop on to the discord to discuss further.

**Comment by briguyjm** [comment]
I don't believe that's not accurate, I have other services that are all connected to the same MySQL server in the same way.

```
$ sockstat | grep mysql

88       mysqld     23591 29 tcp4   192.168.1.100:33060   *:*
88       mysqld     23591 30 stream /tmp/mysqlx.sock
88       mysqld     23591 39 tcp4   192.168.1.100:3306    *:*
88       mysqld     23591 68 stream /tmp/mysql.sock
88       mysqld     23591 69 stream /tmp/mysql.sock
88       mysqld     23591 84 stream /tmp/mysql.sock
88       mysqld     23591 96 stream /tmp/mysql.sock
88       mysqld     23591 97 stream /tmp/mysql.sock
88       mysqld     23591 98 stream /tmp/mysql.sock
88       mysqld     23591 103 stream/tmp/mysql.sock
88       mysqld     23591 106 stream/tmp/mysql.sock
88       mysqld     23591 107 stream/tmp/mysql.sock
88       mysqld     23591 113 stream/tmp/mysql.sock
88       mysqld     23591 114 stream/tmp/mysql.sock
88       mysqld     23591 118 stream/tmp/mysql.sock
88       mysqld     23591 119 stream/tmp/mysql.sock
88       mysqld     23591 120 stream/tmp/mysql.sock
88       mysqld     23591 123 stream/tmp/mysql.sock
88       mysqld     23591 484 stream/tmp/mysql.sock
88       mysqld     23591 539 stream/tmp/mysql.sock
88       mysqld     23591 554 stream/tmp/mysql.sock
88       mysqld     23591 569 stream/tmp/mysql.sock
```

Furthermore, Gitea _used_ to work using the same configuration; now it doesn't.

**Comment by zeripath** [comment]
The above sockstat implies that the mysql server is not listening on `127.0.0.1:3306` but on `192.168.1.100:3306` and `192.168.1.100:33060`. Whether you will be able to connect from the same server to 192.168.1.100 is a question of routing.

However I see that you have a unix socket on `/tmp/mysql.sock` which you could use instead.

**Comment by briguyjm** [comment]
The IP address is the address of the Jail that Gitea is installed in. MySQL is installed in the same jail, as is Apache, phpMyAdmin, and Nextcloud. Nextcloud still works so there has been no changes with MySQL. For reference, the relevant settings from Nextcloud's config file are included below:

```
root@http:/usr/local/www/nextcloud2/config # cat config.php | grep "db"
  'dbtype' => 'mysql',
  'dbname' => 'nextcloud2',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud2',
  'dbpassword' => *****,
```

**Comment by zeripath** [comment]
Your logs are telling you what the problem is: Gitea is not able to connect the MySQL db on 127.0.0.1:3306 - when it opens the port it gets:

`Error: dial tcp 127.0.0.1:3306: connect: operation timed out`

---

The error is coming from the db Ping call. It is an &net.OpError which maps to the `dial tcp 127.0.0.1:3306: connect: operation timed out` part of the error

The `Err` here - `operation timed out` is mapping an ETIMEDOUT error.

Now we don't give you the option to set the timeout for mysql yourself - so the connection string is

```
 	connStr = fmt.Sprintf("%s:%s@%s(%s)/%s%scharset=%s&parseTime=true&tls=%s",
			Database.User, Database.Passwd, connType, Database.Host, Database.Name, Param, Database.Charset, tls)
```

Which means that the Timeout is fixed at 0 - meaning the default for your operating system, so the OS is detecting that nothing accepted the connection.

This is a very low level error. 

---

You need to run sockstat from the jail that gitea runs in or figure out why Gitea isn't permitted to connect to that port.
