### ISSUE TITLE
GPG key recognized, but flagged suspicious

### ISSUE THREAD

**Issue by Pingger** [go-gitea/gitea#16667]
## Solution below! https://github.com/go-gitea/gitea/issues/16667#issuecomment-897014201

- Gitea version (or commit ref): 1.14.6
- Git version: 2.30.2
- Operating system: Debian
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] MariaDB
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (because I don't receive the confirmation mail)
- Log gist:
  - https://gist.github.com/Pingger/0a5d2772871b73ce83b04877738427b7

## Description

For some reason gitea does not recognize any commits I make properly signed. 
` WARNING! Although there is a key with this ID in the database it does not verify this commit! This commit is SUSPICIOUS.` Is all I get as information.

I looked at #10420 and #2401. But neither did help. (My instance is running in UTC)
My local git says, the signature is good.
...

## Screenshots
![image](https://user-images.githubusercontent.com/4761298/129069380-dc406ed5-3854-40d5-a1cc-9104ee7813cb.png)
![image](https://user-images.githubusercontent.com/4761298/129069332-606c4cc0-06f8-4bf8-a6dc-b2aa8751c35e.png)
![image](https://user-images.githubusercontent.com/4761298/129069746-6c316db0-7d36-42f0-838f-d1b2b3344f4d.png)

**Comment by Pingger** [comment]
Issue found:
The mail wasn't verfied yet. And verifying after the commit is made doesn't update the GPG signature checks. I had to remove the gpg key and add it again.

**Comment by jotoho** [comment]
@Pingger This issue and your solution was able to help me out. Thanks!

I was having the same issue after reinstalling Gitea because of webpage corruption on most http requests (likely due to my migration attempt from SQLite to MariaDB). I kept the same configuration file, which caused Gitea to skip the install screen and simply made the first registered account (mine) an administrator. Unfortunately, it did not mark the email address used for registration as activated despite the mailer being disabled.

Adding another email address to my account (which was automatically considered activated) and then deleting and readding my git email address caused Gitea to finally accept my git email as active and caused all my commits to immediately become valid.

**Comment by Pingger** [comment]
Here we see, why one should always post their solution below their own question: There is always someone, who has the same (or very similar) issue.
