### ISSUE TITLE
API authentication not available via `Authorization` header: Missing CSRF token

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#16734]
- Gitea version (or commit ref): 1.16.0+dev-109-gd17f555fe
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description
Swagger lists the option to authorize via the `Authorization: Bearer <token>` HTTP header.
Unlike authorization via query string parameter `?access_token=<token>`, this always fails with the response:
```
Missing CSRF token.
```

I assume this applies to all API routes, I specifically tested with `GET /notifications`.

**Comment by noerw** [comment]
Checking some other routes, looks like only `GET /notifications` is affected. `GET /repos/search` works fine for example

**Comment by zeripath** [comment]
This is very likely a duplicate where it is due to the fact that you're logged with a session in the web API. If you're logged in the with a session then you need a CSRF to post.

Try replicating your problem using curl on the command line. If you can then this is something different but otherwise it's the above.

**Comment by noerw** [comment]
Indeed that's it, didn't think of that
