### ISSUE TITLE
Some links are broken when using a different port than https (443)

### ISSUE THREAD

**Issue by erxbout** [go-gitea/gitea#16884]
- Gitea version (or commit ref): 1.15.0 (from release download)
- Git version: git version 2.19.1.windows.1
- Operating system: WindowsServer2016 (1607 Build 14393.4583)
- Running directly from windows binary by starting it via commandline
- Database (use `[x]`):
  - [ ] MySQL
  - [ ] MSSQL
  - [x] PostgreSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
I am running behind a reverse proxy and a sub path. Works like a charm.. When used with default https port 443..
Sometimes I have to use another port with the same proxy (I configured 444) to connect, but not every url is pointing to the right path with the port addition.
Looks like an inconsistency to me..

Cases are:
- Issue overview (Name of the issue, repository link, but labels work fine!)
- Pull requests overview (same as issue)
- Preview markdown (xhr request)
- Release file attachment downloads (source code zip works)

## Screenshots
hopefully to make my point clear, not to confuse ;)
![giteaissue1](https://user-images.githubusercontent.com/68945126/131390863-4767f897-3113-4ce4-8391-9f08163eb87a.PNG)
![giteaissue2](https://user-images.githubusercontent.com/68945126/131390877-1bcf1b47-be07-41cb-85e7-7d24aa6c5351.PNG)
![giteaissue3](https://user-images.githubusercontent.com/68945126/131390883-3ebb65c4-5d2b-4fad-838a-169ef8083be7.PNG)

**Comment by zeripath** [comment]
What is your app.ini?

**Comment by erxbout** [comment]
you mean this part?

DOMAIN           = erxbout.ddns.net
HTTP_PORT        = 1433
ROOT_URL         = https://erxbout.ddns.net/gogs/

else here is the whole ini with removed creds and stuff
[app.ini.txt](https://github.com/go-gitea/gitea/files/7079469/app.ini.txt)

**Comment by lunny** [comment]
You can only set one `ROOT_URL`, so you cannot visit use two different domains  or ports.

**Comment by erxbout** [comment]
Ok but that still leaves me confused about that most of the website stays usable and cooperates with the changed port and only above cases do not..

**Comment by zeripath** [comment]
Unfortunately,  Gitea does not support multiple different ROOT_URLs. It's essentially luck that some of the urls work but others don't. It's not really a bug that any particular URL doesn't because if you had mounted Gitea on different subURLs - none of the links would work. 

I do have some ideas on how to support multiple different ROOT_URLs and if you would like to support me to add that we can discuss but it's somewhat involved and will require lots of changes and refactors. It's worth doing but it's not going to be a quick process.

**Comment by erxbout** [comment]
I could only help you with testing.. I am not quite familiar with go..

Also it is not a must have for me, if there is more important stuff to do thats also fine ;)

Just thought this was a bug cause of the inconsistency.. ^^

If you still think its worth the effort then go ahead, but I am sorry because there is not much I can do except for testing in my environment for you..

**Comment by zeripath** [comment]
I'm gonna close this, #8697 is the Feature request issue.

**Comment by erxbout** [comment]
Ok, thank you for your fast answers..
I thought about this problem for a few days now, maybe some input for refactoring:
When it is possible one could use relative url paths everywhere and let the proxy handle the host part..
then in the config would only be the subpath and thats it..

Just my two cents or input for possible future refactoring if it is possible to work with this

**Comment by zeripath** [comment]
Thanks for your idea - it's not correct because it doesn't account for SubURL setups and doesn't account for the times we need to return the full URL (which are plentiful)

There's no simple quick solution and but as I said I do have ideas for how to do something approaching multidomain support as we do get given the url the user thought they were requesting from. It would require considerable time and multiple refactors to make it possible.
