### ISSUE TITLE
gitea.db created in wrong folder which running as Windows service

### ISSUE THREAD

**Issue by emisjerry** [go-gitea/gitea#1701]
It's quite strange. Execute in command line and running as service created different db folder.

DB: SQLite setting in app.ini is data/gitea.db

When running as service, gitea.db will be created in c:\windows\system32\data.
Executing in command line, the folder is c:\gitea\data

**Comment by ghost** [comment]
Maybe this is because the working directory for a service on launch is C:\windows\system32\ ? (I don't know whether it is, I'm just guessing)

https://msdn.microsoft.com/de-de/library/windows/desktop/ms683197(v=vs.85).aspx this function could be used to find out where the binary is actually located instead of using the working directory, in case this turns out to be the culprit.

**Comment by emisjerry** [comment]
gogs has the same problem.

The default [database] PATH in app.ini is data/gitea.db

We must use the full path c:/gitea/data/gitea.db to specify the correct db location.

**Comment by lafriks** [comment]
Duplicate of #2159
