### ISSUE TITLE
The derived warehouse is converted to an ordinary warehouse, and the derived quantity has not changed

### ISSUE THREAD

**Issue by yixiaco** [go-gitea/gitea#17026]
- Gitea version 1.15.2:
- Database :  MySQL

## Screenshots
![image](https://user-images.githubusercontent.com/30982989/132994215-570e7eca-34ef-461f-9d22-d8666ba79ec1.png)
The derived warehouse was modified by me to a normal warehouse

**Comment by noerw** [comment]
translation: converting a fork to a standalone repo does not affect the fork counter of the original repo 🙃

**Comment by zeripath** [comment]
The issue is that:

https://github.com/go-gitea/gitea/blob/7c84c9423246c0bd65a151897822adc298933e45/routers/web/repo/setting.go#L558-L564

Does not also call:

```go
		if _, err := sess.Exec("UPDATE `repository` SET num_forks=num_forks-1 WHERE id=?", repo.ForkID); err != nil {
			return fmt.Errorf("decrease fork count: %v", err)
		}
```

within the transaction that `UpdateRepository` happens in.

There should be a new function `ConvertFromFork` within models/repo_*.go that will do the necessary updating of the root repo.

**Comment by zeripath** [comment]
Or probably better UpdateRepository needs to load and check if the repo has changed and handle the necessary changes itself
