### ISSUE TITLE
Translate all doc files with Crowdin

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#17081]
### Feature Description

Currently, it is always painful to see that documentation pages are present in English,
and maybe in another language if you are lucky.
It is, however, a wheel of fortune spin which language that will be.
And most often, these other translations are outdated.

As we have seen, there is a translation community on Crowdin that takes consistent care of translating the most common languages - `French`, `German`, `Spanish` and `Chinese` always seem 100% translated.
As far as I have seen, Crowdin supports editing more than one source file and especially Markdown files as well.
So, what if we would simply use the same mechanism that is used for source strings to translate the documentation files as well?
That way, in the worst case the documentation will stay just as it is now, and in the best case, it will be fully available in more languages and also regularly updated once the English doc file changes. Also, there won't be PRs anymore that only change the doc files in other languages.
If a language does not offer a translation for a file, there will still be the English backup just as there is now.

This can overall only benefit in the adoption of Gitea.

**Comment by comradekingu** [comment]
Close to 800 different people, managed to arrive at one language with coverage, in 6 years…
Translating all 15000 words can be done in a day, by one person.
Were it not for the lackluster functionality and other drive-by translators, that would all work.
Introduce a voting system that holds up strings in translation, and now there is no consistency, and all the smaller languages are at a disadvantage because they have no hope of moving past it.
Without any links or facilities for fixing source strings, the bigger languages help fix issues betwixt themselves, and nobody else gets their workload lightened, much less improve anything for the majority of users for whom English is the default.
Add to this that it is impossible to navigate a big array of strings, and that seeing multiple languages at once can't be done.
Again the eyeballs cater to the stuff that is the easiest to fix, which somehow still hasn't gotten done.
And then there are erroneous and conflicting language codes in use, so that some translations don't even show up.
There is no community anywhere on Crowdin. It is a closed source, as-a-service-only mess.
Why Gitea is associated with Crowdin is beyond me, it seems to have been decided on a whim https://github.com/go-gitea/gitea/issues/8372
Translating documentation is no small feat, and Gitea could really stand to benefit from using Weblate like most every other libre software project does. Then developers could be doing more development, and I dare say the documentation could be up to date.

**Comment by delvh** [comment]
I definitely see your point.
I've also wondered already why Gitea uses Crowdin and not something else.
I've often enough seen the shortcomings of Crowdin.
I only mentioned Crowdin because that system already exists and "works".
I have nothing against switching to Weblate as my quick glance just now seemed promising.

**Comment by comradekingu** [comment]
@delvh
I did some digging and found out nobody answered the request over at Weblate
https://github.com/go-gitea/gitea/issues/114
At the time it didn't support https://docs.weblate.org/en/latest/formats.html#ini-translations and
https://hosted.weblate.org/hosting/ wasn't automated.

**Comment by lunny** [comment]
Closed as docs moved to https://gitea.com/gitea/docs and a new issue opened. Let's discuss it there. https://gitea.com/gitea/docs/issues/6
