### ISSUE TITLE
Use caddy as the main server

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1721]
I think Caddy could be used for the main part of the server. Gitea would listen on a different port on localhost, and Caddy would listen on the main port chosen by the user. This would allow us to do more complex things easier such as:

1. [Automatic HTTPS with Let's Encrypt](https://github.com/go-gitea/gitea/issues/1167)
2. [Redirect HTTP to HTTPS](https://github.com/go-gitea/gitea/issues/1720)
3. [Gitea pages on a separate domain](https://github.com/go-gitea/gitea/issues/302)
4. [Separate domain for raw files](https://github.com/go-gitea/gitea/pull/685)
5. Redirect old URLs
6. Set timeouts
7. Listen on multiple domains and IPs

Many of the issues listed above could be fixed very easily if we integrate Caddy into Gitea.

**Comment by appleboy** [comment]
I will integrate Let's Encrypt with multiple domains and redirect HTTP to HTTPS.

**Comment by sondr3** [comment]
As long as it's optional, I use nginx for everything on my server and would like to keep it how it is right now with Gitea behind nginx. Besides, I don't really understand the need for all of this in Gitea.

**Comment by sapk** [comment]
I think that it is not the role of gitea to handle all of specific frontend config. For exemple in gitea-infrastructure  we use traefik and we should let that choice to user for setting inside is own env. gitea should only offer a simple http interface maybe some additional sugary but we should keep it simple.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by kolaente** [comment]
What about http/2? (For which you would need a secure connection over https)

**Comment by bkcsoft** [comment]
Just make gitea a caddy-plugin :trollface:

**Comment by ShalokShalom** [comment]
+1

**Comment by ShalokShalom** [comment]
@sapk  I see this more as an optional choice. Add it to the documentation, support it. 
Especially Gitea Pages is very important to me and a fundamental benefit to Github.
They offer only support for Jekkyl, one of some hundred of static site generators. 
Open source is all about easy access, otherwise is it just hypocrisy.
Caddy offers https for everyone, in a very simple way. This means a secure internet connection and easy webpages for everyone. I think this is a great idea.

**Comment by sapk** [comment]
We could describe how to use caddy and gitea side by side to work like github pages that not that difficult and everything needed is allready here. Just use the git plugin of caddy to pull changes and execute a command (hugo, jekyll or otherq) if needed.

**Comment by ShalokShalom** [comment]
Github pages work only with Jekkyl. Gitlab pages offer support for more. I am for IPFS anyway:

It is a distributed peer-to-peer network, which offers the hosting of static sites:

https://ipfs.io/
https://ipfs.io/ipfs/QmdPtC3T7Kcu9iJg6hYzLBWR5XCDcYMY7HV685E3kH3EcS/2015/09/15/hosting-a-website-on-ipfs/

**Comment by aoyawale** [comment]
I agree on using nginx/http for the web server and configs

**Comment by mvdkleijn** [comment]
I'm very interested in this discussion... not so much because of caddy... but on what this discussion implies.

Is Gitea going to try to do it all... or is Gitea going to do one thing and rely on integration options for the non-core stuff...

Seems to me that a product like Gitea should focus on the core: git repo management, issues and wiki and rely on proper documentation and integration options for the other stuff. That would be my hope anyway.

Open source is about choice. Stuffing everything into Gitea, creating a big monolithic application in the process, would be horrible.

**Comment by techknowlogick** [comment]
Closing as caddy in front of Gitea currently works.
