### ISSUE TITLE
Deleting the latest comment revision should view previous revision as comment

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#17289]
### Gitea Version

1.16.0+dev-345-g24b83ee1e

### How are you running Gitea?

Build from source, from cli

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

If I delete the latest comment revision, the comment will be still the same as the deleted edit. Example: I edit a comment "hello" to "hello world" and delete the "hello world" revision, then it should be "hello", but it's "hello world".

cc @wxiaoguang 

### Screenshots

https://user-images.githubusercontent.com/80460567/136754079-7b481d14-2102-4f3f-9c35-14b187397b84.mp4

**Comment by qwerty287** [comment]
Ok, I wanted to point out: if I delete the latest revision, it won't be deleted - it will be shown in the comment field

**Comment by delvh** [comment]
I can totally understand that decision: Otherwise, the code complexity increases from constant time to linear time as you then have to backtrack the history to the most recent non-deleted revision, which can take up to n times for a history of size n. And that even ignores the potential problems you might encounter with that feature.
