### ISSUE TITLE
Replay webhook requests

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#17324]
### Feature Description

I think it would be great if Gitea could replay webhook requests. That would make it very easy do re-trigger a CI run that previously failed for some error or another where I can't restart the build in the CI itself.

From a UX point of view, a button in the webhook history would be the best.

**Comment by richex-cn** [comment]
I also think this is necessary.

**Comment by xsirh925** [comment]
I was looking for another issue related to webhooks and saw that this issue was open. I'm not certain exactly which version added this, but as of `1.16.3` there is now a button in the configuration page for a webhook that implements resending the POST request associated with a webhook containing its original payload.
![gitea replay webhook](https://user-images.githubusercontent.com/45466528/159346803-00a364ee-931a-47d2-88db-2dc1ada26548.png)
