### ISSUE TITLE
 delete a user from command line ignores the -c switch with config file

### ISSUE THREAD

**Issue by mariuz** [go-gitea/gitea#17521]
### Gitea Version

1.15.6

### Git Version

git version 2.25.1

### Operating System

ubuntu 20.04

### How are you running Gitea?

i used the binary version with wget 

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

create user from command line works ok and the website is ok  , but the issues start when i try to delete a user 

(ROOT = /home/git/gitea-repositories and works correctly) 
so it tries to write in default folder and ignoring config file  /etc/gitea/app.ini

```
gitea -c /etc/gitea/app.ini admin user delete --id 20

2021/11/02 11:46:42 ...s/storage/storage.go:171:initAttachments() [I] Initialising Attachment storage with type:
2021/11/02 11:46:42 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /usr/local/bin/data/attachments
2021/11/02 11:46:42 main.go:117:main() [F] Failed to run app with [gitea -c /etc/gitea/app.ini admin user delete --id 20]: mkdir /usr/local/bin/data: permission denied
```

**Comment by wxiaoguang** [comment]
You should use the correct `app.ini` (the one was already created by the first gitea setup), never use the non-related ones.

**Comment by zeripath** [comment]
This is interesting because:

https://github.com/go-gitea/gitea/blob/95da01c5cd946d6e6ba0b0110676d3df36ce85db/main.go#L121-L127

should be passing along these values up to the subcommand.

With:

https://github.com/go-gitea/gitea/blob/95da01c5cd946d6e6ba0b0110676d3df36ce85db/main.go#L129-164

being responsible propagating the setting the custom conf correctly.

---

I guess one way to check what's going on would be to stick some logging into that function to check if this Before func isn't getting propagated correctly.

**Comment by wxiaoguang** [comment]
@zeripath 

But my test shows that the global options `-c` position seems correct here.

```
./gitea -c debug/no-such.ini admin user delete --id 123123 
2021/11/02 23:57:28 ...s/setting/setting.go:541:SetCustomPathAndConf() [W] Using 'custom' directory as relative origin for configuration file: '/Users/user/work/gitea/custom/debug/no-such.ini'
2021/11/02 23:57:28 ...s/setting/setting.go:563:NewContext() [W] Custom config '/Users/user/work/gitea/custom/debug/no-such.ini' not found, ignore this if you're running first time
```

The log shows that the gitea is using `debug/no-such.ini`

**Comment by zeripath** [comment]
@mariuz you likely need to set `-w` correctly.

Gitea as compiled by default is not really intended to get placed in /usr/local/bin or /usr/bin. It makes assumptions about where it is going to find things based upon the location of the binary. These assumptions can be overridden by environment variables and/or command line options but if those are not present the default locations will be used. The contrib systemd conf file sets the correct variables by default but your shell is not (nor should it be expected to).

In this case because the data path is not set within the app.ini it is assumed to be the `data/` sub-directory of the "workpath" - that is the directory in which the gitea executable can be found.

Now, there are several ways of getting round this.

1. There is a filesystem hierarchy compliant script that can be found in our contrib folder that I wrote with the intention that this would be what was placed in /usr/bin or /usr/local/bin and the gitea binary placed elsewhere.
2. The other option is when compiling Gitea you can set some LDFLAGS to change the default locations
3. Continue using environment variables and command line options.
