### ISSUE TITLE
Support LFS purely over SSH protocol

### ISSUE THREAD

**Issue by ibigbug** [go-gitea/gitea#17554]
### Feature Description

The current LFS related operations only using `settings.AppURL` as the endpoint:

https://github.com/go-gitea/gitea/blob/bc6df18fb35837b510dfa4daeec53fec32a55af7/services/lfs/server.go#L48

One scenario is I want to have server.ROOT_URL(`settings.AppURL`) to be external faced URL to browse the site.

And I want to have `server. SSH_DOMAIN` to be my internal domain to clone and push code.

But the current implementation only looks at `AppURL`(`ROOT_URL`), should `SSH_DOMAIN` be considered for LFS operations?

**Comment by lunny** [comment]
Hm, git-lfs has supported SSH protocol I think. ref: https://github.com/git-lfs/git-lfs/pull/4446

**Comment by ibigbug** [comment]
good to know, but how to use it?

looks Gitea hasn't support it yet:

```
-> % ssh git@gitea.at.somewhere -p PORT git-lfs-transfer some/repo.git download

Gitea: Unknown git command
Gitea: Unknown git command
```

**Comment by lunny** [comment]
@ibigbug Could you change the title to support a pure ssh lfs protocol something like that?

Yes. Since that PR was merged recently, Gitea itself didn't support that at the moment. But it should fallback to use http/https protocol.

**Comment by ibigbug** [comment]
thanks @lunny 

keen to see Gitea can make LFS over SSH work.

**Comment by ibigbug** [comment]
@lunny any updates?

**Comment by lunny** [comment]
> @lunny any updates?

Nobody are working on this issue.

**Comment by ibigbug** [comment]
@lunny  thanks for letting me know.

How to get someone to take a look at this?

**Comment by davama** [comment]
This feature would be great! :+1:

**Comment by ibigbug** [comment]
looks like https://github.com/git-lfs/git-lfs/pull/4446 is merged.

haven't had a chance to try but will do later

**Comment by fcharlie** [comment]
> @fcharlie did you end up using this project internally and did it work as expected or were there some complications?

Since the prune ssh protocol does not support OSS signature download, and AI needs to download a large number of large files, we disabled it for performance reasons.


Here is also an implementation reference for the SSH protocol:
[https://github.com/charmbracelet/git-lfs-transfer](https://github.com/charmbracelet/git-lfs-transfer)

**Comment by techknowlogick** [comment]
^ that was me that created this bounty (trialing new bounty platform)

**Comment by ConcurrentCrab** [comment]
Hi, is this still being actively worked on or is it up for grabs?

Also just to be clear, integrating [charm.sh](charm.sh)'s (pretty goo looking) https://github.com/charmbracelet/git-lfs-transfer implementation into Gitea successfully such that all LFS functionality starts working over SSH would be an acceptable fix, correct? That is, we don't need a new, in-house implementation?

**Comment by jemiluv8** [comment]
@ConcurrentCrab, I've not been able to get far on this task so it is indeed up for grabs.

**Comment by ConcurrentCrab** [comment]
Thank you for the confirmation, @jemiluv8 

I'm interested in trying my hand at this, so it'd be great if @techknowlogick or another project member could confirm the scope of the task, in regards to my above question.

**Comment by techknowlogick** [comment]
Hi @ConcurrentCrab this is indeed available, and we'd love for you to work on it. Thanks for submitting a WIP PR. In terms of scope, it's "users can interact with LFS using SSH (using either the built-in ssh server, or the integration with opensshd)". Adding the external dep on charm.sh is a-ok.
Documentation would be appreciated but not necessary for completing the bounty (we are in a transition phase with documentation, so I don't want to add extra work to your plate by sorting out where to contribute it), so if you are inclined, even a comment in your PR would be helpful.
If I've missed any of your questions, or you have more, please don't hesitate to ping :)

**Comment by ConcurrentCrab** [comment]
Hi @techknowlogick,

> Adding the external dep on charm.sh is a-ok.

Thanks for clarifying that. To be crystal clear, this is not a build-time dependency, as in pulling in their libraries. This is a run-time dependency on the binary being present in the environment (any compliant implementation would do), just like we're already depending on the git package for the `git-upload-pack`/`git-receive-pack` binaries. Ofc, it's still an "optional" dependency, and if it isn't present we simply fall back onto the HTTP protocol, so we're no worse off than where we started.

As I mentioned, the patch in the PR already makes pure SSH LFS sessions work, according to my experiments I outlined above. But this is very much the minimum-changes-required version of this patch, conceivably can be termed a 'hack'. I think it'd be worth making some refactors to the logic in that handler. There's already quite a bit of convoluted logic in there, so I'd feel bad leaving it there with even more surprise ifs-and-elses :)

And I'll add all the relevant useful information into the commits, as you suggested.

Regarding the security model I think we're mostly fine, except at one point it does seem to care about the "verb":
https://github.com/go-gitea/gitea/blob/621e1ff9c9ec04ea8e6d68cd8e38bb5734f29bdc/routers/private/serv.go#L140
That line seems to be from this commit fixing a bug related to the upload command:
https://github.com/go-gitea/gitea/commit/95013fde60748c425eb910dcab5d1fdd1c89ae18

That seems important. I'll be looking more into what exactly that might mean, as the "upload" mode of our new command should probably be on that list of exceptions too.

**Comment by ConcurrentCrab** [comment]
Whoops, called it too early. The network transfer indeed is working, but the binary isn't placing the objects where Gitea expects them to be. Huh. Going to look into that.
Meanwhile, experimenting with the refactor on another branch: https://github.com/ConcurrentCrab/gitea/commits/lfs-ssh-2/

**Comment by ConcurrentCrab** [comment]
Ah. It seems both Charm and Scutiger store the LFS assets in the `<repo_dir>/lfs`, while Gitea expects them in a separate data directory... which seems to be common across all the repos? That seems like a strange choice, since it'll lead to both higher chances of collision, and slower performance as the directories fill up. Anyway, it would seem the paths need to be changed in `git-transfer-lfs` then.

**Comment by lafriks** [comment]
Gitea stores all LFS blobs in same directory so that same files in multiple repositories could reuse them (especially important for forking), also need to keep in mind that Gitea stores all LFS references to repositories that specific blob is used in database. LFS storage can be not only filesystem but also S3

**Comment by ConcurrentCrab** [comment]
Hi @lafriks,

Thanks for sharing this information.

> Gitea stores all LFS blobs in same directory so that same files in multiple repositories could reuse them (especially important for forking)

Ah, that sounds reasonable.

> also need to keep in mind that Gitea stores all LFS references to repositories that specific blob is used in database. LFS storage can be not only filesystem but also S3

I see. That does significantly complicate things. This certainly doesn't sound like something that could be done by an out-of-process client anymore, not the db stuff and definitely not the S3 stuff. The git protocols take special care to avoid stuff like that (mostly by having a single source of truth), so that multiple protocols like SSH, "dumb" HTTP, "smart" HTTP, etc. can worth together without a hitch.

So how would you suggest approaching this? I would think the simplest way would be throwing away the out-of-process client, and implementing an in-process reader/writer that calls the same functions the HTTP LFS API does. But not being aware of the architecture, I'm open to suggestions.

**Comment by lafriks** [comment]
I think that in-process and internal API to reuse HTTP logic would be the way to go imho

**Comment by ConcurrentCrab** [comment]
Alright, mostly done with the rote work. What I ended up doing was vendoring the transport package for the charm.sh library (earlier I tried just importing it but the certain differences between the file and Gitea API made that unfeasible), modifying it a bit, and adding a "backend" that proxies to the Gitea internal store.

Just need to figure out why transfers are throwing 500s :)

**Comment by ConcurrentCrab** [comment]
Aaaand that should be it. Pushes and clones all seem to work properly, and metadata objects are registered like they should be. I think support for Pure SSH LFS is complete :)

Marking draft PR as final now.

**Comment by ConcurrentCrab** [comment]
Continued in https://github.com/go-gitea/gitea/pull/31516

I guess I had to resubmit with a new PR for the algora bot to see.

**Comment by ConcurrentCrab** [comment]
Finally get everything working, and a `git-lfs` bug pops up :\
https://github.com/git-lfs/git-lfs/pull/5816

I think the PR is largely complete, but I would... suggest holding off on merging it until a fixed version of `git-lfs` is released and is in common use, due to the nature of the bug (in the presence of pure LFS SSH support, it degrades a normal push into a 2-minute wait).

**Comment by ConcurrentCrab** [comment]
You can test it but obvs throw a fixed build of `git-lfs` on your PATH, unless you want to wait 2 mins after every push :P

**Comment by ConcurrentCrab** [comment]
Hi @techknowlogick,

It'd be nice to have some kind of a response to the PR, even if that response is "hi, no, haven't gotten to it yet but will soon".

It doesn't really feel nice to be ghosted for a month after having done all this work (up to and including fixing bugs in the LFS client) :)

**Comment by techknowlogick** [comment]
Hi, @ConcurrentCrab. I'm so sorry for missing the notifications and leaving you hanging. I just tested a build of your PR, and ran into the long hang from git-lfs that you described. I don't think that's a blocker to get this merged, but perhaps LFS over SSH support could be disabled by default in the config, and then in documentation I could add something around disabling automultiplex prior to enabling it?
