### ISSUE TITLE
API access to PR comments

### ISSUE THREAD

**Issue by sotho** [go-gitea/gitea#17683]
The API /repos​/{owner}​/{repo}​/pulls​/{index}​/reviews allows to list reviews and with ​/repos​/{owner}​/{repo}​/pulls​/{index}​/reviews​/{id} the comments of a review can be fetched.

I didn't find a way to fetch the comments that can be done on the Conversation page of an PR. These comments are not attached to code and are not visible with the API above.

In this commit: https://github.com/sotho/gitea/commit/47c66cba3cfed90e1990385420769b88fe1ad3ef
I added a new API call: ​/repos​/{owner}​/{repo}​/pulls​/{index}​/comments that allows to fetch these kind of comments.

What do you think?

**Comment by qwerty287** [comment]
Since issues and prs are the same for Gitea internally, you have to use the issue comment api which will do this. https://try.gitea.io/api/swagger#/issue/issueGetComments

And btw because I took a short look at your changes: the issue ID isn't the index of the issue, so your code wouldn't work - but the new endpoint is notnnecess

**Comment by sotho** [comment]
Thank you. I missed that PR and issue are the same and I need to use this other API. Perfect, then my change is not needed.
