### ISSUE TITLE
Add ability to set a Sign Out URL when using auth proxy

### ISSUE THREAD

**Issue by svh1985** [go-gitea/gitea#17716]
### Feature Description

It would be great if there would be an option to change the logout URL when using the ENABLE_REVERSE_PROXY_AUTHENTICATION setting. This way we can redirect to the Sign Out page of the authentication handler eg: https://auth.domain.com/logout

**Comment by lunny** [comment]
Why don't redirect it in your reverse proxy configuration file?

**Comment by svh1985** [comment]
Ahh that's also an approach to do it. You're talking about a redirect or a return?
I'm not a NGINX proxy expert but I found some code online. But the Gitea URL for logging out is something I cannot find.

Do you know what the logout URL is that I can use?

```
location = /user/logout {
  return 301 https://auth.domain.com/logout;
}
```

**Comment by lunny** [comment]
`POST /usr/logout`

**Comment by zeripath** [comment]
Why not simply change the head_navbar.tmpl to be the correct logout url?

**Comment by svh1985** [comment]
Good point. But currently all changes can be done from the config file, adding another parameter for the logoutURL makes implementation (and documentation) a bit easier for Gitea admins.

**Comment by zeripath** [comment]
I understand but I'm not certain we should jump to make this configurable without allowing other authenticators eg. OAuth2 or LDAP to cascade their logouts too. ​

**Comment by yoyoyonas** [comment]
related / possible duplicate: #14270

**Comment by yoyoyonas** [comment]
> Why not simply change the head_navbar.tmpl to be the correct logout url?

Could you advice me how to achieve logging out from Gitea and from the auth provider?  
Since Gitea requires a `POST` request, I can no solve this simply by letting the auth provider redirect to a Gitea logout URL after logging out there.

So I thought, I can change to `data-redirect` parameter of the logout action to logout from the provider _after_ logging out from Gitea, from `data-redirect="{{AppSubUrl}}/"` to `data-redirect="https://sso.example.com/auth/realms/master/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fgit.example.com%2F`.

But still, Gitea redirects me to `{{AppSubUrl}}/"` after logging out, not to the external URL.  
(I checked the site source; the custom template _did_ work.)

**Comment by novirium** [comment]
Currently it looks like the redirect is actually happening on the [server side](https://github.com/go-gitea/gitea/blob/48eb5ac6856aeed5b6501fcd27899d3dc3da2876/routers/web/auth/auth.go#L405) as a response to the `/user/logout` POST, so it can't be changed by modifying the frontend.

Adding a config option to be able to set the logout redirect URL in `auth.go` would solve this problem, and also provide the basic functionality for #16869 and #14270 (while not implementing the full OIDC spec, it's all that's needed for seamless logout for a lot of SSO use cases).

**Comment by Baitanik** [comment]
any idea when this logout with reverse proxy will get resolved ? 
we have ibm webseal as the authenticator and gitea we have ENABLE_REVERSE_PROXY_AUTHENTICATION = true.

but when logout happens from gitea, it does not call logout from webseal.. 
Please let us know when this will be fixed in gitea

**Comment by wxiaoguang** [comment]
Dup of #14270 ?
