### ISSUE TITLE
Allow unactivated accounts to change email

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#17785]
### Feature Description

Accounts that have not yet been activated only have the option to re-send their activation email. But in case of typos or other mistakes, it would be helpful if they were allowed to change the email address via a simple form (or even access some settings and in the future allow to remove the account, change the password etc).

**Comment by Shea690901** [comment]
Just happened to me, when trying to register on try.gitea.io to try to confirm a bug....

**Comment by treestryder** [comment]
+1 After this just happened to me, on an instance running version 1.14.5+3-g6a3c7856c. I mistyped my email address and now cannot use my preferred username, as I am essentially locked out of it. I can log in. However, I am unable to correct the email address in the profile settings, because the incorrect email address has yet to be verified. 🤔 And never will be.

**Comment by fnetX** [comment]
This is now [implemented in Forgejo](https://codeberg.org/forgejo/forgejo/pulls/1891) so I don't need this feature in Gitea any longer. People who need it, can probably cherrypick the patch.

**Comment by wxiaoguang** [comment]
The code is totally a mess and not worth to be cherry-picked. I will refactor some code first and propose a maintainable solution. I think this feature will be available in Gitea 1.22.

**Comment by lunny** [comment]
It's better to allow deleting the unactive account but not allow it to change the email or name.

**Comment by wxiaoguang** [comment]
Implemented by #29412 and will be in next release 1.22
