### ISSUE TITLE
Cannot check out pull request of private fork

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#17821]
### Gitea Version

1.15.6

### Operating System

Linux

### How are you running Gitea?

[Codeberg/build-deploy-gitea](https://codeberg.org/Codeberg/build-deploy-gitea) - basically compiling via Makefile.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The "official" instructions for fetching a pull request in a private repo (which involves a private fork), tell the user to create a new branch and fetch it.

> Step 1: From your project repository, check out a new branch and test the changes.
> ~~~
> git checkout -b branch_new branch
> git pull remote_url branch_new
> ~~~

But since forks are private, they don't allow a user to access it by default. I cannot find any way to get the commits I see in the Web UI for this pull request to my private repo into my local Git.

The docs aren't more helpful in this case, and since the instructions from the pull request just don't work, I consider this a bug.

**Comment by lunny** [comment]
Have you set up SSH public key or store password into git?

**Comment by zeripath** [comment]
Agh I keep noticing this but it's never percolated to my issue head.

There's a couple of reasons why this is a bit more difficult.

We currently check access at the repo level - this is before we get to know which refs are being requested. So in order to assess access we'd then need to double check if there was any possible pr that could be being pulled/pushed from and then recheck at the pre-receive stage. (And find a similar hook for getting branches too but I'm not sure if one exists.)

Another option is to actually display the pr head ref (which is a ref in the base repo) instead.

Now handling pushes back to that ref is a bit more difficult as we would have to handle pushing back up to the head repo at the same time. That has several gotchas and will require some thought.

**Comment by jjpartyka** [comment]
I think you can checkout PR's code locally, as they are exposed in refs of upstream repo.
Assuming that:
* "upstream" is a repo to which PR exists
* "origin" is your fork of upstream
* ID is PR's number 

you can fetch it into new branch:
`git fetch upstream refs/pull/ID/head:my_local_branch_name`

Then check it out:
`git checkout my_local_branch_name`

And even push into your fork, if needed:
`git push origin my_local_branch_name`

You can list all refs of given repo:
`git ls-remote upstream`

You normally don't see PR branches when you issue `git fetch`, because default pattern for fetching is "fetch = +refs/heads/*:refs/remotes/upstream/*"

**Comment by lunny** [comment]
I think this is outdated. Please open a new issue if it happens again.
