### ISSUE TITLE
Clickable issue/pr links in code tree view

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#17887]
### Feature Description

issue/pr references in commit messages get transformed into clickable links with popup context on the commits view:

![image](https://user-images.githubusercontent.com/2212615/144486508-917b4ffa-c9c4-4292-ae9e-52a6dc57c1f6.png)

but on the code tree view, this is not done:

![image](https://user-images.githubusercontent.com/2212615/144486621-9d09ea3a-e9f9-4bce-b4ce-c03a31f30b21.png)

I think it should be done on the code tree view too. GitHub does that as well.

### Screenshots

On GitHub:

![image](https://user-images.githubusercontent.com/2212615/144486823-1860d209-40d8-4a8e-b9ec-236ba95f201a.png)

**Comment by silverwind** [comment]
This is because the code [naively looks for](https://github.com/go-gitea/gitea/blob/main/web_src/js/features/contextpopup.js#L7) a `ref-issue` class. I think it should be refactored to no longer require this class but instead parse all links and intelligently attach to ones that are internal issue links.

There is already a helper function to parse issue hrefs:

https://github.com/go-gitea/gitea/blob/5f22e2dfb2e3481ff7204566f8b9ec6688c36a1b/web_src/js/utils.js#L56-L60
