### ISSUE TITLE
FR: Could gitea implement a feature like  what Github did with git command line login?

### ISSUE THREAD

**Issue by springrain** [go-gitea/gitea#17934]
### Feature Description

When login Github(HTTPS) in git command line, it will pop up a window which you can open OAuth2 login to finish the login, no password input is needed.

### Screenshots

![github登录](https://user-images.githubusercontent.com/4935705/145185157-5ededa68-cd14-4f7d-b429-685b200f110d.png)

**Comment by a1012112796** [comment]
maybe related to https://github.com/GitCredentialManager/git-credential-manager/issues/145

**Comment by mscherer** [comment]
I am not familiar with the feature on github, can you describe it a bit more ? 

There is no "git login" command, so I am a bit lost on how the popup is supposed to appear.

**Comment by a1012112796** [comment]
maybe the fist step is implement [``oauth2 device flow``](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow)

**Comment by springrain** [comment]
Thank you very much, let me try

**Comment by lunny** [comment]
I don't think this has been resolved.

**Comment by a1012112796** [comment]
fixed by https://github.com/git-ecosystem/git-credential-manager/pull/1062

usage example:

![image](https://github.com/go-gitea/gitea/assets/25342410/54dc58f7-324a-4cd6-b48f-f5377950a7e6)
![image](https://github.com/go-gitea/gitea/assets/25342410/1b4e9a16-e988-4895-8afb-a187ee78332e)
![image](https://github.com/go-gitea/gitea/assets/25342410/30aff978-3157-4289-8566-0a84cbc40f9d)

**Comment by lunny** [comment]
Could you help to create a documentation for that?
