### ISSUE TITLE
Clicking on a feature branch name from a dashboard entry directs to the wrong url (404)

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#17943]
### Gitea Version

1.16.0+dev-670-gc7e23401a

### Git Version

2.34

### Operating System

windows

### How are you running Gitea?

windows service 

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

reports on the dashboard indicate that some parts are clickable 

**eeyrjmr** pushed to **some_branch** at **eeyrjmr/test_issues**

However the branch url points to  **https://try.gitea.io/some_branch**  instead of **https://try.gitea.io/eeyrjmr/test_issues/src/branch/some_branch**   ie the base url does not consider the user/organisation + repository 

![Annotation 2021-12-10 000603](https://user-images.githubusercontent.com/4564448/145494945-00228f08-89bd-493d-aa8a-d5bcba303147.png)
![Annotation 2021-12-10 000627](https://user-images.githubusercontent.com/4564448/145494982-92b62197-6eb4-4089-b0f2-c089a2a930dc.png)

**Comment by jpraet** [comment]
In [#17551 ](https://github.com/go-gitea/gitea/pull/17551/files#diff-dda0bd64abe99b2fc96238e95a74eddf6b89c1210a07130f1d6bedf7528cf461)

`commit_repo = pushed to <a href="%[1]s/src/branch/%[2]s">%[3]s</a> at <a href="%[1]s">%[4]s</a>`
got replaced by 
`commit_repo = pushed to <a href="%[2]s">%[3]s</a> at <a href="%[1]s">%[4]s</a>`
in locale_en-US.ini, but this change was not reflected in feeds.tmpl.

Other types of links in the action feed are simarly broken.

I also wonder about the impact of such structural changes to the parameters passed to existing localized messages: these will need to be updated in all other supported languages, otherwise they will have broken links as well?

**Comment by zeripath** [comment]
We absolutely should not have translators responsible for building URLs. It's bad enough that there's HTML in there but building URLs is not a good idea.

That's why this was changed.

> I also wonder about the impact of such structural changes to the parameters passed to existing localized messages: these will need to be updated in all other supported languages, otherwise they will have broken links as well?

Crowdin notices the change and translators update so this is not a problem.

**Comment by zeripath** [comment]
Ok so it looks like there were a few places missed in feeds.tmpl where the branch URL needs to be correctly formed. Would be a quick pr to fix
