### ISSUE TITLE
If you create a repo called action, it cannot be update

### ISSUE THREAD

**Issue by akkuman** [go-gitea/gitea#18037]
### Gitea Version

 1.16.0+dev-717-g25677cdc5 

### How are you running Gitea?

https://try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

I tried to fix the problem, but found that I could only fix it by disabling the repository that the user created called action.

you can see the demo https://try.gitea.io/Akkuman/action

it cannot be delete or update

**Comment by zeripath** [comment]
Yup this is because it posts to it are being conflicted with:

https://github.com/go-gitea/gitea/blob/2cd1479e774f9bb28a598f6eb34262b996f49112/routers/web/web.go#L488

Two options;

1. Make action a reserved name for repos
2. Move the above endpoint elsewhere.

I think if we can move the above endpoint elsewhere and avoid a reserved name that would be useful. However we need to check the api.go router file to see if there are other conflicted routes that need to be addressed too.

**Comment by lunny** [comment]
How about change the router to `<username>/-/action`?
