### ISSUE TITLE
Milestones of archived Repositories still open

### ISSUE THREAD

**Issue by kimdre** [go-gitea/gitea#18257]
### Gitea Version

1.15.9

### Browser Version

Brave 1.34.80

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Any Milestones of archived Repositories still appear as "_Open_" in the Milestones-Tab (BASE_URL/milestones).
Maybe those should get their own section.

### Screenshots

![Milestone Tab](https://user-images.githubusercontent.com/27567533/149205777-082da055-b21c-42a5-9dc1-eac31f2f6c33.png)
![Milestone View](https://user-images.githubusercontent.com/27567533/149205784-069aca28-223c-4430-ae84-5f42e34e3c34.png)
![Milestone Issue](https://user-images.githubusercontent.com/27567533/149205792-cbc62ec7-3b09-41b6-ac4a-2733db507f75.png)

**Comment by delvh** [comment]
I am not quite sure what you mean:
I also just noticed this, and I think it is not exactly user-friendly.
Normally, if a repo is archived, you don't want it to be displayed in your list of milestones because there is no more development on this repo.
But the purpose of this list should be to notify you where you have (what) work to do...

**Comment by kimdre** [comment]
I think it would be easier if they got their own tab so you can browse between open, closed and archived issues.

**Comment by delvh** [comment]
Or at least some sort of checkbox to switch between displaying archived repos as well.
