### ISSUE TITLE
Add XMPP URI support (RFC5122)

### ISSUE THREAD

**Issue by Neustradamus** [go-gitea/gitea#18294]
### Feature Description

Dear @go-gitea team,

In first, I wish you a Happy New Year 2022!

Can you see for add XMPP URI support?
XMPP URI support must be added because it does not work.

Examples:
- xmpp:username@domain.tld
- xmpp:username@domain.tld?message
- xmpp:mucroom@domain.tld?join

It is a standard:
- RFC5122: https://tools.ietf.org/html/rfc5122

Can you update it and solves this big bug?

There is no problem for mailto.

Thanks in advance.

### Screenshots

https://i.ibb.co/cxMypjG/gitea-xmpp-uri-does-not-work-mailto-ok.png

**Comment by wxiaoguang** [comment]
Can you help to describe where to support XMPP? What do you expect to see.

**Comment by Neustradamus** [comment]
@wxiaoguang: Thanks for your quickly reply!

First, in an issue/ticket/comment.

But you can see to add in user/organization and repository description too:
- https://i.ibb.co/T4gHPJc/gitea-profile-description-and-issue-description.png

Issue:
- https://i.ibb.co/878sCzJ/gitea-issue-example.png

Project (forgotten test@domain.tld on the screenshot but it work):
- https://i.ibb.co/3TVfc3g/gitea-project-example.png

Wiki:
- https://i.ibb.co/TPp8Q4R/gitea-wiki-example.png

Note: mailto:test@domain.tld does not work but test@doman.tld is by default a mailto in an issue/project/wiki.

**Comment by Neustradamus** [comment]
@wxiaoguang: Hello,

Have you progressed on this issue?

Do you need help?

Thanks in advance.

**Comment by wxiaoguang** [comment]
No progress from my side, it's open to be picked up. IMO it's likely related to the markdown parser.

**Comment by DeathByDenim** [comment]
I looked a bit more into this. I tried the release version of Gitea 1.17.0 to see if XMPP link are still broken, and indeed they are.
Then I tested the markdown parser which is goldmark v1.4.13 as far as I can tell. So I wrote an extremely simple test program to test goldmark:
```
package main

import (
        "fmt"
        "bytes"
        "github.com/yuin/goldmark"
)

func main() {
        var md bytes.Buffer
        var html bytes.Buffer
        md.WriteString("[hey](xmpp:node@example.com)")
        if err := goldmark.Convert(md.Bytes(), &html); err != nil {
                panic(err)
        }
        fmt.Println(html.String())
}
```
That indeed produces the correct result `<p><a href="xmpp:node@example.com">hey</a></p>`.

So it must be something that Gitea is doing differently. Maybe in the options it gives to goldmark or something?

**Comment by DeathByDenim** [comment]
Well, it turns out this is not a bug at all. It's just a result of not reading the documentation and by that I mean `custom/conf/app.example.ini` or the [cheat sheet](https://github.com/go-gitea/gitea/blob/main/docs/content/doc/advanced/config-cheat-sheet.en-us.md#markdown-markdown). I traced this issue all the way to the sanitizer policies which by default strips out anything that isn't http, https, or mailto until I finally arrived at `CUSTOM_URL_SCHEMES`.

So it turns out that Gitea does have a setting to allow additional protocols! Add this to your `custom/conf/app.ini`:
```
[markdown]
CUSTOM_URL_SCHEMES = xmpp
```
You can now use XMPP links in your markdown files.

I think this issue can be closed.
