### ISSUE TITLE
Frontend discussion: jQuery & Fomantic-UI

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#18302]
There are many discussions about the frontend refactorings, this issue is to record the details, and avoid bikeshedding in future.

# Background

Gitea is using DOM Native, jQuery and Vue2 together, the UI part is heavily using Fomantic-UI.

# Discussion Topics

## Should Gitea use a new UI framework?

Some maintainers mentioned [Tailwind CSS](https://tailwindcss.com) before.

Gitea frontend now uses Fomantic-UI components heavily, ex: Dropdown, Modal, Checkbox, etc.

Currently there is no conclusion or detailed plan about how to migrate the UI to a new framework. 

## Should Gitea drop jQuery?

The mentioned Cons of jQuery are:

### jQuery Performance

Question: jQuery was proven to be much slower than native (sometimes as much as 10x), just look at their code which is full of hacks to support weird edge cases and legacy browsers. While the performance difference will probably not matter in most cases, I still think it's unnecessary baggage we can avoid by using the underlying APIs directly.

Discussion: In most time it is not that slow and it doesn't affect user experience. JS is slower than C but it doesn't mean that we should write everything in C.

### jQuery Popularity

Question: Modern web developers don't even learn this API any more (SPA frameworks strongly discourage jQuery), so the contributor base that knows jQuery will shrink over time.

Discussion: The current situation is: Gitea has a lot of legacy MVC code and uses many jQuery features: event system, ajax, filter and chained-call `$().parent().foo().bar()`. If we drop jQuery, we would rewrite them all and introduce a house-made jQuery-like framework. if we replace jQuery with a home-made framework, it would be much less popular than jQuery.

### New PRs using jQuery during migration

Question: If we start the migration, a new PR uses jQuery, what should we do? Force the contributor to rewrite, or we rewrite for them, or just accept it?

Discussion: It's not friendly to force contributors to rewrite without jQuery. If we accept the new PRs with jQuery then new code comes and the percentage of jQuery increases. No ﻿conclusion yet. 

### Continuity 

If we decide to start the refactoring, we should guarantee it can succeed. If we stop half-way, then more and more frameworks would be mixed together, it would be a big disaster. That's why we should think carefully and have a clear plan before we continue.

### End-to-end tests

by singuliere: The primary problem with refactoring the UI is the lack of end to end testing (e.g. running a browser and have a test click on the web page, using a selenium driver). Not that it will make it impossible. Just significantly more difficult and prone to regressions. It would make sense to start with adding a reasonable amount of end to end testing so that the result of a human interaction with the UI can conveniently be verified to not change after the framework is replaced.

by wxiaoguang: If we do framework level migration and refactoring, then the pages should be rewritten, then all old tests become invalid and should be rewritten too. So the tests had better to be written in a long-term & stable framework.

# Next Step

If we choose to drop jQuery, before we make a final decision, we should document all detailed steps about:

1. How to deal with Fomantic-UI and its components? If we still use Fomantic-UI heavily, jQuery is a must.
2. How will the home-made library for jQuery replacement look like?
3. How can we guarantee the refactoring succeed? We can not stop half-way, otherwise there would be a big disaster.

If we choose to continue using jQuery and Fomantic-UI, we can make some new guidelines.

**Comment by wxiaoguang** [comment]
@go-gitea/maintainers

**Comment by singuliere** [comment]
The primary problem with refactoring the UI is the lack of end to end testing (e.g. running a browser and have a test click on the web page, using a selenium driver). Not that it will make it impossible. Just significantly more difficult and prone to regressions. It would make sense to start with adding a reasonable amount of end to end testing so that the result of a human interaction with the UI can conveniently be verified to not change after the framework is replaced.

**Comment by wxiaoguang** [comment]
> The primary problem with refactoring the UI is the lack of end to end testing (e.g. running a browser and have a test click on the web page, using a selenium driver). Not that it will make it impossible. Just significantly more difficult and prone to regressions. It would make sense to start with adding a reasonable amount of end to end testing so that the result of a human interaction with the UI can conveniently be verified to not change after the framework is replaced.

If we do framework level migration and refactoring, then the pages should be rewritten, then all old tests become invalid and should be rewritten too. So the tests had better to be written in a long-term & stable framework.

**Comment by kdumontnu** [comment]
> The primary problem with refactoring the UI is the lack of end to end testing (e.g. running a browser and have a test click on the web page, using a selenium driver). Not that it will make it impossible. Just significantly more difficult and prone to regressions. It would make sense to start with adding a reasonable amount of end to end testing so that the result of a human interaction with the UI can conveniently be verified to not change after the framework is replaced.

I completely agree. I don’t have a strong opinion for what front-end test tool to use, but I checked out some options last year. BackstopJS and Cypress seemed like the two best contenders. Backstop is cool, but the problem is where to save the screenshot data without blowing up our repo size (or adding LFS dependency). 

I think Cypress is the best contender. They have a free open source offering, you can test across different browsers, and there is a ton of support and integrations. The downside is that its a bespoke testbed language.

I don’t have a ton of time to develop this near term, but I would be happy to help get things set up and help sponsor development.

**Comment by techknowlogick** [comment]
While I am still reading through the above, I'd also like to explicitly state accessibility as part of the acceptance criteria.

**Comment by silverwind** [comment]
Regarding jQuery, we can use [eslint-plugin-jquery](https://github.com/dgraham/eslint-plugin-jquery) to gradually migrate off of it. Each time a new feature is refactored, a lint rule can be enabled to forbid it.

**Comment by kolaente** [comment]
My two cents:

* I don't think we should build a home-made js framework and use that instead of jQuery. We'll probably be better off using something already made that fits our use case. I've had a good experience using alpine js for these kinds of things, in a similar sized codebase than Gitea. The same is true for tailwind. I personally don't like foomatic UI because of its age and all the hacks it has, back from a time when we did not have flexbox. Maybe a good idea to check what the foomatic community thinks about this and what they plan?
* Another option would be to build an entirely new framework. This has mostly downsides though: we can't do it gradually, we need to choose a framework which everyone knows and it increases the barrier for contribution. The only upside is we'd have a very nice, state-of-the-art Frontend (at least for a few years until the next shiny thing comes around). But it would be so much work to build it, and will likely always lag behind as we keep adding new features.
* From my experience, cypress wins over selenium.

**Comment by tboerger** [comment]
My two cents:

* Start using more VueJS instead of jQuery everywhere. No way to start writing a custom framework!
* Tailwind CSS sounds like a good replacement for the current CSS framework
* Enable eslint-plugin-jquery to prevent reintroduction of jQuery functions within pull-requests

**Comment by silverwind** [comment]
> If we drop jQuery, we would rewrite them all and introduce a house-made jQuery-like framework. if we replace jQuery with a home-made framework, it would be much less popular than jQuery.

No library/frameworks/wrappers of such kinds please. Modern DOM APIs are potent enough to be used without wrappers. Cases like `fetch` could be wrapped for the purpose of authentication/CSRF token, but generally we should just use them as they are.

**Comment by wxiaoguang** [comment]
> > If we drop jQuery, we would rewrite them all and introduce a house-made jQuery-like framework. if we replace jQuery with a home-made framework, it would be much less popular than jQuery.
> 
> No library/frameworks/wrappers of such kinds please. Modern DOM APIs are potent enough to be used without wrappers. Cases like `fetch` could be wrapped for the purpose of authentication/CSRF token, but generally we should just use them as they are.

I was not talking about `ajax`. I mean, what about these chained-calls? `$().parent().foo().bar()`? What's the best method to rewrite these code without jQuery while keeping the code clear and correct?

**Comment by lafriks** [comment]
If we would rewrite dynamic parts to Vue we would not need such constructs

**Comment by wxiaoguang** [comment]
> If we would rewrite dynamic parts to Vue we would not need such constructs

I agree new frameworks won't need such problems. 

The reality is, Gitea uses a lot jQuery and Fomantic-UI. Everyone knows "what to do" is better, but it doesn't help now. I still want to mention that recently some new code were written in Vue but it only makes the `index.js` more messy.

If we can clarify "how to do" ahead and make everyone work together, we could achieve the goal.

A question is: do most of us agree to only write Vue code in future and never touch jQuery and Fomantic-UI any more? If yes, we can write this agreement down and discuss how to start rewriting old code.

**Comment by Matt-Deacalion** [comment]
First, I would advocate for guidelines on any new frontend functionality, for example:

- No storing state in the DOM
- No touching the DOM directly
- Component based
- No side effects between components

Second, once a few things have been delivered like this it will be easier for new and existing contributors to refactor previous features in the same manner.


### How to deal with Fomantic-UI and its components? If we still use Fomantic-UI heavily, jQuery is a must.

We keep it in place, and phase it out as we add new functionality. There will be a transition period where we have both, but if it's clear that we have a single way of adding new functionality - momentum will pick up fast. There will be many "easy pickings" for new contributors to pick up.

### How will the home-made library for jQuery replacement look like?

I think this would be a red herring. We can use ES6, and if we want to "sprinkle" some pizazz in certain bits we could use a tiny framework like [petite-vue](https://github.com/vuejs/petite-vue) or [alpine](https://alpinejs.dev/) (although I'm -1 on this). Once the frontend has moved into a declarative way of doing things (Vue) we won't be writing code to update the DOM, but rather stating how it should behave with data.

### How can we guarantee the refactoring succeed? We can not stop half-way, otherwise there would be a big disaster.

We draft a plan and take it one bite at a time. We don't need to go full SPA. We keep everything we have at the moment, and start adding Vue components - initially they can be populated by loading the data from within the served pages, e.g.

```html
<script>
    const issues = [
        {id: 1, title: 'Not enough funny!', …},
        // etc
    ];

    // Vue component initialized with `issues`… later on this could be refactored into an API endpoint
</script>
```

Then when the components are in place, it will be obvious what an API should look like and we can create a central frontend data store with [Pinia](https://pinia.vuejs.org/) if needed - which all components will have access to. [JSFiddle demo](https://jsfiddle.net/j59dsLn3/).

I'm not sure if the jury is still out on Vue with gitea, but here's my take on why it's a good fit:

- progressive enhancement (can be dropped in bit by bit)
- incremental learning curve, accessible with a low barrier to entry
- solves frontend spaghetti code jungle

Also, I think it's a good idea to have a cap on how complex the frontend toolchain can be, as the more complex they become, the higher the barrier to entry gets.

A next step could be to do some probing experiments, such as making several small components to demonstrate how the frontend could move forward, see what works and then draft a plan.

**Comment by Matt-Deacalion** [comment]
For end to end testing, [Playwright](playwright.dev/) and [TestCafe](https://testcafe.io/) are worth adding as options. Playwright [may be able](https://github.com/mxschmitt/playwright-go) to write front end tests in Go.

**Comment by miku86** [comment]
Does anyone have some data?

E.g.
- How many contributors know these new tools?
- How many pages use these old tools?
- How many pages would we have to rewrite?

**Comment by wxiaoguang** [comment]
>  How many pages use these old tools?

Almost all.

>  How many pages would we have to rewrite?
 
Almost all if we want to drop them.

**Comment by lunny** [comment]
Let me have some summary. Let's have some choices and votes. 

# About end-to-end test tool
All of us agree we need end-to-end test. 
💯 cypress
🥈 selenium
🥉 Playwright
🎱 TestCafe

# About front-end refactor

🔆 Keep the current state
👍  Move all to Vuejs + TaliWind step by step. (which one Vue3/Vue2/?) And only accept new PRs which write with this tools.
🎉  Just remove `jQuery` and use `Fetch`

**Comment by wxiaoguang** [comment]
It's a little early to vote in my mind.

If we want to continue without keeping current state, the first thing we can do is: rewrite the view/diff page totally in Vue (or new frameworks).  The view/diff page is the most complex, if we can succeed on it, then we have enough confidence to go ahead.

**Comment by kdumontnu** [comment]
> It's a little early to vote in my mind.
> 
> If we want to continue without keeping current state, the first thing we can do is: rewrite the view/diff page totally in Vue (or new frameworks). The view/diff page is the most complex, if we can succeed on it, then we have enough confidence to go ahead.

Don't you think we need to implement the testing framework before any major refactoring?

I think we’re combining two issues here (jQuery + visual testing) and we should split them up.

@lunny can you hold off on the vote for visual testing framework? I’d like to create a separate Issue explaining the goals and all of the options. I can do that tomorrow.

**Comment by wxiaoguang** [comment]
> Don't you think we need to implement the testing framework before any major refactoring?

Agree to implement a testing framework (maybe not `before`, but `at the same time`).

Testing framework is an easy choice in my mind, most frameworks should work. I do not think we need to write tests for the old pages which are going to be totally rewritten, we could just write the tests for newly written pages.

So I prefer to rewrite new pages and implement testing framework at the same time.

**Comment by lunny** [comment]
We could add test framework and some tests for the Vue pages or components at first. So that a new coming PR could reuse the testing framework and make CI happy.

**Comment by silverwind** [comment]
This issue discusses like three different issues (jQuery, testing, Vue), it's getting hard to focus.

Regarding the test runner, I think we should keep `jest` and then execute playwright (or whatever other framework) within jest test cases.

I think a primary concern is speed. No one likes tests that run for minutes. They must be fast which will encourage developers to write more tests.

**Comment by tboerger** [comment]
I got good expressions from cypress from the past. It makes sense to add some frontend tests BEFORE rewriting the stuff to see any sideeffect on refactoring. The failing tests can be fixed as part of the PR for the rewrite.

**Comment by oilipheist** [comment]
I think that [qwik](https://github.com/BuilderIO/qwik) and [mitosis](https://github.com/BuilderIO/mitosis) would be worth investigating. Qwik has a tiny footprint compared with anything else I have seen and mitosis is pretty darn flexible.

**Comment by oilipheist** [comment]
Fair enough but Mitosis is designed specifically to [solve](https://mitosis.builder.io/?outputTab=vue) that particular problem. Qwik is designed to do it fast with minimal javascript overhead on the client side(1kb). Instead of getting stuck choosing the right™ framework you could write once and have flexibility to switch from Vue, React, Angular or regular old HTML at a whim later vs choosing one of those and then potentially having to rewrite things again from scratch in the future.

**Comment by silverwind** [comment]
There will be drawbacks with such additional abstractions, either size, performance or flexibility, thought. I think it's more suitable for library use cases.

**Comment by wxiaoguang** [comment]
> I don't see reason for us to switch frameworks on regular base so I don't think there is need for that... We have long ago agreed to use vue and are already partially using it

So, can we confirm that we stay with Fomantic UI/jQuery and Vue and write it into guidelines? I didn't see the necessary to switch frameworks either, but there were so many discussions before (during frontend refactoring, in the discord channel, dropping jQuery, etc), that's why the issue was created.

A real question is: since we are using Fomantic UI which needs jQuery, should the new code be written in jQuery, or in Native? I believe there is no agreement yet.

**Comment by wxiaoguang** [comment]
For the questions in the issue:

![image](https://user-images.githubusercontent.com/2114189/159491762-0a47071d-b048-4d42-b833-75629cbd3305.png)

My answer is:
* continue with Fomantic-UI and jQuery, write code in the clear way with jQuery if it needs go-tmpl & Fomantic-UI.
* use Vue if it can be written in MVVM.

Does everyone agree?
