### ISSUE TITLE
Redirect to Empty after creating Wiki Page that contains "/" 

### ISSUE THREAD

**Issue by HerrHase** [go-gitea/gitea#1839]
Hello,

after creating a Wiki Page that contains a "/", the page will be redirected to a empty Page. I have look at some url's in my Wiki and it seems that there a more characters that are not replaced for a pretty url. 

- Gitea version (or commit ref): 1.0.1
- Git version: 2.10
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [*] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

**Comment by lunny** [comment]
I think it's not supported second tree level wiki now.

**Comment by HerrHase** [comment]
The Problem is, some Title contains a "/". I work on a Project were i describe Bundles of a Symfony Project, title looks like "league/csv". The Questions is, feature or bug ;-) I think is more a Bug...

**Comment by Sharsie** [comment]
Sorry to bump this, but I have discovered this by accident as well, it is not even possible to remove such wiki pages since I can only remove them from the detail (The detail is an empty page with only content printed out)

I have tried searching through the database (postgres), but could not find the table containing the wiki page

This is on gitea version 1.2.0-rc2

Any idea on how to remove such a page without erasing the whole wiki?

**Comment by lafriks** [comment]
@Sharsie wiki pages are stored in special git repository

**Comment by jscaux** [comment]
Sorry I don't think this issue should be closed; better would be to resolve it! It would be really nice to be able to work with subfolder structrures in the wiki.

@Sharsie: I personally removed the pages I inadvertently created (before knowing about this bug) by locally pulling the repo, removing the files, committing and pushing back to origin.

**Comment by Sharsie** [comment]
@jscaux Thanks for the tip, I sort of ignored it since then :)

**Comment by mrsdizzie** [comment]
This appears fixed: https://try.gitea.io/mrsdizzie/parsing-errors/wiki/test%2Fme

Guessing it was fixed by: fd274ff
