### ISSUE TITLE
Monitoring tool codecov

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#18457]
Discussion:
 - remove code coverage monitoring at all
 - find a solution that works on gitea.com too

-> https://github.com/go-gitea/gitea/pull/18443#issuecomment-1024828040
-> https://github.com/go-gitea/gitea/pull/18443#pullrequestreview-867013939

**Comment by 6543** [comment]
cc @go-gitea/maintainers

**Comment by wxiaoguang** [comment]
I am fine with either keeping (not bad) or removing (no help, maybe no one really looks into it)

**Comment by delvh** [comment]
I am in favor of removing it entirely for the following reasons:
a) I dislike that on every single PR, such a comment will be generated.  This makes scrolling in a PR a pain, especially for small PRs simply because of the comment size. (It is wider than a screen is high)
b) I don't understand its algorithm/ information. I have seen coverage changes in PRs that were only adjusting the documentation. Why would the coverage differ in such a case? That seems counter-intuitive to me
c) I have never looked at it at all, despite being present in every PR. Partially because of the reasons mentioned above.

**Comment by zeripath** [comment]
The coverage is slightly different each time the test-suite is run due to the inherent non-determinism in the integration test cases.

The problem is that no-one (including myself) is looking at the coverage or trying to actively increase it or work on preventing coverage getting lower.

**Comment by 6543** [comment]
I personally find the report on pulls useless but tho monitor the trend important...
