### ISSUE TITLE
[Bug Report] Team Permission Status

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18572]
### Gitea Version

1.16 && 1.17.0+dev-75-g7f2530e00

### Git Version

2.33

### Operating System

Windows 10

### How are you running Gitea?

Downloaded from Gitea
Runining as service

### Database

PostgreSQL
MSSQL

### Can you reproduce the bug on the Gitea demo site?

Yes, [SeeOn](https://gitea.com/org/TeamPerm/teams/testteam)

###  Bug 
1. Team permission is alwasy readonly or adminstrator
2. Even if you give all units write access
3. Team Members aren't listed on assignes (this is the currrent behaviour #18555 feature requeste )
4. Team Members won't see Repository before added as collabrators on thier organization if the repository is private
5. Team Members have wirte permission on everything but they don't see thier names on assignes even though they can assigne others

###  Additional Infromation

1. Gitea doesn't have this problem it if it's upgraded from 1.15.10 && you have created the team in 1.15.10
2. found the bug on 1.16 and above

## Test Information
1. Create a new team in gitea 1.16 or 1.17 dev and assign it the team all write permmissions

### Screenshots

![gitea 1 7 dev team general access](https://user-images.githubusercontent.com/98172519/152317630-ef14b5eb-64ab-4eec-8f3b-29e26dd383c3.jpg)
**Even when all units are on given on write Permmssion, the Team has Readonly access** See Below Screen shoot.

![gitea team access](https://user-images.githubusercontent.com/98172519/152317666-711c1008-ee26-48e1-92d8-7ed26af3b327.jpg)
![assignee list](https://user-images.githubusercontent.com/98172519/152317687-2efb13b4-85f8-48b9-88ac-0122f3b5addf.jpg)

**Comment by AaronS8** [comment]
problem doesn't appear on team created on gitea version 1.15, then upgraded to v1.17 it works fine, but if the team is created on v.1.17 it seems the team will either readonly or administrator permission

**Comment by AaronS8** [comment]
@zacheryph could you check this out, I think this major problem on the team permmission assignment.

**Comment by AaronS8** [comment]
@zeripath  Check this link https://gitea.com/org/TeamPerm/teams/testteam username=arons8 password= admin123
check the team permission.

**Comment by techknowlogick** [comment]
@AaronS8 please don't share credentials for gitea.com, if you'd like to share a replication please use try.Gitea.io. I've deleted your comment, but please change the credentials too

**Comment by AaronS8** [comment]
@techknowlogick you don't have to worry about my credential, and I can't creat an organization on try.Gitea.io, I'll change it later,
I wanted to show you the bug, the only way was by using the officail gitea website.

**Comment by zeripath** [comment]
Ugh. There is a real and serious issue here. 

The UI on the sidebar would not be difficult to update - (translations mean that we would need to be cautious in the way we fix this to ensure that backports work.)

The real problem is the access checking underneath for assignees (and likely elsewhere too). This relies on checking the access table which has a coarse permission check only.

I suspect this wasn't considered when the fine grained team permissions pr was added.

Ideally the access table would have been changed to include units in some way - which we can't do now on 1.16.

This means that access checking code will need to be significantly refactored to do the correct tests in order to generate the correct assignees list. 

But everything that relies on the access table is suspect for not doing the right test now.

**Comment by zacheryph** [comment]
I wonder if @zeripath has notifications setup for when i'm mentioned 🤣

**Comment by AaronS8** [comment]
Could it be a simpler problem, I think units assignment works for teams made in pervious version 1.15, could it be just coding problem?

**Comment by zeripath** [comment]
It is not simple. The following are now wrong:

https://github.com/go-gitea/gitea/blob/df4401732825b9b378e51663d74edb795446f2d3/models/access.go#L134-L179 

https://github.com/go-gitea/gitea/blob/df4401732825b9b378e51663d74edb795446f2d3/models/repo.go#L147-L178

Anything that uses the access table as a proxy for write permissions is incorrect - we need to search the entire codebase for other examples.

---

The correct solution is add finergrained permissions checking in to the access table - the access table should have always been a quadruplet:

```
(Repo, User, Unit, Mode)
```

Whether that is in Codd normal form as in a row per repo, user, unit, mode or it is in some more compressed form:

```
(Repo,User,Mode,Unit1, ..., UnitN)
```

or even:

```
(Repo, User, Mode, Units)
```

The problem is that we cannot backport such a change to 1.16. So fixing this is going to be complex.
