### ISSUE TITLE
Unlock conversation's buttons are incorrect

### ISSUE THREAD

**Issue by Gusted** [go-gitea/gitea#19015]
### Gitea Version

https://github.com/go-gitea/gitea/commit/cc643284de106a609b4ac03ed2a7f615ab6d312a

### Operating System

Arch Linux

### Browser Version

99.0a1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The cancel & Confirm button should be under the warning message. Not sure if this is a regression or what's causing it, the lock modal is doing this correctly(even when removing the 2 other elements that the lock modal adds)

### Screenshots

![image](https://user-images.githubusercontent.com/25481501/156944220-29b7e4b8-9387-4cef-aaf7-81c07666fb42.png)
![image](https://user-images.githubusercontent.com/25481501/156944287-828b9e92-b3f1-4ce3-a89d-2aa3a3719078.png)

**Comment by zeripath** [comment]
This is a width dependent problem.

The class "left" here:

https://github.com/go-gitea/gitea/blob/78b38a5ccc1181f7224700f07148c171ce88c938/templates/repo/issue/view_content/sidebar.tmpl#L593

causes this because of `float: left` in:

https://github.com/go-gitea/gitea/blob/9c5696e428347b873d522f9299f1cb8c55b33ea9/web_src/less/_base.less#L804-L811

Both of these classes are suspect IMO. Semantic/fomantic had it's own way for making thing be floated to the left, `left floated`.

I argue we need to get rid of this weird hack.

**Comment by silverwind** [comment]
Yes, we should not override fomantic classes like that. Hacks like this need to go.

**Comment by wxiaoguang** [comment]
@zeripath @silverwind I must point out that, these hacky code are written by hand.

https://github.com/go-gitea/gitea/commit/4447a20f872776123c42d5b8ca987c114fb4b80b

https://github.com/go-gitea/gitea/commit/4447a20f872776123c42d5b8ca987c114fb4b80b#diff-abca4ad6deec2cd6c98ed72628b067bd5112d065354246e8c947a1cb7d6befcfR58-R64

It's not Fomantic UI's fault. 

I always disagree that thinking Fomantic UI does wrong. Even if in some cases Fomantic UI is not that good, but we must admit that most problems are caused by ourselves.

If we want to improve the Gitea UI fundamentally, we should admit that many mistakes are introduced by developers and we must refactor and fix them one by one.

Switching to a new framework won't improve anything, if we do not have good coding style and reviewing standards, new framework will be filled by mistakes soon.

**Comment by wxiaoguang** [comment]
And removing the `.ui .float` and `.ui .right` could be easy:

1. introduce our style: `us-float-left` and `us-float-right`
2. replace all `"ui([^"]*)\b(left|right)\b([^"]*)"` to `"ui$1us-float-$2$3"`
3. remove `.ui .float` and `.ui .right`
4. test

**Comment by silverwind** [comment]
Looks alright currently:

<img width="575" alt="Screenshot 2023-05-01 at 22 00 35" src="https://user-images.githubusercontent.com/115237/235521053-606908f4-cd0e-4970-92f8-231d59917422.png">
