### ISSUE TITLE
Flatpak package for linux

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#19214]
### Feature Description

we recently moved our infrastructure from windows to linux. a flatpak support for gitea will be wonderful to make it much easier to install (even though now its straight forward) and also the ability to update it directly from the terminal instead of copying the executable every time.

**Comment by noerw** [comment]
As of now, the only first-party packages are [snap](https://snapcraft.io/gitea) and [homebrew](https://gitea.com/gitea/homebrew-gitea/), while relying on third parties for providing other packages (due to maintenance overhead).

This may possibly change, please follow or contribute to the discussion in #17841.
