### ISSUE TITLE
Turn on PAM by default

### ISSUE THREAD

**Issue by OdinVex** [go-gitea/gitea#19249]
### Feature Description

It'd be nice if Gitea could enable PAM out of the box. Gogs has it. \*shrug\*

**Comment by lunny** [comment]
PAM is an standalone module external Linux kernel. Maybe not all Linux distribution supports that?

**Comment by OdinVex** [comment]
> PAM is an standalone module external Linux kernel. Maybe not all Linux distribution supports that?

Dynamically load?

**Comment by lafriks** [comment]
imho it would be good to have it as option on install page to enable it but I don't think it's good idea to enable it on already existing installations, it could have undesired side effects

**Comment by OdinVex** [comment]
> imho it would be good to have it as option on install page to enable it but I don't think it's good idea to enable it on already existing installations, it could have undesired side effects
It would have the same effect as adding a new authentication source. Should be perfectly fine. When we say “enabled by default”, we mean “possible to be used”. Current builds don't even have it as a possibility, it's only enabled if compiled for it.

**Comment by OdinVex** [comment]
I was hoping we could use dynamic, yes.

**Comment by zeripath** [comment]
This would necessitate providing multiple builds per libc - eg. glibc versions and muslc versions.

**Comment by zeripath** [comment]
The release-latest task currently takes 20 minutes on our CI. 

You are suggesting that we likely triple the number of builds for linux. We provide 5 types of linux build at present. So around 15 linux builds each with a different build env - possibly more because I bet the arm libc interfaces are less stable. At a conservative estimate that would cause our release-latest task to double in length to 40 minutes. (Every time we release get moans about how github informs people that there is a release but they don't have the packages to download. EVERY TIME - I'm talking about hours worth of maintainer time spent dealing with complaints from a 20 minute delay. Literally hours every release.)

Each release currently creates approximately 1.8Gb of data. Tripling the number of linux builds would make that close to 4Gb.

I'm not sure this is feasible.

If you really want to propose this you need to do the work to determine which build environments we would need to build gitea in to determine compatibility with ubuntu (LTS and the latest versions), Debian (simy),  Fedora (simy), Arch (simy), Gentoo (I don't know what versions), Raspbian and the variants, Alpine and the docker variants, Synology, Centos... and so on...

If it would be the case that there is ONE supradistribution that could fix all of this or there is a way of building a semi-static build that could avoid all of the duplication then maybe we could do it.

**Comment by OdinVex** [comment]
No, that wasn't what I was suggesting, that's just a result of what I was suggesting (which I wasn't aware of, might I also add). I'll just use Gogs, works out of the box with PAM for my NAS.

**Comment by wxiaoguang** [comment]
I have a question, since the SQLite3 is enabled for all builds, how does this C library overcome the glibc and muslc differences? It has the libraries in `sqlite3_other.go`:

```
#cgo linux LDFLAGS: -ldl
#cgo linux,ppc LDFLAGS: -lpthread
#cgo linux,ppc64 LDFLAGS: -lpthread
#cgo linux,ppc64le LDFLAGS: -lpthread
```

If there could be linked to the libpam.so, maybe the pam functions can be called by `dlopen` + `dlsym`

**Comment by annanyearian** [comment]
Is there somewhere which explains in detail how to compile with PAM support?

Unfortunately the system I need to run gitea on doesn't have enough memory to run the build process. I was running into [this issue](https://github.com/go-gitea/gitea/issues/14288) during compilation. Above comments make me think building on a different machine may run into issues if the environments differ. Is there a way of checking compatibility between systems?

> This would necessitate providing multiple builds per libc - eg. glibc versions and muslc versions.

**Comment by wxiaoguang** [comment]
You can use `xgo` to do cross-compile. See the Makefile target `release-linux`.

You can use `MY_TAG=xxx make relase-linux` to build your own binary at the moment.

**Comment by lunny** [comment]
per https://github.com/go-gitea/gitea/issues/24658#issuecomment-1658334538, I think we can close this one.
