### ISSUE TITLE
Use the modern interface by default

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#19306]
### Feature Description

Consider dropping the current styling and adopting the more modern one by [Freeplay](https://codeberg.org/Freeplay/Gitea-Modern)

I think it gives Gitea a more distinctive look, and the first time I think that is an improvement compare to the Github like style. 

Works wonders with some dark

### Screenshots

![Screenshot_115](https://user-images.githubusercontent.com/6344099/161351644-dce560b6-565b-4fba-be83-8c0dd82f5b2d.png)

**Comment by delvh** [comment]
Might be a personal preference, but I don't think that's a good design to use as default.

Unlike now, I have to look really hard to find where things might be placed.
Of course, this might be somewhat due to being accustomed to the current design.

However, this approach painfully reminds me of the pathetic attempt of GitLab to implement a user-friendly UI.
I always need ages to find anything there.

So for me, if you want to use it, then go for it, but I'm against setting this as the default.
I don't know what other maintainers think about that, however.

**Comment by Freeplayg** [comment]
The style is built on top of the default styling, so it's best to recreate it. (My code is an absolute mess, anyways lol)

I would however very much like a layout like this:
![2022-04-01_19-04](https://user-images.githubusercontent.com/40742947/161352746-845f98ab-b29d-43cd-9f6c-fd57d86fa29c.png)

It makes the best use of screen space, and with that right sidebar you add more like contributors and extra links (basically like what Github did).

I do want to contribute to Gitea itself, but I'm still not really comfortable with Git, and it doesn't seem like you can run it on Fedora

**Comment by delvh** [comment]
> It makes the best use of screen space

Yes.
That is pretty much my problem.
Sensory overload.
How am I supposed to find something, if everything is crammed into as little space as possible?
This means I that I have to scan the entire screen in detail to find what I'm looking for, unlike a UI with more space where I have to skim through less on a page.

**Comment by ShalokShalom** [comment]
> Unlike now, I have to look really hard to find where things might be placed.

I guess because you are used to the current design, and see this one first, and have never really used it yourself in production?

Humans are creatures of habit. :)



> I'm still not really comfortable with Git, and it doesn't seem like you can run it on Fedora

You mean running Git on Fedora makes you an issue? IDK, you just install git and run git clone URL in the directory you want the git repo, that is all. 

I think your design is splendid, particularly for the reason you both mention: 
Big, clear icons. And not tons of fine text, with mostly unnecessary info.

It alone inspires me, to use Gitea again on its own. 🥳

**Comment by Freeplayg** [comment]
Oops, I meant run Gitea on Fedora
Git I can run fine, I just need to learn more of the commands and stuff. I've created a mess with Git when trying to contribute to stuff before, so-

**Comment by ShalokShalom** [comment]
I guess since Gitea is written in Go, it can be distributed as a single file, that executes and that's it. 

I personally run it on TrueNAS, but I guess this is no option for you. 
You might open another issue, to get help. 

Thanks a lot

**Comment by silverwind** [comment]
I too prefer GitHub-like layout, not GitLab-like, but that's probably because I almost never use GitLab.

**Comment by lunny** [comment]
> I too prefer GitHub-like layout, not GitLab-like, but that's probably because I almost never use GitLab.

I have ever used, but never liked.

**Comment by mscherer** [comment]
While my design knowledge is quite out of date, there is studies on how visitors read websites, using F-patterns and Z-patterns ( the 2006 Nielsen Norman group studies seems to still be seen as relevant today). This layout do not seems to correspond to any of them (at a first glance).

So I think any changes should be made taking studies in account (even if "reusing existing design" is usually a safe bet, because that's not surprising). In a ideal world, someone should make a user study, but that's quite rare on free software (for a lot of reasons). If not, at least connecting the change to others studies, and/or user scenario/persona would help to convince people (but again, that's also quite rare on free software, for the same reasons as user studies).

**Comment by ShalokShalom** [comment]
I think that wouldn't account to this case, since a webpage/homepage study gets most likely done to accommodate for people using the website for the first time, and not every day, multiple times. I think it makes a radical difference, if I like to glance over a webpage fast, or get used to something as a tool for every days usage.

**Comment by OdinVex** [comment]
If this is added, please allow for a traditional layout versus this modern one... Supportive of both, but I just can't get used to side-menus. Adaptive CSS and fall-back selectors would make it easily maintainable.

**Comment by techknowlogick** [comment]
closing as dupe as there are already several issues open in regards to a frontend refresh

**Comment by ShalokShalom** [comment]
This is unique. Other issues ask for other themes, and other kinds of themes.
