### ISSUE TITLE
migrate from gogs 0.12.6 failed !

### ISSUE THREAD

**Issue by toplinuxsir** [go-gitea/gitea#19333]
### Description

Migrate from gogs 0.12.6 failed

```
Run task failed: Migration failed: Clone: exit status 128 - fatal: unable to access 'http://7d6abbe358e8e3ed0fc366870f5ac063bb51dd1e:
@10.192.2.2:3000/mypos/myprj.git/': Empty reply from server
```

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.20.1

### Operating System

raspberry pi4 debian bulleye

### How are you running Gitea?

gitea web

### Database

SQLite

**Comment by zeripath** [comment]
Double check your username/password combination for your gogs server and ensure that it is running.

**Comment by toplinuxsir** [comment]
@zeripath Yes, username /password all is ok , I use access token.

**Comment by zeripath** [comment]
Well the error is saying that Gitea is getting an empty response from the Gogs server.


Is the Gogs server accessible from Gitea?

Is the URL mentioned above correct?

If not what should it be?

**Comment by toplinuxsir** [comment]
@zeripath 
Yes, empty response from the Gogs server

confirmed : 
1. Gogs server can accessibhle from Gitea
2. URL is correct

**Comment by zeripath** [comment]
I mean are you certain that this:


http://7d6abbe358e8e3ed0fc366870f5ac063bb51dd1e:
@10.192.2.2:3000/mypos/myprj.git/

Is the correct URL for cloning from Gogs?

If it is not what should it be?

If you try it manually from the command line on the Gitea server using `git clone http://7d6abbe358e8e3ed0fc366870f5ac063bb51dd1e:
@10.192.2.2:3000/mypos/myprj.git/` does that work? How does it need to be adjusted to make it work? 

Do you need to set a username and use the token as a password? Or even just set the token as the password instead of the username?

**Comment by toplinuxsir** [comment]
put the token as password for the user (the token related to),can not login!

**Comment by toplinuxsir** [comment]
The problem still exsits! for version 1.16..6

**Comment by 6543** [comment]
@toplinuxsir if you use token, put token in as user and leave password empty
