### ISSUE TITLE
Monaco Editor keybindings

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1936]
## Description

**Feature Request**: Allow the user to choose a keybinding for the web editor, from a dropdown menu. Suggest more keybindings as you find them (Sublime Text, Atom, Light Table, Leo, Brackets, etc.).

- [vim](https://github.com/brijeshb42/monaco-vim)
- [emacs](https://github.com/brijeshb42/monaco-emacs)

[Playground](https://editor.bitwiser.in)

**Comment by ghost** [comment]
Shush.

**Comment by lafriks** [comment]
I think this issue has to be renamed as we no longer use CodeMirror but Monaco Editor

**Comment by megadr01d** [comment]
Then maybe deleted altogether, since the description also has a link to CodeMirror's keymap files.
I couldn't find keymap files for Monaco Editor so, this means that if they still have to be made from scratch by some generous soul, this issue is going nowhere fast.

Let me know if I'm wrong before I close it.

**Comment by lafriks** [comment]
There are vim binding https://github.com/brijeshb42/monaco-vim
