### ISSUE TITLE
Issue count discrepancy

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1937]
- Gitea version (or commit ref): 1.1.1
- Git version: Not sure (3rd party service - Teknik.io)
- Operating system: Windows Server 2016 Datacenter
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No but I can at [Teknik.io](https://git.teknik.io/Teknikode/Teknik/issues)
  - [ ] Not relevant
- Log gist: N/A

## Description

Issue tab count reads 27 while open issues reads 26 (real count).

## Screenshots

![screencap-1497186978076](https://user-images.githubusercontent.com/9649385/27011306-aec38228-4eb0-11e7-8bbc-5f5d2eec4a5c.png)

**Comment by ethantkoenig** [comment]
This seems to be a integrity issue in your database; the count in the Issue tabs (27) is generated from ~the `num_open_issues` column of~ the `repository` table, but the count in the green "Open" box (26) is generated from the `issues` table.

To fix this particular case, an admin could run a SQL query so that ~the `repository.num_open_issues` column~ `repository` table accurately reflects the number of issues in the `issues` table.

The underlying problem seems to be that the two tables became out-of-sync in the first place; it will take more investigation to figure out why that happened.

**Comment by ghost** [comment]
Thanks for the follow-up. I created an issue [there](https://git.teknik.io/Teknikode/Teknik/issues/59) directing here, to see if uncled1023, Teknik's admin, can be of more assistance.

**Comment by uncled1023** [comment]
Alright, i'll run an update on the num_open_issues to get back into sync with the actual number.

**Comment by uncled1023** [comment]
I don't see a 'num_open_issues' column.  I'm running gitea 1.1.1.  There is a 'num_issues' and 'num_closed_issues'.

**Comment by ethantkoenig** [comment]
@uncled1023 You're right, I was confused. The open issue count in the tab (27) is computed as `num_issues - num_closed_issues`, so just make sure the `num_issues` and `num_closed_issues` columns are accurate, and the counts should be correct.

**Comment by ghost** [comment]
Actually, Teknik used to host Gogs and it exhibited the same bug so, if it is a Gitea bug, it probably got carried over from Gogs.

**Comment by uncled1023** [comment]
Fixed with the following query:

```
update gogs.repository r set r.num_issues = (select count(*) from gogs.issue i where i.repo_id = r.id);

update gogs.repository r set r.num_closed_issues = (select count(*) from gogs.issue i where i.repo_id = r.id and i.is_closed = 1);
```

**Comment by bkcsoft** [comment]
Closed as fixed, but opened #1969 to follow up on this

**Comment by bkcsoft** [comment]
@uncled1023 FYI, that might introduce duplicate issue numbers, since that is what `num_issues` is used for :)

**Comment by uncled1023** [comment]
Oh ok, haha.  I will have to keep an eye out.
