### ISSUE TITLE
DefaultBranch is not set correctly when using template which has 'master' as default

### ISSUE THREAD

**Issue by sschroe** [go-gitea/gitea#19470]
### Description

In #19354 the default branch for new repositories was changed from 'master' to 'main'. When running this new version on existing data where 'master' was still used as default this causes a problem when creating a new repository from a template which still uses 'master'.

The files and master branch are correctly copied to the newly generated repository however giteas internal default branch is set to 'main' instead of 'master'. This causes giteas "Branches" page to remain blank despite showing 1 branch and when cloning the repository git shows `warning: remote HEAD refers to nonexistent ref, unable to checkout.`.

When opening the "Branches" page gitea throws an error: `2022/04/23 10:48:22 ...s/web/repo/branch.go:177:loadBranches() [W] [6263bd56] loadBranches: missing default branch main for 60:sschroe/template_test`

Example of a broken repo on the demo site: https://try.gitea.io/steffen/template_test/branches

To reproduce:
- Run gitea with the default config
- Create a new template repository and set its main branch to 'master'
- Create a new repository and select the previously made template with "Git Content(Default Branch)" checked
- Open the "Branches" page on the new repository

### Gitea Version

9550e5a23e9f8581cc13f54b336307ee02d430cc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.36.0

### Operating System

Arch Linux

### How are you running Gitea?

git clone': git clone --recursive https://github.com/go-gitea/gitea.git
cd gitea
TAGS="bindata sqlite sqlite_unlock_notify" make build
./gitea

### Database

SQLite

**Comment by wxiaoguang** [comment]
You should update your template. Otherwise Gitea can not guess what's the correct main branch.

For example, even before https://github.com/go-gitea/gitea/pull/19354 , if you create a template repo with `main` as default branch, then the same thing happens.

One possible way to improve the behavior is to make Gitea use the only (or latest) branch in template as the default branch for the newly created repo if the default branch name doesn't match.
