### ISSUE TITLE
Gitea for Android?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#19538]
### Feature Description

Just a spontaneous idea: Run GItea on Android. In best case on a normal "unrooted" device. 
Have the repo in your pocket. Always on device (battery), low electricity costs, wireless, no annoying LED flashing (LAN), etc.
But the server should be hot pluggable. Means WiFi off/on (airplane mode) should have no issues.
What do you think? Is that possible?

**Comment by techknowlogick** [comment]
This is currently possible as Gitea is packaged for termux

**Comment by twoco** [comment]
Great, it works. Thanks. 

In case anyone is interested: 

1. Download the [Termux](https://f-droid.org/en/packages/com.termux/) app from F-Droid ([PlayStore](https://play.google.com/store/apps/details?id=com.termux) does not work due to OpenSSL issues. Or download APK from [GitHub](https://github.com/termux/termux-app/releases)) 
2. Run Termux and Install Gitea by command `pkg install gitea` and run with command `gitea`.
