### ISSUE TITLE
Gitea incremental backup

### ISSUE THREAD

**Issue by supermangithu** [go-gitea/gitea#19593]
### Feature Description

Can developers add incremental and differential backup modes in Gitea? For Docker,PostgreSQL,MySQL, it is unclear for me  what database software  backup method they own. Gitea’s default backup method is full volume mode. Each migration import hopes to import different parts into another machine. I am not an professional postgradute majoring in computer science.An engineering Postgraduate. I use Gitea for version management. If there is anything wrong, please correct and say nicely.

Git Version
2.35.1

Operating System
Linux &Windows

How are you running Gitea?
The original gitea is 1.16.5 with SQLite
The migration is taking part on a built from source on Linux Ubuntu 16 toWIndows and Another Ubuntu 21.10.

Database
SQLite

**Comment by kaolagithub** [comment]
Git Version
 2.35.1

Operating System
Linux &Windows

How are you running Gitea?
The original gitea is 1.16.5 with SQLite
The migration is taking part on a built from source on Linux Ubuntu 16 toWIndows and Another Ubuntu 21.10.

Database
SQLite

**Comment by wxiaoguang** [comment]
Not feasible at the moment. Gitea can not do everything for you, and the backup methods for different systems vary a lot. The same question to MySQL, do you see MySQL provides the automatic incremental backup and restore? If MySQL doesn't, then Gitea can't.

I would suggest you to use ZFS with snapshot, it's a more general method to do backup & restore, with incremental support.

**Comment by kaolagithub** [comment]
Hi,friend,I am not familar sql(so embarass),I kindly hope Gitea can add this basic feature,it can be(i guess)  a core feature for Gitea provide Backup and Restore related basic feature .i think（ just i think） it provide this feature  to give some convenience to transfer sql database from one place to another real/virtual machines.

 In order to control the size of installation package and the goal of lightweight, functions that are not necessary and  core will not be added. If it's local server/pc incremental / differential backup and recovery, I won't ask this function suggestion. Since Gitea officially has a full backup export database to migrate / transfer data, why not add incremental / differential database export? 
     
    

 On the current machine, due to the lack of good estimation and overall planning for the amount of data at the beginning, the response of SQLite database will be very slow when the amount of data reaches a certain level. The memory size given by the laboratory machine and the hard disk are not the bottleneck. 
      We know that MySQL and PostgreSQL will perform well after configuring the database well, so we want to migrate the data to the PostgreSQL database. At first, it was not configured as PostgreSQL, which was something we didn't consider well. 
Now the database is exported through full backup. It was a worrying experience. If the incremental / differential export database is provided, there is no need to export a large database during migration, and the risk is less.
So I still kindly hope gitea can add an incremental / differential backup function. Just suggestions.
         By the way, the ZFS snapshot you mentioned, which I searched on the Internet, is a functional content of incremental backup. It should be very useful when I know it for the first time.
I'm appreciated that you can reply to me.

**Comment by kaolagithub** [comment]
> Not feasible at the moment. Gitea can not do everything for you, and the backup methods for different systems vary a lot. The same question to MySQL, do you see MySQL provides the automatic incremental backup and restore? If MySQL doesn't, then Gitea can't.
> 
> I would suggest you to use ZFS with snapshot, it's a more general method to do backup & restore, with incremental support.

Hi,friend,I am not familar sql(so embarass),I kindly hope Gitea can add this basic feature,it can be(i guess) a core feature for Gitea provide Backup and Restore related basic feature .i think（ just i think） it provide this feature to give some convenience to transfer sql database from one place to another real/virtual machines.

In order to control the size of installation package and the goal of lightweight, functions that are not necessary and core will not be added. If it's local server/pc incremental / differential backup and recovery, I won't ask this function suggestion. Since Gitea officially has a full backup export database to migrate / transfer data, why not add incremental / differential database export?

On the current machine, due to the lack of good estimation and overall planning for the amount of data at the beginning, the response of SQLite database will be very slow when the amount of data reaches a certain level. The memory size given by the laboratory machine and the hard disk are not the bottleneck.
We know that MySQL and PostgreSQL will perform well after configuring the database well, so we want to migrate the data to the PostgreSQL database. At first, it was not configured as PostgreSQL, which was something we didn't consider well.
Now the database is exported through full backup. It was a worrying experience. If the incremental / differential export database is provided, there is no need to export a large database during migration, and the risk is less.
So I still kindly hope gitea can add an incremental / differential backup function. Just suggestions.
By the way, the ZFS snapshot you mentioned, which I searched on the Internet, is a functional content of incremental backup. It should be very useful when I know it for the first time.
I'm appreciated that you can reply to me.
