### ISSUE TITLE
API: file listing / tree access

### ISSUE THREAD

**Issue by mmarchetti** [go-gitea/gitea#1978]
The current Repo Contents API supports raw file retrieval, but there doesn't seem to be a way to list the files in the repo. (Both GitHub and GitLab support this via the Tree API or a file access endpoint that also supports directory listing).

The motivation for this is that I would like to access a small subset of files in gitea repos, without cloning the repo or scraping the web interface.

Related to #64.

**Comment by necaris** [comment]
See #2749, which is an in-progress response to this, using the [GitHub Tree API](https://developer.github.com/v3/git/trees/) as a model. It follows the structure of code in the UI views (e.g. [the directory view](https://github.com/go-gitea/gitea/blob/master/routers/repo/view.go#L38)), and as I understand it the remaining pieces are:
 - [ ] validate REST API design
   - [ ] do we expose the Git file entry mode (e.g. `0644`, `0755`)
   - [ ] do we expose the Git file size (currently an expensive operation -- perhaps worth adding in a follow-up, or gated behind a query parameter)
 - [ ] add SDK model types for the resulting file entry and tree listing APIs
 - [ ] add model and integration tests for this 
   - [ ] add more content to test fixtures to enable more meaningful (e.g. recursive) tests

Would love feedback from maintainers on whether this will be accepted before we put much more work into it! /cc @lunny since they seem to be a maintainer

**Comment by lunny** [comment]
@necaris The PR is welcome to be compatible with Github Tree API. And also, we need some unit tests or integration tests on the PR.

**Comment by rhaamo** [comment]
any update of progress on this issue and associated PR ?

**Comment by lunny** [comment]
@rhaamo nobody are working on this.

**Comment by necaris** [comment]
I intend to pick it back up but have limited time.

**Comment by lunny** [comment]
@HoffmannP see #5403
