### ISSUE TITLE
Create a branch from issue

### ISSUE THREAD

**Issue by fairking** [go-gitea/gitea#19827]
### Description

Hi everyone,

I cannot find a way to create a new branch from the issue?
Is there any ability to do that?

Normally when issue requires code changes there should be possible to create a new working branch with the same name and id and attach to the issue based on the normal development workflow.

### Screenshots

![image](https://user-images.githubusercontent.com/13495631/170833947-bc721c4e-893c-40b5-9297-a562802ef492.png)

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### Browser Version

Brave

**Comment by dr3st** [comment]
Hi Fairking,

I think this is not supported atm, the official feature-list:
https://docs.gitea.io/en-us/comparison/#issue-tracker

"Create new branches from issues" got an X.

**Comment by fairking** [comment]
> Hi Fairking,
> 
> I think this is not supported atm, the official feature-list: https://docs.gitea.io/en-us/comparison/#issue-tracker
> 
> "Create new branches from issues" got an X.

Ups :-( You are right. So it's not a bug then.

**Comment by ygoe** [comment]
Hm, I was about to create an issue for this here. But as a feature request. And also because the feature comparison in the documentation is not correct, GitHub also has this feature. I'm using it a lot in GitLab but am looking for an easier to maintain alternative, and Gitea looks pretty good. Could we reopen this and redeclare as feature request or should I open a new issue or are feature requests handled elsewhere?

**Comment by zeripath** [comment]
Please open a feature request  - feel free to reference this Issue but comments on closed issues are likely to be missed.
