### ISSUE TITLE
Rootless docker image has problem with DNS (/etc/resolv.conf)

### ISSUE THREAD

**Issue by astromatt** [go-gitea/gitea#20090]
### Feature Description

I had to add: `docker exec -itu root gitea ash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'` to startup script to make it work and migrate repositories from github. Rootfull version works without this problm.

**Comment by bendem** [comment]
Did you maybe forget to add some [dns option](https://docs.docker.com/config/containers/container-networking/#dns-services) to your docker command/compose? You should probably not be using public DNS inside a container (let docker forward to your host's configured dns, otherwise you won't be able to reach other containers in linked networks).

How did you run your containers (commands or compose for rootless and rootfull), which docker version are you running?
