### ISSUE TITLE
.yml (YAML) Issue Templates

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#20232]
### Feature Description

I think it would be great if Gitea had issue template customization using YAML.

This would mimic the Github YAML Issue Templates, but also give the user more control over the template customization that Markdown can't.

**Comment by jolheiser** [comment]
Do you mean the new issue template forms GH has?

**Comment by C-EO** [comment]
@jolheiser Yes, I mean the new issue template forms.
I think it would be a great addition to Gitea 1.18 or so

**Comment by Wazzaps** [comment]
I might work on this on the weekend, I would like to discuss some implementation details:

1. Should I just implement the [GitHub syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) ? (Sounds like the best plan)
2. Also support github's path for these templates (`.github/ISSUE_TEMPLATE`)? This mirrors the behavior of Markdown templates.
3. Should we provide an API/webhook for extracting the fields as JSON for CI/CD purposes? In my org we used (an internal) Jira Service Desk to trigger a build using customer-specified parameters.
    3.a. Could it be queried after the issue has been created? What if it's edited? Do we parse the markdown?

**Comment by JamieJ98** [comment]
What I would love is the ability to generate an actual form like github provides:
![image](https://user-images.githubusercontent.com/16063649/183872605-ef729ffa-c563-45c4-930d-ff59a9fa0536.png)

**Comment by Wazzaps** [comment]
This is exactly what I want to work on :)

**Comment by eeyrjmr** [comment]
> 1. Should I just implement the [GitHub syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) ? (Sounds like the best plan)
> 2. Also support github's path for these templates (`.github/ISSUE_TEMPLATE`)? This mirrors the behavior of Markdown templates.



At the very least  matching syntax and locations provides means to migrate. Whether it is expanded upon ....

**Comment by Wazzaps** [comment]
An initial screenshot, going to need a designer for this later :)
(don't mind the xss labels, just making sure)

![2022-08-12 18 54 02 localhost cb2d5a903bfc](https://user-images.githubusercontent.com/6624767/184397129-b5924305-cbc0-453d-bdf0-173d8d3ac890.png)

I'll work on the API endpoint and then submit a draft PR

**Comment by lunny** [comment]
> An initial screenshot, going to need a designer for this later :) (don't mind the xss labels, just making sure)
> 
> ![2022-08-12 18 54 02 localhost cb2d5a903bfc](https://user-images.githubusercontent.com/6624767/184397129-b5924305-cbc0-453d-bdf0-173d8d3ac890.png)
> 
> I'll work on the API endpoint and then submit a draft PR

Hm, I also plan to implement it but for pull request. I'm glad to review the PR and provide any service for that. I would like to extend GH's syntax to support more validations.

**Comment by delvh** [comment]
By the way, this issue is a duplicate of #16353.
Considering that you're already developing for this issue, I guess I can close the other issue after pasting the relevant content here as well:

---

## Description
As shown in #16349, GitHub now supports issue forms for a unified issue creation behavior.
It would be great and pretty user friendly, if Gitea would support the same.
Syntactically, it would be good, if a GitHub-similar syntax would be chosen (see [the example currently integrated into Gitea itself](https://github.com/go-gitea/gitea/blob/main/.github/ISSUE_TEMPLATE/) or [the GitHub syntax documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)), with the same structure as GitHub as well.

## Included features
- Issue Builder with basically all components that GitHub supports as well
- `config.yml` in the template folder to change the configuration of the issue and PR templates
- Automated Issue template updating when the template folder has been updated

## Potential to be better than GitHub (Later on)
- Localized text (i.e. so that comments can be displayed in the native language with English as fallback - i.e. by having a `locale_<Locale>.ini` in the template folder)
- Ability to refer to a mail account in the `clickable_links:` section of the `config.yml`
- Do not show optional columns where no text has been entered

## Predicted Problems
- Feature will be pretty big (I estimate `~2000-4000` lines of code)
- How to handle issue/ PR creation over API (especially when `
blank_issues_enabled: false` is part of the `config.yml`)

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/124616072-154ff180-de76-11eb-8aaa-7fa5a2d231bf.png)
Current issue creation form displayed on GitHub when creating a new bug report for Gitea

![image](https://user-images.githubusercontent.com/51889757/124616315-43cdcc80-de76-11eb-9ecb-a0068fb91ded.png)
Current representation for an issue created using issue forms

**Comment by lunny** [comment]
> By the way, this issue is a duplicate of #16353. Considering that you're already developing for this issue, I guess I can close the other issue after pasting the relevant content here as well:
> 
> ## Description
> As shown in #16349, GitHub now supports issue forms for a unified issue creation behavior. It would be great and pretty user friendly, if Gitea would support the same. Syntactically, it would be good, if a GitHub-similar syntax would be chosen (see [the example currently integrated into Gitea itself](https://github.com/go-gitea/gitea/blob/main/.github/ISSUE_TEMPLATE/) or [the GitHub syntax documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)), with the same structure as GitHub as well.
> 
> ## Included features
> * Issue Builder with basically all components that GitHub supports as well
> * `config.yml` in the template folder to change the configuration of the issue and PR templates
> * Automated Issue template updating when the template folder has been updated
> 
> ## Potential to be better than GitHub (Later on)
> * Localized text (i.e. so that comments can be displayed in the native language with English as fallback - i.e. by having a `locale_<Locale>.ini` in the template folder)
> * Ability to refer to a mail account in the `clickable_links:` section of the `config.yml`
> * Do not show optional columns where no text has been entered
> 
> ## Predicted Problems
> * Feature will be pretty big (I estimate `~2000-4000` lines of code)
> * How to handle issue/ PR creation over API (especially when ` blank_issues_enabled: false` is part of the `config.yml`)
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/51889757/124616072-154ff180-de76-11eb-8aaa-7fa5a2d231bf.png) Current issue creation form displayed on GitHub when creating a new bug report for Gitea
> 
> ![image](https://user-images.githubusercontent.com/51889757/124616315-43cdcc80-de76-11eb-9ecb-a0068fb91ded.png) Current representation for an issue created using issue forms

Sorry @delvh I think your issue is very helpful.

**Comment by Wazzaps** [comment]
It is indeed, I did not think of most of the problems @delvh presented

**Comment by delvh** [comment]
I think it is, and the unimplemented aspects should probably be extracted into another (summary?) issue.
