### ISSUE TITLE
SSH key cannot be verified due to 2047 length

### ISSUE THREAD

**Issue by BeeFox-sys** [go-gitea/gitea#20249]
### Description

When generating an rsa ssh key, there is a chance the final bit is a zero, resulting in a 2047 bit length key, by default git tea does not allow for these keys. this should be changed to allow people to use them.

### Gitea Version

1.17.0+dev-759-g761db4d53 

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/user/settings/keys

**Comment by zeripath** [comment]
Does this happen for other key types too?

If not, we should change this:

https://github.com/go-gitea/gitea/blob/ed13d7aadf75246a3b9ba68c5cd2def867f89f43/modules/setting/setting.go#L173

to: 

```go
		MinimumKeySizes:               map[string]int{"ed25519": 256, "ed25519-sk": 256, "ecdsa": 256, "ecdsa-sk": 256, "rsa": 2047},
```

and add a comment as to why this is 2047 rather than 2048.

If so, we should change this:

https://github.com/go-gitea/gitea/blob/ed13d7aadf75246a3b9ba68c5cd2def867f89f43/models/asymkey/ssh_key_parse.go#L198

to:

```go
	if minLen, found := setting.SSH.MinimumKeySizes[keyType]; found && length + 1 >= minLen {
```

and add a comment explaining that we allow one byte shorter due to accepting an initial/terminal 0.

---

If you're able to find out which of the above is the case then we can make the patch.

In the meantime as a workaround you can change the defaults to allow minimums one byte less in size.

**Comment by zeripath** [comment]
OK I think it's only rsa that can be affected here. So I'll just do a very simple pr.
