### ISSUE TITLE
Switch to Weblate for translations

### ISSUE THREAD

**Issue by balporig** [go-gitea/gitea#20309]
### Feature Description

Weblate is free and opensource localization tool. The hosted version https://hosted.weblate.org/ is free for libre projects. It can also be selfhosted and it will make sense when gitea repo is moved to https://gitea.com/ from github

**Comment by delvh** [comment]
(Partial) Duplicate of #17081

**Comment by throwawayaccountfor** [comment]
+1

Surprised that Gitea used Crowdin!

**Comment by lafriks** [comment]
Weblate imho is missing multiple features that we need:
* More granular permission system (allow to set proofreaders for each language that can approve translations)
* Translations should not be pushed back to git if proofreader has not approved them (WeblateOrg/weblate#3745)

Taking into account this I don't see how we could currently move gitea translation process to Weblate even through I like it and otherwise is great product.

I will close this issue currently but we can definitely revisit this issue once issues mentioned above have been implemented in Weblate
