### ISSUE TITLE
[BUG]:  slice bounds out of range at modules/git

### ISSUE THREAD

**Issue by secsys-go** [go-gitea/gitea#20315]
### Description

I tried to parse some data with ParseTreeEntries in modules/git, but it crashed instead of returning an error

```go
package main
import "code.gitea.io/gitea/modules/git"
func main() {
	git.ParseTreeEntries([]byte("1006440000000000000000000000000000000000000000000000000000000000000000000000\t\n1006440000000000000000000000000000000000000000000000000000000000000000000000\t\n1006440000000000000000000000000000000000000000000000000000000000000000000000\t\n1006440000000000000000000000000000000000000000000000"))
}

```
Found by [go-fuzz](https://github.com/dvyukov/go-fuzz)

### Gitea Version

with git commit as ee769f7459ffba310563cd735f503d3d7576da60

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 

### How are you running Gitea?

I test the API in Gitea through go-fuzz

**Comment by lunny** [comment]
So I assume you are using SHA256 but not SHA1 ?

**Comment by wxiaoguang** [comment]
> So I assume you are using SHA256 but not SHA1 ?

Since that's generated by a fuzz test, it doesn't need to be SHA256 or SHA1.

**Comment by Gusted** [comment]
Fuzzing Gitea directly by calling it's function is risky and IMO incorrect, because you want to make sure that fuzz-data go trough all stages as a normal workflow would, so just fuzzing a specific function in `modules/` is useless as there's a good chance that before that function is called within Gitea it already did go trough other checks, not all validation and sanity checks live in `modules/` but can also lives at go-chi level or in the `routers/` level. Well they do present an interesting case, unless it's actually "actionable" it isn't worth adding checks when they may already exist.

----

I had a quick look at the function and there are two references, one is for testing and the [other reference](https://github.com/go-gitea/gitea/blob/cb6c5f8193946cf65ba9b325a1989d72faaf2b86/modules/indexer/code/git.go#L72) is a helper function for parsing the raw stdout of git commands. Unless git decides to change this output or somehow be able to corrupt the output this panic cannot ever exist.

**Comment by wxiaoguang** [comment]
->  Refactor parseTreeEntries, speed up tree list #21368
