### ISSUE TITLE
syntax highlighting containerfile

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#20360]
### Feature Description

I would love it if Gitea supported syntax highlighting for container files and recognized Dockerfile.* and Containerfile.* for syntax highlighting.

**Comment by silverwind** [comment]
You should be able to use [`linguist-language` in gitattributes](https://github.com/go-gitea/gitea/blob/07ec8288bff6295c7db5558846153a61625af80d/.gitattributes#L7).

Otherwise, you could try a PR to add this pattern to [chroma](https://github.com/alecthomas/chroma/blob/5ce1d5dd69ed9bfff2894f191b7b5f282b37beb2/lexers/docker.go#L12) which is used by Gitea to detect language.

**Comment by silverwind** [comment]
Actually, I made a quick PR for `Dockerfile.*`: https://github.com/alecthomas/chroma/pull/651
