### ISSUE TITLE
Add a token to CI runs similar to GITHUB_TOKEN

### ISSUE THREAD

**Issue by dorianim** [go-gitea/gitea#20394]
### Feature Description

It would be great if Gitea would add a token to CI runs, similar to GITHUB_TOKEN. Currently, I have to generate a personal access token to push docker containers to the integrated container registry. This is a problem for organizations, as the token belongs to one member.
If that is not possible because of the way Gitea integrates with different CI-providers, it would be nice, if it was possible to create an organization wide access token.

**Comment by 6543** [comment]
tldr: this is not posible because of the architecture gitea integrates with ci providers

long: 
If you find a CI that is willing to integrate a function to inject a token, for the repo it got the request to run the pipeline, into the ci environment - you could have souch feature ...
... I would create a "bot" account that does handle things and reuse it acordingly ..

**Comment by dorianim** [comment]
> this is not posible because of the architecture gitea integrates with ci providers

Alright, that makes sense.

> this is not posible because of the architecture gitea integrates with ci providers

I think, this is quite a hustle for such a small thing. Wouldn't it be possible to just create an access token which only works for a certain organization?

**Comment by 6543** [comment]
well yes with a dedicated account ... - limiting the scope of tokens is already a open feature request
