### ISSUE TITLE
Autocomplete creating problems with text entry, strange unicode (or user error)

### ISSUE THREAD

**Issue by DarrenPIngram** [go-gitea/gitea#20451]
### Description

With a new installation of Gitea (I am getting used to it, rather than use Github) I have had problems with some text, but not all text, creating issues that generate the exclamation point. See earlier report https://github.com/go-gitea/gitea/pull/19990#issuecomment-1192346638

It does seem to occur perhaps when auto-correct or auto-fill wants to leave its impression (how do you turn this off? I am using Gitea in default and see no options), e.g.

U+00a0 space and flashes up "adjust settings" but I've not found how to get that option working as you right click or move the mouse and it has gone.

READ FIRST
READ THEN
DRIVE FIRST
WET DOG
WET pig

All the above get the yellow box in edit mode and then alert when saved. Only wet pig (no capitals) did not create the problem.

Reproduced also at https://try.gitea.io/DarrenPIngram/test/src/branch/main/test

### Screenshots

![Screenshot 2022-07-22 at 13 00 27](https://user-images.githubusercontent.com/7067136/180416633-1b018dc7-4404-44fe-9f27-f07ed51e005c.png)

### Gitea Version

 1.17.0+rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOS 12.4

### Browser Version

Google Chrome version 103.0.5060.114 (Official Build) (x86_64)

Edit: I managed after many attempts in a different place to turn off the highlighting at least, but I feel the default behaviour may not be right. But it does not seem to save the instructions, even with saving the page.

**Comment by zeripath** [comment]
I really don't think the yellow boxing and warning of invisible characters is a bug here. 

U+00A0 `&nbsp;` is not U+0020 ` `. 

Your confusion as to why the "space" is being detected as a "strange unicode error" clearly demonstrates that this is an ambiguous character in need of highlighting as being ambiguous. 

---

As to why Monaco is suggesting nbsps here I don't know. I cannot replicate that.

---

If you're careful you can move the mouse cursor to get to the to the exclude menu but it appears that isn't actually connected. Now that is a bug - however at most a setting here would affect the editor only as it don't think it could be easily passed down to the main rendering system. I would guess the correct thing to do here is to disable that option.

--- 

Now, clearly we may want to think about if and when an nbsp can be non-ambiguous. I don't know when it would be appropriate to not highlight it. I guess it's fine for rendered files but I think it should still always be highlighted as an invisible character in a code view - it's just too ambiguous otherwise.

**Comment by wxiaoguang** [comment]
Similar issue here:

* https://github.com/go-gitea/gitea/issues/23149

So I think this one could be closed. Let's improve the problem in the future.
