### ISSUE TITLE
`docker login` reports sucessful login with incorrect password / token

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#20563]
### Description

```
$ docker login localhost:3000
Username: foobar
Password: 
Login Succeeded
```
↑ this should fail as i entered gibberish for the password

```
$ docker push localhost:3000/foobar/qgis
Using default tag: latest
The push refers to repository [localhost:3000/foobar/qgis]
5a1bd4bee150: Layer already exists 
1b04ddff91f2: Layer already exists 
4dd0c5812fd4: Layer already exists 
unauthorized: authentication required
```
↑ ACLs seem to generally work at least ;)

### Gitea Version

692707f14519b677de4601e5f40469989f82eed6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build from source

### Database

SQLite

**Comment by algernon** [comment]
FWIWI, this appears to be the relevant code:

https://github.com/go-gitea/gitea/blob/ff9b6fa6639bacd4770b0e81661697af35c78aa6/routers/api/packages/container/container.go#L137-L152

I would assume Doer is nil here, because of:

https://github.com/go-gitea/gitea/blob/ff9b6fa6639bacd4770b0e81661697af35c78aa6/routers/api/packages/api.go#L254-L256

Thus, since Doer is nil, it the first block of code uses the ghost user, and thus, succeeds. If my assumption is correct, then it should treat Doer being nil as an error and 403.

Mind you, this is just my quick impression of the code, I have not verified either of the above assumptions.

**Comment by algernon** [comment]
FWIW, I have a fix prepared for this, PR will be coming up shortly.

**Comment by algernon** [comment]
...I spoke too soon. The ghost user is required for anonymous pulls, which *also* hit the token URL, so just going off of `ctx.Doer` being nil alone is incorrect. I'll have a PR up shortly anyway. :)

**Comment by djmaze** [comment]
With 1.17.0, I get the `authentication required` when trying to push a container to `http://gitea/myuser/image`, even with a correct login. Is the pushing of container images broken completely in the release?

**Comment by lunny** [comment]
The Auth interface need to be refactored to have a new return argument which indicate should we continue the next auth method.
