### ISSUE TITLE
LDAP doesn't allow hyphens in email addresses

### ISSUE THREAD

**Issue by mctaguma** [go-gitea/gitea#20857]
### Description

When trying an LDAP sync I see the following in the log:

2022/08/19 14:41:39 .../ldap/source_sync.go:120:Sync() [E] SyncExternalUsers[AD]: Error creating user firstname.name: e-mail address contains unsupported character [email: :firstname.last-name@domain.com]

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.16.9

### Operating System

CentOS 7

### How are you running Gitea?

Using the binary on CentOS 7

### Database

MySQL

**Comment by wxiaoguang** [comment]
Since the error message is:

`Error creating user firstname.name: e-mail address contains unsupported character [email: :firstname.last-name@domain.com]`

You are using `:firstname.last-name@domain.com` as the email address, which starts with a `:` ?

At the moment, it's not a valid email for Gitea.

**Comment by mctaguma** [comment]
The email address was configured with format of first name.last-name@domain.com in Active Directory.

Strange, there was no colon preceding the email address in AD.

I just tried to reproduce this in 1.17.2, and I was unable to reproduce this issue.
