### ISSUE TITLE
Translatable button

### ISSUE THREAD

**Issue by antiuser** [go-gitea/gitea#20862]
### Description

Hi! I have Russian language in accout setting in version 1.17.1.
Button "Go to file" not translatable and showing as 'find_file.go_to_file'.

### Screenshots

![Снимок экрана_2022-08-19_13-53-55](https://user-images.githubusercontent.com/5499424/185583121-352b09c8-d745-4aed-98fb-f3636b266f0b.png)

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Google Chrome 104.0.5112.79

**Comment by delvh** [comment]
1. All our translations are managed on [Crowdin](https://crowdin.com/project/gitea).
If you want, you can improve the translations yourself.
2. As it appears, there is a [proposed translation for this button](https://crowdin.com/translate/gitea/68/enus-ru?filter=basic&value=0#q=find_file.go_to_file), but no one has approved it yet.
Perhaps you should ask in [our #russian Discord channel](https://discord.com/channels/322538954119184384/753449741362135100) whether someone could approve this translation.
3. Is the default language of your server Russian? Because I don't know why else the fallback key would be shown instead of the text in the default language...

**Comment by wxiaoguang** [comment]
It will be fixed by #20834
* #20834

Although I do not know why the backport is merged without translation.

**Comment by wxiaoguang** [comment]
it seems that the English key "find_file.go_to_file" exists for 1.17

https://github.com/go-gitea/gitea/blob/release/v1.17/options/locale/locale_en-US.ini#L2286

I would suggest you to check if you are using customized locale resources and whether they are out-dated.
