### ISSUE TITLE
Cannot Add Large GPG Key

### ISSUE THREAD

**Issue by lekoOwO** [go-gitea/gitea#20894]
### Description

`AddPublicKey: Error 1406: Data too long for column 'content' at row 1` happens when importing a longer GPG Key (e.g. 4096 key size often reaches the 64KB limit in case of MySQL's TEXT field)

Using MySQL 8.

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Using Docker.

### Database

MySQL

**Comment by fsologureng** [comment]
Hello,
This bug should be reopened because importing gpg keys suffered from the same issue.

Reported in @Codeberg-org and @Forgejo [here](https://codeberg.org/forgejo/forgejo/issues/359).

The error log involved is
~~~
2023/02/12 15:37:27 ...user/setting/keys.go:117:KeysPost() [E] [63e907b5-20] AddPublicKey: Error 1406: Data too long for column 'content' at row 1
~~~
The table `gpg_key_import` should also be migrated to enlarge its `content` field size.

**Comment by zeripath** [comment]
Instead of commenting on bugs that have been closed for over 6 months it's better to open a new one and reference the old one.

**Comment by fsologureng** [comment]
Ok. No problem.
