### ISSUE TITLE
Posting a commit in PR via "Ctrl+Enter" finishes the review process

### ISSUE THREAD

**Issue by Artalus** [go-gitea/gitea#20990]
### Description

Posting a comment with `Ctrl+Enter` does not add it to the "review queue", but instead publishes the whole "queue" immediately.
Introduced in 1.17 with #19729.

1. Make a PR and go to "files changed" section.
2. Write a comment somewhere. Notice that there are "Start review" and "Add single comment" buttons.
3. Click "Start review". The comment now has yellow "pending" label.
4. Add another comment. Notice that there is only one button now, "Add comment".
5. Instead of clicking the button, hit `Ctrl+Enter`. The new comment will have gray "review" label, while the old one still has yellow "pending".
6. Try to write another comment. Notice that "Start review" and "Add single comment" are back.
7. Refresh the page. Both comments have "review" label. If you go to "conversation", both comments are visible.

### Gitea Version

1.17

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by wxiaoguang** [comment]
The problem is that the review comment UI is inside a `form`.

To make the logic correct and fix the issue, the AJAX related inputs should be (refactored) moved out of the form, and handle `ce-quick-submit` event by customized code.

Related code:
* `initRepoDiffConversationForm` in `repo-diff.js`
* `<form ...>` in `comment_form.tmpl`

**Comment by wxiaoguang** [comment]
I think https://github.com/go-gitea/gitea/pull/20992 will fix the problem. I have tested it on my side.
