### ISSUE TITLE
Add option to edit mirror interval on repo push mirrors

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#21295]
at the moment you have to recreate a push mirror if you want to change the interval :/

**Comment by CypherpunkSamurai** [comment]
Hello @6543,

I would like to contribute to this issue, I've worked on golang projects before, and would like to work on gitea. how can i get started? :)

**Comment by bitethecode** [comment]
@6543 Could you assign this to me?

**Comment by puni9869** [comment]
As per my understanding 
we have mininum 10 minute default periodic sync time when we setting up any mirror and once we done setting as below 
![image](https://user-images.githubusercontent.com/80308335/226682092-98575a4b-9dfb-42c3-b4c5-133f7d996a0b.png)
screen shot

We don't have option to edit the periodic time in existing setted up push mirror. 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/80308335/226682461-493bdd7b-7350-4a79-b4c0-6df6085a6ca2.png">

So in this ticket we want that small feature so that we don't have to recreate the mirror again and again. 
Am I on the right track?
