### ISSUE TITLE
Docker Hub `latest` Tag Points to Release Candidate 1.18.0-rc0

### ISSUE THREAD

**Issue by julmb** [go-gitea/gitea#21615]
### Description

Currently, the `latest` tag for gitea on docker hub [1] points to the same image as the `1.18.0-rc0` tag [2]. The documentation says that the `latest` tag should only point to stable releases.

This has happened before with 1.17.0 (#20058) and the configuration was apparently changed to prevent it from happening again, but now it has happened again.

[1] https://hub.docker.com/layers/gitea/gitea/latest/images/sha256-167f91cbf8f2d8e031d22c57928a157d4772aa378baa116a2f71f703b70b367f
[2] https://hub.docker.com/layers/gitea/gitea/1.18.0-rc0/images/sha256-167f91cbf8f2d8e031d22c57928a157d4772aa378baa116a2f71f703b70b367f

### Gitea Version

1.18.0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea from Docker Hub run via Docker Compose

**Comment by 6543** [comment]
ref https://gitea.com/gitea/drone-docker/pulls/2

**Comment by lunny** [comment]
Since it has been tagged, I would like to stay latest == 1.18rc0, if we delete the tag, some users will encounter a downgrade. Our task is to push the 1.18.0 releasing ASAP.

**Comment by 6543** [comment]
same game as last time :sweat:

**Comment by MrHaroldA** [comment]
> Since it has been tagged, I would like to stay latest == 1.18rc0, if we delete the tag, some users will encounter a downgrade. 

I actually encountered this, but a downgrade to 1.17 fails to start after an update to 1.18rc0, so I just went with 1.18rc0 after reading that it should be near a real release.

**Comment by ricariel** [comment]
I would love to see a stable tag for this.

**Comment by xPuls3** [comment]
As the documentation says 'latest' is stable, it threw me off to see a release candidate version installed.
I would definitely like a 'stable' tag as mentioned above if this is going to keep happening.

**Comment by lunny** [comment]
> As the documentation says 'latest' is stable, it threw me off to see a release candidate version installed. I would definitely like a 'stable' tag as mentioned above if this is going to continue happening.

Sorry, that's an accident event.

**Comment by f0086** [comment]
So, over a month later, the latest tag is still on the .rc1.
The 1.18.0 milestone seems almost complete for some time (https://github.com/go-gitea/gitea/milestone/120), when are you planning to push the 1.8.0 release?

**Comment by zeripath** [comment]
I think we do need to do another RC of 1.18 or release it. I'm not sure if we feel it's ready yet for release but it's getting there.

**Comment by KN4CK3R** [comment]
1.18.0+rc1 includes everything until 24.11.2022, so the ghost fix you mentioned is included.

**Comment by lunny** [comment]
> I think we do need to do another RC of 1.18 or release it. I'm not sure if we feel it's ready yet for release but it's getting there.

I agree to just release 1.18.0

**Comment by 6543** [comment]
we should not messup at next rc ... (1.19.0-rcX)

**Comment by zeripath** [comment]
I'm not sure it's really a mess-up. I know that people don't like this but we need to get people to test RCs.

**Comment by delvh** [comment]
Only problem: We declare `latest` to be `the latest stable version`. `rc`s are (by definition) not stable.
If we change that, I'm also fine with it.

**Comment by gapodo** [comment]
> I'm not sure it's really a mess-up. I know that people don't like this but we need to get people to test RCs. 

This is a big fat mess-up since latest was declared as the "stable" tag, anything other than a stable therefore is a mess-up.

Also if you want people to test, sneaking them an rc into their setup is a really messed up strategy and IMHO should be considered malicious behavior!

I agree that testing is necessary, but not this way. I get that most do not want to test RCs, I'm usually not keen on it either, as my setup is there to support my other tasks, not to be my task (as in testing, fixing, or desaster recovery), but forcing it on people isn't the way to do it.

If there is something people are waiting for, they will test it (at least if they have the time/resources/need), if existing things break, that's what tests are for... If it only happens under high load, high connection count,... (at scale) users testing RCs likely won't help, as those who are running at such scales usually pin their instances to the sha-digest and run pre-testing on different instances (usually at lower scale as simulating tons of users osn't the simplest rhing to do.

**Comment by jolheiser** [comment]
I also agree that `latest` should not include RCs. While I love the idea of getting them tested, `latest` should probably be reserved for stable.

If not, some option that _does_ only include stable should be provided. 
Alternatively, `latest` can be stable and another label can be used for pre-releases. 

Apologies, I know we've discussed this before, but a cursory search doesn't bring it up on GH.

**Comment by gapodo** [comment]
@zeripath and everyone interested, I've added an edit to my message, as I have missed the tone. Sorry for screwing up that reply.

**Comment by lunny** [comment]
Since 1.18.0 released, I think we can close this one.
