### ISSUE TITLE
Marking pr as manually merged doens't do anything

### ISSUE THREAD

**Issue by tautf** [go-gitea/gitea#21912]
### Description

I merged a pull request the normal way with clicking "Merge". During the "merge process" i left the page which caused this behaviour.

- Branches are merged together
- PR still open and unmergeable because branch is already included in target
![Bildschirmfoto 2022-11-23 um 11 52 43 AM](https://user-images.githubusercontent.com/18403881/203528997-e2f2f963-927d-4d9e-80d7-c32b30907a17.png)

- Clicking "Manual Merge" does nothing
- Im not able to close this PR (with this button, of course with the "Close" functionality")

Maybe dont have "Manual Merge" as a button if nothing happens.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

none, integrated

### Operating System

Windows Server 2019

### How are you running Gitea?

Windows amd64 executable

### Database

PostgreSQL

**Comment by a-n-dokuchaev** [comment]
Help us, please. Last 2 of 50 PRs with this issue.

**Comment by wxiaoguang** [comment]
Sorry I missed this issue.

There are 2 problems here:
1. When the browser leaves the page, the connection is disconnected and Gitea may not finish its work (especially the necessary database updating), so the PR is left open. This problem should be fixed by other approaches.
2. The Manually Merged form is broken, it will be fixed by #23015
