### ISSUE TITLE
the attachment is not carried When I click Release version

### ISSUE THREAD

**Issue by nyxo-dev** [go-gitea/gitea#21992]
### Description

uploaded the jar file in **version release page**
![image](https://user-images.githubusercontent.com/39261437/204858935-b367042d-bdf0-4515-97cd-f7daddb9e61a.png)
**and then**
![image](https://user-images.githubusercontent.com/39261437/204859789-30513b9b-bbfb-418b-abd3-54a05d622c70.png)

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

ubuntu

### How are you running Gitea?

in docker container

### Database

MySQL

**Comment by lunny** [comment]
I think that's the editor attachment but not release assets. And of course, there is something wrong there.

**Comment by BElluu** [comment]
Hi,
I think that's not a bug and it's not problem with .jar extension. If you hover your mouse over this attachment you will see information about max size file (4MB). You want to add .jar with almost 100MB size, that's why you cannot add it. Small .Jar I added without any problem.
![image](https://user-images.githubusercontent.com/11333925/229279710-1220ff13-a12d-434c-9708-bcaf466acfbb.png)

I found in app.ini
![image](https://user-images.githubusercontent.com/11333925/229279813-a9ac5cf7-41c1-4611-a684-0f457817ae06.png)

so if you change this option to 100 then you should be able to upload an attachment up to 100MB.

**Comment by jinlong96** [comment]
> Hi, I think that's not a bug and it's not problem with .jar extension. If you hover your mouse over this attachment you will see information about max size file (4MB). You want to add .jar with almost 100MB size, that's why you cannot add it. Small .Jar I added without any problem. ![image](https://user-images.githubusercontent.com/11333925/229279710-1220ff13-a12d-434c-9708-bcaf466acfbb.png)
> 
> I found in app.ini ![image](https://user-images.githubusercontent.com/11333925/229279813-a9ac5cf7-41c1-4611-a684-0f457817ae06.png)
> 
> so if you change this option to 100 then you should be able to upload an attachment up to 100MB.

Tanks！

**Comment by jinlong96** [comment]
max size file (4MB
