### ISSUE TITLE
/admin/default-hooks/gitea/new 500

### ISSUE THREAD

**Issue by captainstdin** [go-gitea/gitea#22154]
### Description

![image](https://user-images.githubusercontent.com/56504552/208286005-9ab80dfe-8a3e-4141-9ab5-a01c066399a1.png)

![image](https://user-images.githubusercontent.com/56504552/208285976-96030fd9-b1e9-4c09-a64f-f8c69fb57c03.png)

verversion: 1.18.0+rc1

### Gitea Version

1.18.0+rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

```
docker run -it \
--name=gitea \
-p443:3000 \
-p127.0.0.1:2222:22 \
-e USER_UID=1001 \
-e USER_GID=1000 \
-v `pwd`/public:/data/gitea/public \
-v `pwd`/templates:/data/gitea/templates \
-v `pwd`/data:/data/gitea \
-v `pwd`/log:/data/gitea/log \
-v `pwd`/custom/conf/app.ini:/data/gitea/conf/app.ini \
-v /home/git/.ssh/:/data/git/.ssh \
gitea/gitea:latest
```

### Database

SQLite

**Comment by zeripath** [comment]
It would be helpful if the provided logs were as text rather than a screenshot, as the screenshot has slightly cut off the salient part of the error message.

From the bit I can tell there is a template error with some property HeaderAuthorization being missing on the some struct provided to the template (likely a struct named hook given the context)

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/998fe26051514ee74bb9c2f0e7de56014933133b/templates/repo/settings/webhook/settings.tmpl#L254

**Comment by captainstdin** [comment]
> There is no HeaderAuthorization in 1.18 - you're using a template from 1.19/main in 1.18 and that is why you have this problem.
Yes, I got it , you are right。thinks

by the way , gitea/gitea:latest ，  Is it 1.18 actually ?

**Comment by zeripath** [comment]
The docker tag `gitea/gitea:latest` is the latest release or release-candidate. `gitea/gitea:dev` represents the last successful build from the main branch.

In the templates, you're correct that `{{AppUrl}}` will be the set-up application url.

BTW you can use the `gitea embedded` command to extract any built-in templates rather than risk downloading the incorrect version for your current version of gitea.
