### ISSUE TITLE
Nuget NotFound package with version suffex like (1.0.0-rc.1+r12345.26a7053f)

### ISSUE THREAD

**Issue by m2nlight** [go-gitea/gitea#22178]
### Description

We always make nupkg files to append VCS version like `1.0.0-rc.1+r12345.26a7053f`

The gitea nuget repo page (ex: http://gitea:3000/testorg/-/packages/nuget/test.pkg.scanner/1.0.0-rc.1+r12345.26a7053f) is okey. 
And the tip info:

```sh
dotnet add package --source Gitea --version 1.0.0-rc.1+r12345.26a7053f Test.Pkg.Scanner
```

VS2022 get some errors when restore this package:
```txt
GET http://gitea:3000/api/packages/testorg/nuget/package/test.pkg.scanner/index.json
OK http://gitea:3000/api/packages/testorg/nuget/package/test.pkg.scanner/index.json 921 ms
GET http://gitea:3000/api/packages/testorg/nuget/package/test.pkg.scanner/1.0.0-rc.1/test.pkg.scanner.1.0.0-rc.1.nupkg
NotFound http://gitea:3000/api/packages/testorg/nuget/package/test.pkg.scanner/1.0.0-rc.1/test.pkg.scanner.1.0.0-rc.1.nupkg 303 ms
...
```

I got that from the `index.json`
```json
{"versions":["1.0.0-rc.1","1.0.0-preview.1"]}
```

I guess real package address is http://gitea:3000/api/packages/testorg/nuget/package/test.pkg.scanner/1.0.0-rc.1/test.pkg.scanner.1.0.0-rc.1+r12345.26a7053f.nupkg

*The `index.json` should be*

```json
{"versions":["1.0.0-rc.1+r12345.26a7053f","1.0.0-preview.1"]}
```

### Gitea Version

1.18.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea in docker

### Database

None

**Comment by KN4CK3R** [comment]
Thanks for reporting. It's a bit tricky because the array should contain the "normalized versions" (https://learn.microsoft.com/en-us/nuget/api/package-base-address-resource#response) The following request with this version fails because the registry only knows about the non-normalized version. Now the question is how to fix it. If I allow multiple versions with different metadata, it's not clear which version should be presented to the caller because the metadata part is missing. So my current solution would be to normalize the version when uploading a package which would prevent the error but only allow one normalized version. Do you know how other registries handle this?

**Comment by m2nlight** [comment]
Thanks!

We don't like tricky. I will pack normalized version files until there is the right solution.

**Comment by m2nlight** [comment]
I check again, and found this.

I upload nupkg filename: `test.pkg.scanner.1.0.0-rc.1.nupkg`
But, gitea link filename: `test.pkg.scanner.1.0.0-rc.1+r12345.26a7053f.nupkg`
