### ISSUE TITLE
Cloudflare bypasses

### ISSUE THREAD

**Issue by twisted-nematic57** [go-gitea/gitea#22255]
### Feature Description

I'm hosting my Gitea server on a Raspberry Pi 4B 8GB. Of course I'm using ARM64 Ubuntu 22.04 LTS with PostgreSQL 15 database. I'm using Cloudflare Tunnel to route get Gitea online to [my domain](https://gitea.hdg57.eu.org/). Everything is perfect except for two things.

1. Cloning big repositories (such as [this one](https://gitea.hdg57.eu.org/coolstuff/gcc.git)) fails. Cloudflare returns HTTP 524 on requests that haven't been active for 100 seconds or more. Some kind of Git pack service takes more than 100 seconds to finish, which means the Git client that's trying to clone will exit saying that the server returned HTTP 524. This cannot be fixed unless if I get professional-grade hardware which is not my solution.
2. Cloudflare also imposes a 100MB upload limit, meaning that you cannot push commits greater than 100MB (realistically ~90MB) in size. Is there a way for Gitea to take commits in 75MB chunks? That way Cloudflare's limit can be bypassed since we're using multiple POST requests, each smaller than 100MB, to deliver the data. Same goes for the "upload file" button in the web UI.

**Comment by tahaghafuri** [comment]
You Can't Cloudflare Bypass,
Fix:
UnProxy Your Domain!

**Comment by delvh** [comment]
Regarding 1:
I wouldn't have put it like that, but in general, I agree:
It is not our task to fix what you choose to do with Gitea.
Our task is to ensure that Gitea works as universally as possible.
If you choose to host it under a too-restrictive hoster, then there is pretty much nothing we can or should do.

Regarding 2: It would be possible if git would allow for something like this.
I don't think it does at the moment, so please open another issue for them, and if they choose to implement it, we can revisit/ reopen this issue.
It's probably not a good idea to deviate from what git offers itself.

As there is otherwise nothing to do, I'd close this issue for now.
If Git chooses to implement [2], it can be reopened.

**Comment by wfjake** [comment]
To unproxy your Gitea server, you will need to delete that CNAME entry and replace it with an A entry containing the public IP address of your server (If your server has IPv6, you should add an AAAA record too).

**Comment by HackerDaGreat57** [comment]
Yep, the problem was that I was trying to use Cloudflare Tunnel on an unproxied subdomain. Apparently that isn't possible, so I replaced it with an A entry pointing directly to my server's public IP address. It works. Sort of.

The port is mapped like this:
`<public IP>:443` mapped to `<server's local IP>:<Gitea port>`

Web UI traffic goes through nicely, whether the subdomain is orange-clouded or not. Everything Web UI-related still works and the website is still very responsive, and everything is coming directly from my origin server.

So what is so special about the Cloudflare proxy service that without it Git clones won’t even work? When the subdomain is orange-clouded then the Git clone is successful. If it’s grey clouded then running the exact same clone command will complain that it couldn’t even establish a connection since it timed out trying to connect. I’ve tried manually entering my credentials and server port in the clone URL itself, but still no avail. I also waited out the entire TTL when editing the DNS entries plus an entire five minutes extra, but again, still no avail. Please help.

The screenshot below shows what happens when I try to clone a tiny repository when the subdomain is grey-clouded. (When it's  orange-clouded, it works the way you'd expect.)
![image](https://user-images.githubusercontent.com/70416002/209772070-3f3b8dac-c31a-43ad-9206-ea78a281b904.png)

**Comment by wfjake** [comment]
I don't know, I'm not very familiar with Cloudflare. My best guess is that there is some web application firewall running and it blocks requests ending in `.git` to prevent data exfiltration. You might be able to get better help asking on a Cloudflare specific forum or support team if they have one.

**Comment by HackerDaGreat57** [comment]
The problem was that I needed to route external ports `22`, `80`, `443`, and `9418` to my nginx proxy's internal port. Problem solved! (I also learned that Cloudflare Tunnel doesn't support unproxied domains.)

**Comment by roytam1** [comment]
for 1, I wonder if gitea can implement a poll-like approach and let pack/diff/etc. operations running in background, with front-end(i.e. web browsers) querying status by doing check-status poll requests?
