### ISSUE TITLE
`CANNOT` is almost always preferred to 'CAN NOT'

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#22371]
### Description

I believe from hundreds of research and thousands of times that the word 'CAN NOT' is spelled wrongly.

The spelling should be `**CANNOT**`, no space in between.

URL: https://try.gitea.io/user/settings/account

### Screenshots

![image](https://user-images.githubusercontent.com/85847352/211208092-ca43f978-d963-4faf-a54c-108e21c5c900.png)

### Gitea Version

1.19.0+dev-273-gdfd2db569

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Microsoft Edge - 107.0.1418.62 (Official build) (64-bit)

**Comment by jolheiser** [comment]
As far as I know both are fine, though perhaps "cannot" is preferred.

I'd be fine with a PR for this, however I am going to close this issue as it's not necessarily a bug and also technically isn't a misspelling, it's just English being English.

**Comment by delvh** [comment]
> I'd be fine with a PR for this

Done.

**Comment by zeripath** [comment]
As a native British English speaker - I can assure you that `CAN NOT` is valid English. However, in modern contexts it's almost always only used when you want to expressly present something as an option, usually in a sarcastic way.

For example, `You can NOT get into arguments about grammar and spelling, it's far from obligatory...` So yes I would argue we should switch to `CANNOT` over `CAN NOT`.

Now, generally `CAN'T` has been thought of as being informal - but it's definitely sneaked its way into formal arenas and is taking over from `CANNOT` except where you want to express emphasis or where there is no personal pronoun. It might be the case that we want: `You can't do X` instead of `You cannot do X` for at least some of the cases. However, I'm sure you would agree that the sentence `CAN'T do X` would be too informal in comparison to `CANNOT do X` (note no `you` in these).
