### ISSUE TITLE
Milestone filter for closed issues shows only closed milestones

### ISSUE THREAD

**Issue by achikhv** [go-gitea/gitea#22411]
### Description

The issue is somehow related to #11924

We started to use gitea issues and noticed some behavior that could be a bug. It seems that closed issue list allows to filter only by closed milestones. Current opened milestones are not listed there. 

Suppose I have pending milestone, which is only partly done. I cannot see which issues are completed from the issue list. Instead I must go to milestones and click on "Closed" link. It's a little bit confusing. I think that filtering closed issues by pending opened milestones is a common operation and should be available.

Please see test issues. Milestones filter is disabled, as there are no closed milestones.
https://try.gitea.io/achikhv/test/issues?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0&poster=0

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Downloaded windows binary and started as windows service.

### Database

MSSQL

**Comment by BElluu** [comment]
Hi,
I think the problem is that there is no value in the closed issues tab in variable .Milestones in **/templates/repo/issue/list.tmpl**
I can disable condition to enable Milestone dropdown (red underscore) but still in this droplist are not any milestone.
.Milestones must be empty (orange underscore). I do not find why yet.
![image](https://user-images.githubusercontent.com/11333925/229297280-dd1fff4e-ea1e-45ea-a30b-20ba6b77fcd3.png)

**Comment by BElluu** [comment]
Hi,
After 2 hours I found how it works and why :) 
Everything is because of **state**. When we are on Open tab our **state=open** and we see only open milestones. When we are on Closed tab our **state=closed** and we can see only closed milestones. Milestone filter is disabled when you do not have any milestone in a given state - in the case presented by the author of the issue - closed milestone. If you have at least one, it will be enabled. But it's still not good, because we want to filter closed issues by open milestones.

Problem is in **model/issues/milestones.go**
![image](https://user-images.githubusercontent.com/11333925/229306346-f3a49f3c-b0bd-44a2-b11e-5d378efe9604.png)

where we have filtering by is_closed depends on state.

In /routers/web/repo/issue.go we pass state, so we can chage it to **all**
![image](https://user-images.githubusercontent.com/11333925/229307096-3b859df3-f72f-4bc1-abfe-04bd835dabe5.png)

With **all** we can filter open and closed issues by all milestones (open and closed) + milestones tab still works ok.

Milestones
![image](https://user-images.githubusercontent.com/11333925/229307169-7ae2e5f3-4262-4e7e-b2ef-66d5220b04aa.png)
![image](https://user-images.githubusercontent.com/11333925/229307175-8d7dd7b1-69d3-45f1-9b22-d07f66e2e0d4.png)

Issues
![image](https://user-images.githubusercontent.com/11333925/229307203-6dedbe95-1ae5-4fa7-92f8-b55214a18651.png)
![image](https://user-images.githubusercontent.com/11333925/229307209-92cd5c54-efbf-4d15-b993-24d92cb72e51.png)
