### ISSUE TITLE
How do I enable  password reset ?

### ISSUE THREAD

**Issue by freedomtrain** [go-gitea/gitea#2247]
How do I enable  password reset ?

Thanks

**Comment by lunny** [comment]
Password reset is enabled default.

**Comment by captn3m0** [comment]
You can reset password using the command line as well: `gitea  admin change-password --username username --password PASSWORD`

**Comment by pinpox** [comment]
@lunny It is not on the installation with Arch linux's AUR. At least I get an error saying it is disabled.
The command `gitea admin change-password --username username --password PASSWORD` returns an error:
```
models.SetEngine: Failed to connect to database: Unknown database type: 
```

**Comment by lunny** [comment]
you could use --config to indicate where is your app.ini

**Comment by poikilos** [comment]
@techknowlogick  Why was this closed without an answer? There is no obvious setting in the sample app.ini: <https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample> 
* the comments above to not answer the question. The OP did not ask how to reset a password using the command line interface, or whether it was default, but how to turn on the password reset feature. I am on a gitea repo now and the admin does not know how to turn on password reset. If I click reset password, it says:

> **Forgot Password**
> Password reset is disabled. Please contact your site administrator.

**Comment by dipyalov** [comment]
I support @poikilos. Why is this a closed issue? I'm facing the same problem with no clue which config option to change.

**Comment by alexanderadam** [comment]
I'm not a maintainer but this string isn't even [in the source code](https://github.com/go-gitea/gitea/search?q=%22Password+reset+is%22&type=Code). Are you sure that you are using the latest version, because there was also [this PR that was merged in April](https://github.com/go-gitea/gitea/pull/5042).

> @techknowlogick Why was this closed without an answer?

Did his suggestion (`gitea admin change-password --username username --password PASSWORD --config CONFIG_PATH`) not work?

**Comment by jolheiser** [comment]
@poikilos @dipyalov Password reset is only considered enabled when a mail service is set up, as that's how Gitea currently sends the account recovery.  
If no mail service is set up, I believe the CLI is the only other way to do it, or have your admin change it for you and then you change it back after regaining access.  (Not ideal, but I think perhaps a nice feature would be to then allow admins to force users to change their password, similar to how the CLI does)

**Comment by poikilos** [comment]
I was referring to Gitea Version: 1.8.1 (Go1.12.5).

**Comment by poikilos** [comment]
> Did his suggestion (gitea admin change-password --username username --password PASSWORD --config CONFIG_PATH) not work?
@alexanderadam The whole point of this topic is that _users_ cannot reset their passwords. Again, this topic is not discussing manual intervention by admins.

**Comment by alexanderadam** [comment]
> The whole point of this topic is that end users cannot reset their passwords.

Okay, then I probably misread **binaryplease** writing that he tested the admin command it without `--config` and got an error. :wink: 

> this topic is not discussing manual intervention by admins

IMHO it isn't possible to do this on a misconfigured system.
Because you can't add the email configuration without being an admin and you can't execute the gitea command.

So either the admin [adds the email configuration like described in the config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/#mailer-mailer) or he uses [the command **captn3m0** wrote about](https://github.com/go-gitea/gitea/issues/2247#issuecomment-353866212).

Or, to make this clear: the whole point should is, that asking your admin should be the first step if you are an end user and you encounter some problems on a particular installation (which is not only true for gitea).

**Comment by poikilos** [comment]
@alexanderadam 

> Okay, then I probably misread **binaryplease** writing that he tested the admin command it without `--config` and got an error. 😉

He's not the OP, and the command isn't something "disabled".

> Or, to make this clear: the whole point should is, that asking your admin should be the first step if you are an end user and you encounter some problems on a particular installation (which is not only true for gitea).

The OP could be an admin, and my admin doesn't know how to enable it.

**Comment by jolheiser** [comment]
@poikilos There is no setting for password resets. It is considered "enabled" when a mail service is configured, and "disabled" otherwise, as far as I can tell.  
  
Perhaps a better error message could be given, at least to admins?  
`Password reset is disabled. Please contact your site administrator.` seems reasonable to give to a user, since they don't need to know the inner workings.  
However, perhaps an admin should be given more context, such as `Please set up a mailing configuration to enable Password Reset` or something similar?

**Comment by VitaliyAT** [comment]
When I try realize `gitea admin change-password --username username --password PASSWORD`
For me it's:
`
root@TestLab:/usr/local/gitea/gitea# ./gitea admin change-password --username gitea --password gitea --config ./conf/app.ini`
I'v got this:
`2019/08/28 22:14:26 ...s/setting/setting.go:831:NewContext() [F] Expect user 'gitea' but current user is: root`

Try install and use Gitea on DSM Synology. First time it was OK - I'v got admin access, but after relogin "Wrong login or password". I already uninstall Gitea and reinstall it again - no luck, apologize all in data base. 

It's looped problem. I need change password because it write me that it's wrong, but I can't change it because I need this password for change.

How can I reset all Gitea in my situation? I just in the beginning of it and can do it but don't know exactly how.

**Comment by gewure** [comment]
honestly, this issue and the way of communication here bugs me.

many reasons:
#1 why close this twice, when its not resolved, as a question?!
#2 "further muddy this issue". nono, its not the users who are to blame here. Show some respect for people trying to advance documentation of gitea and solve problems they have.
#3 generally: the very most people writing github issues try to solve a problem they already tried solving hard before. most people don't even write an issue then. Its maybe 1-5% of users who write at all --- and being greeted with "don't write!!" adds to the general mood of not asking. Which then results in more question, because none gives a **** about resolving the issues, as meant by the author (who, in most cases is no expert on the matter - because of lack of meaningful documentation).

Also "is enabled by default" is simply not true as an answer, because a working mailserver-conf is a requirement and that is by default not enabled. 

@poikilos "this topic is not discussing manual intervention by admins." well then, to be honest: it should do so!! 

Sorry to comment on a closed one, but .. not that much sorry. Just had the same problem, read the whole issue, am now not really any more informed, other than i got the impression one shouldn't ask questions/write issues ...and (funnily enough) even if someone understands what the *real* question is ("how to manually change password as admin"), there is NO answer to it ':D

like.. why bother with writing answers, if there is no verbose information in it? Not worth the typing. 

whatever. Just my 2 Cents & impression, being a little frustrated. take it as feedback to improve.

**Comment by jolheiser** [comment]
For anyone who finds this issue, I would like to make another comment here at the bottom to address the aggregation of scenarios in this thread.

## How can I enable password reset / How can a user's password be changed?

The original question  
> How can I enable password reset (for end users)?  
  
There is no setting for password resets. It is considered "enabled" when a mail service is configured, and "disabled" otherwise.

-----

> How can a user's password be changed?

- As an **admin**, you can change any user's password (and optionally force them to change it on next login)...
  - By navigating to your `Site Administration -> User Accounts` page and editing a user.  
  - By using the [CLI](https://docs.gitea.io/en-us/command-line/#admin).  
Keep in mind most commands will also need a [global flag](https://docs.gitea.io/en-us/command-line/#global-options) to point them at the correct configuration.
- As a **user** you can change it... 
  - In your account `Settings -> Account` page (this method **requires** you to know your password. Maybe not entirely relevant to this thread, but posted here for completeness.
  - By using the `Forgot Password` link, assuming there is a configured mail service.

**Comment by poikilos** [comment]
@gewure,

2. a different question was asked than the original issue. Posting separate issues will not help the issue get resolved. I'm not trying to be unwelcoming. I'm a user trying to get my problem solved.

3. The maintainers posting how to change the password from the command line then closing the issue is a misunderstanding of the issue or need for GUI solutions or at least meaningful warnings pointing to a solution: see <https://github.com/go-gitea/gitea/issues/2247#issuecomment-499055290> above. It doesn't solve the original problem, that's all I was saying. Again, I'm not trying to be unwelcoming. I'm a user trying to get my problem solved.
