### ISSUE TITLE
readme.html

### ISSUE THREAD

**Issue by bluemmb** [go-gitea/gitea#2254]
Hi.

How can I add this feature, that gitea loads "readme.html" as html file under "readme.md" file in repositories home page ?

**Comment by lunny** [comment]
I think that's not a good idea maybe.

**Comment by bluemmb** [comment]
I don't want to use it in public places or somewhere that can cause security issues or ...
These are the reasons I want to have this feature :
1. Our language is written from Right to Left.
2. My friends who using local gitea are not good in english and main thing for our repos are readme part.
3. With html files we have many features that we haven't it with md files.

I would be grateful If you could help me.

**Comment by lunny** [comment]
Maybe a config default off and admin could turn it on.

**Comment by sapk** [comment]
We could just add dir="auto" like gitlab https://gitlab.com/gitlab-org/gitlab-ce/issues/35#note_14966359

**Comment by sapk** [comment]
For more context, problem around that has been discuss on https://github.com/dear-github/dear-github/issues/147 because github suffer the same problem.

**Comment by lunny** [comment]
@sapk we are different from Github. If user know what the dangerous, he can enable the feature himself.

**Comment by sapk** [comment]
Yes, I am not against. Just suggesting that if it's for RTL language there is maybe a better solution and that is has allready being discuss on other project.
As for displaying html file, some html syntax is allowed in markdown and for more complex I would suggest to use caddy with git plugin. I suggest that because it migth be enough fo the user.
On the other side, if needed we could easily implemnet/enable html file passtrough if admin allow it like you suggest.

**Comment by bkcsoft** [comment]
Allowing `readme.html` to be rendered isn't that much of a problem, IF all JS & SVG is disabled/removed from that file before rendering.

**Comment by 6543** [comment]
I thin it is possible to do with "custom markdown rendering", just add this to the config:

```ini
[markup.html]
ENABLED = true
FILE_EXTENSIONS = .html
RENDER_COMMAND = "cat"
IS_INPUT_FILE = false
```
