### ISSUE TITLE
Error 500 while creating a Pull Request from Gitea WebUI

### ISSUE THREAD

**Issue by zedalaye** [go-gitea/gitea#22716]
### Description

When I try to create a pull request to merge a branch into master, at the end of the process (the last step ?) I get an error 500.

I tracked down things in the log up to 👍 

`2023-02-01 17:25:22 | 2023/02/01 16:25:22 ...ers/web/repo/pull.go:1265:CompareAndPullRequestPost() [E] [63da9272] NewPullRequest: generate pull request index failed: pq: syntax error at or near "ON"`

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/zedalaye/b91153f2cf321b5b9af5813c6f9e7b65

### Git Version

2.36.4

### Operating System

Linux (Docker)

### How are you running Gitea?

Using official docker image `gitea:1.18`

### Database

PostgreSQL

**Comment by lunny** [comment]
What's your postgres database version?

**Comment by zedalaye** [comment]
9.5 (don't remember exactly which variant). In process to migrate to 15

**Comment by lunny** [comment]
Could you try that version because Gitea needs at least 10.
ref. https://docs.gitea.io/en-us/database-prep/#database-preparation

**Comment by zero-sky** [comment]
i have the same question

**Comment by zero-sky** [comment]
2023/04/13 10:56:23 ...ervices/pull/pull.go:764:GetIssuesAllCommitStatus() [E] [64376f57-8] getAllCommitStatus: cant get commit statuses of pull [32]: object does not exist [id: refs/pull/19/head, rel_path: ]
2023/04/13 10:56:45 ...ervices/pull/pull.go:461:pushToBaseRepoHelper() [E] [64376f6d-37] Unable to push PR head for westlake/qr_wl#34 (21:westlake/qr_wl:refs/pull/34/head) due to Error: exit status 1 - Invalid remote name "/mnt/dataDisk/git/data/gitea-repositories/westlake/qr_wl.git": Invalid remote name: "/mnt/dataDisk/git/data/gitea-repositories/westlake/qr_wl.git"
	error: failed to push some refs to '/mnt/dataDisk/git/data/gitea-repositories/westlake/qr_wl.git'
	
2023/04/13 10:56:45 ...ers/web/repo/pull.go:1282:CompareAndPullRequestPost() [E] NewPullRequest: Push: westlake/qr_wl:dev/zyl/bug0413 westlake/qr_wl:refs/pull/34/head exit status 1 - Invalid remote name "/mnt/dataDisk/git/data/gitea-repositories/westlake/qr_wl.git": Invalid remote name: "/mnt/dataDisk/git/data/gitea-repositories/westlake/qr_wl.git"
	error: failed to push some refs to '/mnt/dataDisk/git/data/gitea-repositories/westlake/qr_wl.git'

**Comment by wxiaoguang** [comment]
This issue could be close, it's 100% a postgresql version problem.


@zero-sky 

Your problem is different for the issue author's, you could open a new issue.

At the moment, I have no idea, but I think we can continue investigating the problem.

It looks like your git repository `qr_wl.git` is out-of-sync.

Could you please try to:

1. Enable DEBUG level log ,and set RUN_MODE=dev
2. Try to reproduce
3. Collect the logs, especially the git commands

Then you could try to:

1. Manually run the key commands to see what's the detailed error message.
2. Check your repository's internal state, eg: branches
