### ISSUE TITLE
multi languages support for buildin cli cmd's descriptions

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22761]
### Feature Description

Gitea website support multi languages, but the build in cli cmd's descriptions only support English.
I think we can add multi languages support to gitea cli's descriptions.

The language will based on system setting or env variable such as `GITEA_CLI_LANG`.
I will [work on this](https://github.com/yp05327/gitea/tree/add-multi-language-support-to-cli)

**Comment by yp05327** [comment]
Gitea uses [urfave/cli](https://github.com/urfave/cli) to build a cli app, but it has no build intranslation support :(
https://github.com/urfave/cli/issues/980

**Comment by wxiaoguang** [comment]
The idea is good, but it's not worth to spend time on it.

**Comment by lunny** [comment]
Sorry, I don't think we have enough resources to do that. I proposal to close this.

**Comment by delvh** [comment]
I also don't know of any localized CLI.
Do you have an example for one?

**Comment by yp05327** [comment]
@delvh @wxiaoguang @lunny 
Im sorry for my bad English.
I means to localize the command descriptions, not the commands themselves.

If it's no necessary to do this, I will close this later.

**Comment by wxiaoguang** [comment]
I understood your description before. That's why I said "The idea is good, but it's not worth to spend time on it.". If you meant "commands themselves", I would say "that's impossible" at that time.

The CLI is mainly for site admin, they should have the basic English ability. I ever saw some GNU tools do i18n for their CLI, in the end few people use or like them.

**Comment by zeripath** [comment]
@yp05327 I think it would be possible to do this with some fairly basic changes and a little magic related to looking at locale environment variables, so I'm gonna reopen this feature request.

However I'm not going to take any action to make it happen myself - at least not right now.

If you're interested in making this happen reach out to me on discord and we can chat.

**Comment by wxiaoguang** [comment]
At the moment, I think we shouldn't spend time on CLI i18n. The reasons are:

1. There are a lot of bugs in CLI now.
2. Some CLI texts are just from error messages.
3. We do not have a proper ICU message system.
4. The CLI i18n/l10n doesn't help end users too much, because they only use the web UI.
5. The localized texts may not work well in many systems without a proper environment.
6. If only the "description" is translated, the CLI is still mixed with different languages ......

So, I have objection for this change at the moment .....

**Comment by lunny** [comment]
I think so.
