### ISSUE TITLE
Debatable rendering of external link (and missing space)

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#2282]
A link to an issue on a foreign code hosting is rendered as just `#6` and the space before it is removed. See https://try.gitea.io/strk/postgis/pulls/1

The source code of that PR description is:
```
Mirror of https://git.osgeo.org/gogs/postgis/postgis/pulls/6
```

It is rendered as:
```
Mirror of#6
```

Reported gitea version at the time of writing this report: 27798c3

**Comment by ethantkoenig** [comment]
It seems there are tests in [`markdown_test.go`](https://github.com/go-gitea/gitea/blob/master/modules/markdown/markdown_test.go#L211) that explicitly check for this.

I agree that we should only render issue links for internal links, instead of assuming that any URL ending in a number points to some sort of issue, and am happy to make the fix. I just want to make sure there is consensus before actually making changes.
