### ISSUE TITLE
git command is broken in PR merge 500 error

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#23027]
### Description

1. Create PR
2. Click Create merge commit button and in title add `-`, Example: - Test PR
3. Click Create merge commit button
4. Display 500 error

error log:
`2023/02/21 10:04:47 ...rvices/pull/merge.go:544:rawMerge() [E] git commit [xx/xx:master_xx -> xx/xx:master]: git command is broken`

### Gitea Version

1.18.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

command-line

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
That's caused by 
* https://github.com/go-gitea/gitea/pull/21535

#21535 is used to enhance the security of Gitea. In history, there were many RCE security reports, caused by user-provided `-xxx` inputs.

The side effect of #21535 is very strict, so if there are some leading dashes, it always rejects them.

To fix the problem fundemetally without affecting security:
* all `{"commit", "-m", msg}` should be rewritten to `{"commit", "-m "+msg}` or `{"commit", "-m="+msg}`

**Comment by wxiaoguang** [comment]
The fix:   Use --message=%s for git commit message #23028
