### ISSUE TITLE
Bad MD5 filename for non-default avatars

### ISSUE THREAD

**Issue by as-marcb** [go-gitea/gitea#23041]
### Description

The avatar picture [endpoint](https://try.gitea.io/avatars/5b3f1f53451d50511958a1292e0bb0ce) always returns the `default` picture.
See difference to actual profile picture for [account](https://try.gitea.io/astos-marcb)

Path for the `non-default` picture [resolves](https://github.com/go-gitea/gitea/blob/bd820aa9c52da4568b460a0b8604287f8ed8df26/models/user/avatar.go#L25) to the file content hash `md5(<id>-<md5(content)>)` (as saved in u.Avatar) instead of the standardized `md5(email)`.

### Gitea Version

1.18.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.36.5

### Operating System

Alpine Linux

### How are you running Gitea?

docker, verified on https://try.gitea.io/

### Database

SQLite

**Comment by Zettat123** [comment]
Maybe you want to get your **custom avatar** by accessing `/avatars/{hash}` and the `hash` is `md5(email)`? 
Actually the hash filename only indicates a file, not a user.

**Comment by astos-marcb** [comment]
Exactly, the current user avatar should *always* be available at `/avatars/{md5(email)}`.

The default avatar is saved to the *correct* file name, a **custom avatar** is **not**.
A content/user-derived hash is used as the filename (value in `User.Avatar`) instead of `md5(email)`.
Setting the **default avatar** will actually change the value in `User.Avatar` to `md5(email)`, which in turn does not conform to the expected value in other parts of the code (detecting re-upload of same picture for a user).

An easy fix in *CustomAvatarRelativePath* would be to just throw away what's saved in `User.Avatar` (the user/content-derived MD5 sum in case of **custom avatar**) and just always use the correct filename conforming to `avatars.HashEmail(User.Email)`.

This will of course break references to existing custom avatars which are already saved to a misnamed files…

**Comment by Zettat123** [comment]
Gitea's avatar service is not de designed to be a service like Gravatar. The hash filename only used to distinguish between different files. 
Sorry I couldn't help more because we have no plans to develop this feature in the short term. Please feel free to reopen this issue if you still need help.

**Comment by zeripath** [comment]
It's a fairly interesting idea for Gitea to implement/replicate Gravatar's funcitonality and I don't believe that it would be too difficult to do this - but yes I don't believe that it is a bug that Gitea does not implement this.

@astos-marcb you could open a feature request but you'd need to link to the specs for it.

**Comment by astos-marcb** [comment]
Hm, there are already done some changes to avatar naming for [`v1.20`](https://github.com/go-gitea/gitea/pull/22289).
Will have a look how/if this affects current `/avatars/{md5(email)}` behavior (break/improve?).
