### ISSUE TITLE
Reviewing PRs: Ctrl+Enter submits comment instead of starting a review

### ISSUE THREAD

**Issue by drsybren** [go-gitea/gitea#23241]
### Description

When writing an inline comment on a pull request, the "Start review" button is highlighted as the primary button for the text area:

![image](https://user-images.githubusercontent.com/122987084/222409249-e60508a3-b78c-482d-b8cf-f2cab5b4811b.png)

However, when pressing Ctrl+Enter on the keyboard, it is interpreted as pressing the "Add single comment" button.

The biggest issue here is that the "Add single comment" button **immediately** submits the comment. There is no way to undo this, whereas accidentally starting a review does not immediately send something to the PR author, and thus the review can be cancelled at a later time without bothering anyone, in case it was started by accident.

### Gitea Version

1.19.0+dev-649-g2093ca517

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Self-built from Git

### Database

None

**Comment by wxiaoguang** [comment]
This behavior comes from 

* #19729

Why the Ctrl+Enter doesn't trigger the default primary button: because in the review form, users might want to approve the PR, they might just want to leave a comment.

I agree to improve the UX, while some details could be fine-tuned and considered together.

![image](https://user-images.githubusercontent.com/2114189/222415822-4d2ed3ce-cc09-4512-9817-95d282ed89d0.png)

**Comment by wxiaoguang** [comment]
Quickly go through the code again, making the "Start Review" button as the default action seems not an easy task (not just minutes, but maybe hours), maybe that's the reason why I didn't touch them last time when I added the Ctrl+Enter support .... I can still see my comment for `name="is_review" value="true"` in code 😂

**Comment by wxiaoguang** [comment]
Please test this fix:  Make Ctrl+Enter submits pending comment (starting review) instead of submitting a single comment #23245
