### ISSUE TITLE
[proposal] Create a RC1 for 1.2.0 and release/v1.2 branch

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#2329]
We could create the release/v1.2 branch and pre-release a rc1. We could continue work on future release on master and backport fix for 1.2.0 final version?

These would ease the process of the final release by fixing the changes and keep work to get done in master.

**Comment by lunny** [comment]
Sound reasonable. Any idea? @bkcsoft @appleboy @andreynering @lafriks

**Comment by appleboy** [comment]
LGTM.

**Comment by bkcsoft** [comment]
Yeah, we'd end up "backporting" to the stable-branch (RC2 etc), but it might help with getting stable releases out more often

**Comment by lcges** [comment]
I think so too.
I already see that future version 1.3 will have the same end as current version 1.2
This is a solution to current and future problems.

**Comment by lcges** [comment]
My proposal for future development is:
* Adding a few changes to the new version (currently too many changes, because there are so many bugs)
* Frequent issuing large version (1.1, 1.2, 1.3 ...)
* Milestones close in up to 200 issues
* Bug fixes to version (x.x.1, x.x.2, x.x.3 ...)

A few things are already well run. But you need to improve product releases.

I invite you to open discussion and give your solution.

P.S. Thanks to all creator and co-creator for such a heavy and good project! Together we can do more!

**Comment by sapk** [comment]
Releasing more often large version also limit the work of backport.

We could also start thinking of v2 and what breaking change we would like to do. (allready have some here : https://github.com/go-gitea/gitea/milestone/5)

**Comment by lunny** [comment]
branch release/v1.2 has been created.

**Comment by sapk** [comment]
@lunny thx

**Comment by ptman** [comment]
So the branch and rc1 have been made? Is this done?

**Comment by lunny** [comment]
Yes, you are right!
