### ISSUE TITLE
[Feature] File preview

### ISSUE THREAD

**Issue by TimerWolf** [go-gitea/gitea#23579]
### Feature Description

When you use the web interface, why is it not possible to have preview of a new file that is created in the repository?

You can do it with already created files that you edit but not with new files and i find this very strange, it would be very useful for lets say is you create a new "markdown" file.

`Repository -> Add File -> New File`

But the preview tab is missing

**Comment by silverwind** [comment]
Preview Tab should be there for at least Markdown.

Also see https://github.com/go-gitea/gitea/pull/23333 which touches these parts.

**Comment by brechtvl** [comment]
The Preview tab is not there for New File at all, only for Edit File. Editing a `.txt` file and renaming it to `.md` also does not make a Preview tab appear.

I had a quick look, and there seem to be two things to fix:
* Make the preview tab visible for `IsNewFile` in `templates/repo/editor/edit.tmpl`
* Run the previewable file extensions detection in `createCodeEditor` after editing the file name, not only on page load.

I won't have time to submit a proper fix in the next few days, anyone feel free to take over. Otherwise I'll get to it later.
