### ISSUE TITLE
MySQL database issue after update to version 1.19.0

### ISSUE THREAD

**Issue by dververis** [go-gitea/gitea#23589]
### Description

After the update to version 1.19.0 I get the following bug
`[mysql] 2023/03/20 12:19:16 packets.go:37: unexpected EOF`

Due to the database migration, a rollback to version 1.18.x is not possible.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker Linux Debian

### How are you running Gitea?

- Docker with image gitea/gitea:latest 
- MySQL / MariaDB in version 10.6.10

### Database

MySQL

**Comment by wxiaoguang** [comment]
It needs more clues for the issue report.

> After the update to version 1.19.0 I get the following bug

Have you fully upgraded with success? Have you ever accessed the running 1.19 server?

> [mysql] 2023/03/20 12:19:16 packets.go:37: unexpected EOF

When does this log appear? What's the context? Does it keep appearing and stopping the server, or it just appears randomly?


----

If you keep seeing the error log, I guess it's caused by some misconfiguration, which makes Gitea can not communicate with your MySQL server.

**Comment by wxiaoguang** [comment]
> The error log appears at every restart of the container.

Do you mean that your Gitea server doesn't start because of this error? Could you check whether your docker related files are correct ,and whether the MySQL could be accessed from Gitea container?

**Comment by dververis** [comment]
This is my more or less complete log from the starting of gitea

`Server listening on :: port 22.
Server listening on 0.0.0.0 port 22.
2023/03/20 21:10:43 cmd/web.go:105:runWeb() [I] Starting Gitea on PID: 17
2023/03/20 21:10:43 ...g/config_provider.go:30:deprecatedSetting() [E] Deprecated fallback `[server]` `LFS_CONTENT_PATH` present. Use `[lfs]` `PATH` instead. This fallback will be/has been removed in v1.19.0
2023/03/20 21:10:43 cmd/web.go:159:runWeb() [I] Global init
2023/03/20 21:10:43 ...g/config_provider.go:30:deprecatedSetting() [E] Deprecated fallback `[server]` `LFS_CONTENT_PATH` present. Use `[lfs]` `PATH` instead. This fallback will be/has been removed in v1.19.0
2023/03/20 21:10:43 routers/init.go:118:GlobalInitInstalled() [I] Git Version: 2.38.4, Wire Protocol Version 2 Enabled (home: /data/gitea/home)
2023/03/20 21:10:43 routers/init.go:119:GlobalInitInstalled() [I] AppPath: /usr/local/bin/gitea
2023/03/20 21:10:43 routers/init.go:120:GlobalInitInstalled() [I] AppWorkPath: /app/gitea
2023/03/20 21:10:43 routers/init.go:121:GlobalInitInstalled() [I] Custom path: /data/gitea
2023/03/20 21:10:43 routers/init.go:122:GlobalInitInstalled() [I] Log path: /data/gitea/log
2023/03/20 21:10:43 routers/init.go:123:GlobalInitInstalled() [I] Configuration file: /data/gitea/conf/app.ini
2023/03/20 21:10:43 routers/init.go:124:GlobalInitInstalled() [I] Run Mode: Prod
2023/03/20 21:10:43 routers/init.go:125:GlobalInitInstalled() [I] Gitea v1.19.0 built with GNU Make 4.3, go1.20.2 : bindata, timetzdata, sqlite, sqlite_unlock_notify
2023/03/20 21:10:43 ...dules/setting/log.go:331:initLogFrom() [I] Gitea Log Mode: File(File:info)
2023/03/20 21:10:43 ...dules/setting/log.go:337:initLogFrom() [I] According to the configuration, subsequent logs will not be printed to the console
[mysql] 2023/03/20 21:10:44 packets.go:37: unexpected EOF
[mysql] 2023/03/20 21:10:47 packets.go:37: unexpected EOF
`

The docker related files are in the correct folder, the app.ini is unchanged and the database is reachable (ping) by the gitea container.

Sorry for my late answer and thanks again for the support

**Comment by wxiaoguang** [comment]
> "According to the configuration, subsequent logs will not be printed to the console"

You need to share other logs in your log files, because you didn't make Gitea to output the log to console, so many logs can't be seen fro `docker logs`


> The docker related files are in the correct folder, the app.ini is unchanged and the database is reachable (ping) by the gitea container.

"ping" doesn't mean MySQL is accessible. For example, if your MySQL isn't running on the port (or using wrong port), you can ping but will get `unexpected EOF` error. You could try to use `apk update && apk add mysql-client` in your  Gitea container, to use a mysql client to test whether the MySQL server can be accessed by Gitea's database config.

----

I guess the problem is highly (99%) related to MySQL server setup & MySQL config in app.ini.

**Comment by dververis** [comment]
I switched to the official mariadb image, imported the old database and now it is working again.
Can't explained why
