### ISSUE TITLE
Wrong unicode char reporting.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#23682]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/81045/227459288-57f4a04a-c5c2-47bb-9d33-5b5213f107b5.png">

**Comment by wolfogre** [comment]
It is a Chinese unicode `’`, my typo.

**Comment by silverwind** [comment]
I agree, this detection is still far too agressive. It should only warn on actual suspicious stuff, like RTL characters and such, not "uncommon" punctations.

**Comment by wxiaoguang** [comment]
Also agree that "the detection is too aggressive"

At least, I think we can make the detection skip the Markdown/HTML/XML/etc types. That detection only makes sense for source code files.

**Comment by silverwind** [comment]
I would prefer a solution that adds a config option `ui.CHARACTER_HIGHLIGHT` that triggers on certain character classes:

1. `bidi`: Nefarious BIDI characters like [RTL Override character](https://unicode-explorer.com/c/202E). I think [this list on Wikipedia](https://en.wikipedia.org/wiki/Bidirectional_text#Table_of_possible_BiDi_character_types) is accurate.
2. `ambigous`: Also highlight ambiguous characters like non-standard spaces and puncations.

The default should be `bidi` to cover CVE-2021-42574, but users could also set it to empty string to disable the checking completely.

**Comment by wxiaoguang** [comment]
I think it worries too much.

https://github.com/wxiaoguang/playground/wiki/test-202e

```
$ xxd playground.wiki/test-202e.md
00000000: 6162 63e2 80ae 7879 7a                   abc...xyz
```

![image](https://github.com/go-gitea/gitea/assets/2114189/2c412917-0835-4db8-bc0f-b6f91360a36d)

**Comment by silverwind** [comment]
GitHub only does it for code. I guess that is where it matters the most. So we could do two options:

```ini
[ui]
CHARACTER_HIGHLIGHT=bidi,ambiguous
CHARACTER_HIGHLIGHT_INCLUDE_MARKUP=false

**Comment by wxiaoguang** [comment]
> GitHub only does it for code.

Nope. For markdown in code:

![image](https://github.com/go-gitea/gitea/assets/2114189/7f427096-7a83-4f29-aedf-35a716714b14)

GitHub only does it for "source code", not for rendered contents.

**Comment by silverwind** [comment]
Yeah, that's what I meant, source code, e.g. stuff that renders in a monospace font 😉.

**Comment by jirutka** [comment]
> It is a Chinese unicode ’, my typo.

No, it’s not; `U+2019` (’) is [Right Single Quotation Mark](https://www.compart.com/en/unicode/U+2019). This is the true (typographic) single quotation mark, unlike `U+0027` [Apostrophe](https://www.compart.com/en/unicode/U+0027) (').

This got my attention because of [this](https://github.com/jirutka/setup-alpine/pull/13) nonsensual and stupid PR  in one of my repositories replacing correct characters with their ~~plain~~poor ASCII alternatives. Please remove this stupid “feature”.

**Comment by techknowlogick** [comment]
@jirutka there is a a recently merged config option to disable this highlighting. As for removing it (or disabling by default), due to it being a claimed security issue it is required to have, otherwise we risk having a CVE opened that'll apply to all versions (and ones in the future). If that happens then that prevents many people from running the software (there are many places that can't run software with known CVEs regardless of context, sometimes this is legislated by law too).

**Comment by wxiaoguang** [comment]
You could set this option: `[ui].AMBIGUOUS_UNICODE_DETECTION=false` (Gitea >= 1.21.3)

![image](https://github.com/go-gitea/gitea/assets/2114189/cfb78f8e-dbe1-43bc-8e6e-890bef5a13d3)
