### ISSUE TITLE
Edit File button during PR review

### ISSUE THREAD

**Issue by codetorex** [go-gitea/gitea#23848]
### Feature Description

We love using Gitea and it would be great that if we could edit files during pull request reviews. As a reviewer I go to "Files Changed" tab on a pull request, and it would be great if there is a button called "Edit File" next to "View File" button. Upon clicking on it could be either;
* Convert file view in current page (Files Changed tab) to editable one similar to commenting and it will create a commit with changes upon save
* Show a popup that has editable file in it and that will create a commit with file changes
* Go to existing edit file page in the source branch of the PR where saving the file will create a commit

This would save time on fixing small typos etc encountered rather than going back and forth between people or pulling the entire branch, changing and pushing :)

**Comment by silverwind** [comment]
I think there was some recent work on this.

**Comment by lunny** [comment]
We should have a new mode for changed files review, that is `all changed files will be loaded in the left tree and the right place will only show the chosed file. So that only one file will be displayed in the right panel. Then when click edit button, we can replace the whole patch for this file as an edit box.

**Comment by silverwind** [comment]
Actually I think I'm wrong, there was no recent work. I misread the request 😉
