### ISSUE TITLE
Sort dropdown flashes when loading issue/pr list

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#23857]
### Description

When viewing the issue or pr list, there is a short flash of the sort dropdown content.

![](https://user-images.githubusercontent.com/115237/229263620-27056063-e1df-407e-ae9a-b4d77d95f368.gif)

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by silverwind** [comment]
1.19 is not affected, so this is a very recent regression.

**Comment by wxiaoguang** [comment]
I guess it's related to 
* https://github.com/go-gitea/gitea/pull/23806 

the initial purpose is for:
* #23625

let me see

**Comment by wxiaoguang** [comment]
Removing the "left" style of the "menu" resolves the flash. If you don't mind, I will make the fix in #23856 together, to save time.

**Comment by silverwind** [comment]
Don't mind, but there might be more similar cases, should grep for them.

**Comment by silverwind** [comment]
Actually, I do mind a bit as there is no relation, so separate PR might be good :)

**Comment by wxiaoguang** [comment]
> Don't mind, but there might be more similar cases, should grep for them.

Nope, there won't. The whole story is:

Since the popup position calculation is not stable, so I think it's good to make the "Sort" menu always have the "left" position. However, the "left" style have "display: flex", it should be used with "hidden" together. I didn't find the flash because my window is not large enough during my test. To make things simple, remove the "left" style.

So, it's a simple fix. I just pushed ... and I will update the description.
