### ISSUE TITLE
Add a user-readable changelog

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#2404]
The current changelog for 1.1-rc1 is very long. I think that it might be to much for "normal" users. Is it possible to add a summary at the beginning for the "key" features and bug fixes. Because "normal" users won't understand what currently changed.

**Comment by lunny** [comment]
Normally, we will post a blog to summarize the changelog.

**Comment by strk** [comment]
I agree the CHANGELOG section should be more concise.
In particular I noticed many items referring to OpenID which
should instead appear only once (as OpenID support is new
in this release).

Jonas Franz: it'd be easier if you would send a PR, targetting
the 1.2 branch.

**Comment by bkcsoft** [comment]
Changelog should never be edited after it's been merged other that to remove old versions that are no longer tracked 🙁

**Comment by bkcsoft** [comment]
Also, listing the PRs that went in makes it easier to find what introduced a bug

**Comment by thehowl** [comment]
I think that before the release we should probably go over everything and write a "Release Highlights" section, at least on the blog post. This way we can list the most significant changes; perhaps something like [Godot's changelog](https://godotengine.org/article/godot-reaches-2-1-stable). So that users don't just sigh and say "ugh, gitea wants me to update again", but rather "oh look, Gitea got an update!"

**Comment by lafriks** [comment]
@thehowl it would be nice but we need someone who volunteers to write such blog posts as ours are quite boring as you know ;)

**Comment by thehowl** [comment]
Well then, I'll just have to get typing as the 25th approaches :)
