### ISSUE TITLE
Accept avatars in .svg format

### ISSUE THREAD

**Issue by brobr** [go-gitea/gitea#24264]
### Feature Description

Related to https://github.com/go-gitea/gitea/issues/24263, and initially raised for `.webp` format at [Codeberg](https://codeberg.org/Codeberg/Community/issues/996), also avatars in `.svg` format are not accepted/recognized as an image. It would be nice if that format gets accepted as well.

Thanks.

**Comment by delvh** [comment]
The problem is: While it might seem like exactly the same feature, it is **completely** different:
`webp` is a "normal" image that works with the `<img>` tag.
`svg`s however need their own tag (`<svg>`).
So, this would need a complete rewrite of the logic.
That is such a huge change that I don't think the benefit is worth the effort.
It's far easier to require users to convert their svgs beforehand.
So, from my side this is a weak reject.
I don't know how other maintainers see it.

**Comment by yardenshoham** [comment]
I think you can do `<img>` with SVG https://caniuse.com/svg-img

**Comment by delvh** [comment]
Okay, TIL.
In that case, my comment above is now outdated and no longer a blocker.

**Comment by wxiaoguang** [comment]
Since JS code could be embedded in SVG, the security concern should be addressed first.

**Comment by silverwind** [comment]
Duplicate with https://github.com/go-gitea/gitea/issues/8707. The challenge with SVG is security as SVGs can contain scripts.
