### ISSUE TITLE
Feishu webhook of issue update not linking to full issue url

### ISSUE THREAD

**Issue by xgdgsc** [go-gitea/gitea#24368]
### Feature Description

I hope webhook of issue update include issue url. I find it strange commit webhook has URL while issue webhook notifications has no URL, which I usually would use more frequently,

**Comment by xgdgsc** [comment]
I see only
```
{
  "msg_type": "text",
  "content": {
    "text": "#2 tst1\r\n[org/repo1] Issue closed: #2 tst1 by user1"
  }
}
``` 
when using Feishu webhook.

**Comment by techknowlogick** [comment]
@xgdgsc which version of gitea are you using?

**Comment by xgdgsc** [comment]
Just downloaded latest release 1.19.3

**Comment by Makonike** [comment]
I will fix this later.

**Comment by Makonike** [comment]
hi @xgdgsc, I have submitted a Pull Request to fix this issue. Since the official documentation states that custom bots do not support hyperlink functionality, simply adding it without making some formatting changes would result in an unappealing output. Therefore, I have modified the formatting of the output. You can try using a custom bot. I have previously written one that you can refer to. The repository is located here: [webhook2group](https://github.com/asoul-fanclub/webhook2group)

**Comment by xgdgsc** [comment]
The commit notification message already has the url, which is fine and clickable. So I think just adding the url to the text would be fine? I' ve never used any custom bot before, just used the webhook bot.

**Comment by Makonike** [comment]
> The commit notification message already has the url, which is fine and clickable. So I think just adding the url to the text would be fine? I' ve never used any custom bot before, just used the webhook bot.

Yeah, my PullRequest fix this.
