### ISSUE TITLE
no documentation on how to configure deploy keys

### ISSUE THREAD

**Issue by GDMTT** [go-gitea/gitea#24375]
### Description

Hi, 

I can't find anything in the Gitea documentation on how to configure Deploy keys. I'm specifically looking for windows related instrucitons.

Thank you. 

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.39.1.windows.1

### Operating System

Windows Client

### How are you running Gitea?

K3s install using this guide: https://github.com/kurokobo/awx-on-k3s/tree/main/git

### Database

None

**Comment by wxiaoguang** [comment]
The UI could be slightly different, but it's indeed on the setting page.

![image](https://user-images.githubusercontent.com/2114189/234771540-9656fb9b-ad37-48e8-b141-f9156ece5bab.png)

**Comment by dpedu** [comment]
Issues aren't documentation, this should stay open.

**Comment by wxiaoguang** [comment]
@dpedu could you help to propose a PR for updating the document?

**Comment by dpedu** [comment]
@wxiaoguang I cannot as I am unfamiliar with the feature in question, because it is undocumented and I am unfamiliar with gitea's internals.

**Comment by wxiaoguang** [comment]
From my side, I don't see anything unclear for it. This feature just exists, and it is in the top-level menu on the setting page. Just like "Branches", "Tags", there is no document either, there is no document for "change avatar" or "change email" either.

I agree that document could be written for everything, but I also agree if a feature is clear, then it can be used by intuition without document.

If you think "deploy key" needs a document, please help to elaborate about how to write a better document for it, since the project is open source and crowd-contributed, I will be happy to review.
