### ISSUE TITLE
Global system to manage "labels"

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#2439]
Hello.
My suggestion is to add to your account the ability to create labels.
Now there is poor control over labels, should be more control.
This will make it easier to work with future projects in Gitea. This will make it easier to manage the color of your labels. It will also make it easier to keep your label in order.

**Comment by lafriks** [comment]
You can already add additional system-wide predefined label sets in custom directory

**Comment by lcges** [comment]
I know, but there is little control over it.
How to add your own labels?

**Comment by lafriks** [comment]
You can add additional labels one by one in repository

**Comment by lcges** [comment]
I know exactly. But I'm about to have the option to change all the labels in one place.
For example, I want to synchronize several projects. I do not have to enter them one by one, just do it globally.

**Comment by kifirkin** [comment]
It's a good idea to manage organisation-wide label set somewhere inside org interface.
the main purpose of this not to initialise predefined label set, but bulk edit it inside of many repositories

**Comment by lafriks** [comment]
sure, it just was not clear what exactly you wanted that's why I asked 👍

**Comment by lcges** [comment]
cool.
I will try to draft next week

**Comment by lunny** [comment]
organisation-wide labels maybe usable.

**Comment by xak2000** [comment]
Also org-wide labels feature is usable because you can filter issues from several projects using these labels.

For example you want to concentrate on bugs now, and you don't care what project these bugs belong. These projects are related anyway. So you just click on `Bug` label and voila - you have all issues from all projects of selected org, labeled with this label, on one screen!

Or you have some subsystem (module) which span several projects in your org. You create a label for it and assign this label to all issues realted to this functionality. Then when you want to see all issues for this functionality (no matter what project they from) - voila.

**Comment by mrsdizzie** [comment]
There are organization wide labels in Gitea now
