### ISSUE TITLE
`scan: bufio.Scanner: token too long` when clicking actions sections

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#25451]
### Description

1. Open https://gitea.com/gitea/gitea-docusaurus/actions/runs/133/jobs/0
2. Click any section in the run
3. Nothing happens, stays stuck loading forever and logs an error in the console

Error should be made visible in UI, either inline at the loader or with a [toast](https://github.com/go-gitea/gitea/pull/25449).

<img width="771" alt="Screenshot 2023-06-22 at 21 10 02" src="https://github.com/go-gitea/gitea/assets/115237/be32b824-91d1-49b4-843b-ec4bed85d6b7">

### Gitea Version

1.20.0+dev-999-g8d7893e81

**Comment by wxiaoguang** [comment]
The ReadLog code doesn't handle a line which is longer than 65k bytes gracefully.

Ideally, the "token too long" error should be ignored and continue reading the logs.

**Comment by wolfogre** [comment]
> The ReadLog code doesn't handle a line which is longer than 65k bytes gracefully.

No, it doesn't need to. The line will be truncated if it is too long when written.

https://github.com/go-gitea/gitea/blob/4011821c946e8db032be86266dd9364ccb204118/modules/actions/log.go#L144-L149

I think the real reason is that the log file is broken. It may be related to the malfunction of NFS on gitea.com a few days ago.

I logged on to the machine and downloaded the original log files:

<img width="1317" alt="image" src="https://github.com/go-gitea/gitea/assets/9418365/02599d2f-1964-46a7-a748-405e21b285c6">

And all is well after re-run.

**Comment by wolfogre** [comment]
I agree that errors should be visible in the UI. But I have no idea how to do that, so I will remove self-assignee.

**Comment by wxiaoguang** [comment]
How many "nil" chars there? Could there be a bug in DBFS code?

**Comment by wolfogre** [comment]
> How many "nil" chars there? Could there be a bug in DBFS code?

The number of "nil" chars doesn't really matter. Since the total file size matches the file size recorded in the DB, and the "nil" chars end at the beginning of a line, it couldn't be that the DBFS lost some blocks.

It seems like it opened a non-existent file in DBFS , seek and write, but I have no idea how it could have happened. I will continue to track this bug to see if it happens again.

**Comment by wolfogre** [comment]
I confirmed that it is a bug and figured out the way to reproduce it. It's not related to DBFS or FS malfunction, but the logic of writing action logs.

I'll fix it.
