### ISSUE TITLE
Cannot access /users/username/tokens endpoints

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#25511]
### Description

I created an API token (with scopes "all").

That token permits me access to most of the API (in swagger, for simplicity). Successful example, to show the app is working, my token is valid, etc.:
- request
  ```console
  curl -X 'GET' \
    'https://example.com/api/v1/user' \
    -H 'accept: application/json' \
    -H 'Authorization: token ...token...'
  ```
- response
  ```console
  {
    "id": 1,
    "login": "username",
    ...
  }
  ```

But none of the `/users/username/tokens/` endpoints work.

- Delete token:
  - request
    ```console
    curl -X 'DELETE' \
      'https://example.com/api/v1/users/username/tokens/...token...' \
      -H 'accept: application/json' \
      -H 'Authorization: token ...token...'
    ```
  - response
    ```console
    {
      "message": "auth required",
      "url": "https://example.com/api/swagger"
    }
    ```
- List tokens:
  - request
    ```console
    curl -X 'GET' \
      'https://example.com/api/v1/users/username/tokens' \
      -H 'accept: application/json' \
      -H 'Authorization: token ...token...'
    ```
  - response
    ```console
    {
      "message": "auth required",
      "url": "https://example.com/api/swagger"
    }
    ```
- etc.

I noticed that this problem is [not just me](https://discord.com/channels/322538954119184384/322538954119184384/1103847720516599919).

### Gitea Version

1.20.0-rc2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

linux

### How are you running Gitea?

docker

### Database

SQLite

**Comment by acquleo** [comment]
I love gitea but the permission mechanism is a pain.
I tried to integrate some functionalities of gitea in another website ( tried to make a friendly interface to upload generic artifacts).
At first I tried to allow the user to authenticate using gitea oauth2 but I failed.
I've failed at the beginning because oauth2 API of gitea doesn't support cors, i tried to add headers using a reverse proxy in front of it.
Then I found a bug that was present in gitea 1.19 and tried with 1.20.
At the end of those tries I gave up and decided to use the access token api to manage user authentication.
Then I discovered that even using a valid access token with the right scopes I'm unable to revoke a token created by the same user.
This is the limitation you found, eventually I give up.

**Comment by lunny** [comment]
The problem comes from https://github.com/go-gitea/gitea/blob/83640c449eb6a1b31bc09b1372cc156d114804f8/routers/api/v1/api.go#L687 which limited all `/tokens` must enter the password.

**Comment by acquleo** [comment]
> Hi @lunny.
> 
> When I use these endpoints, I pass the API token: `-H 'Authorization: token ...token...'`.
> 
> I just tried basic auth for those endpoints `-H 'Authorization: Basic ...secret...'` but that also doesn't work:
> > Only signed in user is allowed to call APIs.
> 
> Maybe I'm not understanding you... sorry I'm not a go developer... :-)

You have to use Basic (username):(password)

**Comment by acquleo** [comment]
> I'm doing it via the swagger interface, which does it that way. And it's [correct](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication), the `username:password` is base64 encoded to give that string.
> 
> But regardless, it doesn't work either. So I don't understand the comment above by lunny?
> 
> Does it work for you @acquleo?

Yes, it's working for me.

**Comment by acquleo** [comment]
I'll try again in a couple of your, at work

**Comment by lunny** [comment]
> 

I think it was by design but we can have a new discussion about it here.

**Comment by acquleo** [comment]
in reality you don't need to be an "admin", regular user can do that but only using basic authentication.
