### ISSUE TITLE
Nuget Package Explorer only loads several nuget packages

### ISSUE THREAD

**Issue by pmandalka** [go-gitea/gitea#25564]
### Description

I have uploaded about 2900 Nuget packages to a local installed gitea instance, which worked fine. I can see all packages in the package list of the organisation in the Web-UI an also search for specific Packages.
But if I try to load all Packages e.g. in Visual Studio or in nuget Packages Explorer, i only some several of these packages:
![image](https://github.com/go-gitea/gitea/assets/93120661/c33c6f7d-44f5-4493-973d-3ed5e40de5a3)

In gitea Web-UI it looks like this:
![image](https://github.com/go-gitea/gitea/assets/93120661/b2322a34-8fa6-4ec6-aa33-e6dd6e13f408)

Anybody knows this issue?
I have not testet it on try.gitea.io.

### Gitea Version

1.20.0+rc2-12-g102dcfa3a

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Docker on Debian

### How are you running Gitea?

As docker image

### Database

PostgreSQL

**Comment by DaKaLKa** [comment]
Cannot test on try.github.io - no Package support activated.

**Comment by KN4CK3R** [comment]
I was aware of that problem as it's related to #23191. The problem is the client calling the "list" endpoint with the parameters `query?q=&skip=0&take=15`. The `take` parameter specifies how many packages should be returned. Currently this count is passed into the function which queries the database for the package **versions**. This method finds `take` package versions while it should find `take` packages. I could not build a performant sql query which limits the count of packages but returns all available package versions of these packages.

**Comment by pmandalka** [comment]
Ok, I see the SetSessionPagination set the limit on the versions instead of the packages.

In SQLite the needed query with take = 1 and Skip = 0 would be - so that the limit is executed on the packages and not the pacakge_version table.
`
SELECT * FROM 
(SELECT * 
FROM package
LIMIT 1 OFFSET 0) t1 
INNER JOIN  
(SELECT * FROM package_version) t2 ON
t1.id = t2.package_id
`

But I have no experience in xorm and if it's possible to build such a query with the engine.

**Comment by KN4CK3R** [comment]
I looked into the problem yesterday and will create a PR later which fixes the problem. 👍 

I created 50 packages with 20 versions each and the NuGet Package Explorer works fine now:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/1d987962-f59e-4a9a-8b77-67653458fe49)
