### ISSUE TITLE
Link to PR on project board broken

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#25954]
### Description

On the project board (e.g. https://GITEA/MyCompany/-/projects/2) we can have issues which are linked to a pull request (PR), e.g.:

![image](https://github.com/go-gitea/gitea/assets/2737900/3f362b65-705c-4dc0-8c66-1e07a54cb74d)

Problem the PR link:
Points to:
https://GITEA/pulls/502
where it should point to:
https://GITEA/MyCompany/MyProject/pulls/502

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No, because I cannot create a company nor a project board there.

### How are you running Gitea?

Windows installation

### Database

None

**Comment by delvh** [comment]
Contained in #23318 already:
> If you click on the PR that closed an issue inside an org-wide project, you get redirected to $URL/pull/$ID instead of $URL/$USER/$REPO/pull/$ID

**Comment by LukeOwlclaw** [comment]
@delvh Okay, so this is a duplicate. Thanks for pointing out.

So this issue should already be fixed by PR https://github.com/go-gitea/gitea/pull/23325, right?
But "[jolheiser](https://github.com/jolheiser) merged 3 commits into [go-gitea:main](https://github.com/go-gitea/gitea/tree/main) from [yp05327:fix-project-icon-and-link](https://github.com/yp05327/gitea/tree/fix-project-icon-and-link) on Mar 6"

So shouldn't this fix be already included in version 1.20.0?
