### ISSUE TITLE
Weird Czech translation of the web app

### ISSUE THREAD

**Issue by V-Z** [go-gitea/gitea#25991]
### Description

There are some very weird translations of Czech web interface. It seems it was checked by @j123b567 some years ago, but bit decayed since then.

At least strings

> Jednoduše spusťte binárku pro vaši platformu

* It's at least bit not elegant, although possible.

> běží všude, kde Go může kompilovat

* "It runs everywhere, where Go can compile". Really so? I'm not sure what source should be here. I suppose it can run everywhere, where You can *run* Go? If so, then IMHO at least *běží všude, kde můžete spustit Go*.

> Nestyďte se být přispěvatel

* "Don't be shame to be contributor". Well, to me it doesn't seem really welcoming. It might be personal problem as I dislike this style. Does it mean to contribute financially or by any coding? More logic would be to me something like "Contribute to Gitolite" (and then by what), e.i. *Přispějte Gitolite*.

* These three look like poetry translated by Google Translate.

> Požadavky na natažení

* Ha, ha, it was used in [Czech translation of Pro Git](https://knihy.nic.cz/files/edice/pro_git.pdf), but it's not really used in practice, it sounds weird. Everybody I know just use "pull request" as technical term.

> Úkoly

* In user menu, *Úkoly* means rather *tasks* than *issues*, but it's usable. If it should be primarily for bugs, *Chyby* (sg., pl. is *chyba*) would IMHO be better.

are bit weird...

### Screenshots

Default page before login ![Default page before login](https://github.com/go-gitea/gitea/assets/6032665/a21f0a27-0906-4ab0-af94-51a92bf4798b) (e.g. https://try.gitea.io/ if You have browser running with Czech locales) and user menu after login 
![User menu after login](https://github.com/go-gitea/gitea/assets/6032665/fcbbbca4-cf39-4502-903c-d06c0e4fa5ff)

### Gitea Version

v1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 115

**Comment by j123b567** [comment]
Just general ideas
 - you should translate the meaning of the source English. If the source English is wrong, could you fill PR to fix the source English first? As translators, we can't just translate one text with entirely different meanings just because we don't agree with the source English.
 - there is a blurry line between what to translate and what not. There is only one rule, it must be consistent across the whole application. At the time I started filling in some translations, it was easier to continue with some terms and focus on 100% translation rather than retranslating everything from the past.
 - be aware of collisions of meaning. There are so many terms with overlapping translations but you should choose the right translation so it does not overlap with another term.

To your questions:
 - I see some effort to translate `pull request` in multiple places but we can definitely use the original English term. There just needs to be somebody, who will do the hard work and systematically renames all occurrences. Volunteer? @V-Z ? ;-) 
 - `Issue` is harder to translate. You can take inspiration from some other issue trackers translated into Czech. `Chyba`/Bug is not the right translation.  It is just one type of issue. I didn't find the right word in Czech yet but it is definitely not `Chyba`.
 - Other translations can be corrected/proposed directly in crowdin, as lunny mentioned.

**Comment by jirislaby** [comment]
> > Jednoduše spusťte binárku pro vaši platformu
> 
>     * It's at least bit not elegant, although possible.

Note the Czech language dictates to use "svou", not "vaši".

> > Nestyďte se být přispěvatel
> 
>     * "Don't be shame to be contributor". Well, to me it doesn't seem really welcoming. It might be personal problem as I dislike this style. Does it mean to contribute financially or by any coding? More logic would be to me something like "Contribute to Gitolite" (and then by what), e.i. _Přispějte Gitolite_.

And at the very least "přispěvatelem" (7th case). The first case "přispěvatel" sounds very weird. But "Přispějte, prosím." would sound a lot better. 

> > Požadavky na natažení
> 
>     * Ha, ha, it was used in [Czech translation of Pro Git](https://knihy.nic.cz/files/edice/pro_git.pdf), but it's not really used in practice, it sounds weird. Everybody I know just use "pull request" as technical term.

I asked bard and chatgpt. Apart from "pull request", they suggest also "Požadavek na sloučení" and "Pull požadavek". Both sound better, still the English term "pull request" has settled in Czech among programmers. I hesitate which to use. But definitely not "Požadavky na natažení".

**Comment by jirislaby** [comment]
>     * `Issue` is harder to translate. You can take inspiration from some other issue trackers translated into Czech. `Chyba`/Bug is not the right translation.  It is just one type of issue. I didn't find the right word in Czech yet but it is definitely not `Chyba`.

Bard says:

> The Czech translation of GitHub's "issue" is "problém". It can also be translated as "záležitost", "zádrhel", or "potíž".

ChatGPT:

> The Czech translation of GitHub's "issue" is "problém" or "issue". While "problém" is a direct translation, it's also common to use the English term "issue" in the context of software development and version control systems like GitHub. English technical terms are frequently used in the Czech tech community.

I think ChatGPT is right ;).

**Comment by V-Z** [comment]
Thank You, @j123b567 for prompt reaction. I got familiar with Gitea literally yesterday (and I think @jirislaby also:-) and we bit disliked the translation mentioned above. Which also means I don't have full overview which strings are where. As the languages are not 1 to 1 fitting, picking correct term is sometimes hard. Interestingly, I don't recall any fully issue tracker (fully) translated into Czech, so You have hard times being pioneers. ;-) Regarding *pull requests*, from my experience it's used as *terminus technicus* with Czech grammar applied to it (similarly with commits and some other terms). For this specifically, I see 112 occurrences (which seems a lot) in https://github.com/go-gitea/gitea/blob/main/options/locale/locale_cs-CZ.ini, but it's without context. Crowdin doesn't let me see without account, which is bit weird. So, for *pull request*, I'd suggest either no translation or *pull požadavek* (not *sloučení* as it'd collide with *merge*). For *issue* in context of menu I think *problém* would be better.

**Comment by lunny** [comment]
Closed as these comments and discussion should be placed on crowdin.
