### ISSUE TITLE
about the router

### ISSUE THREAD

**Issue by jianjianxu** [go-gitea/gitea#26005]
### Feature Description

When I am not logged in, I open the webpage "https://gitea.com/user/login?redirect_to=https://gitea.com/work/myjob/issues/15", after logging in, it will redirect normally.

But, when I am already logged in, I open the webpage "https://gitea.com/user/login?redirect_to=https://gitea.com/work/myjob/issues/15", after logging in, I will be redirected to the homepage.

**Comment by lunny** [comment]
What's your suggestion?

**Comment by cassiozareck** [comment]
Hello @lunny, @wxiaoguang and @jianjianxu ! I suppose the right behaviour would be to redirect to the desired route in case he's logged in (in this case gitea.com/work/myjob/issues/15)

I suspect the issue lies in services/auth/middleware.go:

``` go
// Redirect to dashboard if user tries to visit any non-login page.
if options.SignOutRequired && ctx.IsSigned && ctx.Req.URL.RequestURI() != "/" {
	ctx.Redirect(setting.AppSubURL + "/")
	return
} 
```
This code redirects a logged-in user to the homepage if they try to access a route that requires sign-out. However, it doesn't consider the case where the user is trying to access the login page with a redirect_to parameter.

I think I will modify the middleware to account for the redirect_to case. I'll make a PR if it solve the issue

However, the checkAutoLogin function in routes/web/auth.go isn't being called. This function seems to handle the redirect_to paramater if user is signed in. Im new to codebase so I dont know if there's specific cases where it is suppose to get called

``` go
func checkAutoLogin(ctx *context.Context) bool {
	// Check auto-login
	isSucceed, err := AutoSignIn(ctx)
	if err != nil {
		ctx.ServerError("AutoSignIn", err)
		return true
	}

	redirectTo := ctx.FormString("redirect_to")
	if len(redirectTo) > 0 {
		middleware.SetRedirectToCookie(ctx.Resp, redirectTo)
	} else {
		redirectTo = ctx.GetSiteCookie("redirect_to")
	}

	if isSucceed {
		middleware.DeleteRedirectToCookie(ctx.Resp)
		ctx.RedirectToFirst(redirectTo, setting.AppSubURL+string(setting.LandingPageURL))
		return true
	}

	return false
}
```

**Comment by wxiaoguang** [comment]
Many thanks to @cassiozareck for addressing the problem.

@jianjianxu could you try it on try.gitea.io (eg: https://try.gitea.io/user/login?redirect_to=/issues ) to see whether #26105 works? I made some changes there because it seems that the "POST" method is not a must for this issue.
