### ISSUE TITLE
Error adding GPG Key

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#26102]
### Description

When I go to add my public gpg key at https://gitea.domain.rocks/user/settings/keys I'm getting this error:

> An error occurred:
>
> AddPublicKey, Error 1264 (22003): Out of range value for column 'expired_unix' at row 1

### Gitea Version

1.20.1

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### How are you running Gitea?

Official Docker container

### Database

MySql / MariaDB

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1524526/1c9e91fb-60c0-4132-bc38-d330db926fa5)

**Comment by techknowlogick** [comment]
Thanks for this report, could you share your **public** key that you uploaded?

**Comment by STaRDoGG** [comment]
@techknowlogick  Sure thing:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZLxUJhYJKwYBBAHaRw8BAQdAPC+7z3gBawAIuttYV4fbjwlgqBsC782r5TUP
8i9JDv20JUouIFNjb3R0IEVsYmxlaW4gPHN0YXJkb2dnQGdtYWlsLmNvbT6IkwQT
FgoAOxYhBBbsV4Q3umu57TrprgSKH0n69vOCBQJkvFQmAhsjBQsJCAcCAiICBhUK
CQgLAgQWAgMBAh4HAheAAAoJEASKH0n69vOCdmQBANo460PNWuxgd079E5eWsY/c
nX8xevEAP7UFkPzvOOckAP0SiTdae7kZUz6dLKuFopXyiayzNnYVfjYzfSd3twva
Bbg4BGS8VCYSCisGAQQBl1UBBQEBB0B6oqJZgzL5aDCn8nW+XBNQSQraYmr91BNS
xFVD5PWbEgMBCAeIeAQYFgoAIBYhBBbsV4Q3umu57TrprgSKH0n69vOCBQJkvFQm
AhsMAAoJEASKH0n69vOCkTgBAPtlGp4LsiI/qDSDkFyFYMvYb9P42c6RdxA8vqj9
xi5MAP96F64ZxRjYja3YfCHZaE6rowKcaIefQSml8o6twQGyAA==
=ZlkT
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by STaRDoGG** [comment]
Oops, just realized that I had forgotten that I was successful at switching the db from sqlite to my mariadb server. Updated the OP.

**Comment by STaRDoGG** [comment]
If it helps any, here's my table:

![image](https://github.com/go-gitea/gitea/assets/1524526/b09017d4-602a-4662-a460-4784e62977b8)

**Comment by lunny** [comment]
Maybe those columns should be `bigint` but not `int(11)`. How did you convert the database?

**Comment by STaRDoGG** [comment]
@lunny 

You the man. =)

Changed it to `bigint` and re-tried to enter my key and it worked. I wish I could remember exactly how I did the conversion but it was awhile ago. I vaguely think I might remember the Gitea docs had some sort of instruction how to do it?

 One questions, as I'm not the hugest SQL guru; when I go to change the column to `bigint` here:

![image](https://github.com/go-gitea/gitea/assets/1524526/963efd86-0184-4376-b310-2548409f4d3b)

and delete the "11" from the Length column, leaving it blank; then click Save, it ends up saving as `bigint(20)` rather than just 'bigint`. Any idea why? And is that fine, or?
