### ISSUE TITLE
Share SSH key between accounts

### ISSUE THREAD

**Issue by crabdancing** [go-gitea/gitea#26890]
### Feature Description

Currently, Gitea relies on the SSH key itself to figure out which account you're logging in as. This is something of a de facto standard with SSH git accounts, but it seems unnecessarily limiting. Since Gitea has an internal git server, there's in principle no reason we couldn't use the account name provided via SSH protocol have _multiple_ accounts share the same git key, and ID by git 'account name' instead of key. This significantly improves flexibility, when setting up nontrivial secure passwordless local development environments, allowing an intersection of resource access, with access authorization being denoted by being given a specific keypair.

**Comment by lunny** [comment]
I don't know how it works. Once two public keys matched, which user should we think it is doing?

**Comment by alxpettit** [comment]
If the user signs in as, e.g., `alice@git.something.com`, then you look for an account name exactly matching `alice`. For backward compatibility, if the SSH name is `git`, you revert to trying to match by key instead of by git name.

**Comment by lunny** [comment]
> if the SSH name is git, you revert to trying to match by key instead of by git name.
It's impossible from technique.

**Comment by CaiCandong** [comment]
@alxpettit I guess your question is, "How To Set Up Multiple SSH Keys on Your Computer"? 

https://betterprogramming.pub/how-to-set-up-multiple-ssh-keys-ae6688f76570

**Comment by amrsoll** [comment]
@alxpettit You should consider making multiple ssh keypairs instead of using a single ssh keypair to auth as 2 different users. It is fundamentally the opposite intent to using private-public encryption keypairs.

✔️  One user can have multiple ssh keys

❌ Multiple users share one ssh keypair

They are not 'git keys', and it is not a limitation of git (as you point out) but a limitation of the security scheme.

You could generate a new key pair for every user you choose to generate for your dev environment. By tweaking `.ssh/config`, you can create a host definition for each use case, using a different ssh key previously generated

```
Host git_user_a
    Hostname gitea.com
    IdentityFile ~/.ssh/id_user_a
    IdentitiesOnly yes
Host git_user_b
    Hostname gitea.com
    IdentityFile ~/.ssh/id_user_b
    IdentitiesOnly yes
```

You can then setup multiple remotes in git, each one would be pushing as a different user

```sh
git remote add origin git@git_user_a:myrepo.git
git remote add origin git@git_user_b:myrepo.git
```

Then do the git actions using the `-v` flag

```sh
git push -v git_user_a # push to gitea.com:myrepo.git using the ssh key ~/.ssh/id_user_a
```

See [StackOverflow](https://stackoverflow.com/a/11251797/11136955) for more info on how to setup the ssh config file and use it with git

**Comment by lunny** [comment]
I think this could be closed as it's impossible.

**Comment by alxpettit** [comment]
This is far from impossible, but okay...

**Comment by wxiaoguang** [comment]
> This is far from impossible, but okay...

If you think it is possible, you could try to write some code to implement it to see whether it is really possible at the moment.

**Comment by alxpettit** [comment]
For context, I am a NixOS user, managing dozens of systems, each of which have their own SSH keys. If I had a single SSH key per user account, per computer, I would multiply the keys by a factor of 4. Given that there's already 10 machines, and more being added to the cluster, the solutions posited here are frankly somewhat ridiculous. (Also a little condescending to assume I don't know how to use SSH.)

I can automatically generate a keypair for every user on every machine, and then write code specifically to pull the keypairs for every user on every machine that ought to have access to a specific git resource -- and then additionally make sure that's updated when keys expire -- but it seems much simpler to _just share the damn key_ -- as the user accounts in question all have the same security profile and trust level, and the multi-user security model is, frankly, dated and inapplicable. User accounts on machines set up like this _generally_ function less as secure boxes to protect users from each other, and more as profiles for managing diverging personal preferences.

The whole point of such an adaptable model is to, you know, _adapt_ the model. Enforcing a security scheme where it is nonsensical to do so does nothing but increase overhead and increase the likelihood that _something else_ will break the system.

I understand that perhaps Gitea is written into a corner on this one and it would be prohibitively difficult to do the necessary refactoring to implement, but honestly I wish people would have just said that, instead of inexplicably trying to teach me the basics of SSH or flatly declare it impossible.

I am going to consider this issue solved, and the solution to be "move my infrastructure to Gitlab". Thank you for your time.

**Comment by wxiaoguang** [comment]
> For context, I am a NixOS user, managing dozens of systems, each of which have their own SSH keys. If I had a single SSH key per Gitea user account, per computer, I would multiply the keys by a factor of at least 4.

There is  "deploy key" feature, which is not limited to any user.

**Comment by alxpettit** [comment]
So, my understanding is:

1) Gitea users are the only way to acquire access to resources

2) Although Gitea supports asymmetric cryptographic keys, it does _not_ want to make a distinction between the key, and the user with which that key is associated.

3) Therefore, scenarios where resources are _shared_ with minimum duplication of entries are impossible without significant refactoring. See [this diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Zldb5swFIZ%2FDZergg0muVySttOmapWifd554IIlglPjNGG%2FfqYYCJh0VCVAol4FvzYH85xz7GNiwMV6f8vxJrhjHgkNMPH2BlwaAJhwZsqfVEkyxUF2JvicempQKazoX6LEiVK31CNxZaBgLBR0UxVdFkXEFRUNc8521WEPLKw%2BdYN9ogkrF4e6%2BoN6IsjUKXBK%2FROhfpA%2F2USzrGeN88HqTeIAe2x3IMFrAy44YyK7Wu8XJEzh5Vyy%2B26O9BYT4yQSbW6wHvlXgMLPS3zPbh6%2F%2Ff4ebecflJUnHG7VC99hN6ARkaLqi0WSw%2BBsG3kktWcacL4LqCCrDXbT3p10v9QCsQ5Vt7JMuCD7o1M2CxAygghbE8ETOSS%2FASl2Knhg3t6VrijGBAducJSGlff9wnQJSF4oRq%2FgBV7gBQbnBe2x8YIv8JJ9KJQTmP%2Fh8soXBYMBCdpWC4J2nwQtjeCthIClxEnMttxtTlVpWS6RpJ80nVahWQ3MQAOz6amY2W2Y6enaJzPojIwZasMMDsrMRiNjZurb5xeSjGPrrOUkmLSEhU4GS987xwKrnowjgKVvnGOBVc%2FCEcDS1y59nYq8j%2BlxQLbcEMcxdatgSooT2ZIoePIzbVzZefOXGvncWO4PRy4T1coeSzztTFGDKw8xmPtE%2FHdt0b1wQLmpDsk1TkIs6FN1Hk3k1RPuGZUzLJwMjtVBuYlsS1B3HZ466oZqJam2GGcgNEPPgVC89htiY3pusTGUyy0wu7K7cbpuSkv%2BU7t99u72dm5HZmdu10317XagF2QNVaylh0KPVawDRlbF5qlxPrnSYvu0xrR7FiXSq3fPmiET9pxPehn6xtDo0MX2Zbh4VnOx3bOL9Q9M55%2F9g4aGBTsKjbqh3rNf%2F442nuwfuGoCHfkYOQOn%2FyWendFlhEY9%2Fa2uQkM2y%2F8ds%2BHlv7fw%2Bh8%3D) for a quick example.

**Comment by alxpettit** [comment]
> > For context, I am a NixOS user, managing dozens of systems, each of which have their own SSH keys. If I had a single SSH key per Gitea user account, per computer, I would multiply the keys by a factor of at least 4.
> 
> There is "deploy key" feature, which is not limited to any user.

Deploy key? This is news to me! So I could have them be per-project, and forego the accounts entirely? Sorry, I must have missed that. I guess my use case may be covered after all. Thank you for informing me @wxiaoguang!

**Comment by wxiaoguang** [comment]
> So, my understanding is:
> 
>     1. Gitea users are the only way to acquire access to resources

Almost, except "Deploy Key" or some other internal mechanisms.

>     2. Although Gitea supports asymmetric cryptographic keys, it does _not_ want to make a distinction between the key, and the user with which that key is associated.

Gitea distinguishes the SSH keys. Each SSH key should bind to a user (except Deploy Key).

Then, Gitea needs to use the "SSH key user" to find their org / team / repo, etc, to check permissions.

And at the moment, Gitea also supports external SSH server (OpenSSH), which has to only use one pre-defined SSH user to communicate (eg: `git@git-server`, but not `any-user@git-server`).

If you would like to "share" SSH keys between users, then:

1. The permission problem: how to check a SSH key's permission it binds to different users? A lot of code is written based on the above design.
2. The "current user" problem: if you would like to use "alice@git-server" and "bob@git-server" with the same SSH key, how to make OpenSSH work and not break end users?
3. What's the complicity of the “shared SSH key" implementation? Anyone is willing and is able to maintain it?

None of these problem looks like an easy "possible" problem. They might be able to be done, but the question is the balance of the feasibility / benefit / cost.

**Comment by wxiaoguang** [comment]
The "Deploy Key" feature is here:

![image](https://github.com/go-gitea/gitea/assets/2114189/da734a21-74b4-41b0-b3e0-a8afa738470e)

**Comment by alxpettit** [comment]
Yup. Thanks :)

Looks like the reason I missed it, is because I didn't realize it allowed for write access. That's super useful! :)

**Comment by alxpettit** [comment]
![image](https://github.com/go-gitea/gitea/assets/28266167/3c3c87b8-c226-40fe-8cdf-42c704e1ec9c)

Err... may have celebrated a bit too early. What am I doing wrong?

**Comment by wxiaoguang** [comment]
> Edit 2: Looks like the deploy keys [can't be controlled through the Gitea command line interface](https://docs.gitea.com/administration/command-line), so if I have, say, thirty projects and I'm trying to synchronize 4 machine keys on all of them, this may become prohibitively difficult after all. Is there a solution to this?

I think maybe it could add some APIs for managing the deploy keys?

**Comment by alxpettit** [comment]
> > use the account name provided via SSH protocol have multiple accounts share the same git key, and ID by git 'account name' instead of key
> 
> One would usually understand that you were binding real peoples accounts to a single ssh key. Albeit not being the case, it still merited the clarification.
> 
> > To get an idea of what I am trying to implement, and why it would be troublesome to implement, see this diagram:
> 
> Is one distinct account+ssh key/machine not sufficient for your use case? Say user_machine1 has ssk_key1 and granted permission to ressouce 1 and 2 in your example. It is less elegant than the deploy key but probably accessible through the API

So, if I have 50 machines & 50 resources, I simply automatically create 2500 accounts? That would technically work, but the scalability is simply not there. The number of accounts grows as the product of machines & resources.

**Comment by amrsoll** [comment]
No, I was thinking 1 account per machine. Those accounts would have access to however many resources they are allowed to. Each of those accounts have 1 key, i.e. 1 key per machine.

**Comment by alxpettit** [comment]
Yes, that's what I was trying to do initially.

**Comment by alxpettit** [comment]
> > Edit 2: Looks like the deploy keys [can't be controlled through the Gitea command line interface](https://docs.gitea.com/administration/command-line), so if I have, say, thirty projects and I'm trying to synchronize 4 machine keys on all of them, this may become prohibitively difficult after all. Is there a solution to this?
> 
> I think maybe it could add some APIs for managing the deploy keys?

An API for managing deploy keys would be great. I suggested doing this via terminal UI [in this issue](https://github.com/go-gitea/gitea/issues/26943), but if another implementation would be preferred, that's fine too. Let me know what your thoughts are! :)
