### ISSUE TITLE
Wiki: Files are not downloadable

### ISSUE THREAD

**Issue by bauermarkus** [go-gitea/gitea#27121]
### Description

I tried to provide some files in the wiki via the link markdown

So I cloned the repo, I added a new folder, added the files and linked them as described [here](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2)

When you click the link, the wiki opens a new page

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

None

**Comment by BElluu** [comment]
Something is wrong with method **WebPathToGitPath** in file _./services/wiki/wiki_path.go_
@bauermarkus if you need access to your files in wiki pages, for now you can create link like this:
For example, if your main branch is named master, files is directory in root
`[Link name](/raw/branch/master/files/MyFile.pdf "Test Alt text")`

**Comment by bauermarkus** [comment]
@BElluu Thanks a lot. But if I do that, I get a 404

**Comment by rafaelsgirao** [comment]
I'm interested in fixing this bug and would like to open a pull request soon.

I managed to reproduce this locally and made a proof-of-concept fix, which, at first glance, seems to work: 
Relative links to files which are not registered as renderable by Gitea now feature a raw link instead of a regular wiki link.   

Before:
![image](https://github.com/go-gitea/gitea/assets/7544832/25350c77-c176-4cdb-9f13-e4f79edc5afd)

After:
![image](https://github.com/go-gitea/gitea/assets/7544832/8d507fed-8c8d-4184-bedb-774f1a479c85)

For reference, this is the wiki markdown file I created for testing ( `Home.md` ):
```markdown
Welcome to the Wiki.

[Test file](files/test-file.zip "An ordinary test file")
```

**Comment by lunny** [comment]
Since it's not by design in previous versions, I think feature is a better label for this issue.
