### ISSUE TITLE
Action artifact upload from Windows act_runner results in HTTP 400 error

### ISSUE THREAD

**Issue by s-ludwig** [go-gitea/gitea#27314]
### Description

The `actions/upload-artifact@v3` action (or the actions toolkit more specifically) apparently [uses `path.join`](https://github.com/actions/toolkit/blob/master/packages/artifact/src/internal/upload-specification.ts#L87) to generate the artifact file names, resulting in a backslash character being inserted between the name and the file name/path if the workflow runs on Windows. The upload then produces an error status similar to this on the server:
```
::error::Unexpected response. Unable to upload chunk to http://xyz.org/api/actions_pipeline/_apis/pipelines/workflows/53/artifacts/b3900898524801ca942773cfd2301589/upload?itemPath=library-windows-x86_64%255CFreeImageLib.pdb
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "server": "nginx",
  "date": "Wed, 27 Sep 2023 15:11:51 GMT",
  "content-type": "text/plain; charset=utf-8",
  "content-length": "22",
  "connection": "keep-alive",
  "x-content-type-options": "nosniff"
}
###### End Diagnostic HTTP information ######
::warning::Aborting upload for C:\Users\gitlab3\act_builds\e616ea9d8027ca3a\hostexecutor\Source\FreeImageLib\x64\Release\FreeImageLib.pdb due to failure
::error::aborting artifact upload
```

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

Linux

### How are you running Gitea?

Using the official download binary and using act_runner 0.2.6 on Windows.

### Database

MySQL/MariaDB

**Comment by psaintmalo** [comment]
Can confirm the same issue happening to me with 1.21rc1 and the 0.2.6 action runner binaries.

**Comment by psaintmalo** [comment]
Looking further into the code, the backslash that is being inserted into the api call seems to come from the [safeResolve](https://github.com/nektos/act/blob/ace4cd47c7f099864866b1f60e064fecde7f36ea/pkg/artifacts/server.go#L92) function used in [netkos/act](https://github.com/nektos/act/tree/master)/[pkg](https://github.com/nektos/act/tree/master/pkg)/[artifacts](https://github.com/nektos/act/tree/master/pkg/artifacts)/server.go, rather than from the act toolkit.

`return filepath.Join(baseDir, filepath.Clean(filepath.Join(string(os.PathSeparator), relPath)))`

The safeResolve function is then used for the [uploads](https://github.com/nektos/act/blob/ace4cd47c7f099864866b1f60e064fecde7f36ea/pkg/artifacts/server.go#L120) function, which forms part of the [Serve](https://github.com/nektos/act/blob/ace4cd47c7f099864866b1f60e064fecde7f36ea/pkg/artifacts/server.go#L290) function.

The nektos/act/pkg/artifacts is being imported by act_runner in [exec.go](https://gitea.com/gitea/act_runner/src/commit/4c3528817525860ae84c8a5eda19eaced31c58cb/internal/app/cmd/exec.go#L19) which then uses the [Serve function](https://gitea.com/gitea/act_runner/src/commit/4c3528817525860ae84c8a5eda19eaced31c58cb/internal/app/cmd/exec.go#L435).

As safeResolves uses the os.PathSeparator, it would default to backslash instead of forward slash for Windows. 

If I manage to resolve the issue I will make an update.

**Comment by fuxiaohei** [comment]
Fixed in https://github.com/go-gitea/gitea/pull/27840
