### ISSUE TITLE
Trust to custom CA for SSL webhook

### ISSUE THREAD

**Issue by tomas-kulhanek** [go-gitea/gitea#2744]
- Gitea version (or commit ref): Gitea Version: 5f4210a (Go1.8.3)
- Git version: 1.8.3.1
- Operating system: CentOS Linux release 7.4.1708 (Core)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

Please, how can i add SSL CA to trusted CA for gitea webhook?

**Comment by ptman** [comment]
Golang on Linux looks for root certificates here: https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go

On CentOS:

On Fedora since 19, RHEL / CentOS 7, and RHEL / CentOS 6 since this update, the Shared System Certificates feature is available. With that system, the correct method is to place the certificate to be trusted (in PEM format) in /etc/pki/ca-trust/source/anchors/ and run sudo update-ca-trust. (If the certificate is in OpenSSL’s extended BEGIN TRUSTED CERTIFICATE format, place it in /etc/pki/ca-trust/source). On RHEL 6, you have to activate the system with update-ca-trust enable after installing the update; if you don’t want to use it, you can try the approach below.

**Comment by tomas-kulhanek** [comment]
Its working, thanks.
