### ISSUE TITLE
ref_name in actions sometimes blank for scheduled jobs

### ISSUE THREAD

**Issue by nephatrine** [go-gitea/gitea#27678]
### Description

When my actions jobs are running, both ${{ gitea.ref_name }} and ${GITHUB_REF##*/} are empty for some repositories when running from the cron schedule (but work fine during push trigger). When I tried to make a new repo with a minimal test, I was unable to reproduce this issue but it is consistently the case for my existing repos. I slowly built up that minimal example until it was essentially the same as my existing job and it still returned the correct result. I've ran this instance for a while and so those existing repos were created in earlier gitea versions and that's the only thing I can think of that would make them different than a new repo. Any idea on what could cause this behavior and if there is something specific I need to look for and correct in the database maybe for those repos migrated from earlier versions?

### Gitea Version

1.21.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40

### Operating System

alpine:latest

### How are you running Gitea?

self-built in a docker container

### Database

SQLite

**Comment by nephatrine** [comment]
In the Actions UI, it doesn't show the branch name for those particular scheduled jobs either (the top one).
![image](https://github.com/go-gitea/gitea/assets/1461334/7325b662-8cd1-49cb-ad7b-4776ba08d063)

**Comment by nephatrine** [comment]
Oh ok. I swear I looked around in the issues, but didn't see it reported already.

**Comment by ExplodingDragon** [comment]
link #26815

**Comment by nephatrine** [comment]
I guess I must not have looked at closed issues. My main issue isn't that it doesn't show up in the UI, it's that I need the value in my actual action and it's not setting the variables. So far the only way I've found to "resolve" this is to try removing and recreating all my existing repos which isn't something I'm really excited about trying to do.

**Comment by nephatrine** [comment]
So after more experimentation, repo I created as a minimal testcase still hasn't encountered the issue, but other new brand new repos do have this issue. It's nice in some ways because it is a reliable way for me to differentiate push and schedule events in my workflows in light of #27667, but it's all the more vexing to me why it would impact every single one of my repos... except the minimal example. I'll keep playing around and see if maybe something about the workflow size or complexity is actually the cause.

**Comment by denyskon** [comment]
I have the issue too, and I think I now found out when it happens. Basically, when a repo action like update issue label is being executed, the notify method 
https://github.com/go-gitea/gitea/blob/4d1277c0cbb9c02aa5a33a2927073f8cd400c916/services/actions/notifier_helper.go#L111
is being triggered, which updates all the scheduled runs. But some actions like assignment of a label to an issue don't have a ref_name because they belong to the whole repo. For normal workflow triggers, the ref falls back to the default branch https://github.com/go-gitea/gitea/blob/4d1277c0cbb9c02aa5a33a2927073f8cd400c916/services/actions/notifier_helper.go#L141
which is then also passed to the handleWorkflows method
https://github.com/go-gitea/gitea/blob/4d1277c0cbb9c02aa5a33a2927073f8cd400c916/services/actions/notifier_helper.go#L202
but not to the handleSchedules method
https://github.com/go-gitea/gitea/blob/4d1277c0cbb9c02aa5a33a2927073f8cd400c916/services/actions/notifier_helper.go#L198

So the simple fix should be also to pass the ref parameter to the handleSchedules method to use as action schedule ref.

PR incoming :)
