### ISSUE TITLE
API explorer assumes HTTP, breaks curl.

### ISSUE THREAD

**Issue by issmirnov** [go-gitea/gitea#2790]
- Gitea version (or commit ref): 1.2.2
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No - https://try.gitea.io/swagger send me to a user page, not API explorer.
  - [ ] Not relevant

## Description

When I use the API explorer (lives on `/swagger`) I am unable to execute commands. Looking at the generated curl command, I see that it starts with `http` and not `https`. Since the curl command doesn't have the follow redirects flag (`-L`) the command fails.

Error: `TypeError: Failed to fetch`

## Screenshots

![image 2017-10-26 at 22 26 11](https://user-images.githubusercontent.com/5771615/32089074-b9ee48d8-ba9c-11e7-8106-11dd07fe327d.png)

**Comment by issmirnov** [comment]
FWIW, `Application URL = https://git.smirnov.work`, so the HTTPS is there.

**Comment by jonasfranz** [comment]
This is a problem of swagger UI. Please simply select HTTPS as schema if you only use HTTPS. (See screenshot). This can't be removed since some users allow HTTP traffic without redirection. And swagger ui could (not yet) determine if HTTPS is redirected or not.
![HTTPS Schema](https://user-images.githubusercontent.com/5757182/32176517-3199d152-bd88-11e7-9d6a-3ec4be4dd9c3.png)

**Comment by issmirnov** [comment]
Understood, thanks!
