### ISSUE TITLE
No longer showing contributions, even with recent checkins

### ISSUE THREAD

**Issue by binarydad** [go-gitea/gitea#27907]
### Description

I realized the contribution graph on the home page no longer shows commits, even though there are in fact recent commits - they are just not reflected in the graph of in the list of recent projects. I'm not sure which version this issue started with. Thank you.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1760607/29a5a97d-5052-4a51-bdb0-0bdda88c98c7)

### How are you running Gitea?

Self-hosted in docker

### Database

SQLite

**Comment by lng2020** [comment]
Can u provide more detailed information about the commitment `Last month` commit? `Last month` can be 10.1 or 10.30 and I can't tell what the problem is from your screenshot.

**Comment by dousha** [comment]
I'm having an even stranger issue that none of my code pushes would show on the timeline. Repositories would just say it was "updated last month" even if I'm pushing new code into them every day. My instance was set up after 1.20.5 came out (on 2023-10-05), so my timeline is basically blank with only repository creation and merge requests shown.

I believe it is caused by the same underlying issue.

**Comment by wxiaoguang** [comment]
https://docs.gitea.com/help/faq#push-hook--webhook-arent-running

**Comment by dousha** [comment]
> https://docs.gitea.com/help/faq#push-hook--webhook-arent-running

Thank you. After a bit of digging, I have located the problem. It was because the file system used by gitea was mounted with `user` option which implies `noexec`. Fixing the mount options and restarting the docker image resolved the problem.

It caught me by surprise. I've checked the log but there was nothing shown. It would be nice if gitea could check if the file system is configured correctly, or at least print a warning in the log.
