### ISSUE TITLE
Can't download release archives

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#27945]
### Description

Trying to download a tag/release archive results in the following error: 

```
archiver.Await: archiver.StartArchive: context deadline exceeded
```

(This is everything I could find in the logs, with debug mode enabled)

Example: https://kolaente.dev/vikunja/frontend/archive/v0.21.0.tar.gz

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Official Docker image.

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
How big is that file?

**Comment by kolaente** [comment]
Shouldn't be that large (a few mb at most) as it only contains the source code for a tag. How can I check the size if I can't download it?

**Comment by benharri** [comment]
I'm also getting this on archives

`2023/11/29 20:32:35 ...ers/web/repo/repo.go:434:Download() [E] archiver.Await: context canceled`
here's an example release that fails 
https://tildegit.org/sloum/bombadillo/releases/tag/2.4.0

**Comment by wxiaoguang** [comment]
> I ended up clearing the task queues via `/admin/monitor/queue` which seems to have resolved it for now. There were roughly 1500 pendings tasks in the repo-archive queue.

Thank you for your feedback. It seems to be a bug from the legacy queue system (corrupted queue data). The legacy queue system might cause "blocking" bugs, which means that all tasks are pending in the queue.

In new Gitea, we add the ability to "clear" the queue (actually reset the legacy queue system), so I guess there won't be problem.

Feel free to reopen if there is still any problem.

**Comment by kolaente** [comment]
I have roughly 10k items in the queue for repo archive and issue indexer. No worker seems to be available to resolve that. Even if I increase the worker limit. Why is that? 

And if I just clean the queue, the issues are still not indexed, meaning the search does not work. That's not a solution.

**Comment by wxiaoguang** [comment]
> I have roughly 10k items in the queue for repo archive and issue indexer. No worker seems to be available to resolve that. Even if I increase the worker limit. Why is that?

I would assume that you are using the default queue (levelqueue), then the details are here:   Help to recover from corrupted levelqueue #24912 


> And if I just clean the queue, the issues are still not indexed, meaning the search does not work. That's not a solution.

Feel free to reopen or open a new PR for the problem if the root cause is clear, I guess the root cause could be one of:

1. The broken tasks in the corrupted queue were just cleared, so unless you make new changes, the issues won't be pushed into the queue to be indexed (not really a bug, it's just caused by the corrupted legacy queue and need to re-index the issues)
2. There are more and more pending tasks in the queue, the queue doesn't dispatch the tasks to workers. It could be the queue's bug.
3. There are more and more pending tasks in the queue, the tasks could be dispatched properly, but the "worker" / "indexer" doesn't work and can't finish the indexing work. Then it is the indexer bug, not the queue's bug.

Maybe logs could also tell more clues.
