### ISSUE TITLE
The git blame view fails to display the majority of its "prior to change" markers

### ISSUE THREAD

**Issue by jessey-git** [go-gitea/gitea#28280]
### Description

When viewing a file's Blame history, you are presented with the ability to view the file "prior to" commits affecting various lines.  Gitea is enabling this feature in a very sporadic sense and often not at all.

Compare these 2 blames on the same file, one in Gitea and one on GitHub:
Gitea: https://projects.blender.org/blender/blender/blame/branch/main/source/blender/editors/interface/interface_ops.cc
GitHub: https://github.com/blender/blender/blame/main/source/blender/editors/interface/interface_ops.cc

### Gitea Version

1.21.1+406-ga09b13b6d

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Own build.

### Database

SQLite

**Comment by KN4CK3R** [comment]
The problem are moved files. The blame breaks / doesn't show the marker if the file does not exist in the parent commit. Github links to the correct filename at that commit.

Fore example Gitea does not show the marker here because there is no `interface_ops.cc` in the parent:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/27a2c069-60e4-4bd2-802c-d43980ac0887)
Github resolves the old name:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/07aaacbc-4223-4013-bea9-d3cde221c941)

**Comment by KN4CK3R** [comment]
Fixed with https://github.com/go-gitea/gitea/pull/28306
