### ISSUE TITLE
UI: first item is always selected in arc-green/gitea/... theme

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#28292]
### Description

I'm using the arc-green theme and the first repo is always selected in every tab.

![image](https://github.com/go-gitea/gitea/assets/8334250/40748241-6c8b-4cd3-91aa-313692723e01)

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.43.0

### Operating System

Ubuntu 22.04.3 LTS x86_64

### How are you running Gitea?

gitea-1.21.1-linux-amd64

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
> I'm using the arc-green theme and the first repo is always selected in every tab.

It just works that way because it support keyboard navigation.

If you reload the page, there won't be any selected item.

But if you have pressed some keys or have selected an item, then there will always a selected item in the list. You can simply reload the page, then there won't be any selected item.
