### ISSUE TITLE
upload to minio /s3 server directly？

### ISSUE THREAD

**Issue by eastonsuo** [go-gitea/gitea#28410]
### Feature Description

is there a way for user to upload a lfs file directly to minio or s3 server after a batch request?

**Comment by lunny** [comment]
Hi, currently. You can already set lfs backend as minio or s3 compatible server. See https://docs.gitea.com/next/administration/config-cheat-sheet?_highlight=confi#lfs-lfs

And then the files will be stored into minio/s3 after uploaded to Gitea endpoint. They cannot be sent to S3 directly because Gitea needs to store some meta information into database.
