### ISSUE TITLE
How-to Customize Homepage ?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#2878]
- Gitea version (or commit ref): 1.8.3

## Description
Hi,

how can I customize my Gitea installation Homepage ? I would like to put the homepage (when user is not logged in) to fit my company style (logo, introduction text, ...).

Regards,

**Comment by ghost** [comment]
Ok I found, it's a template to override.

**Comment by thundergreen** [comment]
Where is this template?

**Comment by ghost** [comment]
Hi,

the template needs to be retrieved from the Gitea github repository.

**Comment by William-LP** [comment]
Hi,

So do you need to recompile Gitea after customizing the homepage ?
Or can I just drag & drop my updated files somewhere into the custom folder ?

**Comment by T100D** [comment]
@William-LP , you can drop your files in the appropriate folders.

The dark theme has an error in this in the explanation, the files/folders should be in the custom folder and not the main gitea folder.

**Comment by William-LP** [comment]
I'm sorry I feel dumb but I don't manage to update that homepage.

I've updated the file [home.tmpl](https://github.com/go-gitea/gitea/blob/master/templates/home.tmpl) and dragged him into C:/gitea/custom/ folder but I still got the regular homepage after reloading my gitea service. 

I'm missing something but I can't figure out what :/ 

I'd appreciate a bit more details regarding the process to update that homepage :) 

**EDIT** : My bad, I was trying to put the current template folder rather than the 1.4.2 version (the one I'm using), so Gitea was crashing. Now it's all fine :) Thanks again guys!

**Comment by lafriks** [comment]
You need to place it in `C:/gitea/custom/templates/`

**Comment by RivasAlejandro** [comment]
hi ,  i can't find the folder templates

**Comment by lafriks** [comment]
Ask questions in forum not here, it won't be answered in closed issues
