### ISSUE TITLE
Decide to use htmx or not

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#28880]
We do a lot of server-side rendering. And if we want to keep it at least partially, we cannot fully use Vue 3 for that.

htmx fills the gap to do so while making the site more interactive. Though I'm not contributing much to the frontend lately, I did hear only good stuff about it. And if you look at the two pull requests, making the two components interactive in Vue 3 would have been more or less a complete rewrite. The pull requests only had to undergo minor code changes to make it work.

In terms of maintenance and refactoring, that is a huge advantage.

---

example pulls:
- https://github.com/go-gitea/gitea/pull/28871
- https://github.com/go-gitea/gitea/pull/28872
- https://github.com/go-gitea/gitea/pull/28908

**Comment by yardenshoham** [comment]
I think adding htmx is a good idea. The pull requests speak for themselves, they are small and easy to maintain. htmx fits Gitea very well.

**Comment by denyskon** [comment]
HTMX makes it easier to develop interactive UI using our already present template structure. And I think it is better to introduce something we can use to make existing UI better than to wait for someone to rebuild everything using a new framework.

**Comment by wxiaoguang** [comment]
My question is: does htmx really help and will be widely used in Gitea?

I have been following htmx for some time. My feeling is:

* How does htmx handle error messages and network failure in Gitea? How does it handling the "loading" indicator? 
* The basic feature like "replace inner html" could be easily implement by a few lines in our framework, ex: we already have "link-action" and "form-fetch-action"
* Does it need to repeatly write `hx-headers='{"x-csrf-token": "{{.CsrfToken}}"}'` for every reuqest? `link-action` and `form-fetch-action` already handles CSRF token automatically.
* Some advanced features overlaps with existing mechanisms, eg: modal. Should new code use Fomantic/Gitea Modal, or htmx's modal? What if Vue component needs to show a modal, htmx isn't designed to work with Vue IMO.
* Some advanced features like "htmx script" is quite fragile and I don't know how to lint/test them. It would cause maintainability problems.

So, IMO the only useful part of htmx at the moment is the "replacing inner/outer html by ajax", while it is quite simple and could (should) be implemented by existing "link-action" and "form-fetch-action". Other htmx features are unlikely useful in foreseeable future.

**Comment by jolheiser** [comment]
I would be for using htmx over our home-rolled solutions, and for slowly increasing its usage where it would be beneficial.
But I also agree we need to come up with some solid plan for reducing our fracture of JS solutions.
With our current mix I think new additions need to planned out carefully.

**Comment by yardenshoham** [comment]
> How does htmx handle error messages and network failure in Gitea?

From https://htmx.org/docs/#requests:

In the event of an error response from the server (e.g. a 404 or a 501), htmx will trigger the [htmx:responseError](https://htmx.org/events/#htmx:responseError) event, which you can handle.

In the event of a connection error, the htmx:sendError event will be triggered.

> How does it handle the "loading" indicator?

https://htmx.org/docs/#indicators

> The basic feature like "replace inner html" could be easily implement by a few lines in our framework, ex: we already have "link-action" and "form-fetch-action"

Why would we recreate the logic htmx excels at and maintain it?

> Does it need to repeatly write `hx-headers='{"x-csrf-token": "{{.CsrfToken}}"}'` for every reuqest? `link-action` and `form-fetch-action` already handles CSRF token automatically.

We can use https://htmx.org/docs/#inheritance to set it on a root tag, that way all requests include it

> Some advanced features overlaps with existing mechanisms, eg: modal. Should new code use Fomantic/Gitea Modal, or htmx's modal? What if Vue component needs to show a modal, htmx isn't designed to work with Vue IMO.

I don't have experience creating modals. I don't think that the fact htmx has features we already implemented should block us from using it, or any other library that implements functionality we have. I wouldn't use htmx with Vue, I'd use htmx when I don't need the power of Vue.

> Some advanced features like "htmx script" is quite fragile and I don't know how to lint/test them. It would cause maintainability problems.

What do you mean by fragile? Yes, linting is missing in htmx, what kind of rules would you like to enforce?

> The samples PRs https://github.com/go-gitea/gitea/pull/28871 and https://github.com/go-gitea/gitea/pull/28872 are good demo for htmx, but they are too simple and didn't handle error messages / loading indicators.

What's wrong with their error handling? I can work to change it. Just like the previous behavior of the buttons I changed, there were no loading indicators.

> Are there some complex samples for showing how htmx would work for a complex case in Gitea? For example, comment editing, PR merging?

It's not supposed to be used in complex cases, at least I won't force it to.

> So, IMO the only useful part of htmx at the moment is the "replacing inner/outer html by ajax", while it is quite simple and could (should) be implemented by existing "link-action" and "form-fetch-action". Other htmx features are unlikely useful in foreseeable future.

I don't think you've considered the varying possibilities to "replacing inner/outer html by ajax". Are we going to reimplement `hx-target`, `hx-swap`, and `hx-select`? This is no small feat, it's a maintenance challenge

> (I don't mean objection, while I think these questions needs to be clearly answered and some should be written into the guideline / devtest.tmpl if most people would like to use htmx)

I am very new to htmx. Those PRs are the first time I used it. We should try it out and play with it instead of immediately enforcing some prematurely written guidelines.

**Comment by puni9869** [comment]
Having experience with both htmx and vuejs, I currently utilize htmx for smaller applications. However, I've encountered limitations when integrating it into Gitea, especially on complex screens such as code review and the front landing page, where various UI elements are in play. Considering the challenges faced, I believe using to Vue3 would be a more favorable option. It allows us to leverage existing solutions and avoid reinventing the wheel. I leave the final decision to the TOC/maintainers for their consideration.

**Comment by yardenshoham** [comment]
Thanks for the detailed comment.

> Gitea is not a small project, so there are a lot of details which are not easy to be satisfied by 3rdparty library, they need to be customized somewhat.

Sure, but we have more libraries we don't customize than ones we do.

> And I have a feeling that "replacing inner/outer html by ajax" is not that complex in Gitea, no need to fully "reimplement hx-target, hx-swap, and hx-select" like htmx or reinvent the wheel again.

I'd love to see the sample PRs recreated in `link-action` / `form-fetch-action` to compare maintainability.

> And actually the behaviors are changed, that why I asked the questions about error handling / loading indicator:

Regarding the error handling and loading indicator, I am open to add changes, I don't see these as blockers to use htmx.

> If let us predict, after introducing htmx, in which case the `link-action` / `form-fetch-action` should be used, and in which case `htmx` should be used?

The distinction seems pretty clear to me, `link-action` / `form-fetch-action` if you want a full page load, otherwise `htmx`.

**Comment by yardenshoham** [comment]
@go-gitea/technical-oversight-committee please write here your official decision if we can add `htmx` or not

**Comment by yardenshoham** [comment]
I will take "no comment" as silent approval

**Comment by jolheiser** [comment]
My comment is largely as it was above.

I would be for an exploratory PR (similar to the one we recently had and reverted) and we should use that PR to try and define some guardrails around its usage moving forward, as well as giving the opportunity for anyone to be critical of any tradeoffs. 
I think that would be easier to do in a concrete example PR.

I love (the idea of) htmx, my main concern is more fracturing of our frontend framework(s).

**Comment by delvh** [comment]
So, the overall consensus I sense is the following:
We are in favor of introducing HTMX if the PR adding it also adds clear contribution guidelines where, how, and what parts of HTMX to use.

**Comment by yardenshoham** [comment]
I created https://github.com/go-gitea/gitea/pull/28908 with error handling and one use of a request indicator

**Comment by lunny** [comment]
Just notice this closed.

I concens two questions.
1) If we introduce htmx, should it replace vue3 in future or not?
2) If we introduce htmx and keep vue3 at the same, then we have vue3 and then htmx. So when should contributors use vue3 and when should use htmx when sending a PR?
3) I couldn't find htmx is better than ajax/fetch with vue3 even in #28908 . When trasfering a json, you don't need to create a new template file.

**Comment by wolfogre** [comment]
> I will take "no comment" as silent approval

I abstain and respect others' choice since it's the first time I've heard of htmx. Sorry to bother, but I meant to read others' discussions and learn 😄, not give silent approval.

**Comment by techknowlogick** [comment]
Hi, chiming in as well. While I am a fan of htmx and use it elsewhere, I am cautious to include it in Gitea itself regardless of benefits for the following reasons:
* Including an additional way of accomplishing something can duplicate patterns, adding to the overhead in analyzing how something could be accomplished.
* Including a new way of doing something without already entirely removing something that we have fully deprecated (jQuery)
* There is then something that is less well known that does mean that new contributors have to learn before using

I'd be interested in hearing @silverwind's thoughts due to their contributions to the frontend, and being the top voted person in the latest TOC election.

I do see the benefits of it though (see reasons others have listed above).

I realize this isn't a yes/no to the question, but I think it is a valuable discussion to have with any big change of direction (similar to how we did with changing the routing library to chi)

**Comment by yardenshoham** [comment]
> 1. If we introduce htmx, should it replace vue3 in future or not?

No, vue3 is more powerful. htmx is for simple interactions.

> 2. If we introduce htmx and keep vue3 at the same time, then we have both vue3 and htmx. So when should contributors use vue3 and when should use htmx when sending a PR?

By order of reactivity:
1. `link-action` / `form-fetch-action` for a full page load
2. htmx for simple, minimal reactivity
3. vue3 for full reactivity

> 3. I couldn't find htmx is better than ajax/fetch with vue3 even in [Introduce htmx and use it to avoid full page load on `Subscribe` and `Follow` #28908](https://github.com/go-gitea/gitea/pull/28908) . For every request, now we need to create an extra template file, but when doing the same with vue3, we just return json content.

If I compare it with https://github.com/go-gitea/gitea/pull/28914 it seems using ajax/fetch with vue3 is more lines and overall more complex.

> 4. Less people know htmx and contributors have to learn both htmx and vue3, but htmx has no special feature that vue3/javascript cannot finish. So introducing htmx may prevent contributors to contribute more.

Yes but the number of lines needed to achieve the same is drastically different, with vue3 using much more.

> 5. If one button will trigger multiple changes which is not a simple dive replacement, so we have to swithc to vue3 to finish it? Or should we do mutiple requests?

If htmx can't provide something, use vue3. I believe htmx covers a lot of use cases, but not all.

**Comment by lunny** [comment]
The code lines are not much more than htmx. I think the Cons is the layout will be blink, maybe I need some css to fix the height and width.

**Comment by puni9869** [comment]
All views are same and pointing in the same direction. Let's introduce the htmx at appropriate place.

**Comment by anbraten** [comment]
(Accidentally posted this originally on #28908)

Looks like a pretty promising approach using htmx for gitea. One thing I would like to throw into the discussions is how updating UI through events send from the server (websocket / sse) would be handled in the future for things like #2287 or #25661.

There seems to be https://htmx.org/extensions/web-sockets/.

If not would it mean that gitea would use:
- htmx: server-side rendering + interactive client side
- vue3: complex client-side rendering
- jQuery / some vanilla JS to update UI on websocket / sse events?

**Comment by 6543** [comment]
We want to ged rid of jQuery ... else yes thats what at least i have in mind :)

**Comment by puni9869** [comment]
> We want to ged rid of jQuery ... else yes thats what at least i have in mind :)
We cannot get rid of jQuery real soon, honestly. We are too much jQuery.

**Comment by anbraten** [comment]
Did a first attempt on implementing how the websocket "realtime" updating could look like #28958

**Comment by silverwind** [comment]
I don't have much of an opionion on htmx really. Overall it seems to be suited for some limited use cases like content replacement from fetch/ws. But for many complex user cases, we will certainly have to resort to JS and Vue. It seems [reasonably small](https://bundlephobia.com/package/htmx.org@1.9.10), though, so I guess the performance impact of loading it shouldn't be too much.

**Comment by lunny** [comment]
It's unclear for small and big. There is no clear rule for which should use vue+js and which should use htmx.

**Comment by denyskon** [comment]
It looks to me currently like there are much more pros than possible cons of adopting HTMX. It seems to fit well into our current template structure, lowers the amount of development needed for interactive components, lowers the amount of client side rendering, and also seems to make it easier to implement features like websockets. 

@lunny I'd do htmx as long as it is possible because it allows us to continue using go templates. Of course there are pages like the action run view where the whole page has to be interactive, but as long as this isn't the case and the htmx implementation is easier than the vue one, I'd go with htmx.

**Comment by 6543** [comment]
looking at lunnys example pull just for the simple change ... the JS got way more conplex and we got way more lines of code ...

**Comment by lunny** [comment]
> looking at lunnys example pull just for the simple change ... the JS got way more conplex and we got way more lines of code ...

But it's not too much. And it will keep the frontend users only one consistent technique to contribute to Gitea. I'm not a frontend guy, I think it can be shorter for frontend guys.

**Comment by 6543** [comment]
I think we can say htmx is accepted at this point?

**Comment by wxiaoguang** [comment]
Finally, we completely removed htmx in 1.27, just like I predicated ahead:

* https://github.com/go-gitea/gitea/issues/28880#issuecomment-1902643849
* https://github.com/go-gitea/gitea/issues/28880#issuecomment-1903037752
