### ISSUE TITLE
external issues not linked in dashboard

### ISSUE THREAD

**Issue by hmoffatt** [go-gitea/gitea#29152]
### Description

I have configured external issue tracking on my repositories with the alphanumeric (ABC-123) format set. Issues are linked in the commit history for the repositories as expected, but they are not linked in the dashboard for the user or organization.

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Firefox_Screenshot_2024-02-12T23-55-38 671Z](https://github.com/go-gitea/gitea/assets/7577172/d5a90514-7854-488e-818e-9f9942fe1191)
![Firefox_Screenshot_2024-02-12T23-56-02 676Z](https://github.com/go-gitea/gitea/assets/7577172/ddb6a193-7dd2-47bb-9ded-1f214190530a)

### Git Version

2.39.2

### Operating System

Debian bullseye

### How are you running Gitea?

systemd from Debian package

### Database

PostgreSQL

**Comment by hmoffatt** [comment]
I set up a test repository https://try.gitea.io/hmoffatt/hamish-test and it seems to work on there. I see the issue linked in the commit history, the README.md, and in the dashboard.

![Uploading Firefox_Screenshot_2024-02-13T01-13-31.901Z.png…]()

**Comment by charles7668** [comment]
This problem is related to PR #27581, but this fix has not been merged into the 1.21 version

You can test this by simply replacing ($repo.ComposeMetas ctx) with ($repo.ComposeMetas), and then it should work for the 1.21 version.

![圖片](https://github.com/go-gitea/gitea/assets/30816317/c25a6639-4906-4974-9b47-4cb4b55b0dbc)

**Comment by lunny** [comment]
Fixed by #29446
