### ISSUE TITLE
Sign In form UI refactoring

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#29280]
Maybe remove tabs at all (there is already link to register) and openid can be moved as other external buttons

_Originally posted by @lafriks in https://github.com/go-gitea/gitea/issues/28753#issuecomment-1944489167_

**Comment by ijbarnes** [comment]
Can I work on this? Im looking to contribute to an open source project for the first time.

**Comment by lafriks** [comment]
Yes, currently as far as I know nobody is working on this

**Comment by joshuanazareth97** [comment]
Hi, is work being done on this issue or is it open to a PR? Would like to contribute

**Comment by delvh** [comment]
Sure, PRs are always welcome

**Comment by joshuanazareth97** [comment]
Hi @delvh, just wanted to clarify 2 things and share my POA before tackling this PR.

**Current behavior**: Auth mechanisms are split up over 3 tabs: Sign In, Register and Open ID
**Expected behavior**: Remove the tabs, the links in the navbar will be used to navigate between Sign In and Registration, and Open ID will be moved to the sign in page.

I see 2 things that need to be considered in order to make the UX frictionless:
1. There should be no confusion for users about which fields are required for each sign in type, since unlike social login buttons, logging in with Open ID requires the additional input of a URL, which could be confusing if not clearly differentiated from the inputs needed for regular sign in (username and password)

2. The case where users enter a value in all 3 fields should be handled so that there is no unexpected behavior


**Potential Solutions:**
1. Add a button, "Sign In with OpenID" below the social login buttons. Clicking this button dynamically renders a new dismissible input for the OpenID url, while (possibly, if feasible) disabling the fields for regular sign in. Dismissing this new input returns the form to its original state.

2. Add another section (with another "OR" divider) below the social login buttons. This will simply be the OpenID form as it exists right now. Since the submit button is separate, even if values are entered in non-relevant fields, they will just be ignored when the form is submitted.

Would be grateful to know the views you / other maintainers have regarding which of these solutions is the better approach.

**Comment by lafriks** [comment]
I think it would be as button (same as other external auths) and when clicked then either:
* Go to existing OpenID form - so just like it is now only replacing tab link with button
* Open popup to enter URL

**Comment by joshuanazareth97** [comment]
Since there is only one field and the other auth related functionality doesn't trigger popus, I think it would be most consistent then to go with your first suggestion. 
Will add another button that is just a simple link to the existing OpenID form, and on that form will add a button that allows the user to go back to the regular sign in page.

**Comment by delvh** [comment]
Yep, I too think that the first option sounds like the best course of action.
