### ISSUE TITLE
@User in commit message (description)

### ISSUE THREAD

**Issue by SohnyBohny** [go-gitea/gitea#2968]
if you add @User in commit message (description) it won't be blue like in "normal" text areas

Is it a bug or a feature?

**Comment by lunny** [comment]
@SohnyBohny any screenshots or example on https://try.gitea.io ?

**Comment by SohnyBohny** [comment]
![Screenshot 1](https://user-images.githubusercontent.com/10254103/33230979-7d29b83e-d1ed-11e7-871f-b5fee1dac07b.png)
![Screenshot 2](https://user-images.githubusercontent.com/10254103/33231025-42761344-d1ee-11e7-92dd-ab7c05b6a0b1.png)


The red underlined part in the second screenshot should be blue and clickable

**Comment by lunny** [comment]
I think this should be a new feature.

**Comment by svarlamov** [comment]
I was considering creating a new issue, but since the implementation of this seems to be ubiquitous, I will post my thoughts here. This sort of @ mention feature should also show a dropdown of users. There are too many people to remember everyone's username. It would be really helpful to have the Github-style inline auto-complete suggestions when you type the '@'. I'm sure that this is probably something that we can simply add into the HTML templates for issues, and the other related text areas.
