### ISSUE TITLE
URL links not clickable in `Description` of organization's projects

### ISSUE THREAD

**Issue by bilogic** [go-gitea/gitea#30263]
## HTML links
- Show up as links in `Description` of repositories
- Show up as links in `Description` of repository's projects
- Does not show up as links in `Description` of organization's projects

### Gitea Version

1.21.9

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker compose

### Database

MySQL/MariaDB

**Comment by bilogic** [comment]
Hmm, ok, but I can't change the label.

I mean, they are all labelled `Descriptions`, what was the design reason to make the organization's project's `Description` different?

**Comment by bilogic** [comment]
Yea, unfortunately I have not written in go before, i see reporting as a way to contribute back to this project.

**Comment by wxiaoguang** [comment]
Thank you for your report!

->  Fix project description rendering for org #30587

**Comment by bilogic** [comment]
@silverwind I'm running gitea via docker, is there a way for me to test out this PR? Thanks!

**Comment by silverwind** [comment]
Not easily as you would need to install all build dependencies, but you can wait on the nightly release now that it's been merged.

**Comment by wxiaoguang** [comment]
The fix has been backported to 1.21 branch and the nightly build is ready (1.21 nightly will be next 1.21.12 release later).

You could find 1.21 nighly images here: https://hub.docker.com/r/gitea/gitea/tags

And I can see you are still using 1.21.9, so it's also recommended to upgrade to latest 1.21 release, because some security problems were also fixed.
