### ISSUE TITLE
Wrong selection of event type when creating/updating a webhook via Gitea API

### ISSUE THREAD

**Issue by Android-X13** [go-gitea/gitea#30765]
### Description

Example to create a webhook that would be triggered on specific custom events:

```
curl -X POST \
  "http://host/api/v1/orgs/org_name/hooks" \
  -H "Accept: application/json" \
  -H "Authorization: token $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "active": true,
    "type":"gitea",
    "events": ["issues","issue_comment"],
    "config": {
      "secret":"123",
      "content_type":"json",
      "url":"http://domain/webhook.php"
    }
  }'
```

The events that should be set here are `Issues` (Issue opened, closed, reopened, or edited) and `Issue Comment` (Issue comment created, edited, or deleted), however all issue-related events are set. The server's response contains

`"events":["issues","issue_assign","issue_label","issue_milestone","issue_comment"]`

and the webhook's settings on the web interface has all options checked under Issue Events.

Same thing happens with the `pull_request` event which should correspond only to opened/closed/reopened/edited event type but instead sets all pull request events.

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary download, systemd

### Database

None

**Comment by kemzeb** [comment]
Looking at the code further:

https://github.com/go-gitea/gitea/blob/059b2718a5615c01b897283f6ae53c9702f11239/routers/api/v1/utils/hook.go#L150-L152

It appears passing "issues" is treated the same as **setting all of the issue-related events**. What you are looking for is the "issues_only", as we see here:

https://github.com/go-gitea/gitea/blob/059b2718a5615c01b897283f6ae53c9702f11239/routers/api/v1/utils/hook.go#L191-L195

 Running your input (but using `issues_only` instead of `issues`) using the swagger API, we can see that we do get the desired output:
```console
{
  "id": 5,
  "type": "gitea",
  "branch_filter": "",
  "config": {
    "content_type": "json",
    "url": "http://domain/webhook321.php"
  },
  "events": [
    "issues",
    "issue_comment"
  ],
  "authorization_header": "",
  "active": true,
  "updated_at": "2024-04-30T05:20:15Z",
  "created_at": "2024-04-30T05:20:15Z"
}
```

The `pull_request` event also does something similar to this as well. It is weird seeing that we need to pass `issues_only` event only to return an `issues` event. I would rather have `issues` be what we expect it to be and instead use a `issues_all` so that we know that we are trying to listen to all issue-related events.

**Comment by Android-X13** [comment]
Both `issues_only` and `pull_request_only` work fine. Should I close the issue then?
