### ISSUE TITLE
Gogs migration tool

### ISSUE THREAD

**Issue by officereso** [go-gitea/gitea#30983]
### Feature Description

I currently have a gogs deployed v0.14, specifically commit https://github.com/gogs/gogs/commit/c8cd3e712519c1361b8ee47357ee9e2c777c8179. It doesn't seem like there's any good way to migrate over to gitea anymore. 
The steps documented on the wiki are problematic 
1. "Copy gogs/custom/conf/app.ini to gitea/custom/conf/app.ini"
  a. Several config options found in a modern app.ini arnt recognizable to gitea
2. mysql_native_password
  a. If this was resolved the steps provided on the wiki to migrate the database over might maybe work. Doesnt seem like gitea supports modern MySQL8 authorization plugins making the steps "Launch every major version of the binary" not possible. Earliest version that I tried that could actually login to mysql was 1.6.4, but by then gogs and gitea had already differed.
  
It would be really nice to have a proper tool that can be ran either against the gogs database or maybe the gogs backup zip that can convert it over to gitea.

**Comment by lunny** [comment]
Since Gitea's code base is totally different from Gogs, I don't think there is any easy way to do that and I can't expect it in the future. Because no Gitea maintainer would like to read Gogs' code. There are two ways to migrate to Gitea from Gogs now.
 - Migrate one repository by one repository with Gitea's UI or API, you can easily write a script to do that. But since Gogs's API doesn't cover all the features, only a part of them will be migrated.
 - Migrate only git data to Gitea. You can use Gitea's adopt repository feature to import all the repositories one time.

**Comment by officereso** [comment]
I did manage to get most migrated with the exception of avatars by making some modifications to this sql script. https://github.com/lesh59/Gogs2Gitea. I think a bulk of the work would just be database related, although I'm not familiar enough with either code base to say for certain.

**Comment by lunny** [comment]
The git hooks, avatars/lfs/attachments and etc. folder structures may also be different.

**Comment by techknowlogick** [comment]
We have a built-in migration tool from Gogs, which is now the recommended path due to the structure of the two projects changing so much.
