### ISSUE TITLE
Show more lines button seems have two styles?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#31068]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/94f3f239-ec53-426e-a597-39bfe1fde8c2)
https://gitea.com/gitea/changelog/pulls/85/files

not sure whether this is a bug

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

gitea.com

### Database

None

**Comment by silverwind** [comment]
Does GitHub have this? I think they don't and I think it would be better to just always expand in both directions from UX perspective.

**Comment by yp05327** [comment]
I didn't look into it, if we know the PR's id, we can check the discussion.

**Comment by silverwind** [comment]
GitHub does [have this too](https://github.com/microsoft/TypeScript-TmLanguage/commit/06a03eb510673e3b4a522d90a0d1abf4d4aefa66). I think we can do the vertical style instead of the horiztonal one.

<img width="143" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/805a7c95-ca94-4179-81fa-60d56a136659">
