### ISSUE TITLE
distinguish milestones on issues page (opened vs. closed)

### ISSUE THREAD

**Issue by znegva** [go-gitea/gitea#3114]
- Gitea version (or commit ref): 311c83a
- Git version:
- Operating system: ? try.gitea.io
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the ~~bug~~ issue at https://try.gitea.io:
  - [x] Yes <https://try.gitea.io/test/milestones-issue/issues> (login is test:test)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Sorting issues by milestones should distinguish the milestones by _opened_ and _closed_ milestones.
This would improve usability, since one rarely searches/filters for issues of already closed milestones.

A separation between _opened_ and _closed_ milestones is already done when selecting a milestone while creating an issue. I think the UI there is good and should be reused in the issues-overview page.

## Screenshots

__overview of issues, sorting by milestone:__  
![milestones_sort_issues](https://user-images.githubusercontent.com/7450884/33715982-c04895de-db54-11e7-808b-e0f45a2556e1.png)

__creating an issue, selecting milestone:__
![milestones_create_issue](https://user-images.githubusercontent.com/7450884/33715981-c029bfa6-db54-11e7-81cf-d92f24506840.png)

**Comment by bugreport0** [comment]
+1. Today I found out that closed milestones are still listed in the 'Issues' page filter box, I expected them to disappear from view once closed. Because of #4984 old milestones will now forever be in the way at the top of the box.

I think we should either:
- hide closed milestones except for the 'Milestones' page where you can retrieve issue lists for closed milestones; or
- separate milestones in filter boxes into categories as suggested here, with closed milestones at the bottom.

**Comment by adelowo** [comment]
@bugreport0 , #4984 was fixed by #4987 already.. It would be in the `1.6.0` release
