### ISSUE TITLE
Can’t use custom URLs for authentication sources

### ISSUE THREAD

**Issue by FifoF** [go-gitea/gitea#31244]
### Description

Whenever I try adding a custom auth source, I can’t see the option to add a custom URL. I checked it using dev tools and the `tw-hidden` class hides it.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/8145202/6ee94ec8-5445-4859-82cc-1cf9b5df4cbd)

### Gitea Version

v1.22

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

macOS 11.5.1

### Browser Version

Opera GX 109.0.5097.108 (x86_64)

**Comment by wxiaoguang** [comment]
->  Fix admin oauth2 custom URL settings #31246

**Comment by wxiaoguang** [comment]
Let's keep the issue open until the PR is merged ...

Sorry for the inconvenience and thank you very much for the report.

**Comment by wxiaoguang** [comment]
If you are using binary, the new nightly build is ready https://dl.gitea.com/gitea/1.22-nightly/ , it will become 1.22.1 soon.

If you are using docker .... the nightly rootful one is ready but the rootless one is not due to some network error.

You could track the build progress here https://github.com/go-gitea/gitea/commits/release/v1.22

Could you try if 1.22-nightly works well for you?

![image](https://github.com/go-gitea/gitea/assets/2114189/fdeb2574-0492-4452-8163-5b6d1de45a29)
