### ISSUE TITLE
 Italian alphabet onlyin repo + org names

### ISSUE THREAD

**Issue by icf20** [go-gitea/gitea#31345]
### Description

Apparently repo and organizations names cant have

ñ, ç, ț, ă, â, ș, î

yes "Gobierno de España" the Spanish government is not allowed to be an organization 

![image](https://github.com/go-gitea/gitea/assets/17784575/d2359e5c-6a41-49f7-8d63-546ef77c66cb)

dont ask to have ñ->n, last time White House did that i went from feliz año to feliz ano 

### Gitea Version

1,22

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/17784575/c06d2de1-41e6-4e5e-81d1-f1b09aff90da)

### How are you running Gitea?

container

### Database

None

**Comment by delvh** [comment]
> I guess it'd be fine to make this regex configurable

Not a good idea.
We **cannot** control what you write into the regex.
Why is not being able to validate it a bad idea?
Well… the org names must appear on your file system.
I have no idea how well OSs like Windows handle certain names.
Or even Linux, as special chars in a filename are always a good idea to annoy your server admin to no end.
And since we cannot validate the regex, this will lead to hard to understand error messages, and thus pissed off users.
So no, I'm not a fan of allowing non-ASCII chars.

**Comment by silverwind** [comment]
Recent filesystems handle unicode pretty well, but still it's likely better to not let the user unknowingly break the portability of their repos.

**Comment by lunny** [comment]
I don't support relaxing the limitation except the git file system structure has been changed.
