### ISSUE TITLE
Cannot register with OpenID

### ISSUE THREAD

**Issue by mcepl** [go-gitea/gitea#31449]
### Description

When I register using OpenID everything works perfectly until I get the activation email, which leads me to the form which requires a password. At this moment I cannot insert any password (because my account is not properly activated), and I don't even get a button for resetting the password.

### Screenshots

![Screenshot 2024-06-21 at 15-57-17 Gitea Git with a cup of tea](https://github.com/go-gitea/gitea/assets/198999/ef082a5e-ce07-4f0b-8927-d5d2b15bbf18)

### Gitea Version

gitea.com today

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

openSUSE/Tumbleweed

### Browser Version

Firefox 127

**Comment by wxiaoguang** [comment]
gitea.com, or your own instance, or both?

**Comment by mcepl** [comment]
On Fri Jun 21, 2024 at 4:39 PM CEST, wxiaoguang wrote:
> gitea.com, or your own instance, or both?

gitea.com, I don't have my own instance.

**Comment by wxiaoguang** [comment]
Hmm .... maybe it is a bug in Gitea or a configuration problem in gitea.com, maybe some other maintainers could help to figure out.

**Comment by mcepl** [comment]
No, I suspect, that there are just so few users of OpenID that nobody thought about it.

**Comment by techknowlogick** [comment]
Pinging @strk as I know you are a user of openid on Gitea.com

**Comment by mcepl** [comment]
And of course, I would prefer if I would never have to create a password at all.

**Comment by mcepl** [comment]
ping? @strk ?

**Comment by strk** [comment]
Reading this now.

IIRC the OpenID signup screen creates a temporary password which is never given to the user just because as [expressed](https://github.com/go-gitea/gitea/issues/31449#issuecomment-2184150061) by @mcepl OpenID users don't want to deal with passwords...

Why is try.gitea.io not giving the OpenID option ? We'd want to test this there to ensure it can be reproduced.

The "forgot password" link is found on the login page, did you try it ?
For gitea.com the page would be: https://gitea.com/user/forgot_password

What is the rationale for the account confirmation screen to require a password ? I'd think a confirmation button should be enough.

**Comment by mcepl** [comment]
Hmm, I don’t know if anything changed, but the password recovery worked now, and I got reactivation prompt only after recovering of the passport. So, no, I still don’t think it is possible to have OpenID-only account, but at least I have now functioning gitea.com account.

**Comment by strk** [comment]
See also #3521 for a more generic ticket about all the places that ask for a password conflicting with password-less logins.

**Comment by strk** [comment]
See also #1036 for a generic discussion about how to deal with password-less accounts
