### ISSUE TITLE
Admin User Emails page does not allow deleting, changing or adding emails

### ISSUE THREAD

**Issue by hawicz** [go-gitea/gitea#31571]
### Feature Description

As an admin, I should be able to delete an email for a user through the "User Emails" page under Site Administration.
Currently, the only action possible there is to activate or deactivate an existing email.

It would be nice to be able to add an email there too, though the workaround for that is to change the email from the "Edit User Account" page (which adds a new email, rather than changing the existing one)

It would also be nice to be able to change an existing email without needing to add and delete.

I'll note that there is an API endpoint (DELETE /user/emails, with SudoHeader set) but apparently no UI support.

**Comment by SunnyWan59** [comment]
I'm not too sure if being able to add and delete emails addresses directly in 'user emails' would make much sense because you can already add/delete a user with the corresponding email. However, I do think it could be helpful to change the emails on the page, I would be happy to work on this if possible.

**Comment by wolfogre** [comment]
I think it could be closed by #31690
