### ISSUE TITLE
PR Review Add Comment increments counter in Review button but CTRL+Enter shortcut doesn't

### ISSUE THREAD

**Issue by encoder9** [go-gitea/gitea#31622]
### Description

When reviewing a PR, adding a comment via the Add Comment button will increment the counter presented in the Review button in the top right corner.

When adding a comment and using the CTRL+Enter shortcut, the comment is added correctly, but the counter is not incremented.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

We're running a docker container on a Linux VPC

### Database

None

**Comment by henrygoodman** [comment]
I'm looking into this one now. Looks like the on submit functionality doesn't trigger correctly when ctrl+enter submits the form.

**Comment by henrygoodman** [comment]
I've actually encountered another bug (its similar enough to just mention here instead of creating a new one), this is also replicable on Gitea demo site if anyone can confirm.

- PR Diff Page
- Click `+` to add new comment (open dialog)
- With empty textarea, click `Start Review` (or `Add Comment` if review already started) (click 10 times)
- Observe the Review comment counter increments by 1
- Enter some text so the `Start Review` button becomes 'clickable', click `Start Review`
- Observe the comment now submits but the Review comment counter has incremented by 10 (should only be 1 for the 1 valid submission)

**Comment by henrygoodman** [comment]
https://github.com/go-gitea/gitea/pull/19612

May relate to above issue (comments go over some guidelines anyway about frontend code which may be pertinent)

**Comment by wxiaoguang** [comment]
I think it could be fixed by this:  Fix PR diff review form submit #32596
