### ISSUE TITLE
@mention, _italic_, **bold** are not rendered in titles

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#31888]
### Feature Description

Good day!

@mention, _italic_, **bold** are not rendered in titles.

`code lines` are.

The proposition: to handle them.

Thanks!

### Screenshots

![Screenshot_20240820_193225_Chrome](https://github.com/user-attachments/assets/2ebe23bf-53c0-4039-88e1-3315fc4fcd8f)

**Comment by lafriks** [comment]
I don't think the title should render them

**Comment by yardenshoham** [comment]
> I don't think the title should render them

I agree

**Comment by kuraga** [comment]
> > I don't think the title should render them
> 
> I agree

> `code lines` are.

Consistently?

**Comment by lafriks** [comment]
Yes because `code` escapes add context but bold and italic are used just for formatting and this is not really something that we want for titles (this is also consistent with GitHub), GitLab on other hand does not render anything but does render `@mention` and only when viewing issue itself but not in lists so I don't know how useful is that

**Comment by kuraga** [comment]
Thanks!
