### ISSUE TITLE
Pull Request access requires code access

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#32253]
### Description

Our Product Owner needs access to Pull Requests to review completed feature branches.

I gave him _Write_ Access to Pull Requests on `/org/company/teams/po/edit`

However, when he tried to go to PR page he got a 404 error (If I recall correctly). I also tried with _Read_ access, but it also did not work.

I had to give him _Code_ read access as well. The expecation would be, that with PR permission it would be possible to comment on  the PR, but without access to the other tabs (code).

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

None

**Comment by wxiaoguang** [comment]
->  Make owner/repo/pulls handlers use "PR reader" permission #32254

**Comment by yp05327** [comment]
IIRC, I have asked this question before, but no responses. I will try to find it. 🤔

**Comment by yp05327** [comment]
It is here:
https://github.com/go-gitea/gitea/issues/22985#issuecomment-1436222437
And the answer is:
https://github.com/go-gitea/gitea/issues/22985#issuecomment-1652861623

**Comment by wxiaoguang** [comment]
> It is here: [#22985 (comment)](https://github.com/go-gitea/gitea/issues/22985#issuecomment-1436222437) And the answer is: [#22985 (comment)](https://github.com/go-gitea/gitea/issues/22985#issuecomment-1652861623)
> 
> ps: maybe this is outdated. But actually some operations of PR still depends on code unit permission. and it is not documented, so users may confused about it.

That's not related. By design "reader" could always create issues and edit their own issues. "writer" could manage issues. It is not that intuitive but it was indeed designed as that. Just like any GitHub user (reader) could open issues in Gitea's repo.

**Comment by yp05327** [comment]
I'm not talking about issues, but the PRs below.
About issues, I can understand now. Thanks for your explanation.

At that time, user without code permission but have PR read permission can access the PR, and the problem is they can also review and approve it. This is what I want to say,

And it seems that it is related to this change:
https://github.com/go-gitea/gitea/pull/30519/files#diff-3f5521b3af1ddd518b1958e0799d7ab00254d39af04eb96dc00d59d2644eb30fR1564
All `reqRepoCodeReader` was removed to the parent group, but actually pull request does not have it. So the logic changed since this change I think.
![image](https://github.com/user-attachments/assets/c2fc49cb-6bca-4511-bf46-ccd80a38bb6a)

**Comment by wxiaoguang** [comment]
Yes, it is related to #30519, I made that change which is not ideal (or buggy), that's why I proposed a quick fix
