### ISSUE TITLE
Discord Webhooks should hide multiline commit details

### ISSUE THREAD

**Issue by quentinguidee** [go-gitea/gitea#32371]
### Description

While #31668 was resolved (thanks!), the messages of Discord webhooks is still hard/harder to read in some cases like this one :

<img width="371" alt="Capture d’écran, le 2024-10-29 à 19 30 32" src="https://github.com/user-attachments/assets/b400a245-111c-4a73-9759-264bacdfdd21">

Now, the message is truncated after 50 characters like GitHub, but I think that only the first line of the message should be displayed. See GitHub for comparison (these are also multiline commits) :

![image](https://github.com/user-attachments/assets/5928e5b9-edb5-4840-857f-b839db73c7b5)

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Linux

### How are you running Gitea?

Official docker image

### Database

PostgreSQL

**Comment by kemzeb** [comment]
Thanks for the report! This is unattended behavior... https://github.com/go-gitea/gitea/pull/31970 should have removed the commit description and just kept the summary:

https://github.com/go-gitea/gitea/blob/41b4ef825dba14f11b2e9454692b999f92ee1a42/services/webhook/discord.go#L159

Here we split the commit message with `\n` as the delimiter and we only choose the first line. It also removes any trailing `/r` if it exists.

Looking at the Go [docs](https://pkg.go.dev/strings#SplitN) further, I may have misused `SplitN()` and should have done:

```go
strings.SplitN(commit.Message, "\n", 2)[0]
```

... since the last element would be the "unsplit remainder" that the docs talk about. Currently we seem to be using the unsplit remainder (which would just be the message). Reading the code of `strings.SplitN()` also points to this being the case. That PR also had a unit test, but didn't catch this edge case since the commit summary was > 50 (while yours is < 50).

Not sure how I missed this. I'll be making a PR to correct this.
