### ISSUE TITLE
ALLOWED_HOST_LIST not honored

### ISSUE THREAD

**Issue by jacflesher** [go-gitea/gitea#32420]
### Description

i have added the configuration below and rebooted the server.  however i still get `webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting), deny '192.168.0.214(192.168.0.214:8080)'` when i hit the "test delivery" button in the webhook.  It's either a bug, or a result of very (very) poor documentation

`root@gitea:~# cat /etc/gitea/app.ini`
```bash
[webhook]
SKIP_TLS_VERIFY = true
DELIVER_TIMEOUT = 10
ALLOWED_HOST_LIST = *
```

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Screen Shot 2024-11-04 at 7 48 56 PM](https://github.com/user-attachments/assets/57c74443-d6d3-414f-802b-42e64b081e31)

### Git Version

git version 2.39.2

### Operating System

Debian 12

### How are you running Gitea?

binary

### Database

MySQL

**Comment by wxiaoguang** [comment]
Are you sure it is the content of your "app.ini"? It can't be that simple.

![image](https://github.com/user-attachments/assets/28df5308-8810-4b08-9529-721183574b40)

**Comment by yp05327** [comment]
> Are you sure it is the content of your "app.ini"? It can't be that simple.

It means maybe you edited the wrong config file which is not used.

For a possible way, you can get it from log.
![image](https://github.com/user-attachments/assets/79396fb4-9dcd-4d2e-8341-0d6b558dd747)

**Comment by jacflesher** [comment]
@yp05327 

what log?  there is in nothing for gitea in /var/log/ and there is nothing in /etc/gitea besides this app.ini i created myself.  strange that the certs do work when i put them in that file.  how can i get this log?  

the service status : 
jay@gitea:~$ systemctl status gitea
● gitea.service - Gitea (Git with a cup of tea)
     Loaded: loaded (/etc/systemd/system/gitea.service; enabled; preset: enable>
     Active: active (running) since Mon 2024-11-04 20:16:47 EST; 12h ago
   Main PID: 1123 (gitea)
      Tasks: 8 (limit: 2315)
     Memory: 119.2M
        CPU: 1min 8.209s
     CGroup: /system.slice/gitea.service
             └─1123 /usr/local/bin/gitea web

**Comment by jacflesher** [comment]
nevermind i found it!  maybe this step shoudl be included in your cheatsheet documentation?  would have saved me a couple days of pulling my hair out

```
root@gitea:/# find / -name app.ini
/var/lib/gitea/custom/conf/app.ini

**Comment by jacflesher** [comment]
thank you
![Screen Shot 2024-11-05 at 8 34 09 AM](https://github.com/user-attachments/assets/1b050278-d06e-485a-bb1d-e784d9424958)

**Comment by wxiaoguang** [comment]
> nevermind i found it! maybe this step shoudl be included in your cheatsheet documentation? would have saved me a couple days of pulling my hair out

When Gitea starts, it always tells the users which config file it is using, and you could also check it from the admin panel.

And the document also mentions it https://docs.gitea.com/help/faq#where-does-gitea-store-what-file

**Comment by wxiaoguang** [comment]
> what log? there is in nothing for gitea in /var/log/ and there is nothing in /etc/gitea besides this app.ini i created myself. strange that the certs do work when i put them in that file. how can i get this log?

The "log" is also covered by documents: https://docs.gitea.com/help/support

**Comment by jacflesher** [comment]
> > nevermind i found it! maybe this step shoudl be included in your cheatsheet documentation? would have saved me a couple days of pulling my hair out
> 
> When Gitea starts, it always tells the users which config file it is using, and you could also check it from the admin panel.
> 
> And the document also mentions it https://docs.gitea.com/help/faq#where-does-gitea-store-what-file

LOL
![Screen Shot 2024-11-05 at 9 15 16 AM](https://github.com/user-attachments/assets/9f2665c8-0355-4f87-9334-dbe7409f8a12)

**Comment by wxiaoguang** [comment]
![image](https://github.com/user-attachments/assets/9288de65-7742-4528-954e-a5204271d434)

**Comment by jacflesher** [comment]
> ![image](https://private-user-images.githubusercontent.com/2114189/383182444-9288de65-7742-4528-954e-a5204271d434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTY2OTMsIm5iZiI6MTczMDgxNjM5MywicGF0aCI6Ii8yMTE0MTg5LzM4MzE4MjQ0NC05Mjg4ZGU2NS03NzQyLTQ1MjgtOTU0ZS1hNTIwNDI3MWQ0MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTQxOTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg3NWVjNjdkZTM1NjQxZTEyODMwMzc0YTZkYjk2ODMwZDE1Njc2ODhhNTlmM2Y0NzExYzE3MjkxZGVhOTVjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.91VU8kzF-kOsjhYiTdjPUOA6FR6K05i9XyXdMvmJJVw)

can't you see why that's misleading to someone just starting out.   it wouldn't be hard to include this in your cheatsheet page... 

`Log files are usually located here... but you can also find them by using "find / -name app.ini" or watching the logs at startup`

Who knows how many people have been in my position and just given up because of the poor documentation.  If this was my product, I certainly wouldn't want folks to lose interest in my product because I can't property document the most common issues.  

 I'm a technical dev ops cloud native engineer supporting open shift kubernetes, google cloud, and cloud foundry for a company with about 50 thousand applications being hosted.  There's no way this should have been this difficult for me if the documentation was on par.  
 
 Take it from a real profiessional, your documentation sucks.

**Comment by wxiaoguang** [comment]
> can't you see why that's misleading to someone just starting out. it wouldn't be hard to include this in your cheatsheet page...

Sorry but I don't see why it misleads .... the screenshot you shown is in a section called "Can't create repositories/files", and it says it is for "Arch package systemd" and it is an issue (wrong config) which makes files non-writable, I do not think it is related to you question.

----

It seems that your question is about how to find the correct "app.ini" file. There is a section above called "Where does Gitea store what file", it says that `INI (config file) is CustomPath/conf/app.ini`, the `CustomPath` just matches your case `/var/lib/gitea/custom`. It should be able to answer all the questions. If you search "app.ini" in that page, it should be the first matched result.

The path rules are complex because in history many contributors have various requirements , so a lot of patches were added to it, then the problem becomes that the path system is too flexible. It really depends on how you installed the instance ......

----

About how to find the "app.ini" manually, I think `find / -name app.ini` is not a good approach in a production server, there might be a lot of files or event shared network volumes, etc. So the proper approaches could be:

* Use systemd to see the logs (it could assume every systemd user should be able to know how to use systemd log system).
* Go to admin panel's config page, some details are there (hmm .... maybe this is the easiest approach but never mentioned)
* Take a look at Gitea's data directory first, there is something.

----

The documents are also maintained by community contributors, It is always welcome to propose PRs to improve them. https://gitea.com/gitea/docs/pulls

ps: I am just trying to explain some details, and I am not a native English speaker, so sometimes my expression might not be accurate or right, that's why I didn't spend time on the documents ......

**Comment by jacflesher** [comment]
Yes that looks perfect! Thank you for doing that!  I thought to submit a PR
myself but thought it might be rude since I only just now started using
Gitea.  I’m loving it though.  Using it to help my wife learn how to
automate processes using CI/CD and IaC.

Also your English seems great to me

______________________________________
Jac Flesher
(586) 838-6885
