### ISSUE TITLE
Sign In Prohibited in my new account

### ISSUE THREAD

**Issue by polsegu** [go-gitea/gitea#32828]
### Description

I recently created a new account on this Gitea instance. After registering, I linked it to my GitHub account through the provided option. Everything worked fine initially, but after three days, I found my account blocked, showing the error message "Sign in prohibited."

I haven't performed any unusual actions or configurations during this time. I am unsure if the problem is related to linking my GitHub account or if my account was flagged for another reason.

Could you help me identify and resolve this issue?

### Screenshots

![image](https://github.com/user-attachments/assets/f6bc9de8-c3cc-46f8-a7c9-9802b7774c4d)

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows

### Browser Version

Chrome 131.0.6778.140

**Comment by lunny** [comment]
Is this instance owned by yourself?

**Comment by techknowlogick** [comment]
Apologies, @polsegu you are the second out of thousands accounts that have signed up with a Google sites URL and not be spam (not a reflection on you, it's just that spammers use that domain as well because it has Google in it and so it gets a boost for seo). So a lot of spam checkers just flag that domain automatically, including the one I use.

I will reactivate your account and put a flag on it to not be restricted again.

**Comment by polsegu** [comment]
Thank you for the clarification and for reactivating my account. I understand the situation and appreciate you taking the time to resolve it.

Thanks again for your help, and have a great day!
