### ISSUE TITLE
LDAP: gitea admin cmd missing groups

### ISSUE THREAD

**Issue by gregdymek** [go-gitea/gitea#32856]
### Description

I was trying to use gitea admin tool to setup ldap integration,
however the options I see running `gitea admin auth add-ldap --help` are limited comparing to what we see on the UI,
what we're missing is everything group related eg. `group_dn, group_member_uid`
are those options just missing in help or they are not supported?
thank you

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

using docker compose

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
> are those options just missing in help or they are not supported?

I think it a missing feature (not supported yet).  Usually the history is like this:  at the beginning, there is simple LDAP support and simple admin cli support, then some features are improved or changed, but the admin cli might not get updates at the same time.

Because many features are written by different contributors, so if the author didn't need or forgot something, then it would be missing and cause inconsistency. 🤣

**Comment by gregdymek** [comment]
ok, maybe I'll try to do it trough the UI (webscraping) or maybe with sql
