### ISSUE TITLE
404 on welcome page 

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#3362]
- Gitea version (or commit ref): Gitea version 1.3.2 built with: bindata, sqlite
- Git version: 2.15.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

https://gist.github.com/ShalokShalom/2abd30f454660d0d7fb64fca797b11af

## Screenshots

![screenshot_20180112_175243](https://user-images.githubusercontent.com/6344099/34886981-3d38fdf4-f7c5-11e7-853b-78376318765b.png)

**Comment by supervirus** [comment]
Hi,
I had the same problem on my uberspace 7 account, when gitea is used behind an apache as proxy.
Apache tried to open index.html, which doesn't exist...
After adding an additional rewrite rule for index.html everything was ok.

Here is the .htaccess im using:
```
RewriteEngine On
RewriteBase /
RewriteRule ^index.html http://localhost:12345/ [P]
RewriteRule (.*) http://localhost:12345/$1 [P]
```

**Update** instead of rewriting index.html it is better/easier to disabled mod_dir, which is the cause :
```
DirectoryIndex disabled
RewriteEngine On
RewriteRule (.*) http://localhost:12345/$1 [P]
```

**Comment by ShalokShalom** [comment]
Wonderful ^-^

**Comment by ShalokShalom** [comment]
Do you know something about this as well? https://github.com/go-gitea/gitea/issues/3361

Do the links on the explore page and the user pages direct you correctly to the repositories?
