### ISSUE TITLE
Repo indexer - empty results for specific documents

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3383]
gitea master version number d29aa76

Trying to use repository indexer, I seen that some results for specific documents (like JSP and JRXML), doesn't show the context:

![immagine](https://user-images.githubusercontent.com/6648129/34994357-85213d50-fad3-11e7-8e08-4ef6e44a45b7.png)

The line numbers are rights, but not text is showed in result.

To replicate this kind of problem, try to clone this test repo: [https://github.com/1212050/Shopping-web-Jsp-Servlet](url)
and try to search for "jsp" text.
You will see:
![immagine](https://user-images.githubusercontent.com/6648129/34994540-28e74f38-fad4-11e7-81ed-752934521feb.png)

**Comment by lunny** [comment]
Maybe an encoding problem?

**Comment by thehowl** [comment]
Hmmm... tested this on my own and... uhhh... why exactly is this not escaped?

(search HTML)

![image](https://user-images.githubusercontent.com/4681308/34994986-78b7d0f4-fad5-11e7-8ef9-d1aca716ada6.png)

(original file)

![image](https://user-images.githubusercontent.com/4681308/34995010-8947550c-fad5-11e7-8689-b3743ca96e67.png)

This can be seen pretty clerarly by XML tags being encoded as they are.

![image](https://user-images.githubusercontent.com/4681308/34995070-ba9782c6-fad5-11e7-8180-b8cf4471562b.png)

@lunny This is pretty critical because it's XSS. Please add to 1.4.0 and kind/security.

**Comment by ghost** [comment]
Thank you @thehowl , so, it's only needed to escape some additional strings to view the file text context, right?

**Comment by thehowl** [comment]
Yes, that's right.

**Comment by ghost** [comment]
Thank you very much guys. I will test that PR on master release as soon as drone will be able to build/release it
