### ISSUE TITLE
Error 500 when trying to add ed25519 ssh key

### ISSUE THREAD

**Issue by allgoewer** [go-gitea/gitea#3655]
- Gitea version (or commit ref): 1.4.0+rc2-2-g92a3061
- Git version: 2.7.4
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (try.gitea.io is offline)
- Log gist: https://gist.github.com/allgoewer/5cdc94ce997b9e1e5b2eb23a5678bb64

## Description
As the title says. When I try to add a ed25519 key, I get an Error 500

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMW2IwdNx+cZrptZLTa4JhtbkuJPmh0OsJRTlSWGJyrB testkey
```

## Screenshots

![ed25519](https://user-images.githubusercontent.com/6408150/37215632-c95b8dbe-23b8-11e8-80c6-204263af63da.png)

**Comment by ptrunk** [comment]
I dont think it's a generic problem. I can't reproduce it in a fresh installation. I think CentOS6 is the problem here. It is pretty old with a very old OpenSSH release which does not support ed25519 keys (so far as i know). 

The error 500 is not nice. Maybe the documentation should be updated to make clear that it is not a good idea to run Gitea on such old systems or even better there could be a check and a warning in the Webui if an unsupported OpenSSH version is running :-).

**Comment by allgoewer** [comment]
You are absolutely right, openssh is too old. Other than the missing ed25519 support, gitea seems to work fine.

**Comment by lafriks** [comment]
Best would be to detect this when checking key and return correct error that OpenSSH server does not support such key

**Comment by lunny** [comment]
I'll close this now and please feel free to reopen it.

**Comment by bogdanpetrea** [comment]
I have tried adding the deploy key provided in the issue description and it worked.
What always causes a 500 response for me is when I reuse an existing's deploy key title of the same repository, so maybe that was the issue @allgoewer experienced. It happens for any type of key, both in UI and API.
