### ISSUE TITLE
Missing .gitignore, licenses, cannot create repositories.

### ISSUE THREAD

**Issue by qwertyusdfghjkb** [go-gitea/gitea#3798]
- Gitea version (or commit ref): 1.3.0-dev
- Git version: 2.11.0
- Operating system: Debian 9 (stretch) 64bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [x ] Not relevant
- Log gist:

## Description

I installed gitea package from official debian repositories.
After installing this thing on my system and moving repositories from gogs (I just migrated them) I've found that:

.gitignore list is empty
![image](https://user-images.githubusercontent.com/38138290/38779099-f5904136-40c3-11e8-8a54-2b862d1244bc.png)

License list is empty
![image](https://user-images.githubusercontent.com/38138290/38779111-1232f6e4-40c4-11e8-83a2-80fc61878961.png)

Template readme list is empty, I can't even make that dropdown menu appear, maybe it's still work in progress feature?

When creating repository with this option checked:
![image](https://user-images.githubusercontent.com/38138290/38779135-554e87e0-40c4-11e8-8703-c42123decd5a.png)

I get error 500 on page /repo/create

Here is log from my gitea instance (/var/log/gitea/gitea.log):
```web@root /var/log/gitea # cat gitea.log
2018/04/15 06:25:11 [I] Log Mode: File(Info)
2018/04/15 06:25:11 [I] XORM Log Mode: File(Info)
2018/04/15 06:25:11 [I] Cache Service Enabled
2018/04/15 06:25:11 [I] Session Service Enabled
2018/04/15 06:25:13 [I] Git Version: 2.11.0
2018/04/15 06:25:13 [I] SQLite3 Supported
2018/04/15 06:25:13 [I] Run Mode: Production
2018/04/15 06:25:13 [I] SSH server started on *cut*
2018/04/15 06:25:13 [I] Listen: http://0.0.0.0:3000
2018/04/15 06:25:13 [I] LFS server enabled
2018/04/15 09:49:09 [...routers/repo/repo.go:123 handleCreateError()] [E] CreatePost: initRepository: prepareRepoCommit: getRepoInitFile[Default]: Asset file does not exist: readme/Default```

**Comment by kolaente** [comment]
A workaround would be to download the templates from `master` or a release (dl.gitea.io) and then copy the templates manually into `/options` under the install folder.

Are there any folders inside of `/options`?

\cc @strk

**Comment by qwertyusdfghjkb** [comment]
> copy the templates manually into /options under the install folder.

I installed debian package from official repository so I just quered dpkg database.

```web@root ~ # dpkg-query -L gitea-common |grep options
/usr/share/gitea/templates/org/settings/options.tmpl
/usr/share/gitea/templates/repo/settings/options.tmpl
web@root ~ # dpkg-query -L gitea |grep options
```
Even if I'll copy `options` from dl.gitea.io then this problem will come back after package update.
Also, that probably idicates that debian package is just broken (missing files).

And I also don't know where I am supposted to put `options` since my installation root is basically entire OS.

**Comment by lafriks** [comment]
This seems to be packaging problem

**Comment by qwertyusdfghjkb** [comment]
@lafriks So how am I supposted to fix that then? Or should I just wait for someone to fix that package and then update it?

**Comment by techknowlogick** [comment]
ping @MTecknology

**Comment by MTecknology** [comment]
The first thing that needs to be stated is that the gitea package in contrib is *NOT* official. It's the closest thing there is (within the debian ecosystem), but it's not official until it's in main, and that is not likely to ever happen. I spent a year of my life working 50+ hours per week trying to get gitea properly into debian and I had to fight upstream every step of the way.

At this point, there are still two major packages (and all subsequent dependencies) that would still need to make it into debian before gitea could ever have a chance of becoming an official debian package.
- https://wiki.debian.org/Javascript/Nodejs/Tasks/swagger-ui
- https://wiki.debian.org/Javascript/Nodejs/Tasks/semantic-ui

There are also many packages that have been dropped from Debian due to incompatibilities between minor version bumps. Most of them wouldn't be too hard to bring back, but the constant vigilance to keep testing and re-testing and re-re-testing is way too much effort for one person.

I've had many ask how they could help, some claiming they'd help once I was able to build something that worked. This is why I stuck it into contrib. Considering that nobody has stepped up in nearly a year, I intend to file a request to remove this package from contrib. ... thanks for the reminder.

If anyone wants to step up and help, I'm wore than willing to teach what I can. Without help, this is too much for a single person to deal with.

(p.s. I'm in the hospital hyped up on pain killers; please forgive typos and tone.)
