### ISSUE TITLE
host static html and/or markdown pages

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#3834]
other than the wiki, is it possible to host static html and/or markdown pages in gitea? similar to what github does, if possible, make those page only accessible after login as what wiki does, is this possible?

this way I can host documentations along with source code in gitea and be able to view the doc via web.

**Comment by lunny** [comment]
I think we could listen another port which defaultly don't open to host the generated web site.

**Comment by pedro-ricardo** [comment]
Is there a way to vote for this? I'ts been quite a while since this feature was requested . . .
We use Gitea in our company and the software documentation is automatically generated in html. Those files are committed and kept in the repo.
If there was a way to access (serve) those html files as easy as accessing the Wiki page ... It would be awesome.

In my opinion it makes "keeping the documentation up to date" a much easier job.

**Comment by koalp** [comment]
@pedro-ricardo I think that you can add a “thumb up” reaction to the comment of the issue.

I previously upvoted this feature but now think that it isn't in the scope of gitea and should rather be a different software, that way it could be used with other software forges. (however, no such software exist yet to my knowledge).

**Comment by pedro-ricardo** [comment]
I see, thanks I'll do it ... 
I think this issue and the duplicates that show up from time to time are a request to implement something like GitHub offers and people liked it. 

In my opinion it is a way to keep stuff like software documentations in the repository, instead of the separated Wiki markdown pages. And by doing that it increases the maintainability of this documentation.

**Comment by 6543** [comment]
In my opinion its also not in scope of gitea ...

And there exist software: https://codeberg.org/momar/codeberg-pages

**Comment by 6543** [comment]
A nice "hack" you cold also do: use external renderer 'cat' to show html files rendered like you have with markdown ;)

https://docs.gitea.io/en-us/external-renderers/

**Comment by laoshaw** [comment]
considering github is using pages separately from the code repository, displaying html from the same repository is probably technically 'impossible', it has to have its own (http) port.

but github/gitea can render markdown right inside the repository pretty well, similar to those syntax highlighted source code files, it's just hard to navigate(e.g. built-in octotree), so making all document as markdown files might be the way out(instead of html)

markdown can show images directly in gitea, however it can not _directly_ support video playing(be it a local video file or a video link to, say, youtube), you have to click on it and play them in a separate gitea window, which is a pity, otherwise I'm fine with markdown for all my documentations.

**Comment by pedro-ricardo** [comment]
Hold on @laoshaw ... This whole operation was your idea ... :laughing: 

We use html because it is automatically generated, looks pretty and it is easy to navigate  ... 
About being easier in comparison of with Markdown, I was just talking about the Wiki pages that are stored in a separated place.

And in the end ... Well, I'd like it ... But if it is out of the software scope, let's just move on. :+1:

**Comment by 6543** [comment]
UPDATE: the project (now at https://codeberg.org/Codeberg/pages-server) is now [live](https://codeberg.page) and I'm currently refactoring stuff to make it usable to all gitea instances who want that feature

can we close this issue?

**Comment by laoshaw** [comment]
Yes Thanks.
