### ISSUE TITLE
BUILTIN_SSH_SERVER_USER config variable not acknowledged by gitea

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#3847]
- Gitea version (or commit ref): bae2642
- Git version: 2.15.0
- Operating system: Docker/CentOS
- Database (use `[x]`):
  - [X] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant (don't have access to infra to see)

## Description
Under the `[server]` configuration section I've set `BUILTIN_SSH_SERVER_USER` to sample, and the web interface still shows `git` (which is the RunUser), however per https://github.com/go-gitea/gitea/blob/bec69f702ba8ecdc9a77db34ff94b7e55879be59/models/repo.go#L864 the configuration variable should overwrite that for the web interface.

## Screenshots
![screen shot 2018-04-24 at 7 25 16 pm](https://user-images.githubusercontent.com/164197/39218922-59b2055e-47f5-11e8-9dbe-d69f8d9e807f.png)

Related PR: #2678
cc: @geek1011

**Comment by pgaskin** [comment]
This setting only works if you are using the built-in ssh server. Are you sure you enabled it instead of using the system SSH server?

The following settings must be set:
- SSH.Disabled to false
- SSH.StartBuiltinServer to true
- SSH.BuiltinServerUser to a nonempty string

If this is all correct and it still happens, it is probably a regression (as it works fine on my server, which uses an older version of Gitea (I've been short on time to update it)).

**Comment by techknowlogick** [comment]
@geek1011 Yup. That was my problem, thank you. It's now displaying as it should.
