### ISSUE TITLE
ldapi:// integration

### ISSUE THREAD

**Issue by SchoolGuy** [go-gitea/gitea#3869]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.7.4
- Operating system: Ubuntu 16.04LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: Not relevant

## Description
I would like to close my port for ldap:// and instead use ldapi:// to retrieve data from my DIT. This is currently not possible because of the required port-number (and lack of implementation).

If this is a feature you would like to implement I would do it in the following order
- Check the ldap.v2 module for support of `ldapi://` (I found nothing for and against it)
- Implement the `ldapi://` in `gitea/modules/auth/ldap/ldap.go`
- Add a new frontend page in the adminstration section where the port field is missing.
- Test the changes

Sadly my knowledge of Go is zero and my time is to limited to learn go and contribute here.

**Comment by skruppy** [comment]
For my local setup, I have made a [patch](https://github.com/Skrupellos/gitea/tree/ldapi), which lets users specify an LDAP URL instead of a hostname/port combination. But I guess it is not ready for a PR, since it's missing migrations (and I have neither clue nor time to write one :disappointed: ).
