### ISSUE TITLE
Allow access to repositories for active accounts without login permission

### ISSUE THREAD

**Issue by lenidh** [go-gitea/gitea#3957]
- Gitea version (or commit ref): 1.4.1
- Git version: 2.11
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
The current behaviour was introduced with PR #3887 and #3889. Before it worked as expected.

### Expected behaviour
A user account with "Account activated" and "Login disabled" both enabled should not be able to login into the web interface but may access a git repository to which access was granted.

### Actual behaviour
A user account with "Account activated" and "Login disabled" both enabled can neither access the web interface nor a git repository.

## Screenshots

Account options:
![gitea-account-settings](https://user-images.githubusercontent.com/4013111/39961591-d609c18a-5639-11e8-9cbe-37981ab5b1be.png)
Output when accessing a repository:
![gitea-access-error](https://user-images.githubusercontent.com/4013111/39961592-de12c048-5639-11e8-92e7-aa30ff71477d.png)

**Comment by lunny** [comment]
I would like the current behaviour.

**Comment by lunny** [comment]
For non-actived user, he's profile cannot be view by others and his repository will not be visited too.
For login disabled user, he's profile and repository could be visited but he cannot login and cannot change his settings and repositories and cannot clone his private repositories.

**Comment by JacquesOfAllTrades** [comment]
Since this issue is still open, I'd like to go on record by agreeing with @lunny. I would interpret "login disabled" to mean that the user's ability to authenticate has been revoked. And if the user isn't allowed to authenticate, they're in effect anonymous, meaning they can access only resources that are public.

Furthermore, it would be a major security hazard if a Gitea update suddenly granted new privileges to disabled users.

The Deploy Key approach seems reasonable. Or simply strip the user in question of all privileges except access to the necessary repository(ies).

**Comment by zeripath** [comment]
Of note, it's possible for site Admin users to Sudo as these accounts under the API.

**Comment by lunny** [comment]
I think this could be closed now. Please feel free to reopen it.
