### ISSUE TITLE
List rendering from "1", instead of "0"

### ISSUE THREAD

**Issue by lstolcman** [go-gitea/gitea#4021]
- Gitea version (or commit ref): c14870c
- Git version: 2.7.4
- Operating system: Ubuntu 16
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/testlist/testlist)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```markdown
# test list from zero
0. zeroth element
1. first element
2. second element
3. third element
```

## Description
I created README.md with list starting from number zero (0). Gitea renders it from number 1.

## Screenshots

https://i.imgur.com/KgJyPOc.png

**Comment by lafriks** [comment]
Depends on upstream russross/blackfriday#385

**Comment by delvh** [comment]
Well… this issue is outdated by now. It is possible to have lists starting from 0 by now, but they have their own bugs when being nested:
![image](https://user-images.githubusercontent.com/51889757/235307613-24167b39-74d4-4118-bbf7-9e4105a540d3.png)
However, when there's no nesting, they work as expected:
![image](https://user-images.githubusercontent.com/51889757/235307648-b40fba6d-37c2-4325-8b40-76c7906653cb.png)
