### ISSUE TITLE
Gitea website does not properly display newlines in commit messages

### ISSUE THREAD

**Issue by LouieK22** [go-gitea/gitea#4060]
- Gitea version (or commit ref):
- Git version: 773530c
- Operating system: Docker on Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/LouieK22/newline-test
  - [ ] No
  - [ ] Not relevant

## Description
When a commit message contains a newline it is not displayed on the Gitea website.
...

## Screenshots
![](https://i.imgur.com/OjMcEO3.png)
![](https://i.imgur.com/zxkR4ih.png)
The screenshots should have another line that read "WIP and Disabled"

**Comment by lafriks** [comment]
Can you reproduce that on try.gitea.io?

**Comment by LouieK22** [comment]
Yes ![](https://i.imgur.com/aPAeEzZ.png)

**Comment by lunny** [comment]
It's some critical, so I moved it to v1.5.0 and added backport

**Comment by sondr3** [comment]
This might be related to my expandable commit bodies PR, are the lines separated by a `\n` or something else? Cause I forgot that Windows for example does new lines differently than Linux, so it might be a editor issue. 

On second though, this is likely related to the above but more because you didn’t split the lines apart by a double new line. I’m in the middle of my exams so I won’t be able to test myself for a week or so, but if it still is an issue I’ll take a look.
