### ISSUE TITLE
downloadable offline docs

### ISSUE THREAD

**Issue by reclaimed** [go-gitea/gitea#4086]
hello there. it's not a problem to make an offline dump of your docs, however, it would be nice if you could add a way to download a ready to use docs package in html or pdf.

**Comment by sapk** [comment]
The docs is generated via hugo from files inside docs/ folder. I think it is possible to provide an offline copy. You can also directly read markdown file like https://github.com/go-gitea/gitea/blob/master/docs/content/doc/advanced/config-cheat-sheet.en-us.md

**Comment by warren-bank** [comment]
I wanted offline docs for gitea as well, so I just wrote [a tool](https://github.com/warren-bank/save-website-to-pdf/tree/master/tests/01.%20gitea.io) to generate a PDF document from the static html files on the [public website](https://docs.gitea.io/en-us/).

In the past, I've used calibre to convert markdown to pdf. But the way these docs were structured, it didn't seem possible without using hugo to compile them to html. Since the website already hosts these files, recursive download (using wget) and conversion to pdf (using prince xml) seemed like the better/simpler/most-reusable approach.

Attached is the current (circa v1.12.1) manual.
[gitea.io.pdf](https://github.com/go-gitea/gitea/files/4888894/gitea.io.pdf)

**Comment by lunny** [comment]
We could generate pdf or html files and publish them to dl.gitea.io/docs when ci generated docs.

**Comment by warren-bank** [comment]
That would be great if your ci pipeline could generate a pdf that gets published. Big +1..

**Comment by lunny** [comment]
It seems pdf is not supported by hugo. We could zip the output html directory.

**Comment by warren-bank** [comment]
I suppose that's better than nothing. In terms of using such an archive in lieu of crawling the site (which takes less than 1 minute) as input to a tool that can generate pdf, the missing ingredient would be a sitemap that contains an __ordered lists__ all of the html files in the archive. Such a sitemap could be used for 2 purposes. (1) generate a TOC. (2) order the pages in the resulting pdf document.
