### ISSUE TITLE
Move from Github

### ISSUE THREAD

**Issue by Allanitomwesh** [go-gitea/gitea#4108]
Gitea is being recommended as an alternative to GitHub now that Microsoft has bought it. It was just pointed out to me that Gitea source code isn't on a Gitea. Kindly consider this issue.

**Comment by coolaj86** [comment]
How much do you need? Put a button and link to Patreon and you'll get it overnight.

You can't get what you don't enable people to give! (https://github.com/go-gitea/gitea/issues/561)

**Comment by techknowlogick** [comment]
@coolaj86 as @lafriks said in the linked post:

> ... as Gitea is purely community for driven there is no way we could set up paid private repositories as that requires creating company, dealing with taxes, and have full time staff to deal with technical problems

Although there is an opencollective to support hosting of the servers the project currently uses for CI, website, docs, and a few other things:  https://opencollective.com/gitea

**Comment by coolaj86** [comment]
It'll be like $5/month on Digital Ocean (or Vultr) if my off-hand guess based on stars, contributors, and watchers is correct.

If you were using gitea for your project and including google analytics (I am as described at https://git.coolaj86.com/coolaj86/gitea-installer.sh) you'd know how many hits you're getting per day and it would be super easy to estimate.

I've customized my theme to make "login with github" super prominent 
(as seen at https://git.coolaj86.com/coolaj86/gitea-installer.sh) and I get plenty on contributors. Only occasional issues due to https://github.com/go-gitea/gitea/issues/3837

Re: https://opencollective.com/gitea# PUT A FREAKIN GOAL AND DONATE BUTTON IN THE README. You don't get what you don't ask for!! (just like the lady says https://youtu.be/Gj5L9SYhoSE?t=119) 

Set a goal and put it on the main page on the readme. I love this project and hope to see it grow, but if you think that you're getting enough traffic for hosting for this repository to be expensive, I think you're over estimating it's popularity (which I would LOVE to see grow even more).

**Comment by benyanke** [comment]
Same.

I don't have a ton of budget room, but I would commit to a small amount monthly. Don't be ashamed to ask for money - you make a good product. If you have more than the infrastructure needs, you even get some to take home - _and that's a good thing_.

**Comment by techknowlogick** [comment]
Thanks you both @benyanke and @coolaj86 (and others as well) for the backing of the opencollective. It is really appreciated. From my point-of-view (which is mine alone and may not be shared by other contributors) is that Gitea is almost there, just a few features that are missing until we can get there, however as we all have other commitments (day jobs, school, family, etc..) it is hard to commit to specific timelines.

I'm going to close this ticket as it is marked as a dupe, but I don't want this conversation around self-hosting to end as it is an important one so please feel free to continue it in #1029
