### ISSUE TITLE
ALLOW_ONLY_EXTERNAL_REGISTRATION Appears to have no effect

### ISSUE THREAD

**Issue by internalfx** [go-gitea/gitea#4226]
- Gitea version (or commit ref): 1.4.2
- Git version: 
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

`ALLOW_ONLY_EXTERNAL_REGISTRATION` Appears to have no effect

## Screenshots

![image](https://user-images.githubusercontent.com/583701/41250121-dcafe2d8-6d6a-11e8-9927-4180b4061045.png)

![image](https://user-images.githubusercontent.com/583701/41250088-c85e1aac-6d6a-11e8-9082-fedbdd58fa2c.png)

**Comment by techknowlogick** [comment]
Can you try setting `DISABLE_REGISTRATION` to `true` (and leaving the other settings the same)?

**Comment by internalfx** [comment]
That "works" but now you can't signup at all....

![image](https://user-images.githubusercontent.com/583701/41250586-38d44490-6d6c-11e8-901c-3d6e41150d78.png)

**Comment by L-P** [comment]
Do you have any external auth configured?

![auth](https://user-images.githubusercontent.com/947312/41345062-eca739c2-6f02-11e8-8e81-fcc45448673a.png)

**Comment by internalfx** [comment]
yep, two of them....

![image](https://user-images.githubusercontent.com/583701/41353133-274de734-6ed0-11e8-8197-d802da0d4040.png)

**Comment by L-P** [comment]
My bad. I actually have the same issue where I need to create a standard account beforehand and allow the user to link it himself.

This is a bug/evolution already described in #3520

**Comment by lafriks** [comment]
Marking as duplicate of  #3520 than, please reopen if it is not

**Comment by internalfx** [comment]
@lafriks I don't think this is a dup.

They are discussing different config options. I think a core dev may need to read both issues and make a determination, but they _seem_ different to me.

**Comment by lafriks** [comment]
As I said feel free to reopen :)

**Comment by internalfx** [comment]
@lafriks You original statement was perfectly clear. My hesitation was that I reasoned that it might be possible that both bugs are caused by the same issue. However, they _appear_ different, so I thought a developer would make the best determination, hence, my comment.

**Comment by coolaj86** [comment]
I've begun work on a fix for this: https://github.com/go-gitea/gitea/pull/5029

If you'd like to test it out
====

My pull request is against `master`, but [I run it](https://git.coolaj86.com) as backport to v1.5.1 (includes https://github.com/go-gitea/gitea/pull/5006, https://github.com/go-gitea/gitea/pull/5029, https://github.com/go-gitea/gitea/pull/5033):

```bash
git clone https://github.com/coolaj86/gitea.git gitea.coolaj86 -b v1.5.1-coolaj86
pushd gitea.coolaj86
TAGS="bindata sqlite" make generate all
```

I would not recommend replacing your existing gitea, but rather creating a symlink so that you can easily switch back if you don't like it. For example, if you keep `gitea` in `/opt/gitea/bin`:

```bash
rsync -av ./gitea /opt/gitea/bin/gitea-v1.5.1-coolaj86
pushd /opt/gitea/bin
mv gitea gitea-v1.5.1
ln -s gitea-v1.5.1-coolaj86 gitea
```

I've run a couple of manual tests so far, so I feel comfortable with someone else trying it out. I won't be pushing any additional changes to that branch (such as the upcoming changes to address the empty checkboxes in the issue) until I've tested them in production for myself.
