### ISSUE TITLE
custom templates

### ISSUE THREAD

**Issue by Dozecloud-llc** [go-gitea/gitea#4298]
Need help using custom templates.

**Comment by lunny** [comment]
Please see https://docs.gitea.io/en-us/customizing-gitea/

**Comment by Dozecloud-llc** [comment]
The custom folder does not change anything.

**Comment by gdiepen** [comment]
Did you restart gitea after you made changes in the custom folder? From what I understand the changes you make to the templates while gitea is running are not being picked up.

**Comment by Dozecloud-llc** [comment]
When try do change the footer I get template: custom/footer:7:12: executing "custom/footer" at <{{template "custom/b...>: exceeded maximum template depth (100000)

**Comment by Dozecloud-llc** [comment]
I did restart and nothing changed. When I stated the server it started to work.

**Comment by techknowlogick** [comment]
@jsargent7089 are you putting the contents of `templates/base/footer.tmpl` into `templates/custom/footer.tmpl`? because that sounds like a recursion issue.

Edit: do you see `{{template "custom/footer" .}}` near the last line of your template?

**Comment by jsargent7089** [comment]
No I am not

**Comment by bkraul** [comment]
Question, why was this issue closed? Was there an actual resolution to the issue? Or was it because the reporter did not respond? 

I have the very same questions, and nothing I have tried has worked. I have read the document thoroughly, and nothing seems to work. I think we need clarification as to where this **custom** folder is to be placed.

I am using the docker implementation of gitea, and have tried a number of locations for the custom folder, but none seem to be picked up by gitea. I had a similar issue with labels a while back and sorted it out by looking at source. Haven't been that lucky with templates so far.

**Comment by lafriks** [comment]
@bkraul questions should be asked in Gitea forum - https://discourse.gitea.io/

As for custom folder it specified in `GITEA_CUSTOM` variable or by default it is `$GITEA_WORK_DIR/custom`

Custom templates need to be placed in `$GITEA_CUSTOM/custom/templates/custom/` directory

**Comment by bkraul** [comment]
Thanks @lafriks . Will go there for further questions.
