### ISSUE TITLE
Open redirect vulnerability on 2FA

### ISSUE THREAD

**Issue by glitch003** [go-gitea/gitea#4307]
- Gitea version (or commit ref): 1.4.1
- Git version: 2.17.1
- Operating system: Ubuntu 16
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description
**This bug was submitted via a Bug Bounty program my company has, and I'd love to hear your thoughts on it**

During the login process when the victim has entered his/her password and is then redirected to the page where he/she is told to enter his 2FA Code at this point the attacker will send a crafted link "https://try.gitea.io/user/login?redirect_to=//google.com/"

This crafted link will send this to same page he/she was viewing before and he/she will think it is a legitimate page is being loaded from "try.gitea.io"

Now they will enter there 2FA code there and will then be redirected on google.com or any other web page the attacker wants.

More info about open redirect vulnerabilities and why they're a problem:
* http://cwe.mitre.org/data/definitions/601.html
* https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet

## Reproduction

You must have 2FA enabled on your account.
1. Login at https://try.gitea.io/
2. You will be redirected to "https://try.gitea.io/user/two_factor"
3. Open this link "https://try.gitea.io/user/login?redirect_to=//google.com/"
4. Enter the 2FA Code
5. You will be redirected to google.com

**Comment by glitch003** [comment]
Wow that was fast, thanks all!

**Comment by cezar97** [comment]
Thanks for submitting a PR @glitch003  @JonasFranzDEV.
I reported this too some months ago but don't know golang for a fix... So I apologize to the Gitea Team, I know I send ( a lot? ) of emails about this because of it's impact.

**Comment by lunny** [comment]
Thanks @cezar97

**Comment by cezar97** [comment]
Hi, again.
I've just did some more test and I can say that this issue is not mitigated, I'm still able to redirect logins on external sites @JonasFranzDEV . An email to Gitea Team is coming in the next minutes ( Or maybe a public disclosure here on Github? See PS2. ). Hopefully this time I'll get a response and there will be a quick fix from the team...

PS: BTW It was nicer if I had a notification on Github ( mention? ) or an email saying that the issue is fixed and asking if I'm still able to reproduce it after the fix. I thought that's the usual workflow.

PS2: @go-gitea I'm disappointed of the security team beacuse there isn't a response and more important a fix from them...
It's also really sad that Gitea had always an Open Redirect and after more than two months I've reported this there wasn't an answer or a fix. Gitea users had to wait @glitch003 PR's to fix this.
What's the point of reporting vulnerabilities on mail if there isn't an answer or fix? Reporting them on Github seems to be a better solution because the users are aware of them and also get developers attention.
I'm waiting for an answer, after that I'll do my report accordingly.
( I don't know if mentioning @go-gitea notifies all members, anyway I hope all of them are going to know about my above thoughts)
EDIT: @lunny I appreciate the thanks but what's really the point of them after what I said above?

**Comment by cezar97** [comment]
I've just started open source contributions and this isn't the first time I get a bad impression, unfortunately. What a shame.
BTW, I didn't want to be unkind / unfriendly, but there are more than 8000 users that trust you and your software ( There are also some backers ). The trust come also from the project README:
> If you have found a vulnerability in the project, please write privately to security@gitea.io. Thanks!

So it seems that Gitea is expected to be secure and security issues are welcome. But it isn't like that.

Should I mention that I still expecting an answer? Thanks.

**Comment by sapk** [comment]
The check introduce in #4312 should be introduce globaly in https://github.com/go-gitea/gitea/blob/7b2b900e13612f565051c64374b788b0c8a82751/modules/context/context.go#L80
Or display a webpage in between the redirect that show the user he is leaving.
