### ISSUE TITLE
Using port redirection inside Docker result in permission denied

### ISSUE THREAD

**Issue by rkt2spc** [go-gitea/gitea#4365]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.15.2
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Using port redirection inside Docker result in permission denied

## Screenshots

![image](https://user-images.githubusercontent.com/17026876/42293162-4ef7d0ae-8002-11e8-983b-5ec0d2ab9586.png)

## Temporary solution

Specify *PORT_TO_REDIRECT* to something other than 80. Adjust docker ports mapping to it

**Comment by techknowlogick** [comment]
As Gitea doesn't run as root it doesn't have permissions to utilize port 80. Can you try setting `PORT_TO_REDIRECT` option to something over 1024, then in your docker run command or docker-compose map the port that is over 1024 to part 80, ex. `-p 1080:80`

**Comment by jbltx** [comment]
Is there any solution for this? 

Changing `PORT_TO_REDIRECT` in my docker-compose file didn't help, Gitea is unable to bind port 80 in the container. In my setup, I only use inner ports and the load-balancer/reverse-proxy (Traefik) handles external connections. One of my other container, [Drone](https://hub.docker.com/r/drone/drone/), uses ports 80 and 443 internally without any issues.

I can't bind it to the external port 80 since it's already used by Traefik. I need to use port 80 because of Drone builds which try to fetch data on Gitea server using this port.
What are the solutions ? Thank you.

**Comment by techknowlogick** [comment]
Gitea doesn’t run as root, as such it is unable to bind to ports below 1024. Traefik is able to handle accepting traffic on port 80 and passing it to whichever port gitea is using.

**Comment by jbltx** [comment]
I know Traefik can handle that, the issue is not there as it works fine.

Maybe i missed something with GItea configuration : 
```
HTTP_PORT        = 3000
ROOT_URL         = http://git.my-domain/
DOMAIN           = localhost
```

My domain is `localhost` internally, but outside i reach Gitea using `http://git.my-domain/`
This custom domain is reachable because on my client machine i added the domain in `/etc/hosts` to be redirect to my virtual machine running Docker.

Now when Gitea triggers Webhooks, it sends `git_clone_url` with a value like `"http://git.my-domain/user/repo.git"`. 

Now it's an other container which handles the request and has to access git server. Internally it will fail because it doesn't know where to be redirected using `git.my-domain`.

My workaround was to aliases the domain in the docker-compose's network : 

```
services:
  gitea:
    networks:
      traefik:
        aliases:
          - git.my-domain
    expose:
      - "3000"
```

This was half the solution, since aliases works for hostnames, not ports. So finally my CI server tries to reach Gitea on port 80 instead of 3000.

I hope to find a solution without the need to manage a custon DNS server in my local network.
