### ISSUE TITLE
Is there a cross-platform fork system?

### ISSUE THREAD

**Issue by Wqrld** [go-gitea/gitea#4493]
Is it possible to import a repo from github and keep it synced? For example if i want to fork a project on github to my gitea instance.

**Comment by Wqrld** [comment]
This would also require adding
https://github.com/go-gitea/gitea/issues/2488

**Comment by jonasfranz** [comment]
You can create a mirror of the GitHub repo.

**Comment by Wqrld** [comment]
Oh, is see, it seems like "mirror" was mistranslated to "kopie" for me

**Comment by Wqrld** [comment]
Mirrors are read only, i want to have a fork (if possible on gitea)with which i can pull commits from a upstream repo(on github)

(maybe let people make new branches or fork mirrorred repos)?

**Comment by vsund** [comment]
Would love to see this 👍  also I hereby dislike the automated stale bot :)

**Comment by zeripath** [comment]
Can't you just mirror the GitHub as say upstream-mirror and then pull from that mirror?

**Comment by techknowlogick** [comment]
Yes, you can create a fork of a mirror locally. Closing this as federation is being handled in another issue.

**Comment by Cyber1000** [comment]
Sorry to add to this thread, but how to fork locally? I can make a mirror of a github-project, but I can't fork this mirror  in gitea, it says "forking is not allowed, because I own this repo already" (or similiar, I'm using german, so I don't know the exact english message). Do I need to use 2 gitea-user accounts for myself, one that mirrors github and on that forks from that mirror?

Thanks!

**Comment by lafriks** [comment]
@Cyber1000 create new organization (let's say `github`) and add all mirrors under it. Than you won't be owner of that mirror and you will be able to fork mirror under your own user
