### ISSUE TITLE
Resend webhook payloads

### ISSUE THREAD

**Issue by noplanman** [go-gitea/gitea#4589]
- Gitea version: 1.4.3
- Git version: 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
  - [x] (Getting `Bad Gateway` error on try.gitea.io)

## Description
(coming from #3998)

Would be great if it were possible to resend a webhook payload.
It sometimes happens that a webhook call times out, so just being able to kick it again would be super helpful.

Is there a way to do this as it is now?

**Comment by sbrl** [comment]
Erm this is an essential feature for me, @stale. Please don't close it! I've got an issue (see #5470) whereby webhooks are not  being reliably delivered - so this would be a great step to fixing them.

**Comment by skddc** [comment]
Same here. Super useful for debugging and developing integrations for Gitea.

**Comment by mbarinc** [comment]
Very useful, I hope it will be implemented soon

**Comment by xsirh925** [comment]
I was looking for another issue related to webhooks and saw that this issue was open. I'm not certain exactly which version added this, but as of `1.16.3` there is now a button in the configuration page for a webhook that implements resending the POST request associated with a webhook containing its original payload.
![gitea replay webhook](https://user-images.githubusercontent.com/45466528/159346803-00a364ee-931a-47d2-88db-2dc1ada26548.png)

**Comment by noplanman** [comment]
@xsirh925 Brilliant, thanks so much for letting us know 🎉
