### ISSUE TITLE
Custom Gitea Page && Logo

### ISSUE THREAD

**Issue by bestony** [go-gitea/gitea#4660]
- Gitea version (or commit ref): the latest of docker version 
- Git version: 2.15.2
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

How Can I change Gitea footpage 、 Logo  and menu ?

In docker Version , here only these file, no file to change or to edit. 

![image](https://user-images.githubusercontent.com/13283837/43945198-03676cb6-9cb4-11e8-9a72-8225b9873daa.png)

So, How can i change the logo of my site? Should I overwite some file ?

## Screenshots

![image](https://user-images.githubusercontent.com/13283837/43945295-42c50fe4-9cb4-11e8-93a7-5c7389207d3b.png)

**Comment by lafriks** [comment]
See docs for customization (https://docs.gitea.io/en-us/customizing-gitea/), also please use forum (https://discourse.gitea.io/) for such questions.

**Comment by mateuslacorte** [comment]
Can I use the gitea logo at my own private theme?

I really love how gitea works and having in mind that I will have to change the links while custom templating (taking out the gitea.io and other help links for example) I want at least be able to use the gitea logo as I will put on my footer a "proudly using gitea" like I always do on wordpress...

But the problem is, do the MIT license cover up the usage of the project's logo?

If not, then can you guys gimme permition to use it?

Another doubt I have is, as I'm going to change the entire html, css and js files, do I need to put the license of gogs's and gitea's authors on an HTML comment as done in the original theme or can I just put a link to the license? Because comments on the HTML are going to hinder my pagespeed and yslow score, so a link would be a better option for me...
