### ISSUE TITLE
Gitea as a third party package for Synology NAS

### ISSUE THREAD

**Issue by s-celles** [go-gitea/gitea#4669]
Hello,

it will be great if Gitea could be added as a third party package for Synology NAS.
https://forum.synology.com/enu/viewtopic.php?f=190&t=144985&p=539591#p539591

Kind regards

**Comment by techknowlogick** [comment]
This is a good idea, what is the process of creating a third party package, and also adding it to the synology app store?

**Comment by s-celles** [comment]
It seems that @jboxberger have done https://github.com/jboxberger/synology-gitea-jboxberger
But it's not available from Synology app store

There's also
https://github.com/flipswitchingmonkey/gitea-spk from @flipswitchingmonkey

**Comment by towelie42** [comment]
+1

**Comment by typeless** [comment]
References: 
https://gist.github.com/walkerjeffd/374750c366605cd5123d
https://forum.synology.com/enu/viewtopic.php?t=144985
https://github.com/jboxberger/synology-gitea-jboxberger
https://github.com/SynoCommunity/spksrc

**Comment by lunny** [comment]
So that could be closed?

**Comment by Libbum** [comment]
I'd still like to see this happen.

**Comment by typeless** [comment]
I have successfully deployed a Gitea server on a Synology DS1817+ at our department.
I used https://github.com/flipswitchingmonkey/gitea-spk to generate the SPK.
I think it's possible to integrate the SPK generation into the official Gitea release, not sure if that is desirable though.  😄

**Comment by VanKurt** [comment]
Bump! I would love to see an official gitea package in the Synology app store :-)

**Comment by scls19fr** [comment]
Do we know who should we ask (someone probably working at Syno) for such an integration?

**Comment by nguyenxndaidev** [comment]
Instead of install gitea and all required services directly on Synology, we should install all with docker. GitLab is doing a good job to provide synology package, that deploys gitlab and dependencies using docker.

The problem is that GitLab consumes too much CPU and RAM. If Gitea can do the same thing, I am sure I will switch to use Gitea on my Synology.

**Comment by 6543** [comment]
@nguyenxndaidev there already exist docker builds for gitea https://github.com/dockhippie/gitea for example

**Comment by nguyenxndaidev** [comment]
> @nguyenxndaidev there already exist docker builds for gitea https://github.com/dockhippie/gitea for example

I know that there are even official gitea image, but that requires multiple manual steps to configure gitea, database (ex. mariadb), cache (ex. redis), volumns, networks. While GitLab publishes official Synology package, so that I just need to click install and everything is ready to go.

**Comment by zeripath** [comment]
Are you able to generate the appropriate dockerfile for this?

**Comment by techknowlogick** [comment]
I run on my syno NAS using docker following the steps here: https://docs.gitea.io/en-us/install-with-docker/#postgresql-database

**Comment by jboxberger** [comment]
Hello Guys,

i've done all this already for you. Fell free to use or copy. Works simply out of the box, same as the GitLab Package. I've also a modified official GitlabPackage with the "latest" GitLab version possible.

Gitea: https://github.com/jboxberger/synology-gitea-jboxberger/releases
GitLab: https://github.com/jboxberger/synology-gitlab/releases

@nguyenxndaidev : Yes 2GB is minimum 4GB or more is Recommended. You should also mention that the GitLab Redis Worker in the container do not allow the Synology to go to Sleep, if configured so.

Thats why i use Gitea. I don't need the power of GitLab at home so Gitea suites my needs.

Kind Regards

**Comment by nguyenxndaidev** [comment]
I tried to install using the docker GUI provided by DSM following the official docs: https://docs.gitea.io/en-us/install-with-docker/#mysql-database

CPU/RAM usage is amazing:
![image](https://user-images.githubusercontent.com/24372782/73141799-7e7be480-4088-11ea-875a-5a57216fcf81.png)

Here is my steps:

* Download images
![image](https://user-images.githubusercontent.com/24372782/73141702-4922c700-4087-11ea-8054-ffc5576ef6ae.png)
* Launch mariadb container
![image](https://user-images.githubusercontent.com/24372782/73141737-bdf60100-4087-11ea-8fd0-3f57d55ba8b4.png)
![image](https://user-images.githubusercontent.com/24372782/73141780-4a082880-4088-11ea-92cb-b608d51e3e85.png)
* Launch gitea container
![image](https://user-images.githubusercontent.com/24372782/73141749-ef6ecc80-4087-11ea-8408-cf05239459e2.png)
![image](https://user-images.githubusercontent.com/24372782/73141759-1f1dd480-4088-11ea-89ff-3617dc2d3ba8.png)
![image](https://user-images.githubusercontent.com/24372782/73141762-25ac4c00-4088-11ea-8e65-9eabc4989d59.png)
![image](https://user-images.githubusercontent.com/24372782/73141775-36f55880-4088-11ea-964c-28b8fcca79e3.png)

**Comment by jboxberger** [comment]
Yes this is great, you can also use the builtin SQLite database if you're not planing to use the installation with many users. I've used it long time with maria DB an now i am using it with SQLite and do not feel any performance differences at all. 

With SQLite you do not need the additional conatiner and its depenecy for the DB because your DB is a flat File in the mounted Volume.

Just in case you want to make it even more slim.

**Comment by nguyenxndaidev** [comment]
@jboxberger thanks for your advice to use SQLite. If you have a good exprience with SQLite, I think I will do so because I am the only user of my git server.

**Comment by abulka** [comment]
Seems that these days (2020) there is a docker image for Gitea available to be selected via the Docker UI inside Synology - point and click installation! 👌✨

Simply open the official Docker UI app in Synology, click 'Registry' in the left side panel, then type 'gitea' in the search area to find the Gitea image:
![gitea synology 1](https://user-images.githubusercontent.com/11467530/73230146-5e573d00-41d0-11ea-9acc-8283c4087b71.png)

Click 'download' or double click on the image, and it will be run as a container.  Then you can switch to the 'Containers' tab of the Docker UI app and see your running container:
![gitea synology 3](https://user-images.githubusercontent.com/11467530/73230665-2ea93480-41d2-11ea-986e-c800fbdc79f9.png)

Double click on the running container to access more info and view logs etc. Note the local port settings are being displayed:
![gitea synology 4](https://user-images.githubusercontent.com/11467530/73230671-336de880-41d2-11ea-9b38-6789fd198d20.png)

Visit Gitea using the address `YOUR-NAS-IP:32769` e.g. http://192.168.888.999:32769 - or whatever 'local port' is displayed here e.g. for me it was 32769 but because the port is on auto, it will be different for you.

## Setup tips

During the setup (which is triggered when you add the first user), I changed the **Gitea Base URL** from
http://localhost:3000/ to
http://192.168.0.9:32769/
which is the address of my NAS and the port is the 'local port' as reported when you double click on the running container to see more info about it (or click the 'Details button'). I got this tip from #5209 (re the port) but I also changed the domain since I was getting problems with issue text previews and viewing issue images when gitea is accessed from other machines.

On the same setup screen, I also opened up the admin accordion and set up an admin user, as it can be a bit tricky to add an admin user later.

![gitea synology 2 PUBLISHED REDACTED_LI](https://user-images.githubusercontent.com/11467530/73230845-a9724f80-41d2-11ea-910e-27cd36004467.jpg)

## port is changing on every container restart

The port for Gitea was changing randomly every time I restarted the container e.g.
http://192.168.0.99:32769/
http://192.168.0.99:32778/

so I stopped the container and edited the container config to set a fixed port:
![gitea synology 5](https://user-images.githubusercontent.com/11467530/73232492-85fdd380-41d7-11ea-9de7-704e3fab47b2.png)

## Remaining question - where is /data ?

Gitea is running well, the only thing I don't understand is where the repo data is being kept, and where the sqlite database physically is.  Is `/data/gitea` is inside the container? Seems not, since when I restart the container my Gitea data is still OK (containers never persist anything - you have to map a real host volume to a container volume to achieve persistence in Docker's way of doing things). I can't see anything on my host NAS using Synology File Station - yes there is a Docker directory and a subdirectory for GitLab (which I also have installed), but nothing for Gitea?

**Comment by jboxberger** [comment]
It depends on your volume mapping 
mine is at /docker/gitea on the Filesystem it is on my synology "/volume1/docker/gitea".

Hope this helps.
![image](https://user-images.githubusercontent.com/1545845/73300300-10aef480-4211-11ea-89c1-2ca479abfd8c.png)

**Comment by jboxberger** [comment]
I've checked my preinstall script an there i create the data folder befor installation

https://github.com/jboxberger/synology-gitlab-jboxberger/blob/master/src/scripts/preinst

So mybe the tme mount fails because of the missing direcoroy and the data stays within your container.

Try to stop the container and then create the directory 
drwxr-xr-x  1 root root  36 Mar  3  2019 gitea

**Comment by abulka** [comment]
Thanks @jboxberger - yeah it seems the external host directory `/docker/gitea` wasn't created for me, even though I also have GitLab installed and the `/docker` directory on the host nas previously existed ok. As you say, perhaps creating `/docker/gitea` manually using Synology File Station is recommended before creating the Gitea container. Also, I am not sure if the volume mapping `/docker/gitea/ -> /data` is supposed to be automatically created, but that didn't exist for me either, and I had to create that mapping manually. Here are some of my notes I am sharing in case it helps others:

## Solution to the /data persistence issue
It seems that the Gitea container does in fact have persistence (despite containers not supposed to have persistence unless you map to volumes, not sure what is going on with this!) and the container `/data` is created, persisted and populated with the `app.ini` config file, sqlite3 database plus everything else Gitea needs and uses.  

Watch out - if the container gets deleted and recreated, all of this data will be lost, so its worth converting /data into a proper volume mapped to a real directory on the host synology nas, e.g. something in the Synology nas /docker directory (to follow the convention of putting docker related data in /docker/APPNAME) e.g. `/docker/gitea/data`.

To do the mapping simply go into the docker container UI and create the volume mapping `/docker/gitea/data -> /data` (or as @jboxberger has it, `/docker/gitea/ -> /data`, its up to you what the host directory path actually is). 
![gitea synology 6](https://user-images.githubusercontent.com/11467530/73323619-27e6f400-429c-11ea-9cd0-bde755b96194.png)

Note that if you already have installed Gitea without the volume mapping, the existing /data inside the container will be overridden by this new external mount point (but down't worry, the original `/data` inside the container won't actually be lost). If you want to keep your old config and db simply copy the container's existing /data files to the external host  /docker/gitea/data before setting up the permanent volume mount (e.g. temporarily mount `/docker/gitea/data -> /data_pending` then `cp -R /data/* /data_pending` or something like that).

Verify that your Gitea install is picking up the mapped volume config by editing `/docker/gitea/data/gitea/config/app.ini` and changing something e.g. the Site Title as controlled by the `APP_NAME` entry, restart the container and visit e.g. http://192.168.0.99:32769/admin/config to view the Gitea configuration web page - and make sure the new Site Title is being displayed there.

To edit app.ini on your NAS you will probably need to download the file to your machine via the Synology File Station, edit it, then re-upload it into the NAS file system `/docker/gitea/data/gitea/config/app.ini` using Synology File Station.

## Edit your app.ini domain entries correctly
Since you will be accessing Gitea from outside the Synology NAS, you also want to edit your `/data/gitea/conf/app.ini` and set the domain entries to the ip of your nas e.g.

```
SSH_DOMAIN       = 192.168.0.99
DOMAIN           = 192.168.0.99
ROOT_URL  	 = http://192.168.0.99:32769/
```

do not leave them as the default `localhost`.

## SSH port is changing on every container restart
There are two ports needed by Gitea, the main port and the ssh port. As I mentioned in an earlier post in this thread, I had to change the main Gitea UI port to a fixed local port so that it wouldn't change each time I restarted Gitea inside Synology Docker - which unfortunately has those ports set to 'auto' by default. Incidentally the Synology _GitLab_ Docker installation process manages to lock those ports to specific values by default, so perhaps a future Gitea Docker install experience will do the same.
Anyway, so it turns out I need to allocate a fixed port to the SSH port too e.g. 32222 (you can change the ssh _local port_ to any free port number you want, but keep it mapped to the same ssh _container port_ 22).
You will also need to edit your `/data/gitea/conf/app.ini` and set `SSH_PORT = 32222`

After restarting Gitea, verify that the new SSH settings are in effect by looking at the clone url offered by Gitea for any repo in Gitea e.g. `ssh://git@192.168.0.99:32222/andy/test01.git` notice the domain and port are correct. Thus now
`git clone ssh://git@192.168.0.99:32222/andy/test01.git` should work and you won't be prompted with a password, as long as your SSH key is registered in Gitea. Note that the `32222` in the git url is a 
reference to the NAS host  _local port_ which you have specified in both the docker port mappings and also in the Gitea `app.ini` file.

## Environment Variables
I didn't have much luck changing any of the above values using docker environment variables via the Synology Docker UI. I had to actually edit the app.ini file.

**Comment by lunny** [comment]
Good news. So I think we can close this one. And someone could write a blog or send a PR to add something on gitea docs.

**Comment by Wuszek** [comment]
Sure its really good thing, that there is a package available in Docker. Is there any possibility to create a real third party package for Synology NAS - I mean - .spk that could be installed through PACKAGE CENTER. Not all devices are able to use Docker but in the meantime they are fully capable of running Gitea. 

I know, there are third party package like https://github.com/flipswitchingmonkey/gitea-spk but its 3 years old now, and luck of any support. Sometimes it works, sometimes it doesn't.

**Comment by salesgroup** [comment]
We really like gitea and synology.
We have a cron script to create gitea.spk and install it in every update.
So we have Gitea always updated.
You can see the script here:
https://gist.github.com/salesgroup/bacb5882250df8d843491efe2784b38c
Our synology model is: RS815+

We also have:
-a version with acme.sh to renew the SSL certificate.
-boot-up event to start gitea, with "synoservice --start pkgctl-Gitea"

**Comment by Wuszek** [comment]
> https://gist.github.com/salesgroup/bacb5882250df8d843491efe2784b38c

Thx, nice one! Actually, the only thing that should be changed is line 24 and 34, whitch depends on your synology CPU architecture. Do you have any problems with custom confugiration in app.ini in every update? What is being delated and should be replaced by hand after update?

**Comment by caifenglin** [comment]
Can you provide a tutorial for Qunhui to install gitea? I install gitea through Qunhui's docker. I normally enter the setting page. After setting the parameters, I can't find the page. After restarting gitea, I'm still on the setting page. What should I do? The version is 1.15.7

**Comment by techknowlogick** [comment]
https://synocommunity.com/package/gitea
