### ISSUE TITLE
Cannot comment in split diff view

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#4745]
- Gitea version (or commit ref): b1ad573 
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/go-gitea/chardet/pulls/1/files?style=split&whitespace=

## Description
1. ~~It is not possible to add new comments in split diff view because the '+'-button does not show up~~ Resolved by #5038
2. It is not possible to submit a comment at an existing conversation.

**Comment by jonasfranz** [comment]
Reopen since 2. is not resolved.

**Comment by lunny** [comment]
@JonasFranzDEV I think this should be an enhancement but not a bug. And moving it to v1.7 is better.

**Comment by rfwatson** [comment]
Seems to be happening because [this event listener](https://github.com/rfwatson/gitea/blob/0c73755e039fbc62d000af79cf563ce29c136f41/public/js/index.js#L1050) is hijacking the click in split view. It isn't bound in unified view.

You can try removing the listener using Chrome devtools in split view, the issue is immediately resolved.

**Comment by lunny** [comment]
@rfwatson could you send a PR to fix that?
