### ISSUE TITLE
IMAP auth support

### ISSUE THREAD

**Issue by dadosch** [go-gitea/gitea#4776]
You can authenticate users via IMAP just like with LDAP, but it isn't as complicated to set up an IMAP server.

This [library](https://github.com/emersion/go-imap) could be useful.

**Comment by wxiaoguang** [comment]
I do no think IMAP could be used as an auth source.

SMTP is generally safe because even if the password is leaked, no one could access your inbox.

But, if your IMAP password is leaked, others can access your inbox.

Well, in most cases the SMTP password and IMAP password are the same, IMO neither SMTP nor IMAP is the proper auth method, avoid using them.
