### ISSUE TITLE
Outdated vendor/golang.org software

### ISSUE THREAD

**Issue by tuxillo** [go-gitea/gitea#4817]
- Gitea version (or commit ref): 1.5.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

While trying to build gitea on other OSes (SmartOS, NetBSD, ...) I encountered some errors and after checking, it is related to the golang/sys version gitea distributes. Apparently it hasn't been updated in a while.

I've based the list below in the "revisions" found in Gopkg.lock which I assume they were generated by some command based on Gopkg.toml.

| Vendor software  | Date | Version |
| ------------- | ------------- |  ------------- |
| golang.org/x/sys | 2016-07-15 | https://github.com/golang/sys/commit/a646d33e2ee3172a661fc09bca23bb4889a41bc8 |
| golang.org/x/oauth2 | 2016-08-25 | https://github.com/golang/oauth2/commit/c10ba270aa0bf8b8c1c986e103859c67a9103061 
| golang.org/x/net | 2017-01-14 | https://github.com/golang/net/commit/f2499483f923065a842d38eb4c7f1927e6fc6e6d |
| golang.org/x/sync | 2017-03-17| https://github.com/golang/sync/commit/5a06fca2c336a4b2b2fcb45702e8c47621b2aa2c |
| golang.org/x/text | 2017-06-17 | https://github.com/golang/text/commit/2bf8f2a19ec09c670e931282edfe6567f6be21c9 |
| golang.org/x/crypto  | 2018-04-18  | https://github.com/golang/crypto/commit/12dd70caea0268ac0d6c2707d0611ef601e7c64e |

Before trying to send a PR for an updated golang.org/x/sys, is there a procedure to correctly upgrade vendor software? I would assume some test need to be run and passed first, etc.

Also, maybe it would be good to have an automatically generated list of the vendor software and dates of the revisions used, just an idea :smiley:

**Comment by techknowlogick** [comment]
Update to my comment above: I've created a PR to update the minimum used version of golang used to test the build so now the packages you've mentioned above can be upgraded to an appropriate version.

**Comment by tuxillo** [comment]
Thanks. So to update the packages above, do you guys use a specific procedure?

**Comment by techknowlogick** [comment]
Yup, a `dep ensure -update golang.org/x/PACKAGE` (for each package), and then create a PR. You may need to change the revision in `Gopkg.toml` first before running the command.

Our lowest supported version of go right now is 1.9 and so if you want to check that the project builds with that version before pushing you can, but the CI will also check. Because of this, the latest commit for these packages may not work, rather than going commit by commit figuring out which commit is good, I start at most recent, see where the build fails then git blame the line where it fail, and skip to the revision before that and repeat until successful.

Also, personally I'd prefer all of these updates in one PR to make it easier to merge, but it is up to you if you want to do one, or many. My preference is not a strong one and I'd be happy to review either way 😄

**Comment by tuxillo** [comment]
I think I'll work on the updates individually, it's easier for me. I'm going to use the CI as you said, I think it's going to be a better check than my local builds.
I've already opened a PR (#5059). I'll see if I can use your 'git blame' trick.

Thanks!

**Comment by tuxillo** [comment]
Also update [edsrzf/mmap-go](https://github.com/edsrzf/mmap-go) for #4799
