### ISSUE TITLE
Error when deleting organization

### ISSUE THREAD

**Issue by deanpcmad** [go-gitea/gitea#486]
- Gitea version (or commit ref): 1.0
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When deleting an organization, I get a 500 error and this message shows in the logs:

```
2016/12/26 21:56:56 [...routers/user/home.go:47 getDashboardContextUser()] [E] GetOrganizations: user does not exist [uid: 7, name: , keyid: 0]
```

When accessing the database and deleting the correct entry from the `org_user` table, the error goes away so it looks like when an org is deleted, it's not deleting the association there as well

**Comment by deanpcmad** [comment]
That was quick! :)

**Comment by JetpackDuba** [comment]
Shouldn't this be fixed in 1.0.1 instead of 1.1.0? If I delete an organization I get a 500 error in a lot of some pages (Dashboard, issues, pull requests...), not only when deleting organization.

![2016-12-27 14_58_16-internal server error - gsp gitea](https://cloud.githubusercontent.com/assets/16917468/21501079/1e665d92-cc45-11e6-81a5-847d395ff4d1.png)
![2016-12-27 14_58_27-internal server error - gsp gitea](https://cloud.githubusercontent.com/assets/16917468/21501081/1e682cda-cc45-11e6-84ff-830789e1d80c.png)
![2016-12-27 14_58_41-internal server error - gsp gitea](https://cloud.githubusercontent.com/assets/16917468/21501080/1e67e7d4-cc45-11e6-9baa-e9a2827b76b3.png)


EDIT: Nvm! I see that you have created another PR https://github.com/go-gitea/gitea/pull/507

**Comment by lunny** [comment]
This is our workflow. Another backport PR has been sent and is in v1.0.1

**Comment by lunny** [comment]
You have to manually delete some record on your database in `org_user` table.
