### ISSUE TITLE
Can't view "Preview" on comments on pull requests

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#4947]
- Gitea version (or commit ref): f6eb669
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/go-gitea/chardet/pulls/1/files
## Description

If I try to click on the "Preview" tab at the comment at line container nothing happens. If I do the same thing via a reply button everything works like expected.

## Screenshots
- [+] Button
![cannot click on preview](https://user-images.githubusercontent.com/5757182/45616911-13bca100-ba71-11e8-9fb4-b2586f34f6b6.gif)
- "Reply" Button
![can click on reply](https://user-images.githubusercontent.com/5757182/45616912-14553780-ba71-11e8-86a3-3342b5cb7a75.gif)

**Comment by tonivj5** [comment]
I can confirm it, I have the same problem...

Gitea version: 6e03390
Chrome 69.0.3497.92

**Comment by techknowlogick** [comment]
@xxxtonixxx are you able to use a more recent version on master branch?

**Comment by tonivj5** [comment]
I can confirm it happens on 552d8d3 too (latest commit) and I'm digging on JS and I'm found this:
![image](https://user-images.githubusercontent.com/7110786/45679460-01a63580-bb39-11e8-9d00-9a20f79ff1f2.png)

The value of write textarea is not being getted.

I see it's because `$tabMenu.data('write')` output `"write976219"`, but the `.tab.segment` element, where it's the textarea, has a `data-tab` value of `"write976219976219"`, as you can see here:
![image](https://user-images.githubusercontent.com/7110786/45679899-e2f46e80-bb39-11e8-985f-c2250d5210ad.png)

And, If I set a static value to render in preview (`test`) it doesn't show, preview tab doesn't open

And, I have noticed that this pice of code:
```js
$('pre code', $previewPanel[0]).each(function (i, block) {
  hljs.highlightBlock(block);
});
```
Laggy my browser, `$previewPanel[0]` is `undefined` and `$('pre code', $previewPanel[0])` has a length of 1550, is it the expected behavior?
