### ISSUE TITLE
Improvements in email notifications on issues and pull requests

### ISSUE THREAD

**Issue by rasmk** [go-gitea/gitea#5083]
I would like to see some improvements in email notifications Gitea sends on issues and pull requests.

Content extensions:
* distinguish issues and PRs in email subject and body
* distinguish whether the issue is new, updated or closed in email subject and body
* have different notifications on different comment types (e.g. different email, when I get assigned to an issue)

For that, I was thinking about having templates for subjects and adding some more data (e.g. issue and comment) to the _data_ of the body template, so that custom templates can make use of that. Having separate templates per comment type may be an option too.

Besides, I would like to receive some more emails than today:
* when user assignment changes, especially, when I get assigned to the issue/PR
* on coder review, possibly both line-review comments and global review comment

Nice to have: defer the email sending and bundle some related updates into a single mail. This should be particularly useful for the review notifications. This may be somehow related to #145 by @andreynering. 

I would like to hear some feedback. Perhaps I could contribute a PR.

**Comment by kolaente** [comment]
I looked into this and after about an hour I gave up. The whole thing is not built very good. We have notifications, these are ok and get updated far more often than emails are sent. One would expect we have some kind of goroutine which sends mails based on notifications, but the whole notification implementation doesn't send any mails. Mails are being send directly by the function which creates an issue/pr comment. But not for all kinds of comments.... (this is the reason for #4279)

IMHO we should refactor these things in three steps:
1. Refactor the way emails are sent so they're sent based on notifications instead of issue comments
2. Built email content messages based on the notification type, then later add translatable strings (work for this has been done in #3875)
3. Make sure notifications are built for every issue action (assigned, unassigned, updated, etc.). Later possibility to make this configurable on a per-user basis,  letting the user decide which kind of notifications he wants to recieve.

**Comment by lunny** [comment]
@kolaente see https://github.com/go-gitea/gitea/pull/5085 , I will send another PR about mail notification after that merged.

**Comment by kolaente** [comment]
@lunny Great, I haven't seen that!

**Comment by lunny** [comment]
@rasmk I agree with you we need a notification configuration UI after the mail refactoring finished.

**Comment by saitho** [comment]
The mail refactoring mentioned was #5085, right? Can we tackle this issue now? :)

**Comment by lunny** [comment]
Mail notification has merged also. See https://github.com/go-gitea/gitea/blob/master/modules/notification/mail/mail.go

**Comment by oscarlofwenhamn** [comment]
I agree with @rasmk that we would need configuration options with an increase of emails. Is configuration available at all at the moment? I was contacted by a user with the request of opting-out of certain notification emails, though I haven't come across this functionality so far in Gitea. The ability to customize notifications for different repos would be brilliant, as certain repos may require greater attention than others.

**Comment by MarkusAmshove** [comment]
I'm not sure if this is the correct place to report, but it seems like the issue templates can't be customised at the moment, even though the documentation states they are customisable.
If I create the template files according to the documentation/layout the content of the mail's don't change

**Comment by guillep2k** [comment]
#8329 partially addresses this.
Related to #145

**Comment by raycrasher** [comment]
Still in development, see:

https://github.com/go-gitea/gitea/issues/5083

https://github.com/go-gitea/gitea/pull/8329

Meanwhile, I'll see what I can do to hack the code.

**Comment by mrsdizzie** [comment]
Agree most of this is resolved/possible now
