### ISSUE TITLE
Implement CodeClimate (self-hosted)

### ISSUE THREAD

**Issue by Extarys** [go-gitea/gitea#5267]
## Description

Since CodeCLimate integration is a paid feature of GitLab, it would be great if Gitea would find a way to implement CodeClimate code quality check on merging and maybe add a Stats tab to the repo to see the code coverage (and in the future maybe vulnerability scan, etc)

It would be a great addition since there is currently no self hosted software that do it for free (GitLab, I'm looking at you!)

I hope this is a good place to make such suggestion.

**Comment by Extarys** [comment]
Does gitea feature Code Quality feedback on merge request? I haven't started testing anything yet but couldn't find anyone on the web talking about gitea and CodeClimate and I'm new to CI/CD. I was looking for a GitLab equivalent that would gives me a lot of feedback on my repo's status.

**Comment by lunny** [comment]
I think status API could be used by this service to do that like Drone or jenkins to do. Gitea has implemented status API but need more work on pull request UI.

**Comment by Extarys** [comment]
It would be awesome to be able to have something that can have an all-in-one free open source alternative. Right now most services can be linked to GitHub but it is not self-hosted. Some features of GitLab is paid and quite heavy.

**Comment by davidak** [comment]
I just found a CI for Go that is open source (but only seem to work with GitHub). It might can get extended to work with other languages and code hosting plattforms. https://golangci.com/

But maybe to have a sane solution we should focus on integrating ANY CI with ANY code analysis tool for ANY language and just search for or build a plattform to collect and display results, like https://codecov.io/ and https://coveralls.io/ for code coverage. It shouldn't be too complex to replicate the statistic features of CodeClimate and others.

**Comment by alexanderadam** [comment]
There's also [Pronto](https://github.com/prontolabs/pronto#pronto), a self hosted tool [for a variety of languages, frameworks and checks](https://github.com/prontolabs/pronto#runners) that might be relevant in [this list](https://github.com/go-gitea/gitea/issues/5267#issuecomment-436337190).

For a proper support (like the experience users have on other services) there should be [PR support through the API](https://github.com/go-gitea/gitea/issues/5733) (like approvals and rejects — maybe even per line)). Otherwise we can "only" write comments to PRs.

So I would say that #5267 and #5733 are at least a bit related (if done properly). :wink:

**Comment by delvh** [comment]
I don't see a reason why Gitea should get bloated like that.
As already mentioned, it's probably better to integrate it through a third-party service that fails your branch protection or something similar.
