### ISSUE TITLE
XSS in PR review comments

### ISSUE THREAD

**Issue by Aragur** [go-gitea/gitea#5409]
- Gitea version (or commit ref): 0dcf31a
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

The review comment screen allows XSS. (Doesn't sanitize input)

## Screenshots
![image](https://user-images.githubusercontent.com/11004008/49023943-9ca23800-f198-11e8-9194-977bbf273ed7.png)

**Comment by jonasfranz** [comment]
Thank you for reporting, but I think that this is not a XSS since `<h1>` etc. are valid markdown stylings. I've tested it for malicious code like iFrames or JS. These get filtered out like normal comment. There is no difference between the santization of comments and PR comments.

Please reopen if you've another opinion.
