### ISSUE TITLE
POST /api/v1/releases should require target parameter

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#5471]
- Gitea version (or commit ref): 1.6.0

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
When trying to create a release without `target_comitish` parameter the following error occurs:
```
GetCommit: exit status 128 - fatal: ambiguous argument '': unknown revision or path not in the working tree.
```
It would be good to reject this request, instead of querying git with an empty commitish string.

**Comment by techknowlogick** [comment]
@noerw thanks for your PR to the go-sdk repo, are you able to make another one to this repo to update the dep? 😄

**Comment by noerw** [comment]
I quickly searched for the API code but did not find it, so I guess, no?

**Comment by techknowlogick** [comment]
iirc it's just `dep ensure -update code.gitea.io/sdk` in a new branch. If you want me to poke around at it instead just let me know.

**Comment by noerw** [comment]
@techknowlogick I dont have a `dep` binary and dont know what it is, so I guess it'd be best if you did it ;)
Thanks!

**Comment by techknowlogick** [comment]
@noerw np. I can do that, and I will also write up the steps that I do so that you can know what they are if you want to in the future.

[Dep](https://github.com/golang/dep) is a golang dependancy tool, and it allows us to manage dependencies (such as go-sdk which we import from the other repo). You'll see gopkg.toml (and a lock file) which lists all the deps we have, and the vendor directory which is a copy of all the dependancies that we use.

**Comment by techknowlogick** [comment]
@noerw if you are interested in the steps I took I documented them in the PR linked to this issue. If you want to install dep first, you can run `curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh`
