### ISSUE TITLE
Please support the ISSUE_TEMPLATE directory

### ISSUE THREAD

**Issue by cnzgray** [go-gitea/gitea#5488]
This is a proposal:

Please support the **ISSUE_TEMPLATE** directory. Usually there may be more than one template for ISSUE (such as bugs, features, etc.). Currently, only templates that support one ISSUE are not enough.

This idea comes from [github issues template](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/)

**Comment by techknowlogick** [comment]
@mckaygerhard people are free to propose features, especially ones that are helpful.

**Comment by kolaente** [comment]
Gitea does look for issue templates in the `.gitea/` or `.github/` folder. (see https://docs.gitea.io/en-us/issue-pull-request-templates/)

Do you mean it should have support for multiple issue templates? In that case, the title of this issue is a bit misleading.

**Comment by alsmnn** [comment]
I think  @cnzgray wants multiple issue templates; one for bugs, one for feature requests, etc. like in github.
I would like to have that functionality too.

**Comment by themightychris** [comment]
@kolaente this definitely reads as a feature request for supporting multiple issue templates, the title says `directory`--I found this issue looking for how to have [`{.github,docs}/PULL_REQUEST_TEMPLATE/`](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) and [`{.github,docs}/ISSUE_TEMPLATE`](https://help.github.com/en/articles/about-issue-and-pull-request-templates#issue-templates) directories as GitHub supports instead of just [the individual files Gitea supports currently](https://docs.gitea.io/en-us/issue-pull-request-templates/).

I've got a number of projects hosting on Gitea that are hurting for this and feeling a pull to GitHub for getting more organized under a high volume of issues/PRs
