### ISSUE TITLE
SameSite Setting for Cookies

### ISSUE THREAD

**Issue by nuclearbiscoff** [go-gitea/gitea#5583]
- Gitea version (or commit ref): 1.6.2
- Git version: 2.20.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) [https://observatory.mozilla.org/analyze/try.gitea.io](https://observatory.mozilla.org/analyze/try.gitea.io), see "Anti-CSRF tokens set without using the SameSite flag"
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description
The [SameSite](https://www.owasp.org/index.php/SameSite) setting should be enabled on the session and CSRF cookies as an added prevention against CSRF. [Mozilla](https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/) does a good job of explaining its purpose, but the gist is that it prevents cookies being sent in a request initiated from a foreign origin.

## Screenshots
N/A

**Comment by silverwind** [comment]
Yes, this is a good idea, also see https://github.com/gogs/gogs/issues/3525#issuecomment-242985999 for other cookie options.

**Comment by tbleiker** [comment]
What is the state on this?

**Comment by silverwind** [comment]
Not implemented to my knowledge. Browsers are moving towards enabling it by default, so the issue might solve itself eventually:

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

**Comment by alexanderadam** [comment]
> Browsers are moving towards enabling it by default, so the issue might solve itself eventually:

But this is not true for other settings that can increase security, right?

For example [the others you mentioned](https://github.com/gogs/gogs/issues/3525#issuecomment-242985999), like `HttpOnly` and `Secure`

**Comment by dpertin** [comment]
@alexanderadam `HttpOnly` option is implemented since #4706.
However, according to [Mozilla Observatory](https://observatory.mozilla.org/), it seems to be the only one:
![cookie_gitea](https://user-images.githubusercontent.com/1255977/77965018-75a1cc00-72e0-11ea-9775-9cf611813156.png)

**Comment by alexanderadam** [comment]
Ah okay, I didn't know that. Thank you for pointing out. :+1:

**Comment by dpertin** [comment]
While waiting for these flags to be set at the application level, I found a workaround which consists in setting cookie flags at the web server level. For instance with `nginx`, one could adapt the [configuration sample](https://docs.gitea.io/en-us/reverse-proxies/) provided by the documentation by using the [proxy_cookie_path](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path) directive as such:

```
server {
    (...)

    location / {
        # Workaround to set cookie flags:
        proxy_cookie_path / "/; Secure; HttpOnly; SameSite=lax";

        proxy_pass http://localhost:3000;
    }
}
```

Which results in:
![cookie_gitea2](https://user-images.githubusercontent.com/1255977/78503581-e37a4780-7767-11ea-898f-4fba745f1860.png)


If your instance of `gitea` is supposed to be accessed with an unsecure channel (HTTP), remove the `Secure` flag. I also set `SameSite` to `Lax` which provides a reasonable level of protection. `Strict` mode implies higher security rules but it might have potential drawbacks since it prevents the browser from attaching any cookies to cross-site requests. I do not know `gitea` enough to determine if it could be a problem.

**Comment by m-ueberall** [comment]
FYI, the corresponding `apache2` directive is [ProxyPassReverseCookiePath](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreversecookiepath) – just put this below the `ProxyPassReverse` directive from the configuration sample:
```
ProxyPassReverseCookiePath / "/; HttpOnly; Secure; SameSite=lax"
```
Here, the `HttpOnly;` specifically addresses issue #9690 (`lang` cookie) _en passant_ …
