### ISSUE TITLE
org-mode support

### ISSUE THREAD

**Issue by Iced-Sun** [go-gitea/gitea#5710]
It seems to me that goorgeous may be dead. There is a [PR for hugo](https://github.com/gohugoio/hugo/pull/5545) which introduces an alternative implementation ```go-org```. Here is a [demo page](https://niklasfasching.github.io/go-org/go-org-vs-goorgeous) shows the html output of goorgeous (left side) and go-org (right side).

#5430, #3122 should receive immediate [fixes](https://niklasfasching.github.io/go-org/#misc.org) if go-org is adopted. 

Regards.

**Comment by lunny** [comment]
wait for that PR merged. :)

**Comment by michael-k** [comment]
PR has been merged in commit https://github.com/gohugoio/hugo/commit/fad183c4ae55069be9246e64ab1c8b2f43d08d06

**Comment by Ekleog** [comment]
Not sure whether the stale bot is still threatening closing as it appears to have removed the stale label since the reviewed/confirmed tag was put, but this is still an issue.

`goorgeous`, in addition to the bug described by #3122, is also not generating a table of contents, which go-org does. (I am also not sure whether go-org does provide syntax highlighting, as their screenshot does it but not their demo, so… meh)

**Comment by niklasfasching** [comment]
there's a hook for syntax highlighting but go-org itself doesn't bundle anything - for the github pages examples I'm using [chroma](https://github.com/niklasfasching/go-org/blob/a143b04826aadb6d080e2788e71a44526fcdd960/main.go#L49-L59). 

If no one is looking into this i can take a look next week.

**Comment by niklasfasching** [comment]
The development setup seems quite heavy and I have a shitty old laptop - I'm happy to help if you run into any problems but won't take a stab at adding support myself, sorry.

**Comment by sunbing81** [comment]
Per #8560
