### ISSUE TITLE
Gitea Mastodon Account

### ISSUE THREAD

**Issue by BNolet** [go-gitea/gitea#5761]
Hi all,

As Gitea gains more traction the desire for a representative figure begins to become necessary. I was wondering if there were any plans to make a Mastodon account for either posting about updates and/or providing quick support for those who don't need to make a full-on issue here.

I figure it would be a good idea considering it would help lighten the load on the issues queue and would allow more pressing issues to get the attention they need.

I'd be willing to manage such an account but I think there are others who would be much more qualified to be such person. I'm looking forward to getting some feedback and also some suggestions on what exactly could/should be done with a Mastodon account.

I also propose making the account on Fosstodon.org as it's an open-source based instance. For full disclosure, it's important that I mention that I do have an account on Fosstodon.org and I really like the instance.

**Comment by strk** [comment]
I welcome the idea of a Mastodon instance, and would think a volunteer
manager is great as long as owners of the Gitea project (which are
elected yearly) get the keys to the account, shall the volunteer
disappear or act in odd ways :)

**Comment by BNolet** [comment]
I'm not sure if a full instance would be necessary but I can see the appeal as the volunteer/Gitea would have full control over the it. If you guys did go with an instance, be wary of the docker image as there's apparently still problems with sidekiq segfaulting (from what I've read in issues).

**Comment by mrsdizzie** [comment]
I think support is spread thin as it is and having a separate site/account to interact with issue reports wouldn't really help lighten the load at the moment but makes it more work (there are already many support questions in the forums that go unanswered because it is in a separate location, discord, etc...)

We could revisit if there is ever maintainer energy/support for this, but it seems that is not the case at the moment. Closing in the same spirit of lightening the issue queue to make pressing issues more clear.

**Comment by BNolet** [comment]
Understood :) Thanks for the explanation
