### ISSUE TITLE
Admin Command to reset 2FA

### ISSUE THREAD

**Issue by mcrosson** [go-gitea/gitea#5788]
- Gitea version (or commit ref): 1.7.0+rc3
- Git version: 2.18.1
- Operating system: Docker
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I admin a gitea instance and lost access to the admin's 2FA codes and recovery codes... I have access to the server via ssh but cannot find an admin command to reset the 2FA status.

Is this an option or is there a database query that can be run to reset the 2FA status?

**Comment by techknowlogick** [comment]
I've marked this as a feature, so that disabling 2FA can be added into the cli, but in the interim you can probably drop the row attached to your user in the `two_factor` table, I'm on mobile so I can't 100% confirm that'd work.

Also, not sure if you've lost your password as well (I saw something about you being locked out of keepass in your toots), and so if you need to reset your password you can run `gitea admin change-password --username myname --password asecurepassword`.
