### ISSUE TITLE
Proposal: Merge Git & SDK repos into main repo

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#5954]
merge git & sdk into this repo. We can still keep same import path (code.gitea.io/git & code.gitea.io/sdk)

I recommend we use folders: modules/git & modules/sdk

Having the two extra repos creates a barrier for new contributions and multiple redundant PRs. Easier if all other two repos were in this one.

Thoughts?

**Comment by zeripath** [comment]
I think in general this would be a good idea however, we will need to ensure that we somehow keep the external API stable for the SDK. So perhaps we could keep a testing suite outside of the current repo?

I would in particular be very keen to move them in because I think both git and the sdk are not getting updated properly (and I know I'm guilty of this)

**Comment by bclermont** [comment]
I just noticed that there is no test units for the API server (and go-sdk).

I experience few bugs in the go-sdk and I wanted to add tests for the api routers, which will be super easy to do when go-sdk is merged into main repo. Because I just need to implement tests for go-sdk and it will test both server and client.

Will wait until then to do that

**Comment by zeripath** [comment]
Most of the api is tested in the integrations/ tests.

**Comment by bclermont** [comment]
ah thanks, I was looking into go-sdk for `*_test.go` files

**Comment by sapk** [comment]
This would also be more logic because currently the api response are defined in go-sdk. This would help the swagger part to be more maintained and maybe provide a stable generated client in various coding language directly from the swagger api specs.

**Comment by lunny** [comment]
Is move SDK to gitea main repo is a good idea? Maybe we could move all the structs on gitea main repo and sdk repository could dependent that sub package.

**Comment by sapk** [comment]
@lunny We can even move struct to main and generate the various sdk client from swagger.

**Comment by techknowlogick** [comment]
I think it is good for sdk to be in the main repo because we can use sub packages to keep things split up like they are, but still keep PRs manageable. As currently we have to ensure that we merge in sdk PRs before PRs in main repo, it'd be nice if we could just have one PR.

**Comment by lunny** [comment]
@techknowlogick yeah, just structs then most time, we don't have to send two PRs to two repo. And SDK could follow some reversion of the structs sub package  in go mod to keep compatible.
