### ISSUE TITLE
[Question] Why when I merge from web commits are not verified?

### ISSUE THREAD

**Issue by pando85** [go-gitea/gitea#5962]
In GitHub if you merge a PR that commit will be marked as verified. In Gitea merge commits are not verified. Am I missing something?

**Comment by lafriks** [comment]
GitHub generates inrernal pgp key for each user and uses that for commits from web UI and merges

**Comment by pando85** [comment]
I think this is not priority but are you thinking in implement this feature?

**Comment by lafriks** [comment]
currently there is no plans for this

**Comment by jolheiser** [comment]
I was looking in to this today and found something interesting. GitHub actually does **not** generate a key for each user, it only uses one. I had also been under the assumption that each user had their own internal key.
In their [article about GPG](https://help.github.com/en/articles/about-commit-signature-verification) they reveal the link to their [GPG key](https://github.com/web-flow.gpg) they use for "web flow".  

I only mention this in case someone does pick this up, perhaps it would make sense to just generate one internal key for the specific Gitea instance rather than one internal key for each user?

**Comment by adelowo** [comment]
Nice.. Thanks @jolheiser
