### ISSUE TITLE
Mailer errors with TLS when it shouldn't use it

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#5967]
- Gitea version (or commit ref): 1.7.1
- Git version: 
- Operating system: SuSe Linux 12
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2019/02/05 08:44:41 [...les/mailer/mailer.go:246 processMailQueue()] [E] Failed to send emails [some@mail]: Subject: [OutdatedTest] Test (#1), issue comment - gomail: could not send email 1: StartTLS: read tcp giteaip:31542->smtpip:25: read: connection reset by peer       
```
## Description

I'm trying to set up the mailer to send mails to members on updates of PRs, but the mailer seems to fail.

I've made sure that the server Gitea is running on has the permissions to send mails via our mail server and I've confirmed that by sending mails via telnet from the Gitea server.

The error itself is strange, because I'm trying to *not*  use any encryption.

app.ini:
```
[mailer]
ENABLED=true
FROM=...
HOST=smtpip:25
IS_TLS_ENABLED=false
MAILER_TYPE=smtp
```

**Comment by d-Pixie** [comment]
I think I remember seeing that Gitea will always use `StartTLS`, regardless of if the communication is then over TLS...

Yeah, if you look here https://docs.gitea.io/en-us/config-cheat-sheet/ under `Mailer` and `SKIP_VERIFY` it says `Note: Gitea only supports SMTP with STARTTLS.` so that is by design.

As for why, StartTLS is a call to upgrade to TLS if the server supports it. If you specify TLS on the other hand it means the server HAS to support it and negotiations will start out on that assumption. With StartTLS the server might only support plain text, might support SSL or might support TLS and the communication is negotiated depending on what the server replies. Read more here: https://en.wikipedia.org/wiki/Opportunistic_TLS

**Comment by andreymal** [comment]
***@‍stale*** I have the same problem

@d-Pixie @MarkusAmshove plz reopen?

**Comment by MarkusAmshove** [comment]
I can't seem to reopen
