### ISSUE TITLE
Dark blue theme

### ISSUE THREAD

**Issue by artixnous** [go-gitea/gitea#6011]
I've modified arc-green theme to [dark blue](https://gitea.artixlinux.org/artix/gitea-dark-blue/src/branch/master/theme-arc-blue.css), and it's being used at [our gitea repository](https://gitea.artixlinux.org). It's extensively tested and should be pretty much complete, covering even the API/swagger page. If there's any interest, I could do a PR.
## Screenshots
![screenshot at 2019-02-09 01-46-03](https://user-images.githubusercontent.com/6310912/52512281-bc2ff500-2c0c-11e9-9617-ed46bc26c8ea.png)

**Comment by lunny** [comment]
Maybe we should create a theme market so that everyone could upload his themes and others could download and apply.

**Comment by rakshith-ravi** [comment]
> Maybe we should create a theme market so that everyone could upload his themes and others could download and apply.

I really don't want to come-off as a smart ass, but I feel that would be a lot of effort. Shorter goals with more visible achievements usually motivate people better. Perhaps we can try something as simple as a "upload theme" feature in the admin panel where a zip file is uploaded and that places the css, template, etc from the zip file into the public folder so that it automatically starts working on refresh. It would be much more easier to implement as well as would achieve the intended feature.

Again, just my opinion. No offence intended.

**Comment by sapk** [comment]
It should be easily possible for people to use this theme by simply adding the css to https://github.com/go-gitea/gitea/blob/master/templates/custom/header.tmpl
But maybe can add a textfield for admin and user to load a custom css to be accessible via the ui.

**Comment by jolheiser** [comment]
As a current workaround, this file `theme-arc-blue.css` can be added to `custom/public/css` and allow users to choose `arc-blue` as a theme.  
This works only if the supplied style is meant to completely replace `arc-green` (rather than override certain parts) since it essentially "tricks" Gitea into loading it in the header in place of `arc-green`.  

Signed in user
https://github.com/go-gitea/gitea/blob/8d2c24f7f9b9bce3a806e4748623bd3b2742025b/templates/base/head.tmpl#L152

Anonymous user
https://github.com/go-gitea/gitea/blob/8d2c24f7f9b9bce3a806e4748623bd3b2742025b/templates/base/head.tmpl#L155

**Comment by artixnous** [comment]
It's a complete replacement, enabled as described above in gitea's .ini file, only not "arc-blue" but "dark-blue".

**Comment by gsantner** [comment]
Just as a note, added your css file to `custom/public/css/theme-arc-blue.css` and `arc-blue` to app.ini.>THEMES and the option in UI was there, had not to recompile or something

**Comment by Oreolek** [comment]
So any plans on this? Not the theme market, just this theme?

**Comment by jolheiser** [comment]
If you look at my above comment, this is currently possible with a little hacking.  
I named it `arc-blue` instead, but it is the theme from this issue.

![arc-blue](https://user-images.githubusercontent.com/42128690/57787293-b4478b80-76fa-11e9-8f71-1f979d9bed95.png)
![arc-blue-theme](https://user-images.githubusercontent.com/42128690/57787294-b4478b80-76fa-11e9-82ac-b4e33e7ba23b.png)

As for official support for themes, no one is working on it currently that I know of.

**Comment by Th3Whit3Wolf** [comment]
Hmm. I copied the css to `custom/public/css/theme-arc-blue.css`

and copied
https://github.com/go-gitea/gitea/blob/8d2c24f7f9b9bce3a806e4748623bd3b2742025b/templates/base/head.tmpl

into `custom/public/templates/base/head.tmpl` 

but I'm not seeing it as an option for a theme.

I'm using gitea v1.9.2, did I miss something?

**Comment by gsantner** [comment]
THEMES                = gitea,arc-green,arc-blue

settings

**Comment by Th3Whit3Wolf** [comment]
That fixed it. My fault for not reading the documentation first.

**Comment by MasterGroosha** [comment]
Sorry for dumb question, but where are these files in Gitea docker installation? I've /bin/bash-ed into container, but cannot find any html/tmpl/css files at all. Also I'm running an "offline" installation just for me.

**Comment by sapk** [comment]
The default files are packaged inside the binary at build time you need to create a custom folder. Please read the docs: https://docs.gitea.io/en-us/customizing-gitea/
You can find the packaged file like template (as example) in the gitea repository : https://github.com/go-gitea/gitea/tree/master/templates

**Comment by gerroon** [comment]
Hi

This theme has issues with the code (indexer) search pages :(

**Comment by artixnous** [comment]
@gerroon Please, provide a full URL of the problematic page. I only maintain the theme on [our own server](https://gitea.artixlinux.org) and I don't see the "<> Code" tab there.

**Comment by gerroon** [comment]
Code is enabled if you enable "indexer"

https://docs.gitea.io/en-us/repo-indexer/

**Comment by artixnous** [comment]
[Fixed](https://gitea.artixlinux.org/artix/gitea-dark-blue/src/branch/master/theme-arc-blue.css).

**Comment by soulawaker** [comment]
@artixnous Thanks for the dark theme applied to swagger. I tried and it worked but white swagger pages still poke my eyes. How can I apply the theme to swagger? I'm using gitea 1.11.4.

**Comment by artixnous** [comment]
May I see a screenshot?

**Comment by soulawaker** [comment]
@artixnous  Yes, I've attached it.
 
![gitea-api-swagger](https://user-images.githubusercontent.com/5372217/81927224-4213ca80-961e-11ea-8979-fbd9643151b2.png)

**Comment by artixnous** [comment]
Hm, not sure why you get such results; please, have a look into [our Gitea instance](https://gitea.artixlinux.org/api/swagger) and try to find out why yours isn't themed. Also, please make sure you're using the [latest CSS from our repo](https://gitea.artixlinux.org/artix/gitea-dark-blue/src/branch/master/theme-arc-blue.css).
![Screenshot at 2020-05-15 17-50-04](https://user-images.githubusercontent.com/6310912/82064243-2dded480-96d5-11ea-90bd-70ca5777db62.png)

**Comment by soulawaker** [comment]
@artixnous Thanks for reviews! I'll try to find things.

**Comment by lunny** [comment]
Maintaining a theme will spend many times so that we will not maintian many themes officially. So I think this should not be merged into gitea main branch. And you can always find all kinds of themes here https://gitea.com/gitea/awesome-gitea#user-content-themes .

I will close this issue, and please go to https://discourse.gitea.io/c/themes/9 to discuss about themes.
