### ISSUE TITLE
.mailmap support

### ISSUE THREAD

**Issue by netravnen** [go-gitea/gitea#6120]
Do Gitea support `.mailmap` in repositories when viewed in web-interface? _(When trying to verify against my own running instance (version 41a2bfe). It does not seem `.mailmap` support is present in gitea. No previous GH issues/PR on this, either.)_

If not... Is it possible put an implementation of `.mailmap` support on the Gitea Development roadmap?

**Comment by lafriks** [comment]
It is not supported currently

**Comment by nemphys** [comment]
Any news on this one? It would be a nice feature, needed by many nowadays.

**Comment by lapo-luchini** [comment]
#15009 seems to be related.

**Comment by lunny** [comment]
> #15009 seems to be related.

Since the requirement is not very clear. Let's close this one first.

**Comment by lapo-luchini** [comment]
AFAICT this is not closed yet, but I [created a test repo](https://gitea.lapo.it/lapo/mailmap-test/) to make requirements more clear.

I don't know about the OP, but this is what I personally desire: that the GUI does the equivalent of this

```
% git log --mailmap
commit 797567a0b6ea63c0b7ffeeca4d1ca48c893f2b06 (HEAD -> master, origin/master)
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:26:49 2024 +0100

    Add .mailmap

commit 83132f69cac05a086508ffd66599f5a2718ece47
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:24:40 2024 +0100

    Committed with readl name and email.

commit 7371602a84f3f52ac7bb3f6ad144a55fb4ac0848
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:24:17 2024 +0100

    Committed with real name and email alias C.

commit 3631514f0cdeec1da923e0d292f88988d0b7cd7e
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:23:55 2024 +0100

    Committed with alias B

commit 5fc6b26b440ee98f47c1ca33c1702df84381b717
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:23:35 2024 +0100

    Committed with alias A
```

instead of this

```
% git log --no-mailmap
commit 797567a0b6ea63c0b7ffeeca4d1ca48c893f2b06 (HEAD -> master, origin/master)
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:26:49 2024 +0100

    Add .mailmap

commit 83132f69cac05a086508ffd66599f5a2718ece47
Author: Lapo Luchini <lapo@lapo.it>
Date:   Mon Mar 11 23:24:40 2024 +0100

    Committed with readl name and email.

commit 7371602a84f3f52ac7bb3f6ad144a55fb4ac0848
Author: Lapo Luchini <alias_c@lapo.it>
Date:   Mon Mar 11 23:24:17 2024 +0100

    Committed with real name and email alias C.

commit 3631514f0cdeec1da923e0d292f88988d0b7cd7e
Author: Alias B <alias_b@lapo.it>
Date:   Mon Mar 11 23:23:55 2024 +0100

    Committed with alias B

commit 5fc6b26b440ee98f47c1ca33c1702df84381b717
Author: Alias A <alias_a@lapo.it>
Date:   Mon Mar 11 23:23:35 2024 +0100

    Committed with alias A
```

![image](https://github.com/go-gitea/gitea/assets/420454/9b8b7840-3546-4ff3-97ef-0b70e1e99c7f)

So basically I'd like all 5 rows like the first two (with real name and link to user).

Right now this can be obtained in Gitea if each single user add "secondary emails", but `.mailmap` is a way to do that centralized in the repository, which is easier for repos with a lot of contributor (some of which might not even have a local account to add a secondary email to).
