### ISSUE TITLE
Wrong username in registration notification mail

### ISSUE THREAD

**Issue by bouffa** [go-gitea/gitea#6161]
- Gitea version (or commit ref): 1.7.2
- Git version:  2.20.1.windows.1
- Operating system: Windows 7 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Upon registration, the notification mail contains :

`You can now login via username: {{.Username}}.`

Where Username is the full name and NOT the real username.

...

**Comment by mrsdizzie** [comment]
This happens because it uses DisplayName():

https://github.com/go-gitea/gitea/blob/60ba903a57f8ac6f40ba6e10d03f2e23acc7c2c3/models/user.go#L643-L651

In many cases of adding a user, the Web form only asks for a username at first so the email is sent with the right value in Username. However if you use the API or other tool to create a new user where you can also include the full name at the same time, it will then produce the bug above. This probably slipped by because of the confusing choice of "Username" as the variable.

Username should change to always be the actual username and a new/separate value called "Name" or something can be used for the current behavior of using the full name if available and if not falling back to username
