### ISSUE TITLE
UX: Commit status not visible in presence of long log summary

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#6190]
As of Gitea 1.5.2 commit statuses for commits having a summary log longer than a given number of characters are truncated with the final part replaced by `...`. In these cases the commit status icon related to CI reporting (Drone) isn't shown (is truncated, I guess).

Note that the commit page itself does NOT report the status either so there's no way to tell the status of the commit. Pretty annoying.

I did not try on try.gitea.io

**Comment by strk** [comment]
Here's where you can see the problem: https://git.osgeo.org/gitea/geos/geos/pulls/74#issuecomment-3845

**Comment by techknowlogick** [comment]
@strk as I'm a bit jetlagged I just want to ensure that I am understanding everything correctly, I apologize. You mean how on the commits tab of that PR, one of the commits doesn't have a status due to the commit message being too long (but the second commit does)? (I've attached a screenshot of the part I mean)
![screen shot 2019-02-26 at 10 38 54 am](https://user-images.githubusercontent.com/164197/53425333-c8f56c80-39b2-11e9-8ae7-95d674cf7d95.png)
