### ISSUE TITLE
No error message when trying to migrate repository with incorrect name

### ISSUE THREAD

**Issue by mateusza** [go-gitea/gitea#6254]
When providing following incorrect values as target repository name used in migration, gitea returns 500 HTTP response code, and no proper error message is displayed.

- `wrong.git`
- `..`

- Gitea version (or commit ref): ad86b84
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`): not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ( https://try.gitea.io/repo/migrate )
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

## Screenshots
![image](https://user-images.githubusercontent.com/7002/53903140-39e7f480-4043-11e9-9b5d-046563f06ad5.png)

![image](https://user-images.githubusercontent.com/7002/53903333-bda1e100-4043-11e9-9061-02d76e9c415b.png)

![image](https://user-images.githubusercontent.com/7002/53903376-d7dbbf00-4043-11e9-9f8c-93e9dad91538.png)

**Comment by mateusza** [comment]
And here is the log entry from my 1.7.3 instance:

`2019/03/06 19:02:06 [...routers/repo/repo.go:146 handleCreateError()] [E] MigratePost: name pattern is not allowed [pattern: *.git]`

**Comment by techknowlogick** [comment]
This issue has been raised before, however as I can't find the issue I am going to leave this open.

**Comment by jolheiser** [comment]
The issue with the same problem is #3799

The problem is these lines:
https://github.com/go-gitea/gitea/blob/ad86b843e1d1984ec1b69f51276654469644bdd5/routers/repo/repo.go#L142  
https://github.com/go-gitea/gitea/blob/ad86b843e1d1984ec1b69f51276654469644bdd5/routers/repo/repo.go#L265

More specifically the second one. When the error is "sanitized" it is no longer an `ErrNamePatternNotAllowed`, it is a `urlSafeError` and so Gitea returns a `ServerError`
https://github.com/go-gitea/gitea/blob/ad86b843e1d1984ec1b69f51276654469644bdd5/modules/util/sanitize.go#L22-L26


I will try to get a PR in for this, and I'll probably add #6253 to it as well since they are for the same process and shouldn't be very big.

**Comment by jolheiser** [comment]
Just a note, this issue was actually fixed by #6290
