### ISSUE TITLE
Issue with long name does not fit in dependencies dropdown list

### ISSUE THREAD

**Issue by CrowMash** [go-gitea/gitea#6262]
- Gitea version (or commit ref): 1.7.0
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/CrowMash/Test/issues/2 (try adding the issue 1 in dependency)
  - [ ] No
  - [ ] Not relevant
- Web browser: Chrome 72.0.3626.121

## Description

If you try to add a dependency with a long name, it does not fit in the dropdown list.

## Screenshots

![image](https://user-images.githubusercontent.com/9526631/53945743-8f171b00-40c2-11e9-85ef-44ad07983f9c.png)
![image](https://user-images.githubusercontent.com/9526631/53945698-6f7ff280-40c2-11e9-953a-8dcfbd2e4dfe.png)

**Comment by stevegt** [comment]
Related to #4479

**Comment by lunny** [comment]
Is it duplicated?

**Comment by stevegt** [comment]
@lunny I think it's probably not a dup -- #6262 looks like it just needs an HTML/CSS fix, while #4479 has to do with issue search.  I only linked the two because anyone using dependencies and fixing one bug might be interested in fixing the other.  (I was hoping to tackle both bugs two months ago but life has happened to me again...)
