### ISSUE TITLE
cant Pull request inside a forked repo

### ISSUE THREAD

**Issue by salco** [go-gitea/gitea#6318]
- Gitea version (or commit ref):91775c1
- Operating system: https://try.gitea.io

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/nutal/test/pulls/2
  - [ ] No
  - [ ] Not relevant

## Description
If a pull request is open from a forked repo, it will automatically be apply to the source it's forked.
The issue is that we can only see the branch from the source that we've forked and we are unable to easily change the target to apply the pull request.

The only "hack" we can do is change the username or the organisation targeted inside the URL to be able to get the correct usage.

By default I think we need to be able to do pull request inside the repo we work, even if it's a fork.
...

**Comment by lunny** [comment]
duplicated with #6225 ?

**Comment by zeripath** [comment]
Hmm, I'm not certain if this is the same.

So when you click on PullRequest from a fork it is assumed that you want to merge into the original repository not the fork.

Now, there's no way of changing the base repository easily except to change the URL by hand.

The UI for compare needs to allow you to select the fork repository branches to merge in, and needs to allow you to suggest other repositories. Similarly we need to allow users to change repository for the pulled branch.

**Comment by salco** [comment]
Exact and I think it's best if the "default" PullRequest suggested need to be the repository where the PullRequest is created.

**Comment by wpmp** [comment]
Has this issue been resolved?

**Comment by zeripath** [comment]
The compare diff page needs to be rewritten to allow for easy changes to the base repo and head repo

**Comment by dloez** [comment]
Upgraded to Version 1.15.6, this is still happening.

**Comment by creamteam-de** [comment]
we have also the same problem in the latest version :(. Is there any plan to fix it?

**Comment by lunny** [comment]
Hm, what's the problem? Could you show some screenshots or logs? Maybe this is the different thing from before?

**Comment by salco** [comment]
Was it working in 1.15.3 for us it work fine, but we did not try upgrading to 1.15.6 for the moment.

**Comment by dloez** [comment]
We have a main repository, let's call it "main-repo", and a forked repository of "main-repo" called "forked-repo". Both repositories share "master" and "develop" branches. If you create a new branch on "forked-repo" (let's say "new-branch") and then try to create a PR it shows a 404 page. In the URL you can see that git tried to point to "main-repo" instead of "forked-repo". If you change the URL by hand, instead of pointing to "main-repo - new-branch" point to "forked-repo - new-branch" it then works. It wasn´t working either for us on the previous version that we were using (1.12.5). We used others versions (1.9.2, 1.11.1, 1.11.5, 1.12.1, 1.12.5, 1.15.6) but cannot confirm that PRs weren´t working back then because we didn´t use them.

I cannot see anything related on the logs.
![image](https://user-images.githubusercontent.com/40007435/147465200-0e94ccf0-2bd5-4094-a9dd-cfdaa687e702.png)

**Comment by lunny** [comment]
> We have a main repository, let's call it "main-repo", and a forked repository of "main-repo" called "forked-repo". Both repositories share "master" and "develop" branches. If you create a new branch on "forked-repo" (let's say "new-branch") and then try to create a PR it shows a 404 page. In the URL you can see that gitea tried to point to "main-repo" instead of "forked-repo". If you change the URL by hand, instead of pointing to "main-repo - new-branch" point to "forked-repo - new-branch" it then works. It wasn´t working either for us on the previous version that we were using (1.12.5). We used others versions (1.9.2, 1.11.1, 1.11.5, 1.12.1, 1.12.5, 1.15.6) but cannot confirm that PRs weren´t working back then because we didn´t use them.
> 
> I cannot see anything related on the logs. ![image](https://user-images.githubusercontent.com/40007435/147465200-0e94ccf0-2bd5-4094-a9dd-cfdaa687e702.png)

Can you reproduce that in https://try.gitea.io? If that, please give the repository URL?

**Comment by dloez** [comment]
I cannot reproduce the error on https://try.gitea.io. These are the repositories that follow the example I said.
- https://try.gitea.io/lopezd/main-repo
- https://try.gitea.io/lopezd_1/forked-repo

When I click the "New pull request button" the URL for the comparison page is different. On our server gitea tries to fetch new-branch from main-repo (which doesn't exist). On try.gitea.io this is the URL: https://try.gitea.io/lopezd/main-repo/compare/master...lopezd_1:new-branch  It is still pointing to main-repo, which I understand to be the expected behavior, but instead of fetching new-branch, it fetches master.
What can be causing this different behavior?

**Comment by dloez** [comment]
> Edit: I also want to add that in our case the owner of both repositories is the same.

Reproduced on [https://try.gitea.io/](https://try.gitea.io/). Repository [https://try.gitea.io/lopezd/base-repo-fork](https://try.gitea.io/lopezd/base-repo-fork). If you navigate to branch `new-branch` and try to create a new PR from there, you will get redirected to [https://try.gitea.io/lopezd/base-repo/compare/main...new-branch](https://try.gitea.io/lopezd/base-repo/compare/main...new-branch) and get 404 as `new-branch` does not exist on the repo forked from.

We modified the link of the New PR button so it uses `Repository` instead of `BaseRepo` which is actually the behaviour we were looking for but I guess that UI should handle the 404.

**Comment by zeripath** [comment]
I'm really not certain that #21519 and its backport are the solution. 

The main change in those PRs is drop using the short fork notation - which I don't think are going to be the problem.

## Example

If you have the following repos:

`owner/base`

`forker/forked` - forked from `owner/base`

Then the short fork notation `/owner/base/compare/branch...forker/newbranch` should work equally as well as `/owner/base/compare/branch...forker/forked/newbranch`

## What's really going on?

There are two problems I could imagine happening - neither of which are clear from the associated issue:

## Reforked repos

If you have:

`reforker/reforked` - forked from `forker/forked` then the short fork notation won't work on `owner/base` and you'd need the full notation to create a PR from `reforker/reforked` to `owner/base` - but I don't think we'd be offering this by default.

## Permission Denied to create PRs on `owner/base`

I think another possible problem is where the user doesn't have permission to create a PR `owner/base` by default then the compare link is incorrect and we should be checking if the user could have permission to create PRs on `owner/base` before offering the compare link to it.
