### ISSUE TITLE
Gitea wont start , Status Code 2 on Systemd on Centos 7

### ISSUE THREAD

**Issue by dukesx** [go-gitea/gitea#6374]
- Gitea version (or commit ref): 1.7.4
- Git version: 2.19
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist: it doesnt log anything , it wont start at all , systemd is saying status code 2

## Description

So , i have a server with cPanel with Centos 7. I tried installing via the docs but however i work , systemd just does not start Gitea at all. 

Sometimes it says Code 2 or Code 203 , i have tried running "git" user and "root" , both have their own errors.

 I did add relevant permissions to `/etc/gitea` and `/var/lib/gitea` as well. I also `chmod +x` to gitea binary. No solution. Please Help ! 

**Update**: Now the Service , switches state after each second , one second it is up and on the other second it is down ..... See the screenshots 

...

## Screenshots
![ajeeb](https://user-images.githubusercontent.com/5988991/54627059-57ca4600-4a94-11e9-8495-470298f6c338.png)

**Comment by jolheiser** [comment]
Is there anything in your `gitea.log`?

**Comment by Domain** [comment]
> Is there anything in your `gitea.log`?

I have the same issue with gitea 1.11.3 on CentOS 8.1, the exit status is 203 without any log

**Comment by Domain** [comment]
I have the same issue with gitea 1.11.3 on CentOS 8.1 without any log.
systemctl status:

> ● gitea.service - Gitea (Git with a cup of tea)
   Loaded: loaded (/etc/systemd/system/gitea.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-03-18 16:11:19 CST; 169ms ago
  Process: 37372 ExecStart=/home/git/bin/gitea web --config /home/git/custom/conf/app.ini (code=exited, status=203/EXEC)
 Main PID: 37372 (code=exited, status=203/EXEC)

journal entries:

> Mar 18 15:42:54 localhost.localdomain systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Mar 18 15:42:54 localhost.localdomain systemd[1]: gitea.service: Scheduled restart job, restart counter is at 5.
Mar 18 15:42:54 localhost.localdomain systemd[1]: Stopped Gitea (Git with a cup of tea).
Mar 18 15:42:54 localhost.localdomain systemd[1]: Started Gitea (Git with a cup of tea).
Mar 18 15:42:54 localhost.localdomain systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Mar 18 15:42:54 localhost.localdomain systemd[1]: gitea.service: Failed with result 'exit-code'.
Mar 18 15:42:56 localhost.localdomain systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Mar 18 15:42:56 localhost.localdomain systemd[1]: gitea.service: Scheduled restart job, restart counter is at 6.
