### ISSUE TITLE
[API] Add params to milestone API with order

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#6384]
Current milestone API return both closed and open milestones, `/repos/{owner}/{repo}/milestones`.

It would be useful if it accept params to filter close and open milestones easily with order will be plus.
Open:  
`/repos/{owner}/{repo}/milestones?status=open&order=desc`

Closed:  
`/repos/{owner}/{repo}/milestones?status=close&order=desc`

**Comment by esfraner** [comment]
Is it currently possible to get closed milestones by using API? I have tried with `?state=closed`, and 
`?status=closed` but without luck :cry: 

I am using latest from master.

**Comment by adelowo** [comment]
Don’t think that’s possible yet as no one has worked on this

**Comment by esfraner** [comment]
> Don’t think that’s possible yet as no one has worked on this

Thanks for your fast reply :smile:

**Comment by adelowo** [comment]
@mmarif4u I just checked and that endpoint returns only opened milestones since https://github.com/go-gitea/gitea/pull/5051 .  

I will make a PR to add the `state` params to the API like that of GitHub 

See https://developer.github.com/v3/issues/milestones/#list-milestones-for-a-repository and https://github.com/go-gitea/gitea/pull/5051#issuecomment-441560092

**Comment by esfraner** [comment]
Thank you so much for everything :smile:

**Comment by adelowo** [comment]
Done @esfraner .. See https://github.com/go-gitea/gitea/pull/7131
