### ISSUE TITLE
Add release notifications

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#640]
I suppose add a new notification when a new release published. All watched user could receive a release notification via UI or mail. This could be an option for user, default is true.

**Comment by appleboy** [comment]
Nice feature.

**Comment by lunny** [comment]
Since #765 has moved to v1.2, let's move this one also.

**Comment by markg85** [comment]
+1 for this feature. I just had a need for this for another project on github and ended up using gitpunch.
You could choose to not add this and stay compatible with how the release rss looks so that gitpunch also works in gitea.

Still, would be nice if this would be a build-in feature to not rely on a external service for release notifications.

**Comment by suatfk** [comment]
if still open can you assign it to me ?

**Comment by mrsdizzie** [comment]
Release notification added in #12463
