### ISSUE TITLE
1.7.6 release does not contain builds

### ISSUE THREAD

**Issue by NotAFile** [go-gitea/gitea#6600]
## Description

The most recent 1.7.6 security release does not contain builds on github

**Comment by rakshith-ravi** [comment]
This affects 1.8.0-rc3 as well

**Comment by techknowlogick** [comment]
They are currently being built

**Comment by rakshith-ravi** [comment]
Oh. My bad🙈🙈

Is there a link to the right drone build so that we can track the progress?

**Comment by techknowlogick** [comment]
Sadly due to an error with an upstream dependency I am building these offline. I've just published the 1.7.6 binaries to GitHub as well as our download site, and will start on 1.8.0-rc3 now.

**Comment by rakshith-ravi** [comment]
Oh my! Building them offline? What happened to drone? I can maybe help fix it up

**Comment by techknowlogick** [comment]
Do not worry. Nothing is wrong with drone. I am using the drone cli to build. It's due to the cross compiling image that we use has some differences the commands being run in sh vs bash (offline I can target bash as needed). I have a PR ready to submit but as the release has already been tagged and downstream (arch, nix, etc..) is already targeting it, I don't want to re-tag. It'll be resolved by next RC or stable whichever comes first.

**Comment by techknowlogick** [comment]
1.8.0-rc3 binaries have been uploaded to both locations now. I'm going to keep this open to link to a PR that resolves this.
