### ISSUE TITLE
gitea-1.8.0-rc3-linux-amd64.sha256 exposes wrong file?

### ISSUE THREAD

**Issue by Perflyst** [go-gitea/gitea#6614]
In the releases is a file `gitea-1.8.0-rc3-linux-amd64.sha256` which has `gitea-master-linux-amd64` listed instead of `gitea-1.8.0-rc3-linux-amd64`

`d24df15bda3a301fd71ee814d0672f1d9ce7efe88b39fa5f9aebe59506bb9f24  gitea-master-linux-amd64`

**Comment by lunny** [comment]
Where did you mean? github releases or dl.gitea.io?

**Comment by Perflyst** [comment]
GitHub releases

**Comment by lunny** [comment]
@techknowlogick is 1.8rc3's binaries released via drone-cli ?

**Comment by techknowlogick** [comment]
I had to rename the files due to combination of make and `drone exec --event tag --ref v1.8.0-rc3 --repo go-gitea/gitea` setting the file name to be master instead of correct tag. I chose to rename instead of keep master in name so that some auto update scripts that target binaries directly still function. The recently merged PR will resolve this for future builds (and the backport that isn't yet merged will solve this for stable 1.8.0 build). The is same for 1.7.6 release as well.

The above sha hashes should have incorrect filename for both github releases and dl.gitea.io. You can check that the hashes are indeed the same it just has a different filename.

**Comment by Perflyst** [comment]
Yes, hashes are correct. Was just a bit confusing.

**Comment by lunny** [comment]
Let's close this when next build sha is correct.

**Comment by techknowlogick** [comment]
Closing as builds now correctly build and put in correct filename. Next RC will have correct filename.

Thanks for keeping an eye on things like this.
