### ISSUE TITLE
Mirror issues links in commits

### ISSUE THREAD

**Issue by Aviortheking** [go-gitea/gitea#6796]
## Description

Actually if a repo is a mirror and the commit has issue ids in the message they are sended to gitea issues and show 404 error this could be corrected by mirroring issues.

ex: https://gitea.com/gitea/gitea_mirror

...

## Screenshots
![image](https://user-images.githubusercontent.com/15822031/56883687-b60d2000-6a67-11e9-8145-d0a80e92ce65.png)

**Comment by mrsdizzie** [comment]
I don't think mirroring issues is going to happen/makes sense, but this could be fixed by the admin by choosing external issue tracker for the mirror repo and pointing it at the original location (so github in this example).

**Comment by Aviortheking** [comment]
It would be awesome

**Comment by techknowlogick** [comment]
Closing this as you can use "external issues" to appropriately link to issues in remote locations. If you go back to your example above you'll see that I've set up external issues so that when you click on one you are taken to the correct issue in the original repo.

As a side note: I wouldn't want to accidentally create a feature that causes a DDoS against any site (that includes GitHub).
