### ISSUE TITLE
中国人发起的项目，竟然禁止使用中文？这是什么逻辑？

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#703]
Gogs 是中国人创建的项目，竟然禁止在Issues提交中文？这是什么意思？看不起中文吗？
Gogs is a project created by the Chinese people, even banned in the Issues submission of Chinese? What's the meaning of this? Do you look down on Chinese?

中国文化博大精深，每一个字都有深刻含义，可以准确无误的表达任何意思，而英文只有26个字母的组合，有时很难准确表达一件事情的本意。
Chinese culture is broad and profound, each word has a profound meaning, can accurately express any meaning, and English is only a combination of 26 letters, sometimes it is difficult to accurately express the intention of a thing.

其次，既然是中国人创建的项目，凭什么不允许使用中文？种族歧视？瞧不起中国文化？有趣。
Secondly, since it is a project created by the Chinese people, why not use Chinese? Racial discrimination? Look down upon Chinese culture? VERY INTERESTING.

**既然你们嫌弃原作者把项目占为己有，那么你们连使用的语言都进行限制，你们的行为跟他又有什么区别呢？**

**Comment by lunny** [comment]
Gitea want to be a global project. We have to chose one language almost everyone could know it so that we can communicate each other. So which languages should be chosen, Chinese or English? Of course, I think localization is also important. We have already Chinese QQ Qun: 328432459 and a dicscuss channel on gocn.io https://gocn.io/topic/Gitea.

**Comment by ghost** [comment]
既然你们想成为一个国际项目，那么就更应该尊重语言多样化。更何况你们是国际项目，项目本身就支持多国语言，不是吗？那么Issues凭什么就不允许使用中文？我认为这简直是侮辱中国的体现。QQ群的确有用，但是毕竟大部分开发者还是会使用Issues而不是加入一个玩具似的QQ群。

**Comment by lunny** [comment]
如果你用中文，那么你就无法获得很多人的帮助，毕竟愿意向Gitea贡献代码的绝大部分都懂英语而懂中文的是少数。如果哪一天Gitea的贡献者中懂中文的占大多数，我就倾向于用中文作为唯一语言来沟通。

**Comment by appleboy** [comment]
Totally agree with @lunny

**Comment by caiwp** [comment]
Hello world!

**Comment by luffyke** [comment]
Totally agree with @lunny

**Comment by ghost** [comment]
@lunny 说来说去，中文不怎么流通，我们就应该尽量避免使用这门语言。如果所有人都这么想呢？那中文永远都不可能成为国际化语言。我们自己都自发的去阻止，更何况其他人。

其次，您说贡献代码的大部分都是老外或者是懂英语的，但是您知不知道，大部分【使用者】都是不懂英语、真正的中国人呢？那如果使用者想要提交Issues，暂且不说他们会不会用这不支持多国语言的GitHub，那么大部分的BUG难道是开发者能够发现的吗？这就好像微软公司的Windows系统和Linux系统的概念了。微软封闭，自己人发现BUG，能跟全世界的用户发现Linux的BUG是一个级别的吗。

**大部分的问题、BUG和建议，都是使用者发现和提出的，而不是开发者。**

最后，作为一个中国人，我认为，不管中文是否流通、不管国家到底如何、不管别的人懂不懂，我都必然会支持自己的国家，自己的母语，而不是所谓：“如果哪一天Gitea的贡献者中懂中文的占大多数，我就倾向于用中文作为唯一语言来沟通。”

在我们这些使用者看来，甚至有一部分开发者看来，英文对于我们来说才是真正不流通的——因为这是中国人自己的项目。

**Comment by insionng** [comment]
https://github.com/go-gitea/gitea/issues/632 类似问题我也提过意见，但是现在看样子并没有触动什么~

**Comment by lunny** [comment]
@SourcePowered 我说过了本地化也很重要，因此我们有中文的群和论坛都可以提交问题和Bug，这些渠道都是通畅的。

事实上，目前我们的贡献者中大部分都不是母语英语者，法语的，意大利语的，西班牙语的，俄语的，大家都是用英语来交流。而且也许他们的英语并不比你好。微软在全球都有公司，有本地化的人去和客户沟通。我们作为一个开源项目当然做不到这个程度。

**Comment by ghost** [comment]
@lunny 你们当然完全不必做到这个程度，各类语言都使用的到。但是，作为中国人的你，对中国人必定要友好吧？比如，在GitHub上有许许多多的俄罗斯的项目，他们优先使用俄语，英语其次，即使再多的其他国家开发者，再多的人看不懂，他们依然坚持使用俄语，自己的母语。我认为，你们也应该这么做，中文作为首要交流语言，毕竟这项目就是中国的，主要开发者也是中国人，英文辅之，而不是英文首要，甚至中文问题都禁止发表。

**Comment by appleboy** [comment]
@SourcePowered 同意你的論點，但是在這邊我想要表達一點就是，今天你使用 gitea 遇到問題或者是 bugs，你在這邊寫中文，可以想看看，目前有時間或能力幫忙看或者是解決問題的開發者有哪些，他們是否都看得懂中文，當你發了問題，又沒有人可以幫忙的時候，你會感到很無助。如果是用了英文發問題，這邊大多數的貢獻者都看得懂英文，很現實的就是，如果你想要快速得到幫助，你就必須用英文發言。

PS. 目前看得懂中文又可以幫忙解決問題的[貢獻者](https://github.com/go-gitea/gitea/graphs/contributors)，看了一下似乎不超過五個？

**Comment by bkcsoft** [comment]
Actually, since this project was forked among the top 8 contributors only 1 (that I know of) speaks chinese. The others are 2 germans, 1 italian, 1 brazilian, 1 swedish (me) and 2 unknown (they don't tell). If someone speaking chinese wants help they'd have to wait for someone who speaks chinese to translate it, since Google Translate has failed me many times before in Gogs issues.

And in all fairness, Gogs has the same rule, only english 🙁 

![top8_gitea](https://cloud.githubusercontent.com/assets/4726179/22138842/f99fdc1c-dee2-11e6-87c2-c4e82df62022.png)

**Comment by luffyke** [comment]
I don't think we need to discuss such issue many times, as English is the common language the maintainers use, so all the users need to make sense that English is the only way we can communicate with each other.
And i think users should make maintainers more convenience when new a issue, maintainers are busy(they answer the questions, fix bugs, develop features and etc).
I would update the Chinese document let more people know how to post issues by Chinese.
