### ISSUE TITLE
Getting Gitea Installed successfully problems

### ISSUE THREAD

**Issue by SheepDomination** [go-gitea/gitea#7119]
I'm experiencing problems getting gitea installed. I have run the following command; `wget +O gitea https://dl.gitea.io/gitea/1.8.2/gitea-1.8.2-linux-amd64`; followed by `chmod +x gitea`. I now have two files one called `gitea` and another called `gitea-1.8.2-linux-amd64` although I don't know what to do with either of these files ?

**Comment by techknowlogick** [comment]
In your `wget` command you use `+O` instead `-O`, this may be the cause of your problem.

Instead of opening many issues in github with individual questions regarding setting up your Gitea install, discord would be a better place as it can help with troubleshooting. The discord channel can be found at https://discord.gg/Gitea
