### ISSUE TITLE
No link to external issue tracker in commit message

### ISSUE THREAD

**Issue by joestr** [go-gitea/gitea#7121]
- Gitea version (or commit ref): 1.9.0+dev-319-g160e7edd0
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.06
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/joestr/Testing)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I linked to an external issue tracker, but if I mention e.g. 'Fixing #2' in a commit message, there is no URL to click.

## Screenshots

![](https://i.imgur.com/WMloOTM.png)
![](https://i.imgur.com/KDOk8b1.png)

**Comment by joestr** [comment]
Ah, the link only appears if I click on the commit itself.

![](https://i.imgur.com/KclEYUo.png)

But wouldn't it be more convenient if the links would appear in the commit history and repository overview too?

**Comment by mrsdizzie** [comment]
This was changed in the past due to issues like https://github.com/go-gitea/gitea/issues/6809

And as noted, the links are still present for the commit itself. So was a slight trade off for consistence given the differences in Gitea design and implementation of the links

**Comment by mrsdizzie** [comment]
Not without several other changes -- its the same code that sees #2 and ```#2222222222```, or ```http://reallylongurl.com``` or  ```45f588e85dbd3004334718dc9fbbb27675814ee0``` as things to link so while you're particular example wouldn't take up the entire title another would.

**Comment by mrsdizzie** [comment]
Personally I wouldn't mind if they appeared in the commit view since those aren't already links to something else, but I do think they are broken in the repository view and can create a bad experience where it is possible to completely hide/break the link to the commit itself. 

They are just disabled for commit view for consistency with repository view since then the issue would just be "its enabled in one similar list view but not the other".

**Comment by joestr** [comment]
Hm, ok I will accept it then. Thanks for answering my question!
