### ISSUE TITLE
Unable to create a new topic because it's a substring of an existing one

### ISSUE THREAD

**Issue by ViViDboarder** [go-gitea/gitea#7126]
- Gitea version (or commit ref): 1.8.2 
- Git version: 2.17.1
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/iamthefij/test-tag-issue)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After creating a topic such as `prefix-suffix` and saving (on any repo), it becomes impossible to create a new topic named simply `prefix` because Gitea forces completion to `prefix-suffix`.

## Screenshots

![5148376377065472](https://user-images.githubusercontent.com/137025/58923084-ebee9580-86f2-11e9-9ef2-4cf0378821de.png)

**Comment by Cherrg** [comment]
one hotfix/workaround: add `prefix` first, then add `prefix-suffix`

i will take a look on the problem

**Comment by mrsdizzie** [comment]
Testing this, it isn't impossible to create the "prefix" tab, but the behavior of the suggestions dropdown is bad:

* It auto selects the first suggestion when it shouldn't select any (just display them)
* It actually returns the selection on hitting escape instead of closing the suggestions

A work around (if anybody else sees) is to first use the up arrow to unselect the suggestion and then you can type prefix and hit enter as normal.

**Comment by Cherrg** [comment]
thanks for the note about escape behavior

**Comment by Cherrg** [comment]
pr should fix that
