### ISSUE TITLE
Commit status indicator doesn't show latest status

### ISSUE THREAD

**Issue by DavidRobinsonDk** [go-gitea/gitea#7134]
- Gitea version: 1.8.2 built with go1.12.5 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.20.1
- Operating system: Ubuntu Server 19.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:
xorm.log:  https://gist.github.com/dr-consit/a17dd521ca658187b9393006b931c9ff

## Description
On my commits a seemingly random status is shown instead of the latest status.
In the screenshotted example there are 4 statuses:
https://gist.github.com/dr-consit/2dc0ccf34c5246dc9ec7de8fc60a5c97
As can be seen the last status (id: 4) is success, but as seen on the screenshot the failure is the one that is shown.

## Screenshots
![image](https://user-images.githubusercontent.com/26381190/58981013-c2f10200-87d1-11e9-8519-f3604fd73201.png)

**Comment by dr-consit** [comment]
OK, I have been poking about in the code and can see that it's because it shows the "worst" of the last statuses by context.
So if I have "error" as the last status of context "test" and "success" as last status of context "build", then even if the "build" status is newer that the "test" status, the shown status is still the "test" status.

I suppose this is by design.

**Comment by lunny** [comment]
@dr-consit yes, this is also which github's design I think.

**Comment by dr-consit** [comment]
@lunny Yeah, I suppose it's sane enough, I just never considered it. Maybe if the UI element had a hint with the context(s) and status it would be more "obvious" - or maybe I'm just oblivious ;-)

**Comment by lunny** [comment]
I have a PR to add status report on PR UI. see #6845
