### ISSUE TITLE
How upgrade from Gogs ver 0.11.53.

### ISSUE THREAD

**Issue by sloong** [go-gitea/gitea#7146]
My gogs version is 0.11.53.0603. In gitea docs just have "upgrade from gogs version 0.9.146 and older", no say how do if the gogs is newer, Now I don't know how upgrade. Please update the docs.

**Comment by sapk** [comment]
It must correspond to the last version tested. You can always backup data and try upgrade to gitea. If it doesn't work you can always spin-up an fresh install of gitea and migrate repo from gogs.

**Comment by lunny** [comment]
I think It's time to add a feature to migrate data from a Gogs/Gitea instance since we have finished migrate from Github. It's not too difficult, We need implement https://github.com/go-gitea/gitea/blob/master/modules/migrations/base/uploader.go#L9 just like https://github.com/go-gitea/gitea/blob/master/modules/migrations/github.go#L32

**Comment by sloong** [comment]
try replace from gogs to gitea binary file, but it don't works.
