### ISSUE TITLE
Downloads (Outdated shell script)

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#7160]
Hi there :hugs: 

I just installed Gitea after a while and thought the installation process got worse, so I decided to write a short issue: 

1) The current implementation lets me decide between "gitea" "theme" and "dl.sh"

The third item here on the list is an installation script. Great, it could be the default download link, since this is what I guess 99% of all users want. 

Sadly, its out of date, so far as I can see. No younger version as 1.4 is mentioned. 

2) "gitea" leads me into an imho convoluted S3 tree and Gitea itself provides neat UI options for releases. Dog food..

3) The binary is this tree is not signed as executable and also nowhere described as something that has to be marked so. I guess loads of people cant scry this and dont know about this mechanism beforehand. 

Thanks a lot for everything

**Comment by techknowlogick** [comment]
Thank you for the ticket. `dl.sh` is a script that helped up bootstrap our S3 software archive by fetching all the files that existed on Github so we could self-host all of our generated assets, not an install script. For sake of clarity I have since removed that script as it was only used once, and isn't for the end user.

As this script has been deleted from our hosting, I will close this ticket.

**Comment by ShalokShalom** [comment]
Just for clarification: The binary is still undescribed, the installation process still a bit tiresome. 
Thanks a lot
