### ISSUE TITLE
Docs: https://docs.gitea.io/en-us/upgrade/ is blank

### ISSUE THREAD

**Issue by thallada** [go-gitea/gitea#7208]
- Gitea version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description

The docs page for upgrading gitea (which is the top result for "gitea upgrade" is completely blank.

## Screenshots

<img width="1218" alt="Screen Shot 2019-06-14 at 7 48 27 PM" src="https://user-images.githubusercontent.com/1505923/59544196-050af980-8ede-11e9-8fb7-7cc93f6dee0a.png">

**Comment by jolheiser** [comment]
This looks to be a side effect of Hugo, the generator we use for our site.  
The page in question is supposed to be blank, only because it's true use is as metadata to display that "Upgrade" header in the side table of contents.  
  
That being said, if you are looking to update from a previous version:
1. If it's a binary, you can find instructions on the [Binary installation page](https://docs.gitea.io/en-us/install-from-binary/#updating-to-a-new-version)  
2. If it's with docker, we have some instructions on the [Docker installation page](https://docs.gitea.io/en-us/install-with-docker/#upgrading)
3. If you are looking to update from Gogs to Gitea, we have a [page for that](https://docs.gitea.io/en-us/upgrade-from-gogs/) as well as some extra information in the [FAQ](https://docs.gitea.io/en-us/faq/#how-to-migrate-from-gogs-github-etc-to-gitea)

**Comment by zeripath** [comment]
So I think this is caused by our lack of _index.md files in the docs system.  We should probably just put some basic information in these.

**Comment by wxiaoguang** [comment]
Can simply redirect to https://docs.gitea.io/en-us/upgrade-from-gitea/ from `/upgrade/`
