### ISSUE TITLE
Dark theme [$100]

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#730]
I have a proposal to add a dark theme.
Especially work at night - the default theme burns the eyes;)

**Comment by lunny** [comment]
This is related to #56

**Comment by KangoV** [comment]
As most devs work at night when the kids have gone to bed (own up... you do), this would be a welcome feature. Coffee alone is not enough :)

**Comment by lcges** [comment]
I would propose to do this in 1.3.0
It perfectly fits in with the new logo.

**Comment by lunny** [comment]
@qdbdbp any update?

**Comment by lcges** [comment]
I present the second version.
It is proposal by the well-known theme ARC.
Added green color - related to the logo and the entire visual concept of the Gitea.

p.s. Warning. This is the concept. Not ready products!!
Will prepare the final versions after the arrangements.

![2017-08-31t08 05 56 02 00-1131x619](https://user-images.githubusercontent.com/19255071/29909070-84b0e706-8e24-11e7-8aae-868e4590bf21.png)
![2017-08-31t08 09 04 02 00-1194x582](https://user-images.githubusercontent.com/19255071/29909067-84a8e7c2-8e24-11e7-803e-37cae52fb842.png)
![2017-08-31t08 09 29 02 00-1159x609](https://user-images.githubusercontent.com/19255071/29909068-84aa3c8a-8e24-11e7-9e16-b026e3f959f6.png)
![2017-08-31t08 09 49 02 00-1157x594](https://user-images.githubusercontent.com/19255071/29909066-84a73f80-8e24-11e7-8adf-be28c9624287.png)
![2017-08-31t08 10 14 02 00-1325x660](https://user-images.githubusercontent.com/19255071/29909069-84ab677c-8e24-11e7-81a5-e73949ee0728.png)

**Comment by lcges** [comment]
During the design I came up with one more idea of what style to choose.
I will soon propose to you.

Now I'm inviting to discuss

**Comment by anton-dutov** [comment]
Second is better, but IMHO
1. backgrounds should be more to neutral "gray" rather than "blue"
2. Main text color should be brighter, to keep contrast reading, but avoid #FFFFFF (and near as possible =)
3. May be links be more green, like logo

Sublime's default background and text colors pretty good

**Comment by choucavalier** [comment]
Thank you for your work @qdbdbp :) What is the current status on this?

**Comment by lcges** [comment]
The status looks like this:
* I was waiting for the version that will pick the community.
* I have found a few minor stylistic errors - it will adapt to the version 1.2 Gitea

**Comment by ghost** [comment]
I definitely like the second one better :D

**Comment by LinuxRockz** [comment]
I prefer the first one.

**Comment by voidptr127** [comment]
Hi all,
this is basically the first thought I had when I was testing Gitea after first installation. ("Is there a dark theme available? This one burns my eyes. How do I work at my main-hours -- at night")

Since the proposals are from end of August and the last comments are from about a month ago, I wanted to kindly ask you @qdbdbp if there is anything new regarding this issue? Any status updates you can provide?

**Comment by techknowlogick** [comment]
I'm currently running using the second one, and I love it!

Rather than using the user styles I've just injected the styles into my CSS file for my gitea instance. Only the first option's userstyle was posted above, so here is a link to the second version: https://userstyles.org/styles/147413/gitea-io-dark-arc-green

**Comment by techknowlogick** [comment]
One addition to option 2, and it even works with the most recent release of gitea, just add the following to the css file/usersstyles file:
```
.repository .ui.segment.sub-menu .list .item a {
	color:#dbdbdb;
}
```

**Comment by ghost** [comment]
the second option looks great 😄 🎈

**Comment by jonasfranz** [comment]
@techknowlogick @qdbdbp It would be nice to have a "WIP" pr so that the users / reviewers could submit change requests and feedback. This would also make it more easier to test the design.

**Comment by choucavalier** [comment]
@techknowlogick, thank you for providing this temporary solution. That's very generous of you! 
@qdbdbp, thank you for your work!

**Comment by davydov-vyacheslav** [comment]
will there be a chance to switch between dark and light themes?

**Comment by lafriks** [comment]
@davydov-vyacheslav currently there is no such option, that should probably be made as new feature request

**Comment by daviian** [comment]
@davydov-vyacheslav @lafriks There is already an open issue for that: https://github.com/go-gitea/gitea/issues/56

**Comment by lafriks** [comment]
Than I think this can be closed

**Comment by lafriks** [comment]
Probably @techknowlogick we could move that dark theme repository to `go-gitea` organization

**Comment by techknowlogick** [comment]
@lafriks sounds good. let me give you admin permissions over it to move the repo.

**Comment by lafriks** [comment]
Ok, so now it is under https://github.com/go-gitea/gitea-darkmode

**Comment by lunny** [comment]
Thanks @qdbdbp. I think you could apply the bounty from  https://www.bountysource.com
