### ISSUE TITLE
Branch/v1.9 displayed version 1.10.0+dev-5-ga360daeff

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7398]
As title.

**Comment by zeripath** [comment]
The trouble is that the tag 1.10.0-dev was applied to the common root instead of the first differing commit. Could ameliorate by adding a 1.9-rc-dev tag to the first commit on the release/1.9 branch?

**Comment by techknowlogick** [comment]
Yes, as @zeripath has said the tag is applied to the common root. Instead of tagging first commit of release/1.9 banch as in theory the RC starts with the changelog, I propose the `-dev` tag is applied to the commit after the changelog commit on the master branch.

This will be resolved when RC2 is released as that would thenbe the most recent tag on the branch

**Comment by lunny** [comment]
In fact, I don't like adding there tags(only for a version mark). I would like we change the `Version` in code after release branch created.

**Comment by techknowlogick** [comment]
I prefer to have makefile handle this because it can then generate a version such as `1.10.0+dev-5-ga360daeff` if we have it in code then it would not have the commit information `1.10.0-dev` and we would have to add workarounds to know which commit has been used.

**Comment by zeripath** [comment]
I think we can close this now?
