### ISSUE TITLE
Error upgrading from 1.4.3: You can't specify target table 'repo_topic' for update in FROM clause

### ISSUE THREAD

**Issue by foamrider** [go-gitea/gitea#7401]
- Gitea version (or commit ref): 1.4.3
- Git version: 2.15.2
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Hi

I'm having trouble upgrading from 1.4.3 to any version above. I get the following error in `gitea.log` when I change the gitea-tag to anything newer than 1.4.3:
```
2019/07/09 11:11:29 [I] Log Mode: File(Info)
2019/07/09 11:11:29 [I] XORM Log Mode: File(Info)
2019/07/09 11:11:29 [I] Cache Service Enabled
2019/07/09 11:11:29 [I] Session Service Enabled
2019/07/09 11:11:29 [I] Mail Service Enabled
2019/07/09 11:11:29 [I] Migration: Reformat and remove incorrect topics
2019/07/09 11:11:29 [I] This migration could take up to minutes, please be patient.
2019/07/09 11:11:29 [I] Validating existed topics...
2019/07/09 11:11:29 [I] Incorrect topic: id = 1, name = "Contributing"
2019/07/09 11:11:29 [I] Touched repo ids: []
2019/07/09 11:11:29 [I] Exists topic with the name "contributing"? true, id = 1
2019/07/09 11:11:29 [I] Updating repo_topic rows with topic_id = 1 to topic_id = 1
2019/07/09 11:11:29 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Error 1093: You can't specify target table 'repo_topic' for update in FROM clause
```

My `docker-compose.yaml`:
```
version: '2'
networks:
  gitea:
    external: false
services:
  server:
    image: 'gitea/gitea:1.4.3'
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD={{hidden}}
    restart: always
    networks:
      - gitea
    volumes:
      - './gitea:/data'
    ports:
      - '3000:3000'
      - '222:22'
    depends_on:
      - db
  db:
    image: 'mysql:5.7'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{hidden}}
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD={{hidden}}
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - './mysql:/var/lib/mysql'
```

How can I fix this error, or what am I doing wrong? Thank you for your time and help.

**Comment by lafriks** [comment]
Upgrade to latest 1.5 first

**Comment by drtomasso** [comment]
I have tried to upgrade to 1.5.0, 1.5.1, 1.5.2 and 1.5.3. All of these throws the same error

**Comment by lunny** [comment]
This maybe a bug

**Comment by drtomasso** [comment]
Still an issue

**Comment by guillep2k** [comment]
The problem seems to arise here:

https://github.com/guillep2k/gitea/blob/cfe6941905de745aed1f9297d9717249f53e6e67/models/migrations/v68.go#L96-L102

I don't know if the version of MySQL is too old to SELECT ... FOR UPDATE on the same table, but perhaps there's a way to circumvent this problem.

The way I understand that piece of code (I might be wrong) is that it attempts to normalize topics to certain parameters: only lower case aphanumeric characters, no longer than 35 characters, `-` accepted after the first character.

There is a topic `Contributing` that the migration is trying to convert to `contributing`, but first it checks if `contributing` already exists (they could both exist, `Contributing` and `contributing`). If your database happens to only have `Contributing`, you could attempt to correct the name of the topic yourself, so the migration won't have to attempt the SELECT ... FOR UPDATE:
```
-- First check that only one row shows up here!
select id, name from repo_topic where lower(name) = 'contributing';
-- then do:
update repo_topic set name = 'contributing' where name = 'Contributing';
```

**Comment by guillep2k** [comment]
Now that I think of it, if the version of MySQL happens to be very old (in relative terms), perhaps it's worth upgrading it first. Because if the problem _is_ the MySQL version and you correct the repo_topic problem and pass migration, perhaps other parts of the code will fail after that.

I'm no MySQL expert, so I couldn't recommend one, but for reference, I'm using:
```
$ mysql --version
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by drtomasso** [comment]
Thank you for your reply, @guillep2k. I'm running with docker, so the MySQL version is the one mentioned in the documentation, `image: mysql:5.7`

There might be some missing columns here, I don't have those columns in `repo_topic`. Here is my `repo_topic`:
```
mysql> DESCRIBE repo_topic;
+----------+------------+------+-----+---------+-------+
| Field    | Type       | Null | Key | Default | Extra |
+----------+------------+------+-----+---------+-------+
| repo_id  | bigint(20) | YES  | MUL | NULL    |       |
| topic_id | bigint(20) | YES  |     | NULL    |       |
+----------+------------+------+-----+---------+-------+
2 rows in set (0.00 sec)
```

**Comment by drtomasso** [comment]
Found the entry you mentioned in table `topic`.

Ran:
```
update topic set name = 'contributing' where name = 'Contributing';
```

This solved the issue, thank you!
