### ISSUE TITLE
issue tags eg "#1" vs "someprefix#1"

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#7438]
- Can you reproduce the bug at https://try.gitea.io:
 https://try.gitea.io/company/commit-tags-problem/issues/2

## Description
in this issue2 should not be marked within the commit which belongs to issue1
I think for a work around could be writing `KB\#2` but feels uncomfortable and dont work. How to?

Kind regards

**Comment by Cherrg** [comment]
(Note: This does happen here on github too
e.g.: https://github.com/go-gitea/gitea/issues/6371 references to #(1-10))

**Comment by Cherrg** [comment]
may it is possible to prevent commit linking if there is no space before it (exclude line starts)

**Comment by mrsdizzie** [comment]
Hmm yea it shouldn't be doing that, will look and send a fix

**Comment by flobee** [comment]
Is there an update script to update records from the past :-1: :+1: ? It seems the content get static after a push was made :~/

**Comment by mrsdizzie** [comment]
@flobee Unfortunately not as it wouldn't necessarily know what was added there for what reason.

You could manually remove them from the DB and you can find those type of mention comments like this:

```
SELECT * from comment WHERE type = 4;
```

Or you could search for the specific string in the example in this issue:
```
SELECT * from comment WHERE type = 4 AND content LIKE '%KB#%';
```

type 4 is a commit reference which is where this bug was

**Comment by flobee** [comment]
thx!
