### ISSUE TITLE
Updated drone file doesn't build docker images for tags

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#7476]
please see https://drone.gitea.io/go-gitea/gitea/10774/4/1

**Comment by sapk** [comment]
I don't fully understand the problem. Is it related to https://drone.gitea.io/go-gitea/gitea/10772/1/11 that failed to find the last commit time on tag ?

**Comment by sapk** [comment]
From what I have found :
 - ./git/refs/heads/master is not populated by the clone method used on tag.
 - https://github.com/go-gitea/gitea/blob/edc94c70413048107ea728ff330f32ca3de6df88/modules/git/repo_test.go#L15 Failed
 - because https://github.com/go-gitea/gitea/blob/edc94c70413048107ea728ff330f32ca3de6df88/modules/git/repo.go#L326 can not found the file /refs/heads/master

I found two solutions:
 - checkout master before returning to tag (generate /refs/heads/master) 
 - don't define /refs/heads path (but that could change how gitea calculate on repo) git for-each-ref --sort=-committerdate --count 1 --format='%(committerdate)'

**Comment by techknowlogick** [comment]
@sapk specifically this build step https://github.com/go-gitea/gitea/blob/master/.drone.yml#L633 is what should be building images for tags and is not. The conditional in old drone format didn't specify branch. Perhaps, this should be changed to use refs conditionals instead

**Comment by sapk** [comment]
Found better by forcing refresh of master fetch by using `git fetch origin master:refs/heads/master`

**Comment by techknowlogick** [comment]
@sapk that failing test you linked has been backported and solved, this issue is about image not building (which is in a different pipeline)

**Comment by sapk** [comment]
Isn't https://github.com/go-gitea/gitea/blob/master/.drone.yml#L615 just missing tag ?

**Comment by sapk** [comment]
We also lost the tag 1 that is not updated anymore.

**Comment by sapk** [comment]
We should maybe pass similar to https://github.com/drone-plugins/drone-docker/blob/ebce953fc443371d79b5a019fcc9c1976f60a09a/.drone.yml#L99
