### ISSUE TITLE
Filtering on assignee and labels in organization issue overview.

### ISSUE THREAD

**Issue by rikvdh** [go-gitea/gitea#791]
- Gitea version (or commit ref): master
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It is now not possible from the `/org/<name>/issues` overview to filter issues by label, milestone or assignee. Filtering on assigned to me is greatly appreciated.

**Comment by nferrari** [comment]
I agree. 

While observing the bug #3819, I noticed the global Issues page is pretty different than the Issues tab of a specific repository. I couldn't say why but this makes the Issues page not really usable for an organization: for us, filtering by assignee and labels is also a must-have feature.

**Comment by nferrari** [comment]
I keep this issue open by making a new comment: multiple labels filtering is still a must-have feature in order to make Gitea useful for our organization. This is actually possible on a single repository but not on the global issues page.

I think those 2 issues page (global one and specific repository tab) should be the same: they should offer the same ordering/filtering options.

**Comment by PaulBol** [comment]
I agree with @nferrari that an organization-wide view with filtering options would be really helpful. Would be awesome if it had the same filters like the repository issue view.

**Comment by wxiaoguang** [comment]
I think it will be supported by this ?  Add label/author/assignee filters to the user/org home issue list #32779
