### ISSUE TITLE
Readme.md do not display relative path image

### ISSUE THREAD

**Issue by jueti** [go-gitea/gitea#7995]
- Gitea version (or commit ref): 1.10.0+dev-201-gca6fb004a
- Git version: git version 2.23.0.windows.1
- Operating system: Windows 10 Pro Workstation 1903
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) [README.md](https://try.gitea.io/jueti/learn-regex/src/branch/master/README.md)
- Log gist:

## Description

make a migration from a [github repo](https://github.com/ziishaned/learn-regex) as a mirror, and found a image missing error.

## Screenshots

![image](https://user-images.githubusercontent.com/24526369/63742621-f53f6680-c8cb-11e9-9352-c0d5421270f0.png)

![image](https://user-images.githubusercontent.com/24526369/63742557-c2956e00-c8cb-11e9-99da-bc9e9530e6ea.png)

**Comment by jueti** [comment]
Can you reproduce the bug at https://try.gitea.io:
  Yes (provide example URL) [README.md](https://try.gitea.io/jueti/awesome-python/src/branch/master/README.md)
![image](https://user-images.githubusercontent.com/24526369/63924795-7d17a300-ca7b-11e9-9b40-f6e123248bd5.png)
![image](https://user-images.githubusercontent.com/24526369/63924870-a33d4300-ca7b-11e9-83b4-18ff8e566ae9.png)

**Comment by gary-kim** [comment]
The Awesome Python image seems to be loading fine on my system. Could you check your browser console?

**Comment by jolheiser** [comment]
It's because you are using raw HTML and not markdown.  
This may still be considered a bug because GitHub must do some checking for it, however this is non-existing functionality in Gitea that I know of.

For example, here is my fork of your repo where I put the image in markdown instead of raw HTML.
https://try.gitea.io/jolheiser/learn-regex/src/branch/master/README.md
