### ISSUE TITLE
Display multiple commit statuses

### ISSUE THREAD

**Issue by trinity-1686a** [go-gitea/gitea#8054]
- Gitea version (or commit ref): 1.10.0+dev-232-gf1c414882 
- Operating system: linux (docker)
- Database (use `[x]`):
  - [x] PostgreSQL (other untested)
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/fdb-hiroshima/test)
  - [ ] No
  - [ ] Not relevant

## Description
On the web interface, Gitea try to show the most relevant status for a given commit, prioritizing failed check over successful ones. But it only shows one check, there is no easy way to see other status in case of multiple failure. Having some menu showing on hover/click as Github is doing would be nice to see more about statuses.

## Screenshot
how Github handle multiple statuses :
<img width="946" alt="how Github shows multiple statuses" src="https://user-images.githubusercontent.com/35889323/64107032-d16f9b00-cd79-11e9-96e9-7dc82419a618.png">

**Comment by PenguinOwl** [comment]
Hate to necro, but this would be nice.
In addition to this, IMO the commit statuses in the commit list should be displayed to the right of the sha instead of at the end of the commit message. Putting it after the text causes variable placement and makes it hard to get a good idea of the build success trend.

**Comment by Ibmurai** [comment]
This is even more needed now that we can attach different kinds of statuses to the commits.
As an example I am linking to the build artifacts using a status. This works fine when there's a PR involved since that will show all the different commit statuses. But if there is no PR the link is never shown :(

**Comment by cal101** [comment]
+1
 I came here by searching for a way to link build artifacts.

**Comment by jpraet** [comment]
I think this is fixed by #13977?
