### ISSUE TITLE
Team Names too stingy

### ISSUE THREAD

**Issue by worthy7** [go-gitea/gitea#8077]
![image](https://user-images.githubusercontent.com/4762399/64226929-54305b80-cf1c-11e9-8ac2-5cc9c563fd21.png)

Support in Japanese is サポート, this character isn't actually the regular - but it still gets blocked.
Gitea Version: 1.8.2

**Comment by guillep2k** [comment]
Here the problem is not the chōonpu character (ー), but the fact that you're trying to use katakana.

This is more difficult a problem than it may seem.

Currently, team names follow the same or similar rules as for organizations or repositories, which restricts to use only ASCII characters: letters, numbers, `_`, `-` and in some cases, `.` too. However, teams are not bound to file-system resources, so accepting other scripts (like katakana or hiragana) should be safe in some cases as long that those scripts don't include symbols that can cause confusion for being too similar. I know a few scripts that should be safe to support:

* Katakana (Japanese)
* Hiragana (Japanese)
* Hangul (Korean - `U+115F` and `U+1160` might cause problems, though)
* Cyrilic (Russian, etc.)
* Greek

But not all scripts are safe or should be supported. For instance, the unicode CJK (unified Chinese, Japanese, Korean) contains lots of characters that can easily be confused with others, like full and half-width versions, different types of dot (e.g. º), different letter-like symbols, etc. The same goes with the Latin scripts variants like "áàäâã", etc.

These validations are currently taken from Macaron:
https://github.com/go-gitea/gitea/blob/4cb1bdddc88580d20305415869d4c13827097bd9/vendor/gitea.com/macaron/binding/binding.go#L268-L272

And used here:
https://github.com/go-gitea/gitea/blob/4cb1bdddc88580d20305415869d4c13827097bd9/modules/structs/org_team.go#L20-L40

However, if we decide to support any of this, either we restrict the extended support to a reduced set of "easy" scripts, or we need a profound analysis of the impact of such modification.

**Comment by Worthy7** [comment]
If it's complicated then it's probably not worth s big change, instead just
charge the error message to tell the truth :-)

**Comment by guillep2k** [comment]
@Worthy7 But the error message is correct: alphanumeric characters.

**Comment by Worthy7** [comment]
So it does lol. Ok, I guess we'll just use English then. For more difficult words (like operations, stake-holders) I think this is a bit "annoying" basically for non-natives.
