### ISSUE TITLE
Delete Avatar Problem

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#8176]
There is a problem something like this, reproduce:

1. Create 2 organizations
2. Set their avatars as **same** image
3. Delete one organization

Then you will see other organization's avatar reset to default gitea avatar, becouse image removed from disk.

This is same:

- Organization avatar
- User avatar
- Repository avatar

My opinions for solution:

1. Check if there are other same avatar name before remote from disk
2. Check if there are other same avatar name before set avatar and give new name if there

**Comment by guillep2k** [comment]
The filename is a hash of the avatar contents. For this, I think we should add the owner as part of the hash and force the names to be different. Otherwise, we'll have to keep a reference count for every file.

**Comment by jaqra** [comment]
IMHO First one does not affect? If a user add same image to multiple organization then remove one

**Comment by guillep2k** [comment]
If your NASA organization adds `planet.png` as avatar, the file is uploaded as:
```
data/attachments/e/4/e4dc1049-68cd-4ed0-9636-41c0a04b0a69
```
The name is calculated by hashing its content. If ESA adds the _same_ picture of a planet (no matter the file name, only the byte-by-byte content of the file), then it will be named again:
```
data/attachments/e/4/e4dc1049-68cd-4ed0-9636-41c0a04b0a69
```
That's why if ESA deletes its file, NASA's file gets deleted too. However, if we apply other metadata to the hash input, the hash will be different each case, for example:
```
NASA's planet.png       fe5156a4-6562-49a6-8732-1dbb48639560
ESA's planet.png        b519f855-1e11-4893-b64e-95ca221758cd
```
Even if they are the same file.

That should solve the problem, because if ESA deletes or changes its avatar, only `b519f855-1e11-4893-b64e-95ca221758cd` will be deleted, while `fe5156a4-6562-49a6-8732-1dbb48639560` will remain untouched.
