### ISSUE TITLE
unable to reset administrator password - No help topic for 'change-password'

### ISSUE THREAD

**Issue by changchichung** [go-gitea/gitea#8363]
- Gitea version (or commit ref): 1.1.4
- Git version: 2.7.4
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [X] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Not relevant

## Description

try to reset admin password using
```
gitea admin change-password --username admin --password mypassword
```
but return 
```
No help topic for 'change-password'
```
and still not be able to login with new password .

any suggestions ? thanks !

**Comment by guillep2k** [comment]
> Gitea version (or commit ref): 1.1.4

This can't be your Gitea version, or is it? 

The syntax is correct, but I suggest you enclose your password in quotes in case some special character is getting in the way. Also, you probably need to specify the ini file location:
```
gitea admin --config "/abs/path/to/app.ini" change-password --username admin --password "mypassword"
```

Make sure the path to `app.ini` is correct; otherwise Gitea will attempt to create one and the error messages will get really confusing.

**Comment by guillep2k** [comment]
@changchichung These issues are intended for reporting bugs in Gitea. If you keep having problems changing your user password, please ask for support in our [Discord channel](https://discord.gg/NsatcWJ).
