### ISSUE TITLE
git on Gitea ignores the repo's .gitattributes and uses its own

### ISSUE THREAD

**Issue by HarvsG** [go-gitea/gitea#8394]
- Gitea version (or commit ref): 1.9
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Not really sure if this is a bug or a feature. But if a repo has a .gitattributes file the git user running on gitea will ignore it when running functions such as `git diff`.

E.g lets say on the Gitea instance we have:
`git config --global --edit`

To the end of the file we add:
```
[diff "pandoc"]
     textconv=pandoc --to=markdown
     prompt = false
[alias]
     wdiff = diff --word-diff=color --unified=1
```
And the repo contains a .gitattributes with contents
`*.docx diff=pandoc`
Ensuring pandoc is installed we get:
![Screenshot 2019-10-06 at 18 25 39](https://user-images.githubusercontent.com/11440490/66272869-b9060b00-e866-11e9-8161-50dd4ae4f237.png)

However if we set the .gitattributes globally on the Gitea instance we can run `git config --global core.attributesfile <path to some global .gitattributes file>` and point it at a file containing `*.docx diff=pandoc`
We get the desired result
![Screenshot 2019-10-06 at 18 23 11](https://user-images.githubusercontent.com/11440490/66272908-1a2dde80-e867-11e9-8a2f-8abea87fcf56.png)

.gitattributes is used for customising more than just how diffs are rendered. So I imagine this bug could have further implications.

**Comment by guillep2k** [comment]
`git config` has only local scope (your computer), either if you use `--global` or not. When you push to a remote (whether it  runs on Gitea or not), configuration is not transferred. The `--global` flag means "for all projects in this computer", not "for all copies of this repository".

**Comment by HarvsG** [comment]
@guillep2k I am aware of this I will clarify my post to make this clearer

**Comment by zeripath** [comment]
.gitattributes is only interrogated by non bare repositories. 

We use (temporary) bare repositories for almost all of our work - merge is the only place left that does (partial) checkouts but thank you because I now need to check I can't get a merge containing an appropriately malicious .gitattributes to do anything horrible.

In bare repositories if want adjust these options you have to use the config file directly (.git/config) - however I suspect that our extensive use of temporary bare repositories might even prevent that being useful. 

If you can come up with a cogent argument why these shouldn't be global I'll have a think how we can copy config around from the repositories to the temporary bare clones - it could just be copy the file. 

However if you're suggesting that we should allow .gitattributes in the root of the check out from a repository to change configuration like this - that's an absolute no. That would allow arbitrary code execution - that diff command can be absolutely anything.
