### ISSUE TITLE
Merging pull requests results in HTTP 500

### ISSUE THREAD

**Issue by bertptrs** [go-gitea/gitea#8443]
- Gitea version (or commit ref): 1.9.4, also happened in previous versions
- Git version: 2.17.1
- Operating system: Ubuntu 18.04 Bionic Beaver
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
2019/10/09 19:34:40 routers/repo/pull.go:629:MergePullRequest() [E] Merge: git config [filter.lfs.process -> <> ]: From /home/gitea/gitea-repositories/ictgilde/denim
	 * [new branch]        Apache-LKP-config -> head_repo/Apache-LKP-config
 branch]        Apache-LKP-config -> head_repo/Apache-LKP-config
```

## Description

Whenever we attempt to merge a pull request, the its fails with a HTTP 500 error and the error in the logs shown above. The error seems to indicate a problem with LFS which we don't use. I have installed `git-lfs` 2.3.4 from the Ubuntu repository.

Merging locally and then pushing does work, and also properly closes the pull request.

The error message [points to this line of code](https://github.com/go-gitea/gitea/blob/v1.9.4/routers/repo/pull.go#L629) but I'm not familiar enough with Go to see what is happening here.

...

**Comment by wgevaert** [comment]
Issue seems to be caused by [this line of code](https://github.com/go-gitea/gitea/commit/baefea311f#diff-3118802184bbc1301bbf65e551886506R128)
That line of code seems to be explicitly setting LFS-config values. However, these values are already set by default in `module/setting/setting.go` in the function `CheckLFSVersion`. Therefore, I think the lfs-settings in the merge-code should be removed, that should solve this issue

**Comment by guillep2k** [comment]
Can you send a Pull Request changing that?

**Comment by zeripath** [comment]
@wgevaert you're right it's that line which is producing that . IIRC I think they're necessary because of weirdness with LFS and I had to add them.

@bertptrs What version of git are you running on the server? Check the logs - make sure that the version is what you say it is.  `git config --local` is only available from git 1.8.0.

There's probably something else happening here.

**Comment by bertptrs** [comment]
@zeripath git version is as checked on the server. It is the default version shipped with Ubuntu 18.04.

**Comment by zeripath** [comment]
Is there anything else in that log?

**Comment by bertptrs** [comment]
It is the only `[E]` level log, there are various other informational level logs regarding the ORM, none which stick out as problematic or specific to the problem. Are there any switches I could turn on to get a better picture?

**Comment by zeripath** [comment]
Hmm... The trouble is going to be trying to figure out why git config is emitting information. It's weird because AFAIU - although I haven't been able to definitely crawl through git's config.c - `git config --local KEY VALUE` should not emit anything unless there is an error

**Comment by zeripath** [comment]
The message is a bit like a fetch message too. So weird.

**Comment by bertptrs** [comment]
@zeripath Your message got me thinking and it turns out that we have a wrapper for git which prevents us from running it as root. Unfortunately, it also did some unwanted word-splitting in the arguments. When I fixed that the issue disappeared. Thank you for your help.

**Comment by zeripath** [comment]
Hah Wonderful. Knew there was something weird going on!

I was about to suggest running gitea with GIT_TRACE=/some/file/name and seeing whether that helped.
