### ISSUE TITLE
Contributors graph

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#847]
Implement contributor graphs: https://github.com/go-gitea/gitea/graphs/contributors

![screenshot_20170205_131515](https://cloud.githubusercontent.com/assets/6344099/22626066/2eaf097c-eba5-11e6-9ec9-fbdc410785f2.png)

**Comment by bkcsoft** [comment]
Is there a good graph-lib? In my opinion this can be rendered and cached server-side

**Comment by akuzia** [comment]
Any progress?

**Comment by ghost** [comment]
would be nice to have 🎉

**Comment by linusg** [comment]
+1

**Comment by linusg** [comment]
I would like to start working on this feature, if no one is already on it (yeah @lafriks, I learned my lesson, `+1` is not constructive 😉).

I would probably need some assistance every now and then, e.g. on how to decide about server or client side rendering, what charting library to use etc.
I also basically don't know any Go but have good frontend knowledge so it should work, and everything has a first time, also I wanted to dive into hacking on Gitea some while ago 😄

**Comment by linusg** [comment]
*If it works with your general workflow here, I'd be fine with being assigned to this issue.*

---
Some more thoughts on this. Constructive feedback is of course highly appreciated!

**Placing the page link on the UI**

![image](https://user-images.githubusercontent.com/19366641/46828509-a7953a80-cd9b-11e8-9daa-5976d501a9af.png)

That should work fine, no need to restructure anything for now.

Speaking of links, the page should probably live at `https://git.example.com/<owner>/<repo>/contributors`, that's how all the other links up there work.

Another idea, *which I do not prefer*, is putting the contributor graph(s) on the Activity page.

I did some DOM editing:

![image](https://user-images.githubusercontent.com/19366641/46829568-694d4a80-cd9e-11e8-9839-03283d1d3104.png)

I chose [`octicon-organization`](https://octicons.github.com/icon/organization/) as the icon, [`octicon-graph`](https://octicons.github.com/icon/graph/) might work as well.

Now some quick CSS editing on the GitHub contributors chart for Gitea and merging the images:

![image](https://user-images.githubusercontent.com/19366641/46829756-eed0fa80-cd9e-11e8-90cb-ca2f0a0c7991.png)

That's a very rough idea of how it may look like, not taking individual per-user charts into account.

**Comment by ShalokShalom** [comment]
Looks wonderful ^-^

**Comment by lunny** [comment]
@linusg great! Go ahead!

**Comment by Morlinest** [comment]
It is probably a mistake or maybe he has some secret plans with me :D

**Comment by linusg** [comment]
Sooo... here we go! Now it's the time for some external input, so please see below the images.

![image](https://user-images.githubusercontent.com/19366641/50843458-02253f00-1369-11e9-8cff-c6955f656670.png)

(gitea repo taken from GitHub)

![image](https://user-images.githubusercontent.com/19366641/50843530-284adf00-1369-11e9-9e83-ddf57ae77f84.png)

Let me explain:

- Users who are not in the gitea users DB will be shown, but with no link to the profile, obv. Stats are calculated by Username (available is only "name" and "email" per each commit), that's why there's "Unknown", "Unknwon" and "无闻" vs only "Unknwon" in GitHub: The information, that this is all the same user is lost when cloning/importing the repo. **I guess that's the best option available, thoughts?**

- GitHub compiles stats per week, I went with daily stats. **Should this be changed?** 

  That's the reason why the Y-Axis on GitHub ends at ~150 [commits per week] and the Gitea one at 52 [commits per day]. Also it makes the chart on Gitea appear with more "spikes". (interpolation isn't available as well)

- GitHub excludes merge commits from the stats, I didn't implement anything of this kind (and don't know how hard distinguishing one from a normal commit would be). **Do we want this feature?**

- **Do you wish a separate color for the per-user charts?**

- **What else do you think can be improved?**

**Performance:**

I fixed all of the issues noted in my last post, and I'm back to some performance issues. All stats from my dev machine:

The contributors page of the Gitea blog repo takes 1.1s to load, which is probably fine (_Page: 1090ms Template: 7ms_)

The one for the gitea main repo took 1min 14s and reports _Page: 74443ms Template: 47ms_. It has nine years of history and almost 7k commits, though.

Possible improvements: the gitea repo contributor page ends up with 602 user cards, I believe GitHub cuts off at 100. See https://github.com/go-gitea/gitea/graphs/contributors.

**What do you think about that? As the charts become less useful with very few changes/commits because of the fixed Y-Axis, should we either only show top X contributors or maybe don't generate charts for more than e.g. 100 contributors?**

![image](https://user-images.githubusercontent.com/19366641/50844586-503b4200-136b-11e9-8dfa-6131bf5ab54b.png)

Since the whole commit history will be traversed each time the page is visited, we can probably as well improve the situation by caching the stats. No clue if that makes sense and how implementation would look like.

I had to [clear the ServiceWorker's cache](https://stackoverflow.com/a/41675764/5952681) for the changed CSS files to show up (normal cache refresh wouldn't work). What do I have to do here so it works OOTB?

<details><summary>More screenshots, click to expand</summary>
<p>

![image](https://user-images.githubusercontent.com/19366641/50845620-95f90a00-136d-11e9-94a1-dfcdbdcf8908.png)

![image](https://user-images.githubusercontent.com/19366641/50845863-28011280-136e-11e9-8a93-a194dde3115c.png)

![image](https://user-images.githubusercontent.com/19366641/50846330-2be16480-136f-11e9-8aad-e814157d045f.png)

![image](https://user-images.githubusercontent.com/19366641/50846507-9b575400-136f-11e9-9a6f-97f7a9ec28a1.png)


</p>
</details>

**Comment by lunny** [comment]
@linusg Great job!!! How about to let the work as a cronjob when the repository is big(i.e. over 1000 commits)? It can be run one or more days according the configuration. I think top 100 is enough, otherwise pagination is better.

**Comment by ghost** [comment]
@linusg 
> * Stats are for the master branch (hardcoded), this can be easily changed and exposed as an UI control

Maybe you can use the default branch option instead of creating another option.

**Comment by linusg** [comment]
Nope, still working on this - someone might remove the `stale` label!

**Comment by Bryanpedini** [comment]
> 
> 
> Nope, still working on this - someone might remove the `stale` label!

That's good news, hoping to see this feature coming soon!
Hyped to see charts and graphic data representation everywhere...

**Comment by linusg** [comment]
> That's good news, hoping to see this feature coming soon!

Soon :tm:

Time is definitely a problem for me... next to my basically non-existent knowledge of golang, haha.

I'm happy to see all the excitement (I'm excited too, wouldn't work on this otherwise!), but if you folks feel like this is not making progress fast enough (damn, it's been over half a year), I can make a PR with all the changes and someone else can help out?

**Comment by Bryanpedini** [comment]
> Soon ™️

😅 

> but if you folks feel like this is not making progress fast enough

Naaah.. whoever cares of the time you take for a feature, if it is a very good and working feature?

>    I can make a PR with all the changes and someone else can help out?

IDK, maybe you can post your repo publicly here on GH so other people can PR your repo and get it working so than you can PR the official one and get that integrated
OR you can open a PR for a new branch on the official repo from which skilled and time willing people can fork and work and PR that instead, waiting for the branch to get merged into master of course...

**Comment by lunny** [comment]
@linusg Please send a PR that maybe someone could help you when you are absent.

**Comment by a1012112796** [comment]
looking forward to this feature. Is it stale now ? .....Thanks

**Comment by mrenvoize** [comment]
Any further news here?

**Comment by mrenvoize** [comment]
Did a PR or branch ever get submitted here?

**Comment by lunny** [comment]
I think not. @linusg

**Comment by linusg** [comment]
I don't think I ever pushed my changes. Not even sure if I still have them - sorry!

**Comment by IzzySoft** [comment]
So 4 years later: how do chances stand? @linusg did you find your changes? That looked already so promising!

**Comment by cvoges12** [comment]
Any updates on this?

**Comment by new-mikha** [comment]
Plus 1 to the question "any updates on this?"
Would be such a useful feature, please bring it on!

**Comment by sahinakkaya** [comment]
I decided to use [Chart.js](https://github.com/chartjs/Chart.js) to draw the charts. Right now [gitea](https://github.com/go-gitea/gitea) repository looks like this:

<img width="629" alt="image" src="https://github.com/go-gitea/gitea/assets/32161460/cb571f25-b1ea-4c45-8130-3a0c85778784">

There are still some work to do but before continuing I wanted to ask the maintainers if the Chart.js dependency is OK or not. If it is not ok which library should I use?

Any other feedback is also greatly appreciated :)

**Comment by sahinakkaya** [comment]
@wxiaoguang @lunny @techknowlogick @silverwind

**Comment by lunny** [comment]
> @wxiaoguang @lunny @techknowlogick @silverwind

Since it's under MIT license, I think it's acceptable. Is that library the best choice to draw the graph? But of course PRs are always welcome.

**Comment by sahinakkaya** [comment]
@lunny These were my requirements:

- Draw an area chart
- Draw on the client side
- interpolate data to smooth out the edges
- support zoom, pan etc.

Of course none of these requirements are hard requirements but they are nice to have. Chart.js supports all of them (last one available via an extension) If anyone have a simpler alternative in mind, I can take a look at that too.

**Comment by sahinakkaya** [comment]
**Another update (Help needed):**

I copied the Activity page and replace the content with graphs. I think it looks OK except for the top section where it shows dates and period selection menu (they are left-overs from Activity page). 

<img width="1022" alt="image" src="https://github.com/go-gitea/gitea/assets/32161460/ac844448-2a8f-433c-8895-baebfeebb696">

I obviously need to replace that top right menu with contribution type selection (commits, additions, deletions) however, I don't have any idea about how to handle it in a single page. The Activity page's menu redirects you to other endpoints and makes relevant calls to get the data.

In my case, I already have the data and I just need to pass the selected option to my Vue component which draws the graphs. 

>  I have zero experience with go 

I also don't know any Vue either so... I think I need a little bit of help here.

Best way to help: Show me an example from this repository where dynamically selected option is passed to Vue. That's how I implemented all of this, by replicating, without knowing the details of these languages anyway :D

**Comment by lunny** [comment]
If we want to introduce a frontend chart library but not two for this requirement and future requirements, I think we have some options below:

- [ ] chartjs https://www.chartjs.org
- [ ] highcharts https://highcharts.com
- [ ] echarts https://echarts.apache.org
- [ ] d3js https://d3js.org
- [ ] plotyly https://plotly.com
- [ ] chartist-js https://github.com/gionkunz/chartist-js
- [ ] ApexChart https://github.com/apexcharts/apexcharts.js

**Comment by sahinakkaya** [comment]
In my previous message, the graphs are already drawn with Chart.js but this is also a nice list @lunny. I examined them a little bit and I might consider switching to ApexCharts because they have **exactly** what we need: [https://github.com/apexcharts/apexcharts.js#a-little-more-than-the-basic](https://github.com/apexcharts/apexcharts.js#a-little-more-than-the-basic)

<img width="963" alt="image" src="https://github.com/go-gitea/gitea/assets/32161460/eb2d64fc-2ee0-4cac-8ca5-49d111354c63">


I still need help with the issue I mentioned in my previous message though.

**Comment by silverwind** [comment]
Can't really comment on chart libraries but as long as you're lazy-loading them with `await import` only on pages that use them, it should be fine.

apexcharts does look pretty well-suited to the task yes.

**Comment by wxiaoguang** [comment]
> I still need help with the issue I mentioned in my [previous comment](https://github.com/go-gitea/gitea/issues/847#issuecomment-1597876585) though. (Maybe @wxiaoguang could help me)

I am glad to help (if it is in my knowledge), but at the moment, I haven't got the point, the questions (experience with Go/Vue) seems general.

**Comment by sahinakkaya** [comment]
> I suggest to keep the current information easily available, though. Like, make the contributors clickable easily...

@fnetX thanks for the suggestions. I created an endpoint which returns contributors' commits, additions and deletions for each week. I think this data can also be used to generate [code frequency](https://github.com/go-gitea/gitea/graphs/code-frequency) graph. I am not planning to implement it for this PR though as it is out of scope. 

>as long as you're lazy-loading them with await import only on pages that use them, it should be fine.

@silverwind, I don't do any `await import` stuff but I think there is no performance issue because I am doing same thing as what Activity page does. A pull request is coming soon anyway :)

And @wxiaoguang, is there a way to pass some property with pageData and not trigger a re-render of whole page? Fetching data is expensive so in Go file, I fetch all the data I need and pass it to Vue via pageData. When user change selection, I don't want to fetch data again.

<img width="287" alt="image" src="https://github.com/go-gitea/gitea/assets/32161460/01e88e5c-ac6a-47b4-b851-6b2b00d2c73e">

Here, I have all the data for commits, additions and deletions (1 expensive call). If "commits" option is selected I draw graphs with commits data. When user change selected option to something else I just need to change the data I am feeding to graphs. Hope this makes sense and clears up the confusion.

**Comment by wxiaoguang** [comment]
> And @wxiaoguang, is there a way to pass some property with pageData and not trigger a re-render of whole page? Fetching data is expensive so in Go file, I fetch all the data I need and pass it to Vue via pageData. When user change selection, I don't want to fetch data again.

If you want to get some new data without re-rendering, then I think the only way is "fetch"

**Comment by silverwind** [comment]
> @silverwind, I don't do any await import stuff but I think there is no performance issue because I am doing same thing as what Activity page does. A pull request is coming soon anyway :)

Definitely do it. If you don't code-split off the chart library with `await import`, our JS payload for all pages will grow by its size, e.g. 200kb+. There are numerous examples in the codebase for such code-splits.

**Comment by sahinakkaya** [comment]
I opened a pull request: #25439. It would be nice if I can get some review and help from folks following this thread.

@silverwind I just saw your comment. OK, I will look into that 👍

**Comment by sahinakkaya** [comment]
@silverwind I have tried to do await import but I couldn't make it work. Can you look at [this diff](https://github.com/sahinakkaya/gitea/commit/e39e6d008303317e69709cb82733877a34b163ec) and tell me what's wrong?
