### ISSUE TITLE
Show tag messages on releases page

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#8493]
Tag messages are currently not being displayed on the UI. Comparison to GH:

https://github.com/silverwind/symlink-test/releases
<img width="421" src="https://user-images.githubusercontent.com/115237/66719396-68a32600-edef-11e9-8113-ae3166e10896.png">

https://try.gitea.io/silverwind/symlink-test/releases
<img width="505" src="https://user-images.githubusercontent.com/115237/66719397-693bbc80-edef-11e9-8563-419f70995886.png">

**Comment by zeripath** [comment]
It appears that for annotated tags we don't store the SHA1 to the tag object but rather the commit SHA1. We don't store the commit message in the db either. 

So there are three issues:

1. For annotated tags we need to store the annotated tag SHA1 in future. Decide whether to store this in addition or instead of the commit. Probably in addition?
2. We need go back over our tags and store the annotated tag SHA1 - that's a migration task.
3. We need to decide which message to show: a) The commit message b) the annotated tag message or c) both.

We would need to use the same processing we use on commit messages elsewhere.  Including demonstrating if the object is signed.

We should decide if we want to store the commit message/tag message in the db in the notes field - on a large repo that could be slow but equally we're probably going to want to interpret the tag and commit properly.

**Comment by silverwind** [comment]
Just pushed `0.0.4-lw` which is a lightweight tag to my testing repo to see what GH does. In summary:

- For annotated tags, they show tag name, tag message, gpg signature of the tag, link to commit.
- For lightweight tags they show commit name, commit message, gpg signature of the commit, link to commit.

I don't think the commit message in the tag is of much value, assuming it's a copy of the commit it links to so a link to the commit should be fine.

**Comment by silverwind** [comment]
This was fixed recently, minus the tags on the releases list.
