### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by jdkdfjuwicvh** [go-gitea/gitea#8494]
- Gitea version (or commit ref): 1.9.4
- Git version: 2.20.1
- Operating system: Raspbian Buster + pre-release kernel (Raspberry Pi 4)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

The preview tab of the text editor doesn't load anything.

## Screenshots

![screenshot cleaned](https://user-images.githubusercontent.com/56083768/66722374-482d9880-edfc-11e9-8ef6-480856156747.png)

**Comment by zeripath** [comment]
It appears to works on try.gitea.io 

What file format are you trying to preview? What browser are you using?
What's your app.ini? Have you switched off the API?

**Comment by jdkdfjuwicvh** [comment]
I know it works on try.gitea.io. I'm just trying to preview the changes of the README. I tired with Tor browser first, but I also checked with the default profile of Firefox. In my app.ini I just added one rule: MAX_CREATION_LIMIT = 0. I didn't switch off the API, at least knowingly: doing grep 'SWAGGER' app.ini doesn't return anything so I guess the API is enabled.

**Comment by zeripath** [comment]
Ok. Could you check what the browser is sending when you click preview?

It should send a POST message to /api/v1/repos/:username/:reponame/markdown

Is it sending that POST to the correct place?

**Comment by jdkdfjuwicvh** [comment]
Emh, I'm just a teen I don't know that stuff... could you provide a very brief explanation about how to verify that? However, I'm not sure anymore about the state of the API, because when I try to load try.gitea.io/api/swagger my browser loads up a webpage, but if I try to open the "API page" of my gitea istance, my browser doesn't load anything. Does it matter?

**Comment by zeripath** [comment]
It sounds like you've misconfigured Gitea so I'd double check that you have the configuration correct in your app.ini

**Comment by jdkdfjuwicvh** [comment]
Sorry, but my app.ini seems to be fine (https://paste.debian.net/1106435/).
Is there another simple way to check if the API is working or not? Like another element in the page that wouldn't work without the API turned on?

**Comment by zeripath** [comment]
What is the URL you are using to browse to Gitea?

**Comment by jdkdfjuwicvh** [comment]
I was using it locally, but I've just finished setting up a temporary onion service in case you want to test (idk if it can cause other problems tho) : http://f6awmtbw572jcr2jaekqqnteuirdqoag64i6dnewph5y63xpsdmfabqd.onion/

**Comment by zeripath** [comment]
Well the tor won't work unless you tell Gitea that's its ROOT_URL is that onion address.

Similarly by locally, do you mean from a browser on the same machine as the server i.e. your browser was browsing to localhost:3000 or were you doing it across the network because again that would explain why the preview failed.

In Firefox there are likely some developer tools that you can use to check what requests your browser webpages are making. That was what I was meaning by checking what the preview page was POSTing, as I suspect that although the preview page is making a POST it is not sending it to correct place because you have incorrectly configured Gitea to say what it's ROOT_URL is.

If your server and client machines are not the same, a ROOT_URL of http://localhost:3000 is incorrect. It is certainly incorrect if you're trying to access Gitea over Tor.

**Comment by jdkdfjuwicvh** [comment]
Sorry for the delay and thanks for the clear explanation. As you said, the problem was the ROOT_URL, I fixed it and now it works. Thanks for the help!
