### ISSUE TITLE
Gitea tries to use /usr/bin as run dir

### ISSUE THREAD

**Issue by Martmists-GH** [go-gitea/gitea#8552]
- Gitea version (or commit ref): Latest
- Git version: Latest
- Operating system: Arch Linux x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I installed gitea from the repositories using pacman, but whatever I did it always seemed to use /usr/bin as working dir instead of /var/lib/gitea

**Comment by zeripath** [comment]
Unfortunately Gitea has non-fhs standard expectations which mean that just building from source and placing the binary in /usr/bin will not work.

See "Changing the default CustomPath, CustomConf and AppWorkDir" in https://docs.gitea.io/en-us/install-from-source/ for how to set up the build environment to change the default locations so that Gitea will never look in the wrong place.

Or 

Consider using the https://github.com/go-gitea/gitea/blob/master/contrib/fhs-compliant-script/gitea to shim the Gitea binary so that it's environment is set up.

Or

Look at https://docs.gitea.io/en-us/specific-variables/ to see which environment variables you can set to tell Gitea to look elsewhere and/or https://docs.gitea.io/en-us/command-line/ to see the command line options.

Please could you advise your package maintainer change their package to use the LDFLAGS replacement trick described or the fhs compliant script in order to prevent further confusion.

**Comment by ArchangeGabriel** [comment]
@zeripath Thanks for pinging. So just to be sure, it means we should add `-X \"code.gitea.io/gitea/modules/setting.AppWorkDir=/var/lib/gitea\"` to our LDFLAGS, correct? Because I’ve just tried that and it did not worked (still telling `/usr/bin` as the default in `gitea help`).

**Comment by zeripath** [comment]
Damn! It should be AppWorkPath not dir. I'll send a PR to the docs to fix that sorry.

**Comment by ArchangeGabriel** [comment]
OK, that did it. ;) I’ve pushed the new package. :)

**Comment by zeripath** [comment]
Thanks @ArchangeGabriel sorry the documentation is incorrect.

In case you're interested the -X in the LDFLAGS simply changes the default value for the provided variable name. 

In this case we do a delicate dance with this value, setting it when you set environment variables or command line options but if it remains empty then it is set in the end to the program location. By setting it with LDFLAGS you always ensure that it has a default value to fall back on.

Other go projects will likely be adjustable in similar ways even if their developers aren't aware of it.

Sorry once again that the documentation is incorrect.

**Comment by zeripath** [comment]
@martmists I'm gonna close this bug as when you get the updated package it should be fixed.
