### ISSUE TITLE
Account linking does not work if only external registration is allowed

### ISSUE THREAD

**Issue by PKizzle** [go-gitea/gitea#8589]
- Gitea version (or commit ref): 1.9.4
- Git version: 2.22.0
- Operating system: GNU/Linux Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (ALLOW_ONLY_EXTERNAL_REGISTRATION not set to true)
  - [ ] Not relevant
- Log gist:

## Description
The password input is disabled if only external registration is enabled.
However the form can not be successfully submitted because Gitea requires an input to the password text field.

The following code snippet states, that this is a feature for "second factor"-enabled accounts. 
https://github.com/go-gitea/gitea/blob/280f4bebbf5883eef94d8a84b21575393ae5e0e1/routers/user/auth.go#L894-L898 

However if the existing user has set a password already, the password field needs to be shown. Otherwise he is unable to authenticate and link the account.

Maybe there should be an additional setting specifically for "second factor"-enabled accounts instead of using ALLOW_ONLY_EXTERNAL_REGISTRATION?

## Screenshots
![2019-10-07t15-54-24](https://user-images.githubusercontent.com/39984529/67146261-a093e880-f289-11e9-91cc-7b6bbf010cc8.png)

**Comment by jkocot** [comment]
I encountered a similar issue, but I don't think it is related to the ALLOW_ONLY_EXTERNAL_REGISTRATION (we didn't have this option set on our server).
How this looks like:
Prerequisite: I already have an existing Gitea account, and I'm not logged in
1. I use the "Sign in with Open ID Connect" option and log in with my Open ID Connect authentication server
1. I get two options now - to register a new account or to link to an existing account, I choose the second one (the "Link to Existing Account" tab), but the tab has only place for username or email (there is no place for the password)
1. I type e-mail (or username, it doesn't matter - the behavior is the same for the two options) and accept
1. I am now redirected again to the "Register New Account" tag, but now my e-mails/username is filled in (but I cannot create such a user as it already existed)
1. Presumably, the problem is the lack of the password, so I check the "Link to Existing Account" tab again - now it looks different: apart from the username/e-mail field it now shows a password field marked in read as if I had forgot to fill it (but it wasn't there at the start)

Here are the screen-shots showing p. 1, 4 and 5
![link-account-1](https://user-images.githubusercontent.com/4125375/67842084-c9be3f80-faf9-11e9-830b-2018ae4b6db2.png)
![link-account-2'](https://user-images.githubusercontent.com/4125375/67842185-fb370b00-faf9-11e9-8537-72a07509827e.png)
![link-account-3'](https://user-images.githubusercontent.com/4125375/67842188-feca9200-faf9-11e9-92d0-0db2f56bba15.png)

We use version 1.9.3 of Gitea Server. I tried to reproduce it on https://try.gitea.io/ by logging in with GitHub, but there it works correctly (however, once I got a 500 error).

**Comment by hsiejkowski** [comment]
I answer on behalf of @jkocot. We set: `ALLOW_ONLY_EXTERNAL_REGISTRATION = false` and `REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA` is not set, but I believe it inherits the value from `ENABLE_CAPTCHA`, which in our case is set to false. So this results in a hidden password field.

If I set `ENABLE_CAPTCHA = true` the password field shows up, so this works as expected.

**Comment by PKizzle** [comment]
I don't think this issue has been resolved yet. Any further comments @hsiejkowski, @jkocot ?

**Comment by hsiejkowski** [comment]
> I don't think this issue has been resolved yet. Any further comments @hsiejkowski, @jkocot ?

For us this works as expected, so we have no further comments.

**Comment by PKizzle** [comment]
If I understand correctly you enabled the Captcha option and the password field is shown?
Well shouldn't the password field also be visible without Captcha being enabled?

**Comment by hsiejkowski** [comment]
To test it once again I disabled captcha on gitea 1.10.2 and the password field is visible. Regardless if ALLOW_ONLY_EXTERNAL_REGISTRATION is set to false or true.

**Comment by PKizzle** [comment]
I found pull request #9150, which deals with this issue. So I will comment again once I've done the update.

**Comment by PKizzle** [comment]
Okay, so after the update from 1.10 to 1.10.2 everything is working as expected. I'll close the issue.
