### ISSUE TITLE
Having issue with accessing directory inside a repository having same name as username

### ISSUE THREAD

**Issue by hiteshnayak305** [go-gitea/gitea#8603]
- Gitea version (or commit ref): master 20/10/2019
- Git version: git version 2.23.0.windows.1
- Operating system: windows 10 18999 build
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/hiteshnayak305/hiteshnayak305
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/hiteshnayak305/3421c3aa04cafb8a15e540a79936df61

## Description
accessing folders inside repository with same name as user name gives error 500.
...

## Screenshots
![image](https://user-images.githubusercontent.com/22023863/67165515-ab42a080-f3a3-11e9-8247-6240a2853781.png)
![image](https://user-images.githubusercontent.com/22023863/67165523-bbf31680-f3a3-11e9-8e78-684b3cb811b2.png)

**Comment by mrsdizzie** [comment]
Migrating this to view logs suggest problem is unrelated to username but nil reference with new GPG code added recently:

```
2019/10/20 16:37:36 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: invalid memory address or nil pointer dereference
        /usr/local/opt/go/libexec/src/runtime/panic.go:82 (0x40447d0)
                panicmem: panic(memoryError)
        /usr/local/opt/go/libexec/src/runtime/signal_unix.go:390 (0x40445ff)
                sigpanic: panicmem()
        /Users/mrsdizzie/.go/src/code.gitea.io/gitea/models/gpg_key.go:684 (0x4bb116c)
                ParseCommitWithSignature: log.Error("Error getting default public gpg key: %v", err)
        /Users/mrsdizzie/.go/src/code.gitea.io/gitea/routers/repo/view.go:184 (0x4f3225f)
                renderDirectory: ctx.Data["LatestCommitVerification"] = models.ParseCommitWithSignature(latestCommit)
        /Users/mrsdizzie/.go/src/code.gitea.io/gitea/routers/repo/view.go:455 (0x4f37882)
                renderCode: renderDirectory(ctx, treeLink)
        /Users/mrsdizzie/.go/src/code.gitea.io/gitea/routers/repo/view.go:395 (0x4f36d91)
                Home: renderCode(ctx)
```

**Comment by zeripath** [comment]
OK, I think I understand what's happened here. The stack trace implies that L684 here is the cause - but actually it's wrong the cause is coming from L685

https://github.com/go-gitea/gitea/blob/c8f3146cd52887c0bdd815ad0bdeb954b242c8fc/models/gpg_key.go#L682-L685

The `defaultGPGSettings` is `nil`. But how can that be?

https://github.com/go-gitea/gitea/blob/c8f3146cd52887c0bdd815ad0bdeb954b242c8fc/modules/git/commit.go#L503-L508

`c.repo` must be `nil` so this code will return `nil`, `nil`.

**Comment by zeripath** [comment]
Now `c.repo` being nil implies it is an unattached commit. It absolutely should be associated with a repository otherwise we cannot examine whether it was signed by the default key.

So there's another bug that this is revealing in:

https://github.com/go-gitea/gitea/blob/c8f3146cd52887c0bdd815ad0bdeb954b242c8fc/modules/git/commit_info.go#L15

In particular:

https://github.com/go-gitea/gitea/blob/c8f3146cd52887c0bdd815ad0bdeb954b242c8fc/modules/git/commit_info.go#L67-L76

Where at L74 the coerced commit doesn't gain a reference to the underlying repository
So that needs fixing and although L685 is responsible for the panic it was a good thing because we'd have great difficulty tracking down this bug without it!
