### ISSUE TITLE
markdown: does not render line break

### ISSUE THREAD

**Issue by brandonkal** [go-gitea/gitea#8704]
- Gitea version (or commit ref): 1.9.4
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Markdown renderer does not respect new lines created by a trailing <kbd>\\</kbd> slash.

```md
Should break\
Line 2
```

**Comment by warnat** [comment]
I can find no trace inside [markdown documentation](https://daringfireball.net/projects/markdown/syntax) to use a backslash for linebreaks.  
2 spaces at the end of a line or <br/> should do the trick.

**Comment by brandonkal** [comment]
@warnat It is part of the commonmark spec

https://spec.commonmark.org/0.29/#example-631

**Comment by brandonkal** [comment]
And because GitHub Flavored Markdown is an extension of commonmark it is also do documented there https://github.github.com/gfm/#example-655

**Comment by warnat** [comment]
@brandonkal I appologize for not digging deep enough.

**Comment by guillep2k** [comment]
We're using [github.com/russross/blackfriday](https://github.com/russross/blackfriday) to render Markdown. We're currently using v1 (v0.0.0-20180428102519-11635eb403ff), but there's a PR in progress to upgrade into v2. I'm not aware that this case is handled by the library on any version.

**Comment by brandonkal** [comment]
@guillep2k According to the [tests](https://johnmacfarlane.net/babelmark2/?text=first%5C%0Asecond), blackfriday 1.7.4 should be rendering a `<br/>`.

blackfriday has a github_flavored_markdown renderer option. Using that should ensure it is closer to GitHub's renderer. So if the PR uses that option, that will likely resolve this.

No worries @warnat

**Comment by lunny** [comment]
Since we have update `github.com/russross/blackfriday` on a recent PR. Could you try if it's resolved on master?

**Comment by guillep2k** [comment]
I'v just tested with 1.11.0+dev-171-gad6886170 (uses "github.com/russross/blackfriday/v2") and it's not supported either; I couln't find code to support that in it either.

Sorry, @brandonkal you suggest we use **github_flavored_markdown**, but we can't use it because [it has a big limitation](https://github.com/russross/blackfriday#other-renderers):
> It's not customizable, and its goal is to produce HTML output equivalent to the GitHub Markdown API endpoint, except the rendering is performed locally.

We need that said customizations that **github_flavored_markdown** does not provide (`blackfriday.WithExtensions`, `blackfriday.WithRenderer`) in order to generate links and references to other issues and PRs, mentions, etc.

There should exist the possibility of creating a line break by escaping it with two spaces before the end of line:

```
My line__      <--- replace "_" with spaces
other line
```

However it does not work either because all of our content uses `"\r\n"` (why?) and blackfriday expects `"\n`" for that function. 😔

Just for testing, I've tried replacing `"\r\n"` for `"\n"` in the database, and it makes it work for the two-spaces escaping, but it has no effect on the `\`.

**Comment by lunny** [comment]
I think this has been resolved since we have used goldmark to instead blackfriday. see https://gitea.com/lunny/test_markdown/src/branch/master/README.md

**Comment by brandonkal** [comment]
Resolved
