### ISSUE TITLE
Unable to release jar

### ISSUE THREAD

**Issue by Martmists-GH** [go-gitea/gitea#8706]
- Gitea version (or commit ref): Latest
- Git version: Latest
- Operating system: Arch Linux x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Trying to upload a jar fails, even when attachments are configured to allow `application/java-archive`

## Screenshots

![image](https://user-images.githubusercontent.com/16361449/67634569-2a613880-f8be-11e9-946b-7f109215d3ba.png)

**Comment by MayMeow** [comment]
I had similar problem with exe files... you have to allow them in app.ini  https://docs.gitea.io/en-us/config-cheat-sheet/#attachment-attachment

**Comment by martmists** [comment]
I have that enabled, restarted the gitea service and made sure it's still enabled in the config; Yet I still can't upload them.

**Comment by zeripath** [comment]
There are three places where an attachment can be denied:

* The browser
* The proxy-server - e.g. NGinx
* Gitea

What does your browser report the attachment mimetype as? It's possible that dropzone.js is denying the upload because the mimetype the browser is reporting is different from what it is expecting.

Are you running behind a proxy server? Check that it is not denying the upload.

Check your logs to see if the mimetype you are expecting is being passed to Gitea.
