### ISSUE TITLE
Failed Migration from Gogs 0.9.97.0901 to Gitea master

### ISSUE THREAD

**Issue by fettlaus** [go-gitea/gitea#871]
- Gitea version (or commit ref): a195c3fabeed4136b326ab641460fc30d6feaf01
- Git version: 2.6.2
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: https://gist.github.com/fettlaus/e9b7db4ad7a66c28c17c5facf22b84db

## Description

When doing a direct upgrade from Gogs 0.9.97.0901 to Gitea master, the migration failed with the attached errorlog. This doesn't happen when migrating from Gogs to Gitea 1.0.1 and then upgrading to Gitea master.

**Comment by lunny** [comment]
That maybe a migration method bug, both Gitea and Gogs. But I think you can upgrade v1.0.1 and then to master, It will smooth.

Because when you migrate from v7 to v12, but on v9 column `external_tracker_url` should be created by x.Sync2(), but that not in migrations list.

So I think we have to ask all database schemas changes should add a migration even if x.Sync2 could do that.

**Comment by lunny** [comment]
@fettlaus please confirm #929 fix this.

**Comment by fettlaus** [comment]
Sorry, I am unable to confirm this. I don't have the gogs backup anymore and thus can't revert to the old installation.
