### ISSUE TITLE
The pagination result of commit history is incorrect

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8716]
- Gitea version (or commit ref): 1.10.0 / e3875ac
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://gitea.com/gitea/gitea_mirror/commits/branch/master/models/action.go?page=1
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A
## Description
Duplicate commits appear on each page
## Screenshots
Page1:
![1](https://user-images.githubusercontent.com/2960293/67685252-14e03180-f9d8-11e9-9fac-e92e9a3f41b5.png)
Page5:
![2](https://user-images.githubusercontent.com/2960293/67685262-19a4e580-f9d8-11e9-97bb-1f2f0a9a6e3b.png)

**Comment by yasuokav** [comment]
Gentle bump. This issue is still exists in `1.14.0+dev-253-g24330f71b`

Gitea(https://try.gitea.io/yasuokav/gitea/commits/branch/master/models/action.go):
- Page1
![1](https://user-images.githubusercontent.com/2960293/100103899-d6ea6100-2ea8-11eb-9546-b4f8fe6d0f88.png)
- Page2
![2](https://user-images.githubusercontent.com/2960293/100103914-da7de800-2ea8-11eb-9f39-bfe7c9696ae2.png)

Github(https://github.com/go-gitea/gitea/commits/master/models/action.go): 
- Page1
![1](https://user-images.githubusercontent.com/2960293/100104066-0ac58680-2ea9-11eb-8fa4-b85462a748db.png)
- Page2
![2](https://user-images.githubusercontent.com/2960293/100104078-10bb6780-2ea9-11eb-9b30-130760fc9a39.png)

**Comment by lunny** [comment]
The bug could be reproduced when visit a file's history but not commits of a branch.

**Comment by zeripath** [comment]
ugh the issue is that the `--skip` argument doesn't work the expected way.
