### ISSUE TITLE
[impovement] don't reverence same issue multible times next to itself

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8722]
just look at: https://gitea.com/gitea/tea/pulls/45
Gitea Version: 1.11.0+dev-56-g28f60bb5c

![Bildschirmfoto zu 2019-10-28 22-33-12](https://user-images.githubusercontent.com/24977596/67719860-ef045e00-f9d2-11e9-99ee-f28c6a1b4d17.png)

**Comment by 6543** [comment]
@guillep2k didn't you write code in this area, so do you have any idears where to look at?

**Comment by guillep2k** [comment]
Every time you edit the comment it will invalidate previous references and create them anew. The reasons are because previous ones could or could not be the same as the new ones, and because I though a trail would be good for consistency.

The algorithm could be more sophisticated and detect "exact same list", of course. At the time it didn't seem too important. In this case, only a few minutes passed between one edition and the next, but what if days have passed? Mails will have been sent, people will have read that, etc. It made sense to me to leave a trail of changes, but I guess it can be confusing.

I don't know: it's a feature? a bug? :grin:

**Comment by 6543** [comment]
to have a trail is nice ... but add one check if it is next to itself and update instead?

is this hard to do?

**Comment by guillep2k** [comment]
> 
> 
> to have a trail is nice ... but add one check if it is next to itself and update instead?
> 
> is this hard to do?

@6543 on it.
