### ISSUE TITLE
Copyright in footer is misleading

### ISSUE THREAD

**Issue by fireglow** [go-gitea/gitea#8725]
I think the "© Gitea" in [templates/base/footer_content.tmpl#L4](https://github.com/go-gitea/gitea/blob/09b281a6ac445c6bae8399b838005c6be1a9c2eb/templates/base/footer_content.tmpl#L4) is misleading.
While the page is rendered by Gitea, the actual content is not copyrighted by the Gitea project.

Other code-hosting sites like GitHub or GitLab do not show such a copyright.
Sites like nytimes.com or washingtonpost.com do, because the content displayed is actually theirs.

I therefore propose the wording to be changed to something clearer, like "Powered by Gitea", or "Generated by Gitea".

**Comment by MayMeow** [comment]
I can make PR if you decide which one sentence to use :)

**Comment by 6543** [comment]
do we need "© Gitea" for leagal therms in fooder?

-> Licence MIT

**Comment by alexanderadam** [comment]
> do we need "© Gitea" for leagal therms in fooder?

I strongly doubt it because Gitea is not a legal entity (like a company for example) so it probably can't hold any rights anyway.
AFAIK the particular _authors_ own the rights of what they did. Which is true even if you don't write it on every code line you wrote because it's clarified in the the given license.

<details>
  <summary>Kind of related but offtopic anyway. Click to show.</summary>
  So IMHO the license must be distributed as well and I'm not sure why the JS libraries are accessible as a link in the footer but the Gitea library itself is not.

  But again, this would be another issue anyway and of course I'm not a lawyer. So nothing that I write might have any legal value.
  Also [the license situation of Gitea should be clarified anyway because it seems that it currently uses non-free dependencies](https://github.com/go-gitea/gitea/issues/8575).
</details>

**Comment by lunny** [comment]
In fact, that copyright is not related your codes on gitea instance. For example, you can see below in github. But github will not own the repositories' copyright on github. @fireglow I think you are wrong. Go to this page's bottom you will find it.

![image](https://user-images.githubusercontent.com/81045/67760112-a81e7300-fa7b-11e9-837d-cab47ca602f4.png)

Even we are not a company, but we have an organization.

**Comment by alexanderadam** [comment]
> Even if we are not a company, but we have an organization. A person could hold copyright, a company could also, why not an organization?

A legal organization can of course. I'm not sure whether this is a proper wording then.
Or can you just describe who _is_ the organization? And is this organization represented on the Github organization?
Because if so this would mean [only those 24 people who are part of the organization](https://github.com/orgs/go-gitea/people) own the rights on Gitea.
Which is obviously **not** true because _all_ of the authors of have some rights on it [as the license says](https://github.com/go-gitea/gitea/blob/master/LICENSE#L1).

So to conclude: I would still say that `© Gitea` is absolutely _not_ clear here because it's not clear who or what Gitea is from a legal perspective.
Even `© The Gitea Authors` would be clearer.

Otherwise I might have missed what the Gitea organization is and what it's statutes are.

**Comment by fireglow** [comment]
Let's not get off track here, the issue is the "©", not the enitity name.
The "©" suggests that Gitea holds the copyright to the content of the page.

**Comment by fireglow** [comment]
@lunny you are right, GitHub does that. One of my addons hides that.
GitHubs reasoning for that is outlined here: https://help.github.com/en/github/site-policy/github-terms-of-service#d-user-generated-content
That does not apply to self-hosted gitea instances.
Therefore I think the "notfix" label is premature.

**Comment by fireglow** [comment]
@MayMeow I think "Powered by Gitea" would be fine, since it does more than merely generate code listings, like for example cgit (which uses "generated by").

**Comment by lafriks** [comment]
`Powered by` should be ok imho

**Comment by lunny** [comment]
@alexanderadam maybe you are right. Since gitea is a non-registered organization, but we have join conditions and owners elections. 

@ gitea will almost mean © The Gitea Authors . It's different from what you can see from other sites. The maintainers represents the gitea authors to do some community things.

@fireglow And the instances users could add theirs' term services to say what like github did since gitea support custom pages.

**Comment by 0x5c** [comment]
I fixed it, and this is what it looks now
![image](https://user-images.githubusercontent.com/5877043/67937601-3db52200-fba4-11e9-8bb0-10efdfd1c860.png)

I do not know how to use i18n though. Is it simply be a case of replacing the text with `{{.i18n.Tr "powered-by"}}` and adding a corresponding string to the default language file?

Also, I wonder if `Gitea` in that text should be a link to gitea.io:
![image](https://user-images.githubusercontent.com/5877043/67938232-75709980-fba5-11e9-9e94-e0549024d24c.png)

Further, should there be a separator between `Powered by Gitea` and `Version`?

**Comment by lafriks** [comment]
It should probably be something like this:
```
Powered by Gitea version 1.11...
```
where `Gitea` is link to https://gitea.io/ and two translatable strings `Powered by` and `version`

**Comment by 0x5c** [comment]
> It should probably be something like this:
> 
> ```
> Powered by Gitea version 1.11...
> ```
> 
> where `Gitea` is link to https://gitea.io/ and two translatable strings `Powered by` and `version`

That sounds good

> Yes, only in en-US locale
Good

**Comment by 0x5c** [comment]
Looking at the template, it seems that `Version` is already a translatable string

**Comment by 0x5c** [comment]
Since version is a translatable string, but it is capitalised (and likely used in other places as-is), should a new one be created?

**Comment by 0x5c** [comment]
@alexanderadam I just realised that you had already made a PR. My version of the fix is already an i18n string, and has `Gitea` be a link to [gitea.io](https://gitea.io/).

Do you want to continue with your PR or shall I take over?
