### ISSUE TITLE
raspberry 4 raspbian buster install ERROR: Segmentation fault

### ISSUE THREAD

**Issue by wuzy1993** [go-gitea/gitea#8909]
I want install gitea in my raspberry,but execute this Code ERROR:   ./gitea web 
ERROR Content: Segmentation fault.
my system : Raspbian Buster Version:September 2019 Release date:2019-09-26 Kernel version:4.19

**Comment by lunny** [comment]
This is a known issue.

**Comment by zeripath** [comment]
Iirc it's an issue with the kernel not with Gitea and you need to update your Linux kernel. Please check our closed issues for duplicates.

**Comment by wuzy1993** [comment]
got it

**Comment by wuzy1993** [comment]
how long gitea will fix this issue in the kernel ？

**Comment by zeripath** [comment]
Gitea is not responsible for the Linux kernel. You need to update your kernel on raspbian.

**Comment by wuzy1993** [comment]
Thanks，I want know gitea

**Comment by MichaIng** [comment]
It seems that current RPi kernel version/upgrade is responsible for this error: https://github.com/MichaIng/DietPi/issues/3248
It affects at least RPi2 and RPi3 models as well, all `gitea` binaries, even the v1.7.6 ARMv7 ones fail with segmentation fault.

Nothing has been reported on RPi firmware repo: https://github.com/raspberrypi/firmware/issues
I guess kernel devs will say the same: "We're not responsible for single faulty software binaries!"
The question is who has the larger "damage" by this to start investigation, RPi firmware devs due to a single binary failing, or Gitea devs when their binaries fail on the most used SBC out there 😉.
