### ISSUE TITLE
Could reply the issue notification email to add new reply to issue?

### ISSUE THREAD

**Issue by suli3** [go-gitea/gitea#9067]
- Gitea version (or commit ref): 1.10.0
- Git version:
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Now the issue notification email has been configed, and we could get the  notification email when someone @me or reply my issue, 
but how about i reply the email i got then the issue is replyed with the email content? I think it would be a cool function and more convenient for communication.

**Comment by guillep2k** [comment]
It's not a trivial task. Perhaps through a POP account is a good start? Otherwise it would be difficult without a standard mail subsystem. Unix-like systems usually have one, but Windows doesn't. Then each message should be MIME parsed. The real trick however is to strip the quoted parts of a reply, though. Here's one library I've found for that: https://github.com/kvannotten/mailstrip

**Comment by baxandrei** [comment]
This would be a useful function.

**Comment by bagasme** [comment]
@esradioli did you mean [@strk's comment on #6998](https://github.com/go-gitea/gitea/issues/6998#issuecomment-502340323)?

**Comment by esradioli** [comment]
@bagasme  Yes, I think the right description about this issue is **reply-by-mail (comment/reply)**.

**Comment by esradioli** [comment]
> It's not a trivial task. Perhaps through a POP account is a good start? Otherwise it would be difficult without a standard mail subsystem. Unix-like systems usually have one, but Windows doesn't. Then each message should be MIME parsed. The real trick however is to strip the quoted parts of a reply, though. Here's one library I've found for that: https://github.com/kvannotten/mailstrip

I find that this function in Gitlab is called "reply-by-mail".

**Comment by suli3** [comment]
> It's not a trivial task. Perhaps through a POP account is a good start? Otherwise it would be difficult without a standard mail subsystem. Unix-like systems usually have one, but Windows doesn't. Then each message should be MIME parsed. The real trick however is to strip the quoted parts of a reply, though. Here's one library I've found for that: https://github.com/kvannotten/mailstrip

I think https://github.com/emersion/go-imap would be a better choice.

**Comment by corneliusroemer** [comment]
I second the usefulness of this feature request. We've had a discussion about this over at https://codeberg.org/corona-contact-tracing-germany/cwa-android and wondered whether there was a feature request issue open already.

@suli3 maybe you can rename the issue title to "[Feature request] Add Issue reply by mail"? That way it'd be easier to figure out at a glance what this issue is about.

**Comment by lunny** [comment]
A PR to fix this #13585

**Comment by lcnittl** [comment]
#2386 seems to be related
