### ISSUE TITLE
I can ssh to my gitea repos from emacs over anlinux, but can't browse or clone them over ssh

### ISSUE THREAD

**Issue by 0xameer** [go-gitea/gitea#9087]
- Gitea version (or commit ref):n/a
- Git version: n/a
- Operating system: anlinux on Android
- Database (use `[x]`): n/a
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ *] Not relevant
- Log gist:

## Description

...
In subject. Guided to post hereby Gitea
https://mobile.twitter.com/giteaio/status/1196950294019526656

## Screenshots
![Screenshot_1574239337305](https://user-images.githubusercontent.com/847157/69224734-151cb880-0ba3-11ea-93ed-7b8635a1759a.jpg)
![Screenshot_1574239280230](https://user-images.githubusercontent.com/847157/69224750-1bab3000-0ba3-11ea-8fbd-46b761179279.jpg)

#

**Comment by zeripath** [comment]
Hi! It's not clear what emacs command you tried to run here but it looks like tramp is trying to connect as a shell or to run a command over ssh that gitea does not support. On the server we only support  `git upload-pack`, `git upload-archive`, `git receive-pack` or the lfs commands.

So we need some more information:

* What command were you running in emacs?
* Are you able to find out what it trying to run on the Gitea server?
* Does what you are trying to do work on Github? If it doesn't we're unlikely to want to support it.

It's really important that you tell us what version of Gitea you are trying to connect to, if it's Gitea.com that's fine just say.

Of note you're connecting the message tells us that you're connecting with a deploy key rather than a user key - is that really intended?
