### ISSUE TITLE
Issue VS code permissions

### ISSUE THREAD

**Issue by vincentdavis** [go-gitea/gitea#9131]
I see some related issues related to permissions. I think having separate permissions for code and issues would be a good idea. Then maybe in the future allow per repo or team permissions that define both issue and code permissions.

My need: I need to allow some users to create, comment on issues but not be able to edit the code.
This is kinda akin to the permissions I have here making this issue and reading others.

I sent some sponsor money your way again. Keep up the great work!
Would be great if some part of this was in 1.11

**Comment by guillep2k** [comment]
You can have finely grained permissions if you move the repo to an organization and create teams for it. Each team individually can have access to code or issues etc. That's not available if the repo is under a normal user. You can create organizations using the `[+]` menu just at the left of your avatar.

**Comment by vincentdavis** [comment]
@guillep2k 
I have organizations defined but did not realize permissions where different there. I'll take a look.

**Comment by vincentdavis** [comment]
@guillep2k I think that worked.
It is not clear what the result of choosing READ ACCESS and then NO CODE would be or for that matter wite and no code.

- READ ACCESS. Members can view and clone team repositories. (yes)
- CODE: Access source code, files, commits and branches. (no)

**Comment by guillep2k** [comment]
To be honest, I didn't check very well the effect of the permissions myself. As far as I understand, the following is true:

* One user can belong to zero, one or more teams.
* The highest permissions prevail.
* A team can have read, write or admin permissions on different _units_. For example, a team can be admin for issues and nothing else. Then another team can be writer for code and nothing else. Finally, a user that belongs to both teams is writer for code and admin for issues.

There's a particular case that might be misleading and it's what actually is meant by read/write permissions on issues/pull requests:

* **None** (*) means the issues/PRs can't be accessed at all.
* **Read** means the user can view and comment on any issues/PRs, and *can create, modify and delete* their own issues/PRs.
* **Write** means the user can view and comment on any issues/PRs, and can modify, delete other people's issues/PRs and comments.

(*) _None_ happens when the user doesn't belong to any team that has at least read permissions.

**Comment by lunny** [comment]
@vincentdavis You could create two teams. One team have write permission to issues unit, and another have write permission to code unit. I think that's done.

**Comment by mqgmaster** [comment]
@lunny its working? At 1.8.2 the code tab is always visible and accessible for every repository of the team. The @vincentdavis question is very good. Makes sense Read permission granted and Code access disable at same time?

**Comment by lunny** [comment]
@mqgmaster Yes, I think it works from at least 1.8.0 .
