### ISSUE TITLE
Helm chart for gitea?

### ISSUE THREAD

**Issue by titou10titou10** [go-gitea/gitea#9237]
- Gitea version (or commit ref): v1.10
- Operating system: Kubernetes (OpenShift) + Helm 3.0

## Description
Is there a runnable helm chart for gitea?
I've seen [this PR in helm/charts](https://github.com/helm/charts/pull/6124/files) and [this "issue" on here](https://github.com/go-gitea/gitea/issues/4294) but they are both more than one year old and seem dead
Is there somewhere a working helm chart for gitea? or at least a work in progress where I could help/contribute? 
If not, should it be maintained on here (go-gitea/gitea) or in the helm/charts repo?

**Comment by techknowlogick** [comment]
I know of https://github.com/jfelten/gitea-helm-chart

**Comment by titou10titou10** [comment]
@techknowlogick thanks. It is a nice effort and a good work from @jfelten but IMHO the chart is strangely structured, variables are grouped by type (persistence, resources, images etc) instead of componernt (gitea, postgres..)    
Q: Is there a will to get an "official" helm chart for gitea  that will be updated with each version of gitea?    
If so, should it be maintained side by side the gitea code? in another gitea repository or in the helm/charts repo?    
I could find the time to contribute to this as we are about to deploy gitea in OpenShift v4.x

**Comment by techknowlogick** [comment]
Gitea ❤️'s k8s (we run gitea.com on-top of k8s), and while we don't use Helm, I would be supportive of creating a repo in our org for the helm chart.

**Comment by lunny** [comment]
Or maybe we should implement a gitea operator?

**Comment by titou10titou10** [comment]
@lunny Sure ! or both. Who will design this operator?

**Comment by lunny** [comment]
@titou10titou10 Contributors or maintainers of gitea!

**Comment by titou10titou10** [comment]
@techknowlogick would you mind sharing (in private?) your k8s objects (Deployments, STS, PV/PVC, etc) in order to have a base from a running gitea

**Comment by lunny** [comment]
@titou10titou10 @techknowlogick I think not currently. It needs more work as a public project.

**Comment by titou10titou10** [comment]
I found 2 operators, one for k8s and one for OpenShift (because of a "route" object being created, easily replaced by an "ingress" I guess). The latter one is from the OpenShift team lead Wolfgang Kulhanek    
Also a gitea docker image runnable in OpenShift (ie running with non-root user and other high privileges processes..) with an OpenShift "template" with persistent and ephemeral deployment

Could be a great  source of inspiration

https://github.com/wkulhanek/gitea-operator
https://github.com/integr8ly/gitea-operator
https://github.com/wkulhanek/docker-openshift-gitea

**Comment by loleg** [comment]
^ One more Rancher-style k8s config

**Comment by cdrage** [comment]
Hey all @loleg @titou10titou10 @techknowlogick @jfelten

I've actually been working on a Gitea Helm chart for the past week and I'd be more than welcome to contribute / donate it to the Gitea project in it's own separate repo.

It was originally based upon https://github.com/jfelten/gitea-helm-chart but I ran into a few issues with regards to its structure. My following chart does the following different:

- Database is de-coupled and the chart uses the official mariadb database from: https://github.com/helm/charts/blob/master/stable/mariadb this helps in terms of stability rather than having the databased coupled within the same Pod (as @jfelten 's helm chart did)
- Upgrade functionality
- Uses `ingress` by default and `LoadBalancer` for the SSH port on port 8022
- Persistency has been enabled / integrated
- Let's Encrypt has been enabled / integrated into the Helm chart

It is located here:
https://github.com/cdrage/charts/tree/master/gitea

To try:

```sh
helm repo add cdrage http://charts.charliedrage.com
helm install gitea cdrage/gitea
```

For production / persistency:

```sh
helm show values cdrage/gitea > values.yaml
vim values.yaml # Edit to enable persistent storage
helm install gitea cdrage/gitea -f values.yaml
```

**Comment by bclermont** [comment]
I rather deploy simple apps like gitea with helm chart
but I love operator that manage it

I started to build an operator that configure org, team, repos, users, etc

https://github.com/robotinfra/gitea-operator

**Comment by titou10titou10** [comment]
@bclermont , for inspiration, I found 2 other operatora for gitea and OpenShift, but I'm not sure of the maturity of both:
https://github.com/integr8ly/gitea-operator
https://github.com/wkulhanek/gitea-operator

**Comment by bclermont** [comment]
@titou10titou10 I looked at them already, they install gitea, not manage it once deployed.

for the installation of gitea I just use helm

**Comment by kristofre** [comment]
Hi all, anybody having an issue described here: https://github.com/go-gitea/gitea/issues/11408?

Basically using this helm chart, any push (via git client or gitea ui) results in the following error message:

```
The change was rejected by the server with the following message:
Gitea: Internal Server Error
Unable to contact gitea: Post http://0.0.0.0:3000/api/internal/hook/pre-receive/dynatrace/test: net/http: invalid header field value "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1ODk0NTQxOTJ9.iWBvmOHvMVDnPNwVtNaAZ91gMBPljH-3lDVvM0_0HEE\n" for key Authorization
Please check githooks.
```

The helm chart is listed in the linked issue.
Thanks in advance!

**Comment by zuh0** [comment]
Hello,

Just to know: is anyone still working on an official Helm chart for Gitea ?

If it is the case, I would love to help write and maintain it !

**Comment by cdrage** [comment]
https://github.com/k8s-land/gitea-chart

Is a actively maintained.


I've proposed to have this chart as the official one for Gitea but I've got no response yet.

**Comment by lunny** [comment]
@cdrage Sorry for the slow response. And thanks for your significant work on gitea chart. Once we accept your repository as an official one, we should update the chart with every gitea release. I think currently we have no enough maintainers and test environments to do it well. We should have at least another two maintainers (except you if you want to become one) to follow gitea's review policy - Every PR should be reviewed by at least two maintainers before it could be merged.

**Comment by luhahn** [comment]
Hello we've also created a gitea helm chart. It is fairly new and currently only used in our own kubernetes clusters. But we've decided to make it public.

https://github.com/novumrgi/helm/tree/master/charts/gitea

current support for:
 * built in support for memcached, postgresql, mysql via dependencies.
 * support via values for nearly all settings from https://docs.gitea.io/en-us/config-cheat-sheet/
   and we're working on a more flexible way to provide all the settings.
 * statefulset so your repository settings only getting lost if you really want them to
 * ldap and admin user settings via values (currently via init container, it would be nice to have this supported by app.ini or api)

Since we're actively using gitea in our company cluster we're going to maintain the chart for a long time.

However I don't want to start a "which chart is better" war. So if someone is interested let me know, or just use it :). 

If you want to use our chart as official helm chart for gitea, let me know.

**Comment by techknowlogick** [comment]
@luhahn that's awesome! feel free to send a PR to https://gitea.com/gitea/awesome-gitea/ to list it there as an option :)

I'm going to close this now, as we have many different options for helm charts now, and so the goal of this ticket is now complete.

**Comment by lunny** [comment]
We have an official helm chart https://gitea.com/gitea/helm-chart based on @cdrage 's recently. It's welcome to send PRs to that repository.

**Comment by luhahn** [comment]
Sorry, but since our helm chart already supports admin user, ldap and much more we won't start working on another one. We're already using ours in our company and it supports all our needs, so it is highly unlikely that we're allowed to develop another one, which doesn't support the features we need.

However we're happy to help if you have questions, or if you decide to use ours and need support.

**Comment by lunny** [comment]
Let's discuss on discord. An official helm-chart with more features could help more people.

**Comment by sstubbs** [comment]
This is great news that this has been done.
