### ISSUE TITLE
Keep preferences when submitting comment

### ISSUE THREAD

**Issue by wgevaert** [go-gitea/gitea#9272]
- Gitea version (or commit ref): 1.9.4
- Git version: Not relevant
- Operating system: Not relevant

## Description
I am reviewing a big feature, using the option to ignore all whitespace changes. When I then make a comment, the whitespace preferences are discarded. (Probably because of the `#issuecomment-<number>` part in the url)
When I then again set my whitespace preferences, I am no longer automatically moved to the comment I just made. Hence, I have two feature requests:

- When making a comment, your whitespace & splitscreen preferences should not be discarted.
- When changing your preferences, you want to be moved to the comment in your URL.

I think this can be fixed by changing the comment movement parameter to a GET-variable, but I am not sure if this is indeed possible (I do not know any GO).

**Comment by mnazarov** [comment]
I think it can also be considered as a bug, because in some cases when the whitespace setting is reset after pressing 'add commit' the page can't restore the reading position with the anchor link (I guess because it shows different lines then before)

related report: https://github.com/go-gitea/gitea/issues/13758

**Comment by wxiaoguang** [comment]
It has been fixed by https://github.com/go-gitea/gitea/pull/15566
