### ISSUE TITLE
[help] Gitea cannot run in the Windows development environment

### ISSUE THREAD

**Issue by scotox** [go-gitea/gitea#9389]
- Gitea version (or commit ref): source branch v1.10.1 
- Operating system: Windows10 x64

## Description
1. goland 2019.2
    - Enable Go Modules (vgo) integration
    - Proxy: `goproxy.io`
    - `GOROOT` and `GOPATH` is ok.
2. go version go1.13 windows/amd64
3. goland Run/Debug Configurations to `Go Build`
    - Run kind: File
    - Files: xxx\code.gitea.io\gitea\main.go
    - other is default
4. run Debug to panic.
>`panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: The system cannot find the path specified.`

## Screenshots

![image](https://user-images.githubusercontent.com/48884300/71021919-4228a080-213a-11ea-81e1-3a5dd6ff1d6d.png)

**Comment by jolheiser** [comment]
https://docs.gitea.io/en-us/install-from-source/#build
https://docs.gitea.io/en-us/make/

Simply running `main.go` will not work, doubly so because GoLand runs the built binaries in temp build locations.  
It _may_ be possible for GoLand to run it correctly if given the correct tags so that assets are bundled, but it's probably a better strategy to use the documented way for the time being.

**Comment by zeripath** [comment]
I suppose we could wrap our CSS and js generation steps in go:generate then you don't need the make step...

**Comment by scotox** [comment]
TKS All the guys

The problem was solved ...... the goland Run/Debug Configurations has three fields ("Directory", "Output directory", "Working directory"), I left out the "Output directory" item .... set this item to project root path then it's all right ..... not on the make of command line .... not on the npm build ...... 
go straight to code breakpoint mode.
Now i can have a happy break point again.....
