### ISSUE TITLE
Sometimes Ctrl+C cannot stop gitea

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9398]
macOS

<img width="1178" alt="图片" src="https://user-images.githubusercontent.com/81045/71050631-aa9a7080-2180-11ea-8bf1-6948dfe37f01.png">

**Comment by bagasme** [comment]
Have tried killing Gitea process?

**Comment by zeripath** [comment]
So since graceful took over the handle signals with a lifecycle there are a few places which may need to pay attention to shutdown and stop too - I've noticed the dB initialisation code needs to pay attention. 

The fundamental is cause is likely that the waitGroups are not being emptied - thus web won't finish.

I'll take a look.

**Comment by zeripath** [comment]
OK I noticed that things waiting on the issue indexer won't shutdown nicely because the holder doesn't listen to shutdown - that's fixed in #9363. #9313 removed the equivalent problem from the repo holder but, introduced other bugs which should be fixed by: #9476

**Comment by guillep2k** [comment]
@zeripath is this issue still pending?

**Comment by lunny** [comment]
Let's close now.

**Comment by zeripath** [comment]
There's probably other places but we can reopen when they become apparent
