### ISSUE TITLE
When a pull request merged, base repository's all PR's status will be checking

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9406]
I think we missed `checkAndUpdateStatus(pr)` on `services/pull/check.go:193`.

```diff
 pr, err := models.GetPullRequestByID(id)
			if err != nil {
				log.Error("GetPullRequestByID[%s]: %v", prID, err)
				continue
			} else if manuallyMerged(pr) {
-                              continue
			} else if err = TestPatch(pr); err != nil {
				log.Error("testPatch[%d]: %v", pr.ID, err)
-                              continue
			}
			checkAndUpdateStatus(pr)
```
<img width="1038" alt="图片" src="https://user-images.githubusercontent.com/81045/71085312-27a20600-21d2-11ea-9654-fa1ec09fdeb6.png">

**Comment by zeripath** [comment]
Hmm it's weird because that would be a change from the previous logic AFAIU. I think I will have to take another look.

Sorry for adding this bug

**Comment by zeripath** [comment]
So I'm confused - this shouldn't happen. @lunny is it just that you have to wait a bit longer?

`manuallyMerged()` will check if it can find a merge commit appropriate for the PR and if so will set the pr.Status to ManuallyMerged. If it returns true it will update the status. If it returns false then TestPatch will run.

Now the only way that the status will remain in Status Checking is if TestPatch subsequently throws an error. 

Do you have any logs so that we can see where the issue is?

I guess it would be reasonable to skip TestPatch if the status is set to ManuallyMerged by manuallyMerged even if it returns false?

**Comment by lunny** [comment]
@zeripath I cannot find that repository again. Maybe it spent too long time to do that. Assume a base repository has 200 PRs.

**Comment by zeripath** [comment]
Once queues are merged we can let this thing have a dynamically growing worker pool.

**Comment by lunny** [comment]
I just close this now.
