### ISSUE TITLE
Feature request - changing default branch name

### ISSUE THREAD

**Issue by clarfonthey** [go-gitea/gitea#9542]
Right now, gitea always defaults to creating a `master` branch as the default, and the default can be changed per repo with a setting. It would be nice if we could change the default branch name so that new repos would be created with the given name, e.g. if you wanted to use `prod` instead of `master`.

**Comment by zeripath** [comment]
The first branch you push to an empty repository will become the default.

**Comment by clarfon** [comment]
You're given the option to initialise the repo with a readme and license, which always chooses master.

**Comment by zeripath** [comment]
Ok.

Fairly simple thing to do - good first pr.

If you want it quickly stick a bounty on bounty source.

**Comment by clarfon** [comment]
Still would like this.

**Comment by TimerWolf** [comment]
Is this a typo?

https://github.com/go-gitea/gitea/blob/bbd910ed1b4f52ee66a5cdd8d11f856598161bef/modules/repository/generate.go#L116

**Comment by zeripath** [comment]
No it's a `go fmt` related change. (The `Depth: 1` option is used when generating from template repos.)

**Comment by TimerWolf** [comment]
@zeripath: fun that you did not notice it, or even check the commit i could be wrong. But before the commit it's only use one white-space whit the commit two white-spaces are used.

Even more strange if that you clear out that it is "Depth: 1" and not "Depth:  1" as the code says, that's why i asked if it was a typo or not, but even if the code works it could be a typo i think depending on how you see on it :)

**Comment by zeripath** [comment]
It's a go fmt change.

**Comment by TimerWolf** [comment]
I don't know what that means, i don't code go code, i just think it was worth a notice :)

Sorry if bother you...

**Comment by zeripath** [comment]
Instead of looking at the diff take a look at the file:

https://github.com/go-gitea/gitea/blob/cf4f2cfa3ee0e71632df971e154c7b926c39ba80/modules/repository/generate.go#L115-L118

See how the values now align vertically. Look elsewhere in that file and you'll see various other places where there is vertical aligning.

If you add an attribute to a struct initialiser or definition `go fmt` will align them. 

Go is quite opinionated on its formatting - code should and often must be formatted with gofmt.
