### ISSUE TITLE
[bug] global explore show repos of hidden org

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9555]
![Bildschirmfoto zu 2019-12-31 00-39-16](https://user-images.githubusercontent.com/24977596/71605024-2ffd2800-2b66-11ea-8f79-9569e89d0162.png)

if you like to look at it - you get a 404 wich shows that the repo view handle rights in a correct way

**Comment by jolheiser** [comment]
To aid anyone looking into this, the problem comes from 
https://github.com/go-gitea/gitea/blob/08424648ae0e7db107d0a1d8b4454557cb9f275f/models/repo_list.go#L230-L232

Because even though the repo is public, this condition doesn't take private orgs into account.  
I have been mulling it over off and on, but truth be told that function is a tricky mess that needs refactoring imo  
I'll keep thinking on it, but in the meantime someone else is more than welcome to swoop in and take it. :sweat_smile:

**Comment by 6543** [comment]
@jolheiser how do you create this code views in markdown?
