### ISSUE TITLE
PR review comments are deleted after push.

### ISSUE THREAD

**Issue by airamrguez** [go-gitea/gitea#9763]
- Gitea version (or commit ref): 1.9.3 
- Git version: git version 2.21.0 (Apple Git-122.2)
- Operating system: macOS Catalina
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Steps to reproduce:

1. Make a PR.
2. Add some inline comments to any lines using the review UI.
3. Modify those lines in the code and push the changes.

What happens?

Review comments are deleted.

**Comment by guillep2k** [comment]
There has been a lot of work on comments since 1.9.3. Upgrading to 1.10.2 (latest stable) should get you some improvements, but if I recall correctly your problem may have been fixed recently in 1.11.0 
(currently RC1). You can try on [try.gitea.com](try.gitea.com) (which has a slightly newer version than that) to see if you can reproduce the problem there.

**Comment by airamrguez** [comment]
@guillep2k thanks. We'll upgrade to 1.11.0 and try it again.

**Comment by lcnittl** [comment]
@guillep2k it is [try.gitea.**io**](https://try.gitea.io), right?

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k it is [try.gitea.**io**](https://try.gitea.io), right?

Of course, thank you.

**Comment by zeripath** [comment]
Please note that just like here, when you write inline comments they are pending unless you press one of approve, comment, request changes

**Comment by airamrguez** [comment]
I have upgraded Gitea to version 1.10.3, wrote some inline comments, then pressed "Request changes", then git push and after all that comments still disappear.

**Comment by lunny** [comment]
That comments maybe out of date so it cannot be displayed.

**Comment by airamrguez** [comment]
@lunny We actively use Gitea in our team. We do code reviews every day so I suppose they cannot be out of date

**Comment by guillep2k** [comment]
@airamrguez An outdated review is one that no longer matches a line of a PR code. For example, if you comment on line 80 of a file, but a later commit removes that particular line, then the review comment doesn't have a context for being displayed.

**Comment by airamrguez** [comment]
@guillep2k this is what happening, but is this how it should be? I mean, I don't want to lose those comments.

**Comment by guillep2k** [comment]
@airamrguez You are running Gitea 1.9.3. I think that your problem is currently solved, but I'm not certain about the right version (1.11 is release candidate now, and we're working in the 1.12 branch). This kind of review didn't generate a record in the `comment` table, but now they do.

What you can do:

- Upgrade to the latest 1.10.x or 1.11.0 when it comes out. I believe the problem was fixed in the 1.11 branch. Make sure to download a three-numbered version (e.g. 1.10.3 or 1.11.0) which is a release and not a two-numbered version  (1.10, 1.11) which is our repo's head to add modifications.
- If the above doesn't solve your problem, check if you can still reproduce it in try.gitea.io, which has the latest _unstable_ version of Gitea.

Please mind that old comments might be hidden forever; you need to create new comments.

**Comment by airamrguez** [comment]
@guillep2k We hace upgraded to version 1.11.0-rc2 and I think that comments are now preserved. It’s ok for me. Thank you all for your support
