### ISSUE TITLE
Resurrection?

### ISSUE THREAD

**Issue by vtolstov** [go-gitea/gitea#99]
Sometimes ago gitea closed, because author of gogs merge some or and continue to develop it.
Why gitea now resurrected again?

**Comment by metalmatze** [comment]
Because the only maintainer of gogs is absent for over a month now, again.
We will push this project and won't wait for anyone.

**Comment by lunny** [comment]
We build a continuous and active development organization. Please checkout https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md. And this time, we will not stop even if Unknwon come back.

**Comment by tboerger** [comment]
So as you can see we plan to keep Gitea and to make it the successor of Gogs. If you want to come back to the development you are really welcome. As @lunny already linked we've got a wide range of people actively working on Gitea, we currently got 10 maintainers and 3 owners, so we will not run into issues if somebody leaves.

I will close this issue for now because the question have been answered.
