### ISSUE TITLE
View pull request 500

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9914]
In a migrated repository, some pull request pages return 500 when view the page.

```
2020/01/21 20:53:09 ...vices/pull/update.go:67:GetDiverging() [T] PushToBaseRepo[11]: pushing commits to base repo 'refs/pull/661/head'
2020/01/21 20:53:09 routers/repo/pull.go:348:PrepareViewPullInfo() [E] GetDiverging: exit status 128 - fatal: ambiguous argument 'master..unknown repository': unknown revision or path not in the working tree.
	Use '--' to separate paths from revisions, like this:
	'git <command> [<revision>...] -- [<file>...]'
	
2020/01/21 20:53:09 ...s/context/context.go:139:HTML() [D] Template: status/500
```

**Comment by 6543** [comment]
think this is caused by #9784 

look's like a reverence is missing :(

maby `GetDiverging` [Link](https://github.com/go-gitea/gitea/blob/8cb9b2f016f0a5c1aa3e907d4d6640c3c9ba5d57/services/pull/update.go#L66) should check if HeadBranch != "" ? but this should be not be the case for a correct PR either ...

**Comment by 6543** [comment]
so maby there is a issue with migration witch drop some needed information

**Comment by 6543** [comment]
@lunny how to reproduce?

**Comment by lunny** [comment]
The head repository or head branch maybe deleted before merged. I think that's the problem. This should be a regression.
