### ISSUE TITLE
Local instance of gitea don`t display images.

### ISSUE THREAD

**Issue by Lourens-Rich** [go-gitea/gitea#997]
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/Lourens-Rich/markdown-image-bug/src/master/2017/02/note.md)
  - [  ] No.
  - [  ] Not relevant

On this link (https://git.r208.tk/Lourens-Rich/markdown-image-bug/src/master/2017/02/note.md) Gitea don't display image. (All repos images on my instance now are broken.)

**Comment by Lourens-Rich** [comment]
Repo on try.gitea.io have 500 error. (https://try.gitea.io/Lourens-Rich/markdown-image-bug)

Also, i uploaded copy of this repo here: https://git.r208.tk/Lourens-Rich/markdown-image-bug

**Comment by lunny** [comment]
it's duplicated with #988 and we have a PR #993  to fix this.

**Comment by lunny** [comment]
About the 500 error, could you fire another issue? Thanks!

**Comment by Lourens-Rich** [comment]
I transform this issue to my another problem.

**Comment by Lourens-Rich** [comment]
@lunny, please reopen it.

**Comment by lunny** [comment]
OK. Please change your issue content also.

**Comment by Lourens-Rich** [comment]
Cast @lunny. Updated post and approved the problem on try.gitea.org.

**Comment by lunny** [comment]
@andrew-boyarshin could you see this issue? I think maybe it's related with the markdown render.

**Comment by andrew-boyarshin** [comment]
@lunny in progress...  _The comment will be updated._

Definitely bug, most likely related to my PR.

UPD: Path not combined correctly. The problem is with [markdown.go:L214](https://github.com/go-gitea/gitea/blob/master/modules/markdown/markdown.go#L214), url.QueryEscape.

UPD: Fixed locally by reverting change in my PR, with a couple of additional fixes to URLJoin. Improved test coverage.

UPD: I am now trying to clone this repo and try out the result.

UPD: PR is to be created. Bug fixed.

UPD: Looks like the bug was too huge. I underestimated it. It was caused by too complicated structure of file retrieval. Work in progress. Another large PR is to be expected.

UPD: I managed to narrow the set of required changes to a relatively small amount. Plus, I managed to fix wrong behavior of commit and issue URLs rewrite introduced in my PR.

UPD: Internal code review in progress.

UPD: PR submitted.

**Comment by andrew-boyarshin** [comment]
This is fixed now by #1027. Confirmed to be working correctly: <https://try.gitea.io/Lourens-Rich/markdown-image-bug/src/master/2017/02/note.md>. You can close the issue now.

**Comment by Lourens-Rich** [comment]
Wow! Great! @andrew-boyarshin, thank you brother, thank you!

**Comment by kiemrong08** [comment]
I can't display image in markdown.
https://try.gitea.io/kiemrong08/testimage/src/branch/master/README.md

**Comment by andrew-boyarshin** [comment]
@kiemrong08 why do you have `/src/` specified instead of `/raw/`, if you are so willing to use absolute URLs?

**Comment by kiemrong08** [comment]
@andrew-boyarshin can you give me some example of using image in gitea ?

**Comment by kiemrong08** [comment]
@andrew-boyarshin Thank you
